### ISSUE TITLE
No Worker Heartbeat With Solo Pool

### ISSUE THREAD

**Issue by dsanders11** [celery/celery#3768] opened 2017-01-15 15:16 UTC
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

1. Run celery with a single worker set to use the solo pool such as `celery worker -c 1 -P solo`

## Expected behavior

Expected that a single-process worker would exist and be able to use heartbeats.

## Actual behavior

Single-process worker exists but does not use heartbeats. All timer related tasks don't work, so this is the root cause of heartbeats not working.

If this is intended behavior then it should be mentioned in the documentation as it is very much not clear.

I know the documentation for solo says 'single-threaded' but I didn't take that to mean that it wouldn't handle timers correctly as well. A layman's reading of that (along with the name) implies that the worker pool has a single thread and that's it (so one worker), not that the process itself can't have any threads to facilitate things like timers.

**Comment by pnovotnak** [comment] 2017-01-20 09:36
Much bump. Many tears

<img width="1047" alt="screen shot 2017-01-20 at 01 35 32" src="https://cloud.githubusercontent.com/assets/5713245/22143956/cdd741ec-deb0-11e6-8cf7-e076c0b019c7.png">

**Comment by pnovotnak** [comment] 2017-01-20 09:50
BTW, @dsanders11 how did you debug this? I've been using tcpdump, but there have to be a dozen better ways...

**Comment by dsanders11** [comment] 2017-01-20 11:22
@pnovotnak, I traced the code. I saw log messages from the worker having trouble reconnecting constantly and saw rabbitmq messages about closing connection due to no heartbeat. Tried tweaking the heartbeat frequency down to 10 seconds and still happened, seemed like heartbeats just weren't being sent.

From there it was a fairly painful process of tracing the code and adding debug statements trying to find a cause. Came to a section of the code that branched off based on the pool type, so tried removing the pool argument so that it used the default prefork made it all start working. Made it clear that 'solo' pool was the problem, decided that was enough for a bug report.

**Comment by messer** [comment] 2017-02-03 20:24
bump. all the pain.

**Comment by LPiner** [comment] 2017-06-17 14:18
This problem seems to still exist.

**Comment by RobertAtomic** [comment] 2017-06-21 03:14
Is it possible to send heartbeats from within a task?  In my case I'm using solo because the task uses it's own multiprocessing.Pool.  I could easily send heartbeats from the main process while waiting for the pool to finish its work.  I tried variants of:
`app..default_connection().fallback().connection.heartbeat_tick()`
but no luck.

**Comment by auvipy** [comment] 2017-12-19 16:33
if anyone can verify this on master there would be consensus to fix it on next big release

**Comment by auvipy** [comment] 2018-01-17 11:30
could anyone start with a testcase to start for a fix? also may be this is a duplicate or not

**Comment by auvipy** [comment] 2018-01-17 11:31
may be duplicate of https://github.com/celery/celery/issues/3430 report if not

**Closed by auvipy** 2018-01-17 11:31 UTC
Labels: Status: Needs Testcase ✘
