### ISSUE TITLE
Swallowing Exception and silently ignoring tasks during autodiscover

### ISSUE THREAD

**Issue by Idraen** [celery/celery#3939] opened 2017-03-27 12:46 UTC
Hi,

We have discovered that Celery might be swallowing a raised exception during task discovering, resulting in silently ignoring tasks. 

We run Celery  in a Django Project. We run the autodiscover process to fetch all the tasks defined in each one of our tasks.py file in our installed apps packages. We want Celery Beat to fire periodical tasks using Crontab.

Steps to reproduce : 
``` 
# In function.py
def add2(number):
  return number + 2

raise Exception()

# In tasks.py
from celery import shared_task
from . import function

@shared_task
def add2(number):
  return function.add2(number)

# In settings.py
CELERY_BEAT_SCHEDULE = {
    'test_tasks': {
        'task': 'path.to.task.add2,
        'schedule': crontab(hour=0, minute=0)
    }
}
```

I mention that tasks.py is not imported by any other module. It seems to us that when discovering tasks Celery will be the only one trying to import it from a string, so we can’t see the issue happening unless we manually try to import it ; that is actually how we discovered our issue. 

Cheers,
Adrien Czerny

**Comment by auvipy** [comment] 2018-01-17 15:01
possible duplicate of https://github.com/celery/celery/issues/3986 plz cross check and report

**Closed by auvipy** 2018-01-17 15:01 UTC
