### ISSUE TITLE
main process killed by SIGSEGV

### ISSUE THREAD

**Issue by MidTin** [celery/celery#6796] opened 2021-06-01 08:09 UTC
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.7 / 5.1.0
**Django version**: 3.1.11
**Redis version**: 3.2.12

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.1.0 (sun-harmonics) kombu:5.1.0 py:3.9.0
            billiard:3.6.4.0 redis:3.5.3
platform -> system:Linux arch:64bit, ELF
            kernel version:3.10.0-1160.6.1.el7.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

When i try to run many tasks (some of the tasks will make a grpc call), the main worker died cause by the segmentation fault after a few minutes.

these is some trace log print by `strace  -e trace=signal,process,file,network`, it seems always be killed after recvfrom call.

```
recvfrom(28, 0x312e050, 65536, 0, NULL, NULL) = -1 EAGAIN (Resources are temporarily unavailable)
recvfrom(21, "*-1\r\n", 65536, 0, NULL, NULL) = 5
sendto(21, "*6\r\n$5\r\nBRPOP\r\n$6\r\ncelery\r\n$9\r\nc"..., 79, 0, NULL, 0) = 79
open("/proc/loadavg", O_RDONLY)         = 40
recvfrom(30, 0x31316a0, 65536, 0, NULL, NULL) = -1 EAGAIN (Resources are temporarily unavailable)
sendto(30, "*3\r\n$7\r\nPUBLISH\r\n$29\r\n/14.celery"..., 827, 0, NULL, 0) = 827
recvfrom(30, ":2\r\n", 65536, 0, NULL, NULL) = 4
recvfrom(28, "*4\r\n$8\r\npmessage\r\n$21\r\n/14.celer"..., 65536, 0, NULL, NULL) = 856
recvfrom(28, 0x312e050, 65536, 0, NULL, NULL) = -1 EAGAIN (Resources are temporarily unavailable)
+++ killed by SIGSEGV +++
```

```
recvfrom(31, "*4\r\n$8\r\npmessage\r\n$21\r\n/14.celer"..., 65536, 0, NULL, NULL) = 856
recvfrom(31, 0x2359040, 65536, 0, NULL, NULL) = -1 EAGAIN (Resources are temporarily unavailable)
recvfrom(21, "*-1\r\n", 65536, 0, NULL, NULL) = 5
sendto(21, "*6\r\n$5\r\nBRPOP\r\n$6\r\ncelery\r\n$9\r\nc"..., 79, 0, NULL, 0) = 79
recvfrom(21, "*-1\r\n", 65536, 0, NULL, NULL) = 5
sendto(21, "*6\r\n$5\r\nBRPOP\r\n$6\r\ncelery\r\n$9\r\nc"..., 79, 0, NULL, 0) = 79
open("/proc/loadavg", O_RDONLY)         = 40
recvfrom(30, 0x2359040, 65536, 0, NULL, NULL) = -1 EAGAIN (Resources are temporarily unavailable)
sendto(30, "*3\r\n$7\r\nPUBLISH\r\n$29\r\n/14.celery"..., 827, 0, NULL, 0) = 827
recvfrom(30, ":1\r\n", 65536, 0, NULL, NULL) = 4
recvfrom(31, "*4\r\n$8\r\npmessage\r\n$21\r\n/14.celer"..., 65536, 0, NULL, NULL) = 856
recvfrom(31, 0x2359040, 65536, 0, NULL, NULL) = -1 EAGAIN (Resources are temporarily unavailable)
+++ killed by SIGSEGV +++
```

These outputted by the Python's faulthandler
```
Fatal Python error: Segmentation fault

Thread 0x00007fc6a0680740 (most recent call first):
  File "/srv/www/venv/lib/python3.9/site-packages/kombu/utils/eventio.py", line 82 in poll
  File "/srv/www/venv/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 305 in create_loop
  File "/srv/www/venv/lib/python3.9/site-packages/celery/worker/loops.py", line 81 in asynloop
  File "/srv/www/venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 618 in start
  File "/srv/www/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 116 in start
  File "/srv/www/venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 326 in start
  File "/srv/www/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 365 in start
  File "/srv/www/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 116 in start
  File "/srv/www/venv/lib/python3.9/site-packages/celery/worker/worker.py", line 203 in start
  File "/srv/www/venv/lib/python3.9/site-packages/celery/bin/worker.py", line 346 in worker
  File "/srv/www/venv/lib/python3.9/site-packages/celery/bin/base.py", line 132 in caller
  File "/srv/www/venv/lib/python3.9/site-packages/click/decorators.py", line 21 in new_func
  File "/srv/www/venv/lib/python3.9/site-packages/click/core.py", line 610 in invoke
  File "/srv/www/venv/lib/python3.9/site-packages/click/core.py", line 1066 in invoke
  File "/srv/www/venv/lib/python3.9/site-packages/click/core.py", line 1259 in invoke
  File "/srv/www/venv/lib/python3.9/site-packages/click/core.py", line 782 in main
  File "/srv/www/venv/lib/python3.9/site-packages/click/core.py", line 829 in __call__
  File "/srv/www/venv/lib/python3.9/site-packages/celery/bin/celery.py", line 213 in main
  File "/srv/www/venv/lib/python3.9/site-packages/celery/__main__.py", line 15 in main
  File "/srv/www/venv/bin/celery", line 8 in <module>

```

**Comment by thedrow** [comment] 2021-06-01 10:35
Can you provide a test case for us to reproduce the issue?

**Comment by MidTin** [comment] 2021-06-07 02:16
👌 I will try to make a simple test case later

**Comment by smuuf** [comment] 2021-06-18 07:38
I'm having similar situation with Celery `5.1` (`5.0.5` was fine), where the main worker process segfaulted after someone else calling `revoke(task_id, terminate=True)` on any task processed by that worker.

_(we have a dedicated "revoke_task" task, which actually calls the `Control.revoke(...)`, because our PHP-side uses [`celery-php`](https://github.com/gjedeer/celery-php/), which [does not implement revoking](https://github.com/gjedeer/celery-php/blob/869e9462a443a1bc5e608f1da3712629b3463f90/src/AsyncResult.php#L249))_

```
[2021-06-17 13:09:02,677: INFO/MainProcess] Terminating php_60cb2d417149e0.42543968 (Signals.SIGTERM)
[2021-06-17 13:09:02,684: INFO/ForkPoolWorker-3] Task mylovelylovelyapp.tasks.control.revoke_task[php_60cb2d4e7fe3d6.22926463] succeeded in 0.135165s
Segmentation fault (core dumped)
```

This was reproducible each time in our (rather complex) service. When I tried to create a minimal reproducible example from scratch, I wasn't able to do it.

However with the latest `5.1.1` https://github.com/celery/celery/releases/tag/v5.1.1 the issue _seems to_ be resolved.

**Comment by auvipy** [comment] 2021-07-07 12:17
> However with the latest `5.1.1` https://github.com/celery/celery/releases/tag/v5.1.1 the issue _seems to_ be resolved.

closing based on that

**Closed by auvipy** 2021-07-07 12:17 UTC
Labels: Issue Type: Bug Report, Status: Needs Testcase ✘
