### ISSUE TITLE
Add Python 3 exception context support when logging failures

### ISSUE THREAD

**Issue by roosmaa** [celery/celery#2688] opened 2015-07-05 17:16 UTC
It would be nice if Celery logged the whole exception chain, currently only the latest exception is displayed, the causing exception is lost.

**Comment by malinoff** [comment] 2015-07-06 00:51
You should receive full tracebacks on py3, could you please include the traceback you're talking about?

**Comment by roosmaa** [comment] 2015-07-06 06:57
I have already nuked my python3 experimentation, will recreate if I have some time. But I remember that for whatever reason my exceptions were pickled and unpickled through UnpickleableExceptionWrapper could it be the reason why the __context__ isn't getting carried over?

**Comment by malinoff** [comment] 2015-07-06 07:08
Maybe because your exceptions are not subclassed from Exception class.

**Comment by roosmaa** [comment] 2015-07-06 07:12
That's the weird thing, they are. Couldn't really figure out why it went
through the wrapper in the first place, so I just played along and
populated the args property so that it would get serialised back properly.
Works fine in python 2, but the new context stuff didn't seem to work.

Can probably make some easy test case in the evening to demo this.

**Comment by roosmaa** [comment] 2015-07-06 19:25
Here's a sample project source used to generate the output below: [celery-2688.tar.gz](https://www.dropbox.com/s/to0regoskceaw4e/celery-2688.tar.gz?dl=0)

When running unit-tests the python3 exception is displayed correctly:
```
$ python manage.py test
E
======================================================================
ERROR: test_some_error (demo.tests.DemoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/sample/demo/tasks.py", line 15, in make_error
    whatever()
  File "/tmp/sample/demo/tasks.py", line 10, in whatever
    raise ValueError('Yeah, that.')
ValueError: Yeah, that.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/sample/demo/tests.py", line 11, in test_some_error
    tasks.make_error()
  File "/Users/mart/.virtualenvs/celery-bug/lib/python3.4/site-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/Users/mart/.virtualenvs/celery-bug/lib/python3.4/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/tmp/sample/demo/tasks.py", line 17, in make_error
    raise SomeError('That happened.')
demo.errors.SomeError: Sample error - That happened.

----------------------------------------------------------------------
Ran 1 test in 0.008s

FAILED (errors=1)
```

Now, when triggering the background task in celery with `GET /demo/background/`:

```
$ celery -A sample worker -l debug
[2015-07-06 19:20:22,886: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2015-07-06 19:20:22,888: DEBUG/MainProcess] | Worker: Building graph...
[2015-07-06 19:20:22,888: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Queues (intra), Pool, Autoscaler, Autoreloader, Beat, StateDB, Consumer}
[2015-07-06 19:20:22,897: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2015-07-06 19:20:22,898: DEBUG/MainProcess] | Consumer: Building graph...
[2015-07-06 19:20:22,917: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Mingle, Gossip, Tasks, Control, Agent, event loop}
/tmp/.virtualenvs/celery-bug/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning:
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

[2015-07-06 19:20:22,918: WARNING/MainProcess] /tmp/.virtualenvs/celery-bug/lib/python3.4/site-packages/celery/apps/worker.py:161: CDeprecationWarning:
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))


 -------------- celery@machine.local v3.1.18 (Cipater)
---- **** -----
--- * ***  * -- Darwin-14.4.0-x86_64-i386-64bit
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         sample:0x110b926a0
- ** ---------- .> transport:   redis://192.168.59.103:6379/1
- ** ---------- .> results:     disabled
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . demo.tasks.make_error
  . sample.celery.debug_task

[2015-07-06 19:20:22,929: DEBUG/MainProcess] | Worker: Starting Hub
[2015-07-06 19:20:22,929: DEBUG/MainProcess] ^-- substep ok
[2015-07-06 19:20:22,930: DEBUG/MainProcess] | Worker: Starting Pool
[2015-07-06 19:20:22,944: DEBUG/MainProcess] ^-- substep ok
[2015-07-06 19:20:22,945: DEBUG/MainProcess] | Worker: Starting Consumer
[2015-07-06 19:20:22,945: DEBUG/MainProcess] | Consumer: Starting Connection
[2015-07-06 19:20:22,993: INFO/MainProcess] Connected to redis://192.168.59.103:6379/1
[2015-07-06 19:20:22,993: DEBUG/MainProcess] ^-- substep ok
[2015-07-06 19:20:22,993: DEBUG/MainProcess] | Consumer: Starting Events
[2015-07-06 19:20:23,022: DEBUG/MainProcess] ^-- substep ok
[2015-07-06 19:20:23,022: DEBUG/MainProcess] | Consumer: Starting Heart
[2015-07-06 19:20:23,026: DEBUG/MainProcess] ^-- substep ok
[2015-07-06 19:20:23,026: DEBUG/MainProcess] | Consumer: Starting Mingle
[2015-07-06 19:20:23,026: INFO/MainProcess] mingle: searching for neighbors
[2015-07-06 19:20:24,066: INFO/MainProcess] mingle: all alone
[2015-07-06 19:20:24,066: DEBUG/MainProcess] ^-- substep ok
[2015-07-06 19:20:24,066: DEBUG/MainProcess] | Consumer: Starting Gossip
[2015-07-06 19:20:24,083: DEBUG/MainProcess] ^-- substep ok
[2015-07-06 19:20:24,083: DEBUG/MainProcess] | Consumer: Starting Tasks
[2015-07-06 19:20:24,112: DEBUG/MainProcess] ^-- substep ok
[2015-07-06 19:20:24,112: DEBUG/MainProcess] | Consumer: Starting Control
[2015-07-06 19:20:24,130: DEBUG/MainProcess] ^-- substep ok
[2015-07-06 19:20:24,131: DEBUG/MainProcess] | Consumer: Starting event loop
/tmp/.virtualenvs/celery-bug/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2015-07-06 19:20:24,131: WARNING/MainProcess] /tmp/.virtualenvs/celery-bug/lib/python3.4/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2015-07-06 19:20:24,132: WARNING/MainProcess] celery@machine.local ready.
[2015-07-06 19:20:24,132: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2015-07-06 19:20:24,132: DEBUG/MainProcess] basic.qos: prefetch_count->32
[2015-07-06 19:20:25,441: INFO/MainProcess] Received task: demo.tasks.make_error[e71f726c-a896-4545-a9d6-0397155d6b13]
[2015-07-06 19:20:25,442: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x110c7ad08> (args:('demo.tasks.make_error', 'e71f726c-a896-4545-a9d6-0397155d6b13', [], {}, {'taskset': None, 'retries': 0, 'delivery_info': {'routing_key': 'celery', 'exchange': 'celery', 'priority': 0, 'redelivered': None}, 'reply_to': '435449fb-7b52-38be-920d-a67c3143dcfb', 'expires': None, 'errbacks': None, 'headers': {}, 'utc': True, 'args': [], 'eta': None, 'timelimit': (None, None), 'group': None, 'chord': None, 'is_eager': False, 'task': 'demo.tasks.make_error', 'correlation_id': 'e71f726c-a896-4545-a9d6-0397155d6b13', 'id': 'e71f726c-a896-4545-a9d6-0397155d6b13', 'kwargs': {}, 'callbacks': None, 'hostname': 'celery@machine.local'}) kwargs:{})
[2015-07-06 19:20:25,452: DEBUG/MainProcess] Task accepted: demo.tasks.make_error[e71f726c-a896-4545-a9d6-0397155d6b13] pid:40212
[2015-07-06 19:20:25,452: ERROR/MainProcess] Task demo.tasks.make_error[e71f726c-a896-4545-a9d6-0397155d6b13] raised unexpected: SomeError('That happened.')
Traceback (most recent call last):
  File "/tmp/.virtualenvs/celery-bug/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/tmp/.virtualenvs/celery-bug/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/tmp/sample/demo/tasks.py", line 17, in make_error
    raise SomeError('That happened.')
demo.errors.SomeError: Sample error - That happened.
```

Not a single mention of the underlying `ValueError`, which should be attached in the `SomeError.__context__`.

**Comment by Daenyth** [comment] 2016-01-12 13:37
I think I'm seeing this as well; my python log contains an exception (#2997) but the cause isn't showing up.

flower does show the full trace in my case

**Comment by ask** [comment] 2016-01-12 20:55
In 4.,0 the logging happens in the child process, so the pickled exception shouldn't be used for storing results.

**Comment by ask** [comment] 2016-06-24 00:21
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Closed by ask** 2016-06-24 00:21 UTC
Labels: Issue Type: Enhancement, Python Version: Python 3
