### ISSUE TITLE
Feature: Beat should avoid concurrent invocations

### ISSUE THREAD

**Issue by charles-dyfis-net** [celery/celery#251] opened 2010-11-17 16:03 UTC
Requiring the user to ensure that only one instance of celerybeat exists across their cluster creates a substantial implementation burden (either creating a single point-of-failure or encouraging users to roll their own distributed mutex).

celerybeat should either provide a mechanism to prevent inadvertent concurrency, or the documentation should suggest a best-practice approach.

**Comment by jaredkerim** [comment] 2015-01-06 17:04
@ingmar Thanks for this!  I'm going to give this a shot on my worker cluster.

**Comment by patrickwolf** [comment] 2015-06-22 18:00
+10 as the current implementation means a single point of failure which goes away from why we use a distributed queue in the first place

**Comment by aldarund** [comment] 2016-01-07 18:32
+1

**Comment by amirrustam** [comment] 2016-01-10 09:14
+1

Looks like this is going to be in v5.0.0 https://github.com/celery/celery/milestones/v5.0.0

**Comment by maxicecilia** [comment] 2016-05-25 22:01
+1

**Comment by ask** [comment] 2016-06-23 23:26
Closing this, as with current resources it will take 10 years to complete.

**Closed by ask** 2016-06-23 23:26 UTC
Labels: Component: Celerybeat, Issue Type: Feature Request

**Comment by ze-phyr-us** [comment] 2016-06-24 05:17
Sorry, but this is a serious problem for a so-called "distributed" queue. However long this will take to implement, it should eventually be fixed. Closing a perfectly valid issue because you don't have the resources *right now* does not seem right. Could you perhaps re-open it and apply a label that indicates that it's low priority at the moment?

**Comment by ask** [comment] 2016-06-24 05:56
I know my reason for closing was absurdly abrupt, so as a user of software I can understand your sentiment, but technically Beat is more like an add on feature.  It's completely decoupled from the rest of Celery, and it was intentionally designed to be non-distributed to keep the implementation simple. It started as a neat way of defining cronjobs from Python as a bonus for users already using Celery, then more and more people used Celery as a cron replacement.

The issue has been open for SIX years now, and even though it's requested often, and countless companies are depending on it, none have ever offered to pay for an implementation of it.

It was actually one of the issues I figured would be interesting for companies to sponsor.  Granted it's not like it's common for companies to offer to pay for any feature, bug fix, or even for helping to solve a production issue.  I can probably count them on one hand (you are awesome), so now I know how utterly naive that idea was :)

I closed a duplicate of this issue today also, see #1495.  There have been pull requests trying to solve the issue, and several are promising, but given the dedication required to prove that a given implementation works I still have not had the time to review them properly.  Maybe this springs someone into action, even if not I think it's better than keeping a feature request open for six years, when nobody is working on it.  That's also a sort of disservice to users who want to see this fixed.

**Comment by ze-phyr-us** [comment] 2016-06-25 08:02
@ask Fair enough. It is true that distributed cron is a big complicated problem, like you say in the other thread. And it does sound like something that should live outside of Celery.

Thank you for taking the time to explain your reasoning in detail.

**Comment by mikeschaekermann** [comment] 2016-11-05 07:30
@ask I was wondering if this problem might be circumvented by locating the `celerybeat-schedule` file (used by `celery.beat.PersistentScheduler`) inside a NFS volume that's shared across all nodes in the cluster?

The `PersistentScheduler` class uses `shelve` as a database module, so concurrent writes to the `celerybeat-schedule` file should be prevented by design. This is an excerpt from the `shelve` [documentation](https://docs.python.org/dev/library/shelve.html#restrictions):

> The shelve module does not support concurrent read/write access to shelved objects. (Multiple simultaneous read accesses are safe.) When a program has a shelf open for writing, no other program should have it open for reading or writing.

Assuming we start celery beat like this:

```
celery -A project-name beat -l info -s /nfs_shared_volume/celerybeat-schedule
```

where `/nfs_shared_volume` is the shared volume (e.g., managed by AWS Elastic File System), can we expect that schedules will not be messed up even if there is one celery beat process running on every node in the cluster?

**Comment by ze-phyr-us** [comment] 2016-11-05 11:50
@mikeschaekermann If I am reading the docs correctly `shelve` makes no effort to prevent concurrent write access. It just tells you not to let it happen. The section you quoted goes on to say "Unix file locking can be used to solve this, but this differs across Unix versions and requires knowledge about the database implementation used."

**Comment by mikeschaekermann** [comment] 2016-11-05 21:15
@ze-phyr-us I think you're right, and I misinterpreted the `shelve` docs. Still, I'm wondering if the problem would be solved assuming the `Scheduler` backend ensures **atomic** operations on the schedule? @ask does the `django-celery-beat` [package](https://github.com/celery/django-celery-beat) support atomicity to solve the problem? I saw that it does use transactions to do some of the updates.

**Comment by ddevlin** [comment] 2017-11-05 16:41
For anyone else who ends up here while searching for a distributed / auto-scaling friendly celery beat, and is happy to use Redis as a backend; I tried both BeatCop and single-beat mentioned above, but ultimately picked [RedBeat](https://github.com/sibson/redbeat).

**Comment by ankur11** [comment] 2018-08-06 11:12
Hi ddevlin
I am having similar issues, what problems did you face while using single-beat? Also if its not too much, could you please share the implementation sample of how you configured redbeat for multiple servers.

**Comment by ddevlin** [comment] 2018-08-07 08:59
@ankur11 single-beat ensures that only one instance of celery beat is running, but doesn't synchronise the schedule state between instances. 

If I used the default scheduler with a periodic task intended to run every 15 minutes, and had a failover with single-beat 14 minutes after the last time the task ran, the task wouldn't run until 15 minutes after the the new celery beat instance started, resulting in a 29 minute gap.

To share the schedule state between instances I needed to use an [alternative scheduler](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#using-custom-scheduler-classes). [django-celery-beat](https://pypi.org/project/django_celery_beat/) is the alternative mentioned in the Celery docs, but my preference was to use Redis as the backend for schedule syncing, since I was already using Redis as my Celery backend. 

Redbeat includes both Redis backed shared schedule state and locking to ensure only one instance is scheduling tasks, so I didn't need single-beat or BeatCop once I started using that.

In our implementation celery beat is started by supervisord on all instances, with Redbeat as the scheduler (e.g. `exec celery beat --scheduler=redbeat.RedBeatScheduler --app=myproject.celery:app`). Unfortunately I can't share work-related code, but I'm happy to answer any additional questions about implementation in general.

**Comment by rrauenza** [comment] 2018-08-23 15:31
@mikeschaekermann you could try wrapping your celery beat with /use/bin/flock to lock the access ...

`flock /nfs/lock.file celery beat ...`

Assuming you trust your NFS lock implementation :)

This would ensure only one actually runs and the others block until the locker dies.

**Comment by swt2c** [comment] 2019-01-15 16:46
> @mikeschaekermann you could try wrapping your celery beat with /use/bin/flock to lock the access ...
>
> flock /nfs/lock.file celery beat ...
>
> Assuming you trust your NFS lock implementation :)
>
> This would ensure only one actually runs and the others block until the locker dies.

I tried this method.  Unfortunately, if the client holding the NFS lock loses connectivity to the NFS server, the lock can be revoked by the NFS server and given to another client.  When the original lock holder regains connectivity, flock doesn't realize that the lock has been revoked so now there are two nodes believing they are the 'leader.'

**Comment by rrauenza** [comment] 2019-01-15 22:18
I ended up using an advisory lock in Postgres.  I made a Django management command that uses the django_pglocks module and runs celery beat in a subprocess.

**Comment by swt2c** [comment] 2019-01-17 16:00
> I ended up using an advisory lock in Postgres. I made a Django management command that uses the django_pglocks module and runs celery beat in a subprocess.

This seems like it could be susceptible to the same issues that I saw with using NFS.  What happens if the client holding the lock loses connection with the Postgres server, or if the Postgres server is restarted?

**Comment by harisibrahimkv** [comment] 2019-02-20 06:54
@ddevlin I was glad to see your comment since that was the solution I was thinking of implementing as well.

However, if you could share the logic of how autorestarts `redbeat-1` when `redbeat-2` goes down, that'd be a great help.

This might be due to my lack of understanding regarding `supervisor`, but it seems the `autorestart=True` is effective only for programs that at least get into the `RUNNING` state once.

My problem is:
1. I have two `program` in my supervisor.conf of `celery beat` with `redbeat.RedBeatScheduler`.
2. Starting supervisor, one `beat` (`beat-1`) gets the lock and runs, while the other (`beat-2`) tries to start a couple of times and enters into the `FATAL` state.
3. Ideally, if `beat-1` stops, then I want supervisor to start `beat-2`.
4. However, that doesn't happen since it was never in a `RUNNING` state to begin with.

Off the top of my head, the solution would be to have a `cron` that keeps doing a `supervisorctl restart all` every 5 seconds or so, but just wanted to get your thoughts on how you were able to achieve that redundancy with supervisor.

**Comment by ddevlin** [comment] 2019-02-20 10:41
Hi @harisibrahimkv, your issue is that you're starting two identical instances of celery beat on the same host; I expect you're seeing `ERROR: Pidfile (celerybeat.pid) already exists.` in your logs for `beat-2`? I can see that having two instances of celery beat running on the same host would be useful for testing failover between them, but for real redundancy you probably want celery beat running on multiple hosts.

To get multiple instances running on the same host, have supervisor start them with the `--pidfile` argument and give them separate pidfiles: e.g.
```
# beat-1 
celery beat --scheduler=redbeat.RedBeatScheduler --pidfile="beat-1.pid" ...
# beat-2
celery beat --scheduler=redbeat.RedBeatScheduler --pidfile="beat-2.pid" ...
```
Both instances should start successfully under supervisor, but if you check the log files only one of them should be scheduling tasks. If you stop that instance you should see the other instance take over task scheduling.

Our goal was to have an auto-scaling pool of identical hosts running celery workers and celery beat under supervisor. Each host has a single celery beat instance. In this configuration, celery beat should successfully start on all hosts, but any instances of celery beat that don't acquire the lock will effectively be hot standbys and not schedule tasks. If the instance with the lock is stopped (for example when the pool is scaled down, or when we're doing a rolling upgrade of hosts in the pool), then one of the standby instances will acquire the lock and take over scheduling tasks.

**Comment by harisibrahimkv** [comment] 2019-02-21 02:01
@ddevlin Thank you so much for getting back to me and making the Internet such a wonderful place! Sincerely appreciate it! (was running around telling my entire family about your reply :D )

1. The `pidfile` bit worked and I was so so happy seeing `beat-2` take up the tasks when the other one stopped. Could configure the time of the beat with `CELERYBEAT_MAX_LOOP_INTERVAL = 25` (on celery 3.x).

2. Yes, for real redundancy, we plan to have this setup on different instances altogether. Thank you for explaining the setup that you were using. Going to work on that now. The "multiple host on the same instance" setup, as you rightly understood, was to just initially validate whether the concept of failover works with this supervisor setup.

Warm thanks,
From a little village at the southern most tip of the Indian subcontinent. :)
