### ISSUE TITLE
Celery group.apply_async().join() never returns

### ISSUE THREAD

**Issue by bakcsa83** [celery/celery#5040] opened 2018-09-07 10:45 UTC
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.6.6
billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:redis://localhost/

broker_url: 'amqp://guest:********@localhost:5672//'
result_backend: 'redis://localhost/'
- [ ] I have verified that the issue exists against the `master` branch of Celery.
   _I've installed Celery using pip._

## Environment
Miniconda - Python 3.6.6 (see requirements.txt for details below)
Debian 9 running in Virtualbox. VM Config: 4 cores and 8GB RAM
Redis 4.0.11
RabbitMQ 3.6.6 on Erlang 19.2.1

## Steps to reproduce
0. Install RabbitMQ and Redis, use default config.
1. Create conda environment using [requirements.txt](https://github.com/celery/celery/files/2360605/requirements.txt)

2. Save the script below as tasks.py
3. Start a worker: `celery -A tasks worker -l info`
4. Start python and call the `start()` function
```
>> from tasks import *
>> start(20,100)

```
tasks.py:
```
from celery import Celery
from celery import group
import time

app = Celery()
app.conf.update(
    broker_url='pyamqp://guest@localhost//',
    result_backend='redis://localhost',
)

@app.task
def my_calc(data):
    for i in range(100):
        data[0]=data[0]/1.04856
        data[1]=data[1]/1.02496
    return data

def compute(parallel_tasks):
    tasks=[]
    for i in range(parallel_tasks):
        tasks.append([i+1.3,i+2.65])

    job = group([my_calc.s(task) for task in tasks])
    results = job.apply_async().join()
    #results = job.apply_async().join(timeout=120)


def start(parallel_tasks,iterations):    
    for i in range(iterations):
        exec_time = int(round(time.time() * 1000))
        compute(parallel_tasks)
        exec_time =  int(round(time.time() * 1000)) - exec_time
        print('Iteration {} Exec time: {}ms'.format(i,exec_time))
```
## Expected behavior
The script should run without error even if the parallel_tasks value is relatively high.
## Actual behavior
Execution stops somewhere between the 5th and 12th iteration in the `start()` function. Note that the higher the `parallel_tasks` value the sooner process stuck. The example script runs just fine when  the `parallel_tasks` value is relatively low. (e.g. 4).  
If is set a timeout `results = job.apply_async().join(timeout=120)` it throws the following exception:
```
Traceback (most recent call last):
  File "/home/bakcsa/tools/miniconda3/envs/cel/lib/python3.6/site-packages/celery/backends/async.py", line 255, in _wait_for_pending
    on_interval=on_interval):
  File "/home/bakcsa/tools/miniconda3/envs/cel/lib/python3.6/site-packages/celery/backends/async.py", line 54, in drain_events_until
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bakcsa/work/awst/projects/qa4sm/celery-test/celery_test/tasks2.py", line 31, in start
    compute(parallel_tasks)
  File "/home/bakcsa/work/awst/projects/qa4sm/celery-test/celery_test/tasks2.py", line 25, in compute
    print(result.get(timeout=20))
  File "/home/bakcsa/tools/miniconda3/envs/cel/lib/python3.6/site-packages/celery/result.py", line 224, in get
    on_message=on_message,
  File "/home/bakcsa/tools/miniconda3/envs/cel/lib/python3.6/site-packages/celery/backends/async.py", line 188, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "/home/bakcsa/tools/miniconda3/envs/cel/lib/python3.6/site-packages/celery/backends/async.py", line 259, in _wait_for_pending
    raise TimeoutError('The operation timed out.')
celery.exceptions.TimeoutError: The operation timed out.
```

**Comment by alugowski** [comment] 2018-09-07 21:41
What makes you think the timeout isn't caused by the tasks simply taking more than 20 seconds to compute?

Especially with 4 cores, you'd expect task runtime to increase once you start to oversubscribe by using more than 4 parallel tasks.

**Comment by bakcsa83** [comment] 2018-09-07 22:06
Thanks for looking at the issue.

> What makes you think the timeout isn't caused by the tasks simply taking more than 20 seconds to compute?
1. See updated start() function. One iteration with 20 parallel tasks takes 60-100ms. 20 seconds is more than enough.
2. If I remove the timeout constraint the call never returns. 
3. The CPU usage of the worker drops to zero 20 seconds before the timeout.

**Comment by abhisheksurendran14** [comment] 2018-09-25 15:17
Hello, Even i am facing the same issue with redis backend. Can we confirm if this is an issue with the 4.2.1 so that we can use an earlier version in the meanwhile ?

**Comment by toddpi314** [comment] 2018-10-17 22:41
As referenced in https://github.com/celery/celery/issues/4925#issuecomment-410233096, just wait until the AsyncResult returns True for `ready()`

**Comment by charlescapps** [comment] 2018-12-07 01:08
We're experiencing a similar issue using Redis for backend and broker. I can't conceive of a way we would be getting deadlock, because we have two separate queues, and our topology is really simple: primary tasks kick off about 50 smaller tasks that run in a separate queue. That should make deadlock impossible.

**Comment by pembo13** [comment] 2019-04-12 02:27
Seeing the same problem, also have a Redis backend. Initially was on the latest Redis available, 3.2.x and thought maybe the Redis server was the issue. So I upgraded the Redis server to the latest 5.x available in Remi. 

The problem persists. Even more troubling, `asynresult.ready()` is `True` after I wait a more than generous timeout. Also, `successful()` is `True` and `completed_count()` matches the number of tasks in the group.

I'm on Python 3.6 if it matters. My broker is also Redis.

**Comment by pembo13** [comment] 2019-04-12 02:29
@toddpi314 #4925 (comment) is a poor solution though.

**Comment by fdoumet** [comment] 2019-05-09 02:16
@toddpi314, neither `asynresult.ready()` nor `asynresult.successful()` ever returns `True` for me. I just get stuck in the loop until timeout. I have verified that the tasks do indeed succeed.
Using `apply` instead of `apply_async` obviously works fine.

Any ideas?

**Comment by pembo13** [comment] 2019-05-10 05:24
I'm fairly sure that this is a duplicate of #4925

**Closed** 2019-05-10 05:26 UTC
Labels: Component: Canvas, Issue Type: Bug Report, Status: Duplicate ✘
