### ISSUE TITLE
Migrate from 3.1.25 to 4.0.0 (SQS)

### ISSUE THREAD

**Issue by jairhenrique** [celery/celery#3630] opened 2016-11-28 22:36 UTC
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

```bash
Django==1.10.3
boto==2.43.0
boto3==1.4.1
botocore==1.4.78

software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:2.7.6
            billiard:3.5.0.2 sqs:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqs results:disabled
```

## Steps to reproduce
Just a project upgrade dependency.

## Actual behavior
Celery work stops when start, only with `sqs` broker. My test environment run with `redis` broker and works fine.

With `... worker -l debug`, I can see my `sqs` queues and the worker stop with this message:

```
[2016-11-28 20:31:58,487: DEBUG/MainProcess] Canceling task consumer...
[2016-11-28 20:31:59,493: DEBUG/MainProcess] Canceling task consumer...
[2016-11-28 20:31:59,493: DEBUG/MainProcess] Closing consumer channel...
[2016-11-28 20:31:59,493: DEBUG/MainProcess] closing all HTTP connections
[2016-11-28 20:31:59,493: DEBUG/MainProcess] closing all HTTP connections
[2016-11-28 20:31:59,494: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
```

PS: The messages are delayed to queue normally.

**Comment by adamn** [comment] 2016-11-29 19:45
Same issue for me with Python 3.5.

```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.2
            billiard:3.5.0.2 sqs:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:sqs results:disabled
```

**Comment by adamn** [comment] 2016-11-29 19:59
In addition, in my debug I see `[2016-11-29 19:54:32,082: DEBUG/MainProcess] b'<?xml version="1.0"?><GetQueueAttributesResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><GetQueueAttributesResult><Attribute><Name>ApproximateNumberOfMessages</Name><Value>6</Value></Attribute></GetQueueAttributesResult><ResponseMetadata><RequestId>dc9f8aaa-62ae-5c59-bfcf-da1dbd96f5ba</RequestId></ResponseMetadata></GetQueueAttributesResponse>'` which indicates that it's getting the correct number of messages (6) but celery does nothing with them.  I've tried this with DEBUG on and off as well as `CELERY_TASK_CREATE_MISSING_QUEUES` on and off as well.  I'm using Django in case that's relevant.

**Comment by adamn** [comment] 2016-11-29 20:07
Not to spam everybody, but it should be noted that I'm using the pickle serializer explicitly:

```
    CELERY_ACCEPT_CONTENT = ['pickle']
    CELERY_TASK_SERIALIZER = 'pickle'
    CELERY_RESULT_SERIALIZER = 'pickle'
```

**Comment by mvantellingen** [comment] 2016-11-29 22:57
This seems to be a duplicate of #3221 right? The workaround there (using custom endpoints for boto) solved that/this error for me.

**Comment by jairhenrique** [comment] 2016-11-30 00:29
@mvantellingen I can't understand why it works on `3.1.25` and not on `4.0.0`.. the `boto` library is the same.

**Comment by ask** [comment] 2016-11-30 00:59
The SQS implementation in Celery 4 is completely rewritten to use async I/O.   It can be a while before I can dig down to debug this though.

**Comment by jairhenrique** [comment] 2016-11-30 16:39
@ask maybe migrating to `boto3` is a good idea!

**Comment by adamn** [comment] 2016-11-30 17:25
I think it would be great to move to `boto3` while 4 is still in the dot zero release.

[From the creator of boto](http://stackoverflow.com/a/32323454/26235) "The boto3 library is being actively developed by AWS and is the one I would recommend people use if they are starting new development."

**Comment by rafales** [comment] 2016-12-05 13:17
I had the same issue, but in my case my django logging configuration simply hid the error. So If you have any problem, try commenting out `LOGGING` configuration in django and running the worker again.

(In my case it was this error: `ImportError: The curl client requires the pycurl library.`)

**Comment by adamn** [comment] 2016-12-22 15:52
[This commit in Kombu](https://github.com/celery/kombu/commit/8104aed13096510374261529be87dddf8fc41316) should have gone out with the 4.0.2 release which should have fixed this.  I'm wondering if kombu's setup.py file isn't installing the packages in the `extras_require` dict?

Anyway, anybody using SQS needs to install `pycurl` explicitly for now.

**Comment by alejandrodnm** [comment] 2017-01-27 09:28
I had this problem and this is what I had to do to solve it in Centos 7.2 with python 3.5.

    > celery -A proj report

    software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.5.1
                billiard:3.5.0.2 sqs:N/A
    platform -> system:Linux arch:64bit, ELF imp:CPython
    loader   -> celery.loaders.app.AppLoader
    settings -> transport:sqs results:disabled


First what @rafales said applied also to my project, the django LOGGING was hiding the pycurl import error. I installed pycurl, but kept getting the import error, importing manually pycurl via the CLI gave me this message:

    > import pycurl
    ImportError: pycurl: libcurl link-time ssl backend (nss) is different from compile-time ssl backend (none/other)

From the pycurl installation docs:

    pip uninstall pycurl
    export PYCURL_SSL_LIBRARY=nss
    pip install pycurl

Then I got the host error from the boto endpoints (boto/endpoints.js), so I had to change them to:

    "sqs": {
        "ap-northeast-1": "sqs.ap-northeast-1.amazonaws.com",
        "ap-northeast-2": "sqs.ap-northeast-2.amazonaws.com",
        "ap-south-1": "sqs.ap-south-1.amazonaws.com",
        "ap-southeast-1": "sqs.ap-southeast-1.amazonaws.com",
        "ap-southeast-2": "sqs.ap-southeast-2.amazonaws.com",
        "ca-central-1": "sqs.ca-central-1.amazonaws.com",
        "cn-north-1": "sqs.cn-north-1.amazonaws.com.cn",
        "eu-central-1": "sqs.eu-central-1.amazonaws.com",
        "eu-west-1": "sqs.eu-west-1.amazonaws.com",
        "eu-west-2": "sqs.eu-west-2.amazonaws.com",
        "sa-east-1": "sqs.sa-east-1.amazonaws.com",
        "us-east-1": "sqs.us-east-1.amazonaws.com",
        "us-east-2": "sqs.us-east-2.amazonaws.com",
        "us-gov-west-1": "sqs.us-gov-west-1.amazonaws.com",
        "us-west-1": "sqs.us-west-1.amazonaws.com",
        "us-west-2": "sqs.us-west-2.amazonaws.com"
    },

**Comment by diwu1989** [comment] 2017-03-27 00:01
`pyCurl` is really difficult to install compared to using `requests`
is there any way to not use pycurl and instead use a http library that's easier to install?

**Comment by adamn** [comment] 2017-03-27 16:35
@diwu1989 You should do a PR on Kombu if you want that changed.  I think it would be a good change but Celery using `pyCurl`, Kombu is.

**Closed** 2017-12-20 07:48 UTC
Labels: Component: Amazon SQS Broker, Version: 4.0
