### ISSUE TITLE
Async code in eager mode cause "Never call result.get() within a task!"

### ISSUE THREAD

**Issue by kstachniuk** [celery/celery#5126] opened 2018-10-19 09:41 UTC
Celery version 4.2.0

I want to get results of tasks in group.
In development i'm using a CELERY_ALWAYS_EAGER=True. 
If i run code below:

```
@shared_task
def task_in_group():
    return "something"

@shared_task
def task_finishing_chain(results):
    return results

@shared_task
def task_launcher():
    chain_tasks = chain(
        group(
            task_in_group.si(),
            task_in_group.si()
        ),
        task_finishing_chain.s())
    chain_tasks.apply_async()

def run_tasks():
    task_launcher.apply_async()
```

then i'm getting the following exception:

<pre>
Task my_app.tasks.task_in_group[36c33a48-3047-4be8-82f1-70b985e87980] succeeded in 0.00011961600012000417s: 'something'
Task my_app.tasks.task_in_group[1e3a13c3-fbb7-4535-bf68-3f988a331a42] succeeded in 3.561300013643631e-05s: 'something'
Task my_app.tasks.task_launcher[0fbbae47-f3fc-4a2d-b2ce-b10c8e91182c] raised unexpected: RuntimeError('Never call result.get() within a task!\nSee http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks\n',)
Traceback (most recent call last):
  File "/home/vagrant/python35/lib/python3.5/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/vagrant/my_app/tasks.py", line 268, in task_launcher
    chain_tasks.apply_async()
  File "/home/vagrant/python35/lib/python3.5/site-packages/celery/canvas.py", line 1230, in apply_async
    body=body, task_id=task_id, **options)
  File "/home/vagrant/python35/lib/python3.5/site-packages/celery/canvas.py", line 1239, in apply
    args=(tasks.apply(args, kwargs).get(propagate=propagate),),
  File "/home/vagrant/python35/lib/python3.5/site-packages/celery/result.py", line 671, in get
    on_interval=on_interval,
  File "/home/vagrant/python35/lib/python3.5/site-packages/celery/result.py", line 722, in join
    assert_will_not_block()
  File "/home/vagrant/python35/lib/python3.5/site-packages/celery/result.py", line 41, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
</pre>

On production everything works normally with CELERY_ALWAYS_EAGER=False.

**Comment by kstachniuk** [comment] 2018-10-19 09:42
Also if i run same code with calling `task_launcher` as a normal function (without apply_async) 
```
def run_tasks():
    task_launcher()
```
then error is not occurring.

**Comment by slavab89** [comment] 2018-11-04 17:05
Seems like a duplicate of https://github.com/celery/celery/issues/4661

**Closed** 2018-11-22 06:55 UTC
