### ISSUE TITLE
Celery error calling add_consumer randomly ocurrs

### ISSUE THREAD

**Issue by jclark360** [celery/celery#3751] opened 2017-01-08 23:39 UTC
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).

  
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Call add_consumer in celery control randomly from a worker that's been up for awhile.  It seems to happen after a worker has been up for a day or so.  For us it's happening every day.

Code:

```
celery_app.control.add_consumer(
                queue.name,
                exchange='foo',
                destination=['foo-worker@foo.com']
            )
```

## Expected behavior
That consumers are always added after the call..

## Actual behavior
The exception below is thrown:

```
File "/usr/lib/python3.5/site-packages/celery/app/control.py", line 293, in add_consumer
    **kwargs
  File "/usr/lib/python3.5/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/usr/lib/python3.5/site-packages/kombu/pidbox.py", line 315, in _broadcast
    serializer=serializer)
  File "/usr/lib/python3.5/site-packages/kombu/pidbox.py", line 285, in _publish
    with self.producer_or_acquire(producer, chan) as producer:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.5/site-packages/kombu/pidbox.py", line 247, in producer_or_acquire
    with self.producer_pool.acquire() as producer:
  File "/usr/lib/python3.5/site-packages/kombu/resource.py", line 74, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: Acquire on closed pool
```

Celery report:

```
software -> celery:4.0.1 (latentcall) kombu:4.0.1 py:3.5.2
            billiard:3.5.0.2 py-amqp:2.1.3
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

event_queue_ttl: 60
task_acks_late: True
task_always_eager: False
task_create_missing_queues: True
task_default_queue: 'default'
include: ['crawler_service.crawlers.reviews',
 'crawler_service.crawlers.product',
 'crawler_service.crawlers.facet_discovery',
 'crawler_service.crawlers.discovery',
 'crawler_service.crawlers.zone_discovery',
 'crawler_service.crawlers.crawler_stats',
 'crawler_service.crawl_scheduler.schedule_task']
task_soft_time_limit: 300
beat_schedule: {
    'every-30s': {   'args': '',
                     'schedule': datetime.timedelta(0, 30),
                     'task': 'crawler_service.crawlers.crawler_stats.crawler_stats_rollup'},
    'every-60s': {   'args': '',
                     'schedule': datetime.timedelta(0, 60),
                     'task': 'crawler_service.crawlers.crawler_stats.crawler_health_check'},
    'every-day': {   'args': '',
                     'schedule': datetime.timedelta(1),
                     'task': 'crawler_service.crawlers.crawler_stats.crawler_stats_cleanup'}}
broker_transport_options: {
 'confirm_publish': True}
result_serializer: 'json'
task_serializer: 'json'
worker_max_tasks_per_child: 30000
broker_heartbeat: 30
task_routes: <crawler_service.celery.router.CrawlerRouter object at 0x7fc43f8b56a0>
worker_redirect_stdouts_level: 'DEBUG'
broker_url: 'amqp://*******:********@foo.com:5672//'
task_queues:
    (<unbound Queue scheduled_tasks -> <unbound Exchange scheduled_tasks(direct)> -> scheduled_tasks>,
 <unbound Queue crawl_scheduler -> <unbound Exchange crawl_scheduler(direct)> -> crawl_scheduler>)
accept_content: ['json']
task_time_limit: 500
```

**Comment by jclark360** [comment] 2017-01-09 13:06
Also, this error started after we upgraded to celery 4.

**Comment by jclark360** [comment] 2017-01-17 01:19
Looks like 4.0.2 might have fixed this, haven't seen the error in a week.

**Comment by kichooo** [comment] 2017-01-23 22:45
I keep getting this on celery 4.0.2, but only after system is productive for some time, so better watch

**Comment by elephanter** [comment] 2017-02-22 08:35
I call celery_app.control.revoke and in production sometimes i get " Acquire on closed pool"
   File "/usr/lib/python2.7/site-packages/celery/app/control.py", line 210, in revoke
   File "/usr/lib/python2.7/site-packages/celery/app/control.py", line 436, in broadcast
   File "/tmp/pip-build-YNwIXB/kombu/kombu/pidbox.py", line 315, in _broadcast
   File "/tmp/pip-build-YNwIXB/kombu/kombu/pidbox.py", line 285, in _publish
   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
   File "/tmp/pip-build-YNwIXB/kombu/kombu/pidbox.py", line 247, in producer_or_acquire
   File "/tmp/pip-build-YNwIXB/kombu/kombu/resource.py", line 74, in acquire
 RuntimeError: Acquire on closed pool

celery: 4.0.2
kombu: 4.0.2

Maybe the reason is when worker in shutdown/restart process it received and run task anyway. If that task used pool - it failed

**Comment by jclark360** [comment] 2017-02-24 01:27
I'm reopening this, this error still happens at random

**Comment by failedguidedog** [comment] 2017-03-22 23:21
+1
I'm seeing the same thing too. Sometimes running a retry logic around this gets it done, but a lot of such actions fail anyway.

python: 3.4.3
celery: 4.0.2
kombu: 4.0.2
pool: eventlet & prefork

**Comment by jcccss** [comment] 2017-06-15 11:51
+1

Python: 2.7
billiard: 3.5.0.2
celery: 4.0.2
kombu: 4.0.2

It happens really soon after checking tasks using query_task, scheduled, reserved and active sequentially (unless one of the method provides an anwser).

**Comment by jsynowiec** [comment] 2017-08-11 12:38
Same problem encountered after running worker process for a bit over a day (c.a. 1.2k jobs processed).

```
celery:4.1.0 (latentcall)
kombu:4.1.0
py:2.7.11
billiard:3.5.0.3
librabbitmq:1.6.1
```

RabbitMQ + Redis as backend store.

Worker started with `--autoscale=30,2 -Ofair`

**Comment by syre** [comment] 2017-10-03 08:02
I am getting this also when trying to revoke a task:
```python
File "/srv/publish/prod/code/publish/celery_publish.py", line 22, in revoke_task
    app.control.revoke(task_id)
  File "/srv/publish/prod/env/local/lib/python2.7/site-packages/celery/app/control.py", line 210, in revoke
    }, **kwargs)
  File "/srv/publish/prod/env/local/lib/python2.7/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/srv/publish/prod/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 315, in _broadcast
    serializer=serializer)
  File "/srv/publish/prod/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 285, in _publish
    with self.producer_or_acquire(producer, chan) as producer:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/srv/publish/prod/env/local/lib/python2.7/site-packages/kombu/pidbox.py", line 247, in producer_or_acquire
    with self.producer_pool.acquire() as producer:
  File "/srv/publish/prod/env/local/lib/python2.7/site-packages/kombu/resource.py", line 74, in acquire
    raise RuntimeError('Acquire on closed pool')
```
RabbitMQ as backend store
worker started with: `celery worker --loglevel=INFO --statedb=celery-worker-state -n "worker.%%h" --task-events --max-tasks-per-child=100`
```
python 2.7.9
celery==4.1.0
kombu==4.0.2
billiard==3.5.0.2
```

**Comment by syre** [comment] 2017-10-16 11:15
It seems for us the problem disappeared when removing the `--max-tasks-per-child` option

**Comment by kotfic** [comment] 2017-10-24 14:15
We are also seeing this issue when calling revoke.  I have bandwidth to debug this issue. Can anyone reliably reproduce the conditions in a test environment (i.e. more than run worker "for awhile")?

**Comment by auvipy** [comment] 2017-12-20 15:26
removing the --max-tasks-per-child option work for this issue? If you can relate more related issues that would be easier for tracing the bug

**Comment by syre** [comment] 2017-12-21 08:29
@auvipy yes when removing the `--max-tasks-per-child` from the worker launch options, we no longer get the error when trying to revoke a task.

**Comment by jsynowiec** [comment] 2017-12-22 07:20
@auvipy Not using `--max-tasks-per-child` is a workaround, not a solution. Why did you close this issue if there is still a bug resulting in `Acquire on closed pool` errors. It's also happening in other scenarios. I've tried to describe in detail what I'm observing in https://github.com/celery/celery/issues/3085#issuecomment-321283237

**Comment by neaket360pi** [comment] 2017-12-22 18:57
I created a project to reproduce the `Acquire on closed pool` error most of the time.  I noticed that once the `Acquire on closed pool` error occurs, it will continue to occur every-time until the process is restarted.

It seems like https://github.com/celery/kombu/blob/master/kombu/resource.py#L139 might be getting called at the wrong time and setting `_closed =True`

See instructions in README.md in 
https://github.com/neaket360pi/celery_issue_3751

Observations:
- Setting `max_tasks_per_child` is required
- Needing multiple celery worker processes might be required

Error Log:
```
[2017-12-22 18:45:49,197: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2017-12-22 18:45:51,207: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...

/usr/local/lib/python3.6/site-packages/celery/platforms.py:795: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2017-12-22 18:45:56,447: ERROR/ForkPoolWorker-1] Error - to delete queue new_queue_322
Traceback (most recent call last):
  File "/src/celery_app.py", line 72, in delete_rabbitmq_queue
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Object Not Found for url: http://rabbitmq:15672/api/queues/%2f/new_queue_322
[2017-12-22 18:45:56,601: ERROR/ForkPoolWorker-4] Error - to delete queue new_queue_312
Traceback (most recent call last):
  File "/src/celery_app.py", line 72, in delete_rabbitmq_queue
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Object Not Found for url: http://rabbitmq:15672/api/queues/%2f/new_queue_312
[2017-12-22 18:45:56,607: ERROR/MainProcess] Control command error: ConnectionResetError(104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/pidbox.py", line 42, in on_message
    self.node.handle_message(body, message)
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 129, in handle_message
    return self.dispatch(**body)
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 112, in dispatch
    ticket=ticket)
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 135, in reply
    serializer=self.mailbox.serializer)
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 265, in _publish_reply
    **opts
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 194, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 194, in <listcomp>
    [maybe_declare(entity) for entity in declare]
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 102, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/usr/local/lib/python3.6/site-packages/kombu/common.py", line 129, in maybe_declare
    return _maybe_declare(entity, declared, ident, channel, orig)
  File "/usr/local/lib/python3.6/site-packages/kombu/common.py", line 135, in _maybe_declare
    entity.declare(channel=channel)
  File "/usr/local/lib/python3.6/site-packages/kombu/entity.py", line 185, in declare
    nowait=nowait, passive=passive,
  File "/usr/local/lib/python3.6/site-packages/amqp/channel.py", line 616, in exchange_declare
    wait=None if nowait else spec.Exchange.DeclareOk,
  File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 258, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
[2017-12-22 18:45:56,655: ERROR/ForkPoolWorker-5] Error - to delete queue new_queue_319
Traceback (most recent call last):
  File "/src/celery_app.py", line 72, in delete_rabbitmq_queue
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Object Not Found for url: http://rabbitmq:15672/api/queues/%2f/new_queue_319
[2017-12-22 18:45:56,718: ERROR/ForkPoolWorker-6] Task celery_app.remove_queue[44c17c37-d7be-47d2-aca9-3f4d95eaa78b] raised unexpected: RuntimeError('Acquire on closed pool',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/src/celery_app.py", line 34, in remove_queue
    queue_name
  File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 304, in cancel_consumer
    arguments={'queue': queue}, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 315, in _broadcast
    serializer=serializer)
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 285, in _publish
    with self.producer_or_acquire(producer, chan) as producer:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 247, in producer_or_acquire
    with self.producer_pool.acquire() as producer:
  File "/usr/local/lib/python3.6/site-packages/kombu/resource.py", line 74, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: Acquire on closed pool
[2017-12-22 18:45:56,763: ERROR/ForkPoolWorker-7] Task celery_app.remove_queue[a1812f5c-1c28-442a-b94c-e141ec32822b] raised unexpected: RuntimeError('Acquire on closed pool',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/src/celery_app.py", line 34, in remove_queue
    queue_name
  File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 304, in cancel_consumer
    arguments={'queue': queue}, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 315, in _broadcast
    serializer=serializer)
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 285, in _publish
    with self.producer_or_acquire(producer, chan) as producer:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 247, in producer_or_acquire
    with self.producer_pool.acquire() as producer:
  File "/usr/local/lib/python3.6/site-packages/kombu/resource.py", line 74, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: Acquire on closed pool
```

**Comment by auvipy** [comment] 2017-12-23 10:16
@neaket360pi thanks for your effort. any thought on fix? pr most welcome

**Comment by neaket360pi** [comment] 2017-12-27 23:34
I will probably have time to look into this issue in the new year.   I still have to investigate the issue some more before suggesting or making a fix.

Next steps will be to see if forking is raising some unexpected exceptions in Celery or Kombu.  
I am guessing the `_after_fork_cleanup_resource` code in Kombu is doing something unexpected.
```
    try:
        resource.force_close_all()
    except Exception:
        pass
```

**Comment by neaket360pi** [comment] 2018-01-03 16:32
I found the problem and made a possible fix in https://github.com/celery/kombu/compare/master...neaket360pi:fix-producer-pool-after-fork?expand=1

I will likely have to refactor my fix and move it fully into the Celery project to be consistent with other `_after_fork_cleanup_resource` functions.


Scenario.
1. Master Worker uses the Mailbox to send a message.  (Mailbox.producer_pool is cached)
2. Celery forks a new worker (Mailbox.producer_pool is closed but not recreated)
3. Celery worker sends a message (RuntimeError: Acquire on closed pool)

**Closed** 2018-02-03 14:20 UTC
Labels: Issue Type: Task, Status: Feedback Needed ✘, Status: Needs Verification ✘
