### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by mvaled** [celery/celery#3798] opened 2017-01-27 21:01 UTC
I'm using Celery 4.0.2. I'm embedding the Celery Worker Controller into my [own server](https://github.com/merchise-autrement/odoo/blob/merchise-8.0/openerp/service/server.py#L990).  Thus my server process spawns a process called DefaultCeleryWorker which embeds the WorkerController, and this process spawns the PoolWorkers.  

I noticed that some of the PoolWorker are dying (possible cause being killed by OOM - though not confirmed) and not being reaped by the parent process and kept lurking around.  I noticed that the Controller is being awaked because of the SIGKILL of the children:

```
$ sudo strace -p 2461
[sudo] password for manu: 
Process 2461 attached
recvfrom(83, 0x3447660, 65536, 0, 0, 0) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=2471, si_status=SIGKILL, si_utime=9236, si_stime=186} ---
recvfrom(83, 0x3447660, 65536, 0, 0, 0) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=2475, si_status=SIGKILL, si_utime=11292, si_stime=230} ---
recvfrom(83, 
```

The 83 fd is the Redis connection.

Flower shows the worker as offline after this point.

Do I need to do something more to properly embed the WorkerController into my own process?

The following a screenshot showing one Z process.

![screenshot from 2017-01-27 15-23-54](https://cloud.githubusercontent.com/assets/270825/22386793/ab294d10-e4a6-11e6-9c17-a079143482b8.png)

**Comment by auvipy** [comment] 2018-01-17 15:36
hope the issue is resolved in master. report if not

**Closed by auvipy** 2018-01-17 15:36 UTC

**Comment by mvaled** [comment] 2018-01-17 21:05
Hi @auvipy 

I stopped embedding the WorkerController in my own processes.  I should have closed this myself.  Thanks.

**Comment by auvipy** [comment] 2018-01-18 04:33
thanks for clarifying :)
