### ISSUE TITLE
supervisord run got the error 'pkg_resources.DistributionNotFound: meld3>=0.6.5'

### ISSUE THREAD

**Issue by will835559313** [celery/celery#3444] opened 2016-09-14 05:57 UTC
I install supervisor-3.3.1 use pip on centos6.5 
when I run supervisord I got the error please help me !

```
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5

```

**Comment by will835559313** [comment] 2016-09-14 06:27
I know how to resolve this error
upgrade the setuptools
```
pip install --upgrade setuptools
```
and then everything is ok

**Comment by berkerpeksag** [comment] 2016-09-18 17:35
Thanks for the report. Without further information. this doesn't like an issue caused by or in Celery. Since you've already mentioned a workaround, I'm closing this.

**Closed by berkerpeksag** 2016-09-18 17:35 UTC
