### ISSUE TITLE
Calling AsyncResult.get() on task with ignore_result=True making DEADLOCK

### ISSUE THREAD

**Issue by wbar** [celery/celery#2652] opened 2015-06-14 12:45 UTC
This is example code of tasks:

    from celery.app.log import get_logger as task_logger
    t_log = task_logger(__name__)

    @task(ignore_result=True)
    def error_task():
        raise Exception('deadlock example')

    @task
    def error_log(task_id):
        result = AsyncResult(task_id)
        try:
            with allow_join_result():  # only to suppress warning
                result.get(propagate=False, timeout=1)
        except TimeoutError as e:
            t_log.error('Dead lock detected!')

Calling those tasks in this way:

    error_task.apply_async(link_error=error_log.s())

Makes deadlock. I think that calling `AsyncResult.get()` for `task_id` doesn't look at `ignore_result=True` flag and waits until `timeout`:

    [2015-06-14 12:36:56,016: INFO/MainProcess] Received task: spark_etl.tasks.error_task[a36d1da5-208d-4386-ab20-b659478bf74f]
    [2015-06-14 12:36:56,033: INFO/MainProcess] Received task: spark_etl.tasks.error_log[b91c8fca-8bf3-4119-8409-5314abae4256]
    [2015-06-14 12:36:56,034: ERROR/MainProcess] Task spark_etl.tasks.error_task[a36d1da5-208d-4386-ab20-b659478bf74f] raised unexpected: Exception('deadlock example',)
    Traceback (most recent call last):
      File "/home/bartosak/.virtualenvs/spark/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
        R = retval = fun(*args, **kwargs)
      File "/home/bartosak/.virtualenvs/spark/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
        return self.run(*args, **kwargs)
      File "/home/bartosak/Projekty/RP/spark_etl/tasks.py", line 377, in error_task
        raise Exception('deadlock example')
    Exception: deadlock example
    [2015-06-14 12:36:57,508: ERROR/Worker-2] Dead lock detected!
    [2015-06-14 12:36:57,525: INFO/MainProcess] Task spark_etl.tasks.error_log[b91c8fca-8bf3-4119-8409-5314abae4256] succeeded in 1.4897235730022658s: None

**Comment by thedrow** [comment] 2015-06-14 13:10
The problem with ignore_result might be that is also ignores exceptions as well.
I think it's by design though. Any suggestions on how to fix this issue?

**Comment by wbar** [comment] 2015-06-14 14:21
>  The problem with ignore_result might be that is also ignores exceptions as well.

No. Celery detects error and starting error callback correctly.

I think the solution might be quite simple. When applying `get()` on object `AsyncResult`received from tasks with `ignore_result` should instantly return and `result` should be `Null`. 

Look at this example:

    @task(ignore_result=True)
    def step_error_ignore_result(*args, **kwargs):
        a = 1/0

Ipython console:

    In[1]: result = tasks.step_error_ignore_result.delay()
    In[2]: result
    Out[2]: <AsyncResult: f11dac64-62ed-40e2-9511-55d5e4e54f64>
    In[3]: result.id
    Out[3]: 'f11dac64-62ed-40e2-9511-55d5e4e54f64'
    In[4]: result.get(propagate=False, timeout=1)
    Traceback (most recent call last):
      File "/home/bartosak/.virtualenvs/spark/lib/python3.4/site-packages/celery/backends/amqp.py", line 155, in wait_for
        on_interval=on_interval)
      File "/home/bartosak/.virtualenvs/spark/lib/python3.4/site-packages/celery/backends/amqp.py", line 231, in consume
        conn, consumer, timeout, on_interval)[task_id]
      File "/home/bartosak/.virtualenvs/spark/lib/python3.4/site-packages/celery/backends/amqp.py", line 210, in drain_events
        raise socket.timeout()
    socket.timeout

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/bartosak/.virtualenvs/spark/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 3035, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-7-9b54fc24a41c>", line 1, in <module>
        result.get(propagate=False, timeout=1)
      File "/home/bartosak/.virtualenvs/spark/lib/python3.4/site-packages/celery/result.py", line 169, in get
        no_ack=no_ack,
      File "/home/bartosak/.virtualenvs/spark/lib/python3.4/site-packages/celery/backends/amqp.py", line 157, in wait_for
        raise TimeoutError('The operation timed out.')
    celery.exceptions.TimeoutError: The operation timed out.

**Comment by ask** [comment] 2016-06-24 00:11
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Closed by ask** 2016-06-24 00:11 UTC
Labels: Status: Has Testcase, Worker Hangs
