### ISSUE TITLE
Django 2/3 only one post_save generated celery signal received each time model is saved

### ISSUE THREAD

**Issue by soerendip** [celery/celery#6204] opened 2020-06-30 21:27 UTC
I use multiple post_save functions to trigger different celery (4.8.3) tasks and tried django 2 and 3. For some strange reason celery stopped executing all tasks in parallel instead only one task gets received each time model is saved. To run all the tasks, I have to save the model multiple times. It was working before and I have no idea why the behavior changed all of a sudden. 

I am starting the queue with: 

    celery -A appname worker -l info -E

My post save functions:

    @receiver(models.signals.post_save, sender=RawFile)
    def execute_rawtools_qc(sender, instance, created, *args, **kwargs):
        rawtools_qc.delay(instance.path, instance.path)
    
    @receiver(models.signals.post_save, sender=RawFile)
    def execute_rawtools_metrics(sender, instance, created, *args, **kwargs):
        rawtools_metrics.delay(instance.abs_path, instance.path)

And my tasks:

    @shared_task
    def rawtools_metrics(raw, output_dir):
        cmd = rawtools_metrics_cmd(raw=raw, output_dir=output_dir)
        os.system(cmd)
    
    @shared_task    
    def rawtools_qc(input_dir, output_dir):
        cmd = rawtools_qc_cmd(input_dir=input_dir, output_dir=output_dir)
        os.system(cmd)

Before those tasks where executed in parallel as soon as the model was saved. Now, the first task gets executed when the model instance is saved, and the second instance is executed the second time the model is saved. And then the functions alternate each time. Any idea what may cause this strange behavior?

UPDATE: I think both task are executed randomly, but only one for each save. 

Also, there are no other celery workers running. 

https://stackoverflow.com/questions/62665094/django-2-3-only-one-post-save-generated-celery-signal-received-each-time-model-i

**Comment by auvipy** [comment] 2021-02-18 17:14
which version of celery it was working & which isn't working?

**Comment by thedrow** [comment] 2021-03-29 09:33
Celery 4.8?

**Comment by thedrow** [comment] 2021-03-29 09:38
Everything here seems to be in order and there's not enough information to reproduce this problem.
I'm closing this issue for now.
If you can provide more details, please comment and we will re-evaluate.

**Closed by thedrow** 2021-03-29 09:38 UTC
Labels: Component: Django, Issue Type: Bug Report

**Comment by soerendip** [comment] 2021-04-25 16:38
Sorry, I lost track of it.
