### ISSUE TITLE
Getting results from RPC result backend failed according to the order of retrieval

### ISSUE THREAD

**Issue by gus-kimjihyeon** [celery/celery#3111] opened 2016-03-11 01:26 UTC
Hi,
I'm using celery 3.1.18 and Django 1.8.7 with gevent monkey patching.
RPC is used as result backend and RabbitMQ version is 3.5.6

The issue I have is that task results have gone away from time to time in live environment.
So, I made simple test code as below.

```
results = []
for idx in xrange(0, 10):
    results.append(some_task.delay(arg1, arg2... ))
```

And then, tried to get task results from the array in various ways.

If results are taken from the end, there’s no issue.
For example,
results[9].get()
results[8].get()
results[7].get()
...

But, if results are taken from the beginning, it's not possible to get whole results.
For example,
results[0].get()
results[1].get()
results[2].get()
...

results[0].get() always succeeds but from results[1] or results[2], get() call returns nothing
(just pending without timeout or timeout error with timeout)
Sometimes results[1].get() call succeeds. I’m not sure the reason.

As investigated, all results are taken at once when first get() is called regardless of the order.

If get() is called from the end, results[0~8] are cached. (all results are cached until wanted result is returned)
So, subsequent calls (results[8].get(), results[7].get()… ) have no issue.

But if get() call starts from the beginning, nothing cached because first call returns wanted result and,
result queue in RabbitMQ changed to empty state. (results[1~9] are abandoned)
So, subsequent call cannot return anything.

Related module is celery.backends.amqp.py

I’m not sure if this behaviour is intended.

**Comment by ask** [comment] 2016-03-17 02:06
Could you try the development version instead?

I've radically refactored how this works, so that there is one consumer that persists between calls,
and I would like to focus on getting things to work properly for 4.0.

**Comment by gus-kimjihyeon** [comment] 2016-03-21 02:25
Thanks for confirming.
I'll try to test with development version.

**Comment by ask** [comment] 2016-06-24 01:07
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Closed by ask** 2016-06-24 01:07 UTC
Labels: Component: RPC Results Backend

**Comment by davidhalter** [comment] 2018-06-10 08:34
I can confirm that this was fixed in 4.1. I was able to reproduce it in 3.1 even with just two task executions.

Thank you for fixing it!

The only thing I would ask for the future is that you guys add these "known" issues to the documentation. It is extremely surprising that this doesn't work, especially, because this seems to be the goto result backend for celery. I know that 3.1 came out a while ago and it's not maintained anymore, but two years ago you could have added a warning :)

**Comment by auvipy** [comment] 2018-06-10 10:41
please keep in mind that with limited resource we are also struggling to support 4.x branch too!

**Comment by davidhalter** [comment] 2018-06-10 21:59
No worries man. I know how you guys must feel from maintaining Jedi. It's just that a small warning sometimes prevents people from opening new tickets, so you might make your own lives easier as well.

Thank you for your work anyway.

**Comment by auvipy** [comment] 2018-06-11 06:03
thanks for your inputs

**Comment by auvipy** [comment] 2018-06-11 06:04
you can open an issue for suggesting your developer experience improving suggestions to cep repo

**Comment by davidhalter** [comment] 2018-06-11 07:55
@auvipy Don't get me wrong, I think it's now too late for the celery 3.1 branch. It was more of a general suggestion for you guys that instead of closing such an "important" ticket you should probably have added a warning in the docs. It's probably too late now, because everyone is going to use 4.1, so you're fine :)

**Comment by auvipy** [comment] 2018-06-11 08:57
I am not getting you wrong, from now one we can do this for 4..x branch as we will kick star v5 soon so

**Comment by auvipy** [comment] 2018-06-11 08:58
if you can send patch against v3 i will take care of it
