### ISSUE TITLE
Workers appear to stall, but sending a management message causes them to continue. 

### ISSUE THREAD

**Issue by vietord** [celery/celery#1960] opened 2014-04-08 01:27 UTC
I'm running into an issue where some of my worker processes will stop processing new tasks, causing them to pile up on the queue server. Left alone it will sometimes clear, and sometimes grow to impact all workers, effectively blocking processing. 

However, if I issue a management command, such as "celery inspect scheduled" it will cause workers to resume operation immediately. Although sometimes only briefly before halting again. 

**The setup:**
* celery 3.1.9
* kombu 3.0.12
* amqp 1.4.4
* RabbitMQ (3.1.3) / ampq for all communication and results.
* Mid-sized config: 7 worker nodes, 13 queues for service differentiation, and about 40 total worker processes per worker node.   
* Nodes are running the prefork worker, with 1-8 processes per queue, depending on the queue.
* CELERYD_PREFETCH_MULTIPLIER = 1
* CELERY_ACKS_LATE = True
* CELERYD_MAX_TASKS_PER_CHILD = 16
* I'm using -Ofair, as even within a given queue some tasks may take very different times to execute. Overall task per second throughput has never been an issue.
* Example command line:
>python /home/celeryworker/web/manage.py celery worker --without-gossip --loglevel=INFO -Q transcode -Ofair -c 2 -n celery-worker-7-prod_transcode

I believe it may have to do with scheduled tasks, as everytime I've been able to catch it in action there have been a fairly large number of tasks waiting for a countdown to expire. On the order of the total number of task slots available for that queue (I'm counting 7 workers, listening with -c4 on a queue, and a prefetch multiplier of 1 to be 28 task slots)

I have not been able to confirm if the rabbitmq channel prefetch value is being correctly incremented when this issue is occurring and there are scheduled tasks; though it is being correctly incremented by scheduled tasks during normal operation. (I'll double check that the next time this recurs.)

In general the above config is doing exactly what I expect; one task per worker process, multiple tasks per node, and the next task coming out of the queue as soon as any given worker is no longer busy. It's only occasionally that things go off the rails and, one node at a time, new tasks will no longer be executed. (Other processes listening on other queues on that node will continue to work, or fail, independently.)

**Comment by ibushong** [comment] 2015-06-18 02:22
I believe I'm running into this very issue. Any follow ups?

I was using a dedicated EC2 instance for my RabbitMQ server before, but now I'm trying things out with CloudAMQP. I just have one worker running and I have a particular task that is delayed by an hour. It seems that when the worker restarts after a few of these tasks have been queued up (Unacked), it (not sure of proper terminology here) releases them back to RabbitMQ (Ready), and then when it starts back up, RabbitMQ reports that a few have gone back to Unacked (it seems to max out at 4), but I don't see any indication via the celery worker console that the task has been received.

Under some conditions (still haven't nailed it down), when I restart the worker, the clog appears to free up and the tasks come rushing through. Note that some of the tasks that are blocked are non-delayed tasks.

I'm a celery/RabbitMQ noob, so not sure how else I can be helpful, but just wondering how I can debug this.

**Comment by ask** [comment] 2015-10-23 00:05
I haven't been able to reproduce the issue myself, but maybe I can try with --without-heartbeat

**Comment by aehlke** [comment] 2016-01-11 16:03
Just to note, we're running into this issue. All of worker processes (each consuming a different queue) on our one Celery machine stall; then we run `manage.py celery events -d` and it reliably causes them to continue immediately. Will post with more details.

**Comment by ask** [comment] 2016-01-12 23:39
Looks like a duplicate of #1847, are you running Celery 3.1.19?

**Comment by aehlke** [comment] 2016-01-13 17:04
@ask 3.1.18. We'll try that out, thanks!

**Comment by dankilman** [comment] 2016-02-28 21:45
I've run some tests on using Celery 3.1.20 and reached the following conclusions:
The fix applied here
https://github.com/celery/celery/blob/v3.1.20/celery/worker/loops.py#L53 solves most cases but leaves the following, unsolved:
If the number of tasks waiting in queue is smaller or equal to prefetch_count (which will always hold if prefetch_multiplier is set to 0), then celery will consume all messages from the queue. The applied fix the in the link above will trigger a single task processing, but because all tasks are already consumed, there will be no other task to "release" them and get the event loop going. In which case, only sending additional application or admin tasks will "fix" the state.

In my tests, I have `--without-mingle`, removing this flag (and enabling mingle), solves this issue, although in my use case, I prefer disabling it.

I'll admit I did not go though the entire thread in this issue, but I did do so in #1847. I believe these are similar issues. It should be noted that I am able to easily reproduce the different scenarios by writing tasks with a client while no worker is running, and then starting a worker.

I'll be happy to supply additional details if you find it necessary, I would do so now, but I'm not sure what you'll find useful.

Thanks!

**Comment by koizo** [comment] 2016-05-09 11:43
Hello

I am having the same problem.
Using RabbitMQ and Celery 3.1.10 with Ofair, if i have many scheduled tasks, the workers hangs at startup:

[2016-05-09 12:01:12,512: INFO/MainProcess] Received task: app.tasks.start[dbedecb2-e23f-4cbb-9be2-e87547273680] eta:[2016-05-10 21:52:46+01:00]
[2016-05-09 12:01:12,513: INFO/MainProcess] Received task: app.tasks.start[2acc22ba-91f8-4a3b-a76b-e4fb5e403663] eta:[2016-05-10 21:59:48+01:00]

The only workaround is to increase the number of workers.

Best regards

**Comment by ask** [comment] 2016-06-23 23:39
Closing this, as we don't have the resources to complete this task.

**Closed by ask** 2016-06-23 23:39 UTC
Labels: Issue Type: Bug, Worker Hangs

**Comment by koizo** [comment] 2016-07-04 21:09
Is there any workarround for this?
We still have the same problem. Only increasing the number of workers solves the problem

**Comment by ak58** [comment] 2017-05-10 17:20
@koizo How did you solve that problem? I am having same problem whether I use `Rabbitmq` or `Redis`. My workers hang and do nothing unless I increase the number of workers. I am currently using `Celery 4.0.2`.
How can I overcome this issue?
