### ISSUE TITLE
relation "task_id_sequence" does not exist when SQLAlchemy is configured as the result backend

### ISSUE THREAD

**Issue by RyanBalfanz** [celery/celery#3213] opened 2016-05-17 18:16 UTC
The Exception is thrown when using postgresql, but not when using sqlite.

```
CELERY_BROKER_URL=redis://redis
CELERY_RESULT_BACKEND=db+postgresql://postgres:postgres@db/postgres
```

```
worker_1  | [2016-05-17 09:32:07,886: CRITICAL/MainProcess] Task composeexample.celery.debug_task[49b2046c-2619-4ad7-9b3b-ad67ea4f0c03] INTERNAL ERROR: ProgrammingError('(psycopg2.ProgrammingError) relation "task_id_sequence" does not exist\nLINE 1: ...us, result, date_done, traceback) VALUES (nextval(\'task_id_s...\n                                                             ^\n',)
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 283, in trace_task
worker_1  |     uuid, retval, SUCCESS, request=task_request,
worker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/backends/base.py", line 271, in store_result
worker_1  |     request=request, **kwargs)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/backends/database/__init__.py", line 63, in _inner
worker_1  |     return fun(*args, **kwargs)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/celery/backends/database/__init__.py", line 125, in _store_result
worker_1  |     session.flush()
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
worker_1  |     self._flush(objects)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
worker_1  |     transaction.rollback(_capture_exception=True)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
worker_1  |     compat.reraise(exc_type, exc_value, exc_tb)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
worker_1  |     raise value
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
worker_1  |     flush_context.execute()
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
worker_1  |     rec.execute(self)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
worker_1  |     uow
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
worker_1  |     mapper, table, insert)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
worker_1  |     execute(statement, params)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 914, in execute
worker_1  |     return meth(self, multiparams, params)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
worker_1  |     return connection._execute_clauseelement(self, multiparams, params)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
worker_1  |     compiled_sql, distilled_params
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
worker_1  |     context)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
worker_1  |     exc_info
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
worker_1  |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
worker_1  |     raise value.with_traceback(tb)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
worker_1  |     context)
worker_1  |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
worker_1  |     cursor.execute(statement, parameters)
worker_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "task_id_sequence" does not exist
worker_1  | LINE 1: ...us, result, date_done, traceback) VALUES (nextval('task_id_s...
worker_1  |                                                              ^
worker_1  |  [SQL: "INSERT INTO celery_taskmeta (id, task_id, status, result, date_done, traceback) VALUES (nextval('task_id_sequence'), %(task_id)s, %(status)s, %(result)s, %(date_done)s, %(traceback)s) RETURNING celery_taskmeta.id"] [parameters: {'result': None, 'status': 'PENDING', 'date_done': datetime.datetime(2016, 5, 17, 9, 32, 7, 831590), 'task_id': '49b2046c-2619-4ad7-9b3b-ad67ea4f0c03', 'traceback': None}]
```

``` shell
(.venv) ➜  pip freeze
amqp==1.4.9
anyjson==0.3.3
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
billiard==3.3.0.23
celery==3.1.23
decorator==4.0.9
dj-database-url==0.4.1
Django==1.9.6
django-celery==3.1.17
flower==0.9.1
ipython==4.2.0
ipython-genutils==0.1.0
kombu==3.0.35
pexpect==4.0.1
pickleshare==0.7.2
psycopg2==2.6.1
ptyprocess==0.5.1
pytz==2016.4
redis==2.10.5
requests==2.10.0
simplegeneric==0.8.1
SQLAlchemy==1.0.13
tornado==4.2
traitlets==4.2.1
```

**Comment by ask** [comment] 2016-05-23 21:49
hmm, I'm not sure why this would happen.

It's weird that a sequence is being defined for the primary key at all, doesn't seem like something a sane API would require by default.

**Comment by NotANormalNerd** [comment] 2016-06-22 11:56
I have the same issue with an Oracle Database:
On the Worker side:
```
[2016-06-22 13:20:49,606: WARNING/Worker-11] Failed operation _store_result. Retrying 2 more times.
Traceback (most recent call last):
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/celery/backends/database/__init__.py", line 63, in _inner
    return fun(*args, **kwargs)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/celery/backends/database/__init__.py", line 125, in _store_result
    session.flush()
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/users/dschmala/.virtualenvs/tp_transfer_worker/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (cx_Oracle.DatabaseError) ORA-02289: sequence does not exist
 [SQL: 'INSERT INTO celery_taskmeta (id, task_id, status, result, date_done, traceback) VALUES (task_id_sequence.nextval, :task_id, :status, :result, :date_done, :traceback) RETURNING celery_taskmeta.id INTO :ret_0'] [parameters: {'status': 'PENDING', 'task_id': u'48db1f51-3475-44f6-af45-f8c887f60e7f', 'date_done': datetime.datetime(2016, 6, 22, 11, 20, 49, 603309), 'traceback': None, 'result': None, 'ret_0': <cx_Oracle.NUMBER with value None>}]
```

I am using the SQLAclhemy Backend on the Worker side and the django-celery:DatabaseBackend on the Django side.

I already found [this](http://stackoverflow.com/questions/35775342/using-sqlalchemy-with-oracle-and-flask-to-create-sequences-for-primary-keys) but I don't know if this applies.

I also did the migrations with djcelery.

**Comment by vnavkal** [comment] 2017-06-06 03:43
I don't suppose anyone made any progress on this?  I think I'm seeing the same error with Celery 4.0.2, SQLAlchemy 1.1.10, Django 1.11, and PostgreSQL.

I'll post here if I figure anything out.

**Comment by vnavkal** [comment] 2017-06-13 20:28
In my case, this seems to have been caused by the following sequence of events:
1. A while ago, some combination of an old Celery version, django-celery, and an old SQLAlchemy version created a `celery_taskmeta` table but no sequence called `task_id_sequence`.
2. django-celery was eventually removed, and Celery and SQLAlchemy were upgraded.  Celery was reconfigured not to use any result backend.
3. Celery was configured to use the database as the result backend.  But the database didn't have the structure that Celery expected (in particular, `task_id_sequence` didn't exist, and I think `celery_taskmeta` also didn't have the same structure that Celery uses now), so this error occurred.

I resolved this by removing the old `celery_taskmeta` and `celery_tasksetmeta` tables before configuring Celery to save task results in the database.  It seems like Celery tries to create those tables, with the correct structure, when they don't already exist, so I now have the tables with the correct structure.

**Comment by ranjith19** [comment] 2018-07-10 15:15
@vnavkal Which versions of celery and SQLALchemy do you have?

**Comment by vnavkal** [comment] 2018-07-11 18:46
@ranjith19 I did end up getting Celery 4.0 and subsequently 4.1 to work after following the instructions I posted.  I don't remember what SQLAlchemy version I ended up with.  I'm no longer using Celery or SQLAlchemy.

**Comment by auvipy** [comment] 2021-10-30 09:47
i am closing his for now.

**Closed by auvipy** 2021-10-30 09:47 UTC
Labels: Status: Not a Bug, NEEDS HELP, Issue Type: Documentation, Component: SQLAlchemy Database Results Backend, Status: Needs Verification ✘, Sprint Candidate
