### ISSUE TITLE
celery beat: OSError: [WinError 87]

### ISSUE THREAD

**Issue by emmanuelobo** [celery/celery#4638] opened 2018-04-04 16:49 UTC
Suddenly I started getting this error when I run celery beat

```
celery beat -A proj 
```

Funny thing is that celery worker still runs but beat doesn't.
I'm running version 4.1 (latest version) btw.

```
celery beat v4.1.0 (latentcall) is starting.
OSError: [WinError 87] The parameter is incorrect
...
SystemError: <class 'OSError'> returned a result with an error set
```

**Comment by thedrow** [comment] 2018-04-09 09:35
We cannot reproduce this with the information you provided.
If you'd like, provide more information and a reproducible test case and I'll try to help.

In the meanwhile, this issue is closed.

**Comment by na387** [comment] 2018-07-06 19:09
This error occurs from: celery/platforms.py:199 (remove_if_stale)
```
try:
    os.kill(pid, 0)
except OSError as exc: # os.error as exc:
    if exc.errno == errno.ESRCH:
        print('Stale pidfile exists - Removing it.', file=sys.stderr)
        self.remove()
        return True
```

It can be fixed by catching SystemError and wiping the pidfile, e.g:
```
SystemError as exc:
    print(exc.__repr__())
    print('Stale pidfile exists - Removing it.', file=sys.stderr)
    self.remove()
    return True
```

but Im not entirely sure how this error was triggered originally as I cannot seem to reproduce it now.

**Comment by auvipy** [comment] 2018-07-07 07:50
can you send a PR?

**Closed** 2018-08-12 13:08 UTC
Labels: Issue Type: Bug, Operating System: Windows
