### ISSUE TITLE
ImportError: No module named utils

### ISSUE THREAD

**Issue by pigletfly** [celery/celery#2197] opened 2014-08-18 09:16 UTC
I am using celery 3.1.13 on mac OS X 10.9.4.The traceback is below.
```
Traceback (most recent call last):
  File "test_email.py", line 4, in <module>
    add.delay(4,4)
  File "/Library/Python/2.7/site-packages/celery/local.py", line 143, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Library/Python/2.7/site-packages/celery/local.py", line 221, in _get_current_object
    return self.__evaluate__()
  File "/Library/Python/2.7/site-packages/celery/local.py", line 251, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/Library/Python/2.7/site-packages/celery/local.py", line 101, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/celery/app/base.py", line 259, in _task_from_fun
    base = options.pop('base', None) or self.Task
  File "/Library/Python/2.7/site-packages/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/Library/Python/2.7/site-packages/celery/app/base.py", line 575, in Task
    return self.create_task_cls()
  File "/Library/Python/2.7/site-packages/celery/app/base.py", line 485, in create_task_cls
    keep_reduce=True, abstract=True,
  File "/Library/Python/2.7/site-packages/celery/app/base.py", line 503, in subclass_with_self
    Class = symbol_by_name(Class)
  File "/Library/Python/2.7/site-packages/kombu/utils/__init__.py", line 92, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/celery/app/task.py", line 26, in <module>
    from celery.utils.mail import ErrorMail
  File "/Library/Python/2.7/site-packages/celery/utils/mail.py", line 11, in <module>
    import smtplib
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 46, in <module>
    import email.utils
ImportError: No module named utils
```

**Comment by thedrow** [comment] 2015-06-19 10:22
Can you guys try the latest version of Celery and tell me if you can still reproduce this?

**Comment by hussaintamboli** [comment] 2015-10-12 06:12
Hey guys, any update on this? I am having the same issue.

**Comment by thedrow** [comment] 2015-10-13 07:10
Is it reproducible with the latest celery version?

**Comment by hussaintamboli** [comment] 2015-10-13 08:34
Actually I just resolved the issue yesterday. It's weird.

I had a python package named `email` in the same directory as my celery workers. When I renamed it to `mail`, the issue was gone.

**Comment by ask** [comment] 2015-10-13 23:36
That's probably it.

Python implicit relative imports are evil.  It's fixed in Python 3, but in Python you have to add `from __future__ import absolute_import` to the top of modules to get the new behavior.

If you have this error, then look for a module named "email.py" in your path.

**Closed by ask** 2015-10-13 23:36 UTC
Labels: Status: Feedback Needed

**Comment by thedrow** [comment] 2015-10-14 05:47
@ask is this documented properly?

**Comment by ask** [comment] 2015-10-14 20:10
It's not a bug in celery, it's just python.  We don't have any way of protecting against it, and it's not specific to the "email" name.  The name `base64` in that traceback is just as likely to cause problems
if you add a "base64.py" module in the toplevel path.

**Comment by ask** [comment] 2015-10-14 20:17
And in that case is not even related to relative imports as far as I can tell.  It will actually be an absolute import, caused by the order in `sys.path` preferring the local version to the one in the stdlib.

Example:



Try this:

    $ echo "print('hello')" > base64.py
    $ python -c'import smtplib'
    hello

    $ rm base64.py base64.pyc
    $ echo "print('hello')" > email.py
    $ python -c"import smtplib"
    hello
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 46, in     <module>
        import email.utils
    ImportError: No module named utils
    $ rm email.py email.pyc
