### ISSUE TITLE
kwargs and args are getting strip in celery flower and unable to serialize for manual retry

### ISSUE THREAD

**Issue by yrvnthvrm** [celery/celery#5080] opened 2018-09-27 18:02 UTC
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
```
@task
def foo(text):
    print(text)
 >>> foo.delay('H' * 1021)
```

## Expected behavior
![screen shot 2018-09-27 at 2 01 06 pm](https://user-images.githubusercontent.com/36310977/46165126-d10f7b80-c25d-11e8-8154-186c4062770b.png)

## Actual behavior
![screen shot 2018-09-27 at 1 58 56 pm](https://user-images.githubusercontent.com/36310977/46165092-b9d08e00-c25d-11e8-8dbf-dc75f1febf5b.png)

@ask  Can you help me out here?

**Comment by jheld** [comment] 2018-11-18 17:12
This may be down in the safe_repr or similar method. I'm interested, too!

**Comment by auvipy** [comment] 2019-05-06 07:48
is it a flower issue or celery? @mher

**Comment by mher** [comment] 2019-05-06 09:41
Celery strips long args/kwargs before sending events

**Comment by auvipy** [comment] 2019-05-06 09:51
If you allow, I would like to help collaborate on flower repo as a co-maintainer. I have the bandwidth for celery related projects. @mher

**Comment by mher** [comment] 2019-05-08 10:00
Sure, shoot me an email. I will help you with the setup, etc.

**Comment by auvipy** [comment] 2019-05-08 10:02
May I get your email?

**Comment by mher** [comment] 2019-05-08 10:11
mher.movsisyan at gmail

**Comment by jheld** [comment] 2019-05-08 10:47
There is a way to adjust the repr length on the worker, at start up.

Additionally, with the new extended results feature (celery 4.3), you can store all of this correctly in the task meta output in the result backend. But this is reliant on how long you would keep the output (long expirey).

**Comment by auvipy** [comment] 2019-05-30 06:21
so what is the resolution of the issue? should we close this?

**Comment by jheld** [comment] 2019-05-30 11:05
The way this seems to me, it is not a bug (deficiency/how celery events was designed), and increasing the repr sizes on the workers or enabling the extended results on the workers (and optionally using that here for retry), would suffice.

**Comment by sp1rs** [comment] 2019-07-22 16:55
@jheld  How can we increase repr size of workers?

@auvipy Isn't the docs should come in flower repo?

**Comment by jheld** [comment] 2019-07-23 00:40
Not easy to find.

in `celery.app.amqp` you'll find `argsrepr_maxsize` etc. If you set this at an __init__ in your project's startup, you can adjust it/them.

**Closed** 2019-08-08 08:21 UTC
Labels: Category: Documentation, Issue Type: Bug Report
