### ISSUE TITLE
ALWAYS_EAGER: TypeError: run() got multiple values for keyword argument 'header'

### ISSUE THREAD

**Issue by jonblack** [celery/celery#2546] opened 2015-03-20 08:46 UTC
I have a complex nested workflow that works fine until `CELERY_ALWAYS_EAGER` is set to `True` (which is required for testing). Then I get the following error:

    Traceback (most recent call last):
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/behave/model.py", line 1456, in run
        match.run(runner.context)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/behave/model.py", line 1903, in run
        self.func(context, *args, **kwargs)
      File "tests/features/steps/report.py", line 47, in step_create_report
        r = context.app.post('api/create/', data=payload)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/werkzeug/test.py", line 772, in post
        return self.open(*args, **kw)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/flask/testing.py", line 108, in open
        follow_redirects=follow_redirects)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/werkzeug/test.py", line 736, in open
        response = self.run_wsgi_app(environ, buffered=buffered)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/werkzeug/test.py", line 659, in run_wsgi_app
        rv = run_wsgi_app(self.application, environ, buffered=buffered)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/werkzeug/test.py", line 855, in run_wsgi_app
        app_iter = app(environ, start_response)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/jon/projects/hope-flask/hope/middleware.py", line 36, in __call__
        return self.app(environ, start_response)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/jon/projects/hope-flask/hope/frontend/api/endpoints.py", line 38, in create
        form.mutation.data)
      File "/home/jon/projects/hope-flask/hope/domain/report/__init__.py", line 36, in create_report
        report_id = _create_report(sequence, position, mutant)
      File "/home/jon/projects/hope-flask/hope/domain/report/__init__.py", line 147, in _create_report
        result = workflow.delay()
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/canvas.py", line 175, in delay
        return self.apply_async(partial_args, partial_kwargs)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/canvas.py", line 504, in apply_async
        add_to_parent=add_to_parent)
      File "/home/jon/projects/hope-flask/hope/factory.py", line 169, in __call__
        return TaskBase.__call__(self, *args, **kwargs)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/app/task.py", line 422, in __call__
        return self.run(*args, **kwargs)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/app/builtins.py", line 161, in run
        [stask.apply(group_id=group_id) for stask in taskit],
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/canvas.py", line 181, in apply
        return self.type.apply(args, kwargs, **options)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/app/builtins.py", line 371, in apply
        args=(res.get(propagate=propagate).get(), ))
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/canvas.py", line 522, in apply
        return Signature.apply(self, *args, **kwargs)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/canvas.py", line 181, in apply
        return self.type.apply(args, kwargs, **options)
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/app/builtins.py", line 202, in apply
        **options).get()
      File "/home/jon/.virtualenvs/hope-flask/local/lib/python2.7/site-packages/celery/result.py", line 870, in get
        raise self.result
    TypeError: run() got multiple values for keyword argument 'header'

The workflow itself looks like this:

```python
workflow = group(
    chord(
        tasks.blast_pdb.s(report_id, sequence, position),
        group(
            chord(
                tasks.get_structure_features.s(report_id, sequence,
                                               position),
                group(
                    tasks.get_hssp_features.s(report_id),
                    tasks.create_stills.s(report_id, position, mutation),
                    tasks.create_movies.s(report_id, position, mutation)
                )
            ),
            tasks.get_pisa_features.s(report_id)
        )
    ),
    chord(
        tasks.blast_swissprot_uniprot.s(report_id, sequence, position),
        group(
            tasks.get_esp_features.s(report_id),
            tasks.get_uniprot_features.s(report_id),
            tasks.get_reprof_features.s(report_id)
        )
    ),
    tasks.get_interpro_features.s(report_id, sequence)
)
```

I'm using celery 3.1.17 and using the behave test framework.

**Comment by ask** [comment] 2015-05-06 15:42
My advice is to start using mocks instead of eager for testing.

With eager you are merely testing the emulation path anyway, and the emulation is only used for testing so it's pretty much useless.

So:

- Test each individual unit (function)

- Mock the tasks used in each unit

As for this particular issue, I'm not sure what the header argument is for, so hard to tell

**Comment by thedrow** [comment] 2015-07-13 07:18
Can you please provide a working test case we can use to reproduce your problem and see if it's a bug in celery?

**Comment by opensrcken** [comment] 2015-09-17 03:57
This is a real issue. I have spent some time trying to debug this, but am quite stuck, and if I get time, I will add a failing test. But I hope by providing some of the details of what I've witnessed, a core dev will know what's wrong.

In eager mode, when invoking `celery.canvas.chord` with the second argument being another chord, recursively, the `run` method on the `Chord` class, as defined in builtins.py, is being called with `header` twice.

In my tracing, I've noticed that in `trace.py`, under trace_task, in some cases that I do not yet understand, `args` takes on a value of `([None])`, which is being passed into the `run` method in the position of the `header` argument, causing the error as reported.

**Comment by opensrcken** [comment] 2015-09-17 04:01
I have a stronger hunch now. It appears that this error starts occurring when `chord`'s are nested at least 3 levels deep.

**Comment by atin65536** [comment] 2016-02-20 08:40
+1 For this.
Possible workaround is passing `immutable=True` into the chord method.

**Comment by meteozond** [comment] 2016-02-20 08:41
+1

**Comment by tayfun** [comment] 2016-06-07 16:38
I don't think `immutable=True` is a good workaround because that means the chord cannot be used as a partial.

I find that the latest master doesn't have this problem but 3.1.23 does. Here's a simple test case:

```python
from celery import Celery, chain, chord
app = Celery()

@app.task
def noop(*args):
    pass

noop_task = app.tasks['__main__.noop']
first_chord = chord(header=[noop_task.s(), noop_task.s()], body=noop_task.s())
second_chord = chord(header=[noop_task.s(), noop_task.s()], body=noop_task.s())
first_level_chord = chord(header=[first_chord, second_chord], body=noop_task.s())
my_chain = chain(noop_task.s(), first_level_chord)
my_chain.apply()
```

This results in **TypeError: run() got multiple values for argument 'header'**.

**Comment by ask** [comment] 2016-06-07 18:17
If it's fixed in master then we should close, as we really need to focus on finishing 4.0.  At this point we don't even know the number of open issues that are already fixed in master, and we could spend ages fixing them again, or get the release out the door.

**Comment by tayfun** [comment] 2016-06-08 11:38
Fair enough :)

**Comment by tayfun** [comment] 2016-06-09 15:02
I'm sorry, I thought master worked, but it only did not throw an error. In master also arguments for chord were not handed over correctly in eager mode. I've created #3245 for master and #3244 for the current issue.

**Comment by ask** [comment] 2016-06-24 00:08
Closing this, as we don't have the resources to complete this task.

Please don't use ALWAYS_EAGER, mock your tests instead.

**Closed by ask** 2016-06-24 00:08 UTC
Labels: Component: Eager mode

**Comment by tayfun** [comment] 2016-06-24 12:19
Hello @ask , I think I fixed this partly in https://github.com/celery/celery/pull/3244 but also introduced a bug, which I think is fixed in https://github.com/celery/celery/pull/3269

Let me know what you think.
