### ISSUE TITLE
can't set max_retries parameter to None on retry

### ISSUE THREAD

**Issue by michaelvmata** [celery/celery#2781] opened 2015-08-24 04:59 UTC
If a Task object has a non None value for max_retries, we can't set max_retries to None when raising a retry.  The retry method uses None as a default value, so it falls back to the Task's current max_retries value.

**Comment by ask** [comment] 2015-09-04 20:26
Thanks! This is an issue that is not easily fixed and it's a duplicate of #1875 (see reasoning there)

**Closed by ask** 2015-09-04 20:26 UTC
Labels: Status: Duplicate
