### ISSUE TITLE
Group tasks' results order getting messed up when using redis

### ISSUE THREAD

**Issue by nitheeshas** [celery/celery#3781] opened 2017-01-23 07:36 UTC
I upgraded to celery v4.0.2 from an old v3.x version and now I'm facing a weird issue with groups.
So here is my tasks file to reproduce the issue:

```python
from celery import group, chord
from worker import app


@app.task(name='task')
def task(i):
    return i


@app.task(name='dummy')
def dummy(result):
    print result


@app.task(name='mainTask')
def mainTask():
    groupTask = group([task.s(i) for i in range(0,10)])
    job = chord(groupTask, dummy.s())()
    return job
```

The expected output of the variable `result` is:

> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

and this is indeed what I'm getting when using `amqp` as result backend. But when I use `redis`, the output gets messed up. Basically, the redis backend is serving the results in the order the group tasks get finished, and not in the order its assigned. A sample would be:

> [0, 1, 2, 3, 4, 8, 6, 9, 7, 5]

Is there something I'm missing? I've posted the same thing over in [stackoverflow](http://stackoverflow.com/questions/41800124/celery-v4-group-task-behaviour-with-redis-backend) as well.

**Comment by georgepsarakis** [comment] 2017-02-11 10:28
I think I found why this is happening. If you check the code of the Redis backend, you can see [here](https://github.com/celery/celery/blob/master/celery/backends/redis.py#L260) that the results are pushed in a Redis list. When [all results have been gathered](https://github.com/celery/celery/blob/master/celery/backends/redis.py#L272), the chord callback is executed, fetching the Redis list, without any other re-ordering. With parallel execution, the order of the results in the list will not be deterministic and the sequence of the stored results will be the same with the task execution sequence.

So, I am guessing that in order to maintain the order, the code would have to keep track of the sequence of the tasks when storing them in a Redis structure. Perhaps [sorted sets](https://redis.io/commands/zadd) could be a solution here, setting the score to the task's group sequence index for example.

However, I am not sure that generally the order of task results from a group is guaranteed to be preserved by design, since they are executed in parallel, or if this happens to be a side-effect of the AMQP backend.

**Comment by nitheeshas** [comment] 2017-02-13 05:41
Thank you for replying! Now it makes sense. But I actually forgot to mention one more point here. Redis, with Celery v3.x works properly, with the exact order of task results. So now I'm thinking, in the older version, celery might have been sending the results to backend, in the order its been assigned. But in v4.x, that process changed to sending the results in the order the task finishes.

Anyway, I finally used something similar to what you had mentioned to maintain the order. It seems like a dirty fix, but does the job.

**Comment by georgepsarakis** [comment] 2017-02-13 07:21
Yes, there were a lot of [changes](https://github.com/celery/celery/compare/3.1...4.0#diff-accb7090ee45fffb2262cbceeabef002) in the Redis backend between these two versions.

**Comment by teehamaral** [comment] 2017-03-13 21:18
I'm with the same issue. But my celery version is 3.x yet and I have some queues running. How did you start your celery workers? I already tested many options, but I didn't have success yet.

**Comment by nitheeshas** [comment] 2017-03-14 07:24
@teehamaral It works sometimes, just because it was coincidental. If you have less number of groups, then its more likely that the results might come in correct order, but this will not always be the case. If you check the sample I had provided, the first 4 group tasks returned in same order and only after that, the order got messed up.

To get rid of this problem, I just assigned an index to all the group tasks while calling it and, returned this index along with the task's results. Later, when all the group tasks were finished, I just sorted the results according to that index. A totally dirty solution, but couldn't come up with anything else since it was an urgent requirement for me.

But, I'm not sure how you got this problem in v3.x though.

**Comment by auvipy** [comment] 2018-01-17 15:33
closing now. will revisit after v4.2 release

**Closed by auvipy** 2018-01-17 15:33 UTC
Labels: Component: Redis Results Backend, Status: Needs Verification ✘

**Comment by benjolitz** [comment] 2018-02-16 18:53
This bug just took a giant bite out of my ass. I ended up rolling back to v3 to buy time.

It really, really should be documented that the order of a group() result is effectively random and should not be depended on in any circumstance.

**Comment by thedrow** [comment] 2018-02-18 12:48
I'm sorry you had a bad user experience with Celery.
Feel free to issue a PR with the necessary documentation changes.

**Comment by benjolitz** [comment] 2018-02-18 19:15
I get a distinct feel that this project doesn't take seriously downstream problems. From reading the other bug report, it seems this overall problem is more likely a "Wont-Fix" that's been that way for a few months. If it wasn't a severe enough problem to document then, I don't see the call to action now. I'll have to focus on more integration tests instead.

**Comment by thedrow** [comment] 2018-02-19 08:14
It's not that we don't take issues seriously. We simply don't have the time, the funds or the manpower to handle them properly.
The contribution cycle on this repository is long as it is and we cannot block a PR forever. We also cannot dedicate full time in fixing problems in said PRs.
We welcome contributions and criticism, it's what drives this project forward. If you recognize that something is wrong with the way celery works you are most welcome to fix it. The other alternative is to pay us to fix it for you. If we happened to have the same problem you had, one of us would fix it.
These are the three options we have to fix a problem or introduce a feature. The rest is simply work we do for absolutely free. 

It is impossible for the maintainers of this project to keep track of *all* the changes and all side effects of said changes, wanted and unwanted and adjust the code or documentation accordingly. It's the sad truth of open source development.

**Comment by lpsinger** [comment] 2018-05-09 12:34
> I think I found why this is happening. If you check the code of the Redis backend, you can see here that the results are pushed in a Redis list. When all results have been gathered, the chord callback is executed, fetching the Redis list, without any other re-ordering. With parallel execution, the order of the results in the list will not be deterministic and the sequence of the stored results will be the same with the task execution sequence.

@georgepsarakis, those links to the source code are out of date. Would you please update those links to the source code using a version tag? Then I can take a look.

**Comment by georgepsarakis** [comment] 2018-05-09 16:03
@lpsinger I updated https://github.com/celery/celery/issues/3781#issuecomment-279135257 , let me know if you have any questions.
