### ISSUE TITLE
Chain/Group possibile BUG

### ISSUE THREAD

**Issue by Ixiodor** [celery/celery#5958] opened 2020-02-11 10:31 UTC
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] I have included the contents of ``pip freeze`` in the issue.
* [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* None

#### Possible Duplicates
* None

## Environment & Settings

**Celery version**: 4.4.0 (cliffs)

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.0 (cliffs) kombu:4.6.7 py:3.6.9
            billiard:3.6.1.0 py-amqp:2.5.2
platform -> system:Linux arch:64bit, ELF
            kernel version:4.15.0-76-generic imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

</p>
</details>

# Steps to Reproduce
## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: RabbitMQ 3.6.10
* **Minimal Result Backend Version**: DB Postgres
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```

```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
task = chain(group(AClass.execute.si("", ""),
                   AClass.execute.si("", ""),
                   AClass.execute.si("", "")),
             group(AClass.execute.si("", ""),
                   AClass.execute.si("", ""),
                   AClass.execute.si("", "")),
             group(AClass.execute.si("", "")),
             group(AClass.execute.si("", "))
)
```

</p>
</details>

# Expected Behavior

Group1 get executed 1 time( 3 task)
Group2 get executed 1 time( 3 task)
Group3 get executed 1 time( 1 task)
Group4 get executed 1 time( 1 task)

# Actual Behavior

Group1 get executed 1 time( 3 task)
Group2 get executed 1 time( 3 task)
Group3 get executed 3 times( 1 task)
Group4 get executed 3 times( 1 task)

**Comment by Ixiodor** [comment] 2020-02-11 10:49
Checking the result from task.delay() i see the correct tree.
An AsyncResult with 1 result, a parent to a GroupResult: 3 and this parent with a parent of GroupResult: 3.

**Comment by Ixiodor** [comment] 2020-02-11 13:38
Tryed this:
![aa](https://user-images.githubusercontent.com/21291221/74241117-a780b400-4cdb-11ea-859a-833bf0bd36f9.png)

and this:
![aa2](https://user-images.githubusercontent.com/21291221/74241205-d3039e80-4cdb-11ea-9a03-e7aac29b172b.png)

With same results.
BUT this:
```python
task = chain(group(AClass.execute.si("", ""),
                   AClass.execute.si("", ""),
                   AClass.execute.si("", "")),
             group(AClass.execute.si("", ""),
                   AClass.execute.si("", ""),
                   AClass.execute.si("", "")),
             AClass.execute.si("", ""),
             AClass.execute.si("", ")
)
```
works fine.

**Comment by jheld** [comment] 2020-03-02 00:53
Unsure but there is a bug around group/chord such that for long canvas the tasks may start before the group/chord has been fully defined. I think there either was a fix on 4.4 or a fix was opened.

**Comment by Ixiodor** [comment] 2020-03-02 18:45
I think it's about chord upgrade(I think that feature should be removed), couse group of 3 chained with group of 1 become a chord and something that will be chained after can be parallelized losing the chain structure. It's inconsistent in each case, sometimes you get the chord promote and sometime dosn't.

**Comment by Ixiodor** [comment] 2020-04-21 23:19
>         task = chain(group(task1.si("1"),
                           task1.si("2"),
                           task1.si("3")),
                     group(task1.si("4"),
                           task1.si("5"),
                           task1.si("6")),
                     group(task1.si("7")),
                     group(task1.si("8"))
                     )
        t = task.delay()
still not fixed...prints: 1 2 3 4 5 6 7 7 7 8 8 8

**Comment by TauPan** [comment] 2022-11-22 07:02
I'm pretty sure this is what hits us in Celery 5.1.2, see https://groups.google.com/g/celery-users/c/4IpsL0_j6SA

**Comment by auvipy** [comment] 2022-11-22 07:47
@Nusnus when ever you have time, please have a cross check

**Comment by Nusnus** [comment] 2022-11-22 15:39
I'll try to spare some time soon 🙏

**Comment by Nusnus** [comment] 2022-11-23 23:00
> ```
> >         task = chain(group(task1.si("1"),
>                            task1.si("2"),
>                            task1.si("3")),
>                      group(task1.si("4"),
>                            task1.si("5"),
>                            task1.si("6")),
>                      group(task1.si("7")),
>                      group(task1.si("8"))
>                      )
>         t = task.delay()
> ```
> 
> still not fixed...prints: 1 2 3 4 5 6 7 7 7 8 8 8

It appears the bug is caused by chaining a chord with a group where `group(task1.si("7"))` and `group(task1.si("8"))`  were chained to `task1.si("4")`, `task1.si("5")` and `task1.si("6")`, instead of `group(task1.si("7"))` being chained to `group(task1.si("4"),task1.si("5"),task1.si("6"))`, and `group(task1.si("8"))` being chained to `group(task1.si("7"))`, which is why they get executed exactly 3 times instead of only once.
Try adding to the second group for example `task1.si("6b")`, and you'll get 1 2 3 4 5 6 6b 7 7 7 7 8 8 8 8.

This happens when the chain upgrades the groups to chords and attempts to chain the upgraded primitives again, it fails to recognize the upgraded chord which is why it doesn't link it correctly (a.k.a to the body of the new chord). 
I attempted a fix at `chord.__or__()`.

Investigating it, I found that "manually" upgrading the chord reproduces the bug in a different flow!
```python
task = chain(
           chord(
               header=group(task1.si("1"), task1.si("2"), task1.si("3")),
               body=group(task1.si("4"), task1.si("5"), task1.si("6"))
           ),
           group(task1.si("7")),
           group(task1.si("8"))
       )
t = task.delay()
```
Will also cause a similar bug due to similar reasons, but in `chain.__or__()`

@Ixiodor @TauPan I've opened a PR with a possible fix. If there's a way you can test it on your systems as "acceptance tests" (in addition to the new integration tests I've added), it could confirm the fix really worked without hurting anything else (which is hard to know from my perspective) before merging to `master`.

**Comment by TauPan** [comment] 2022-11-25 14:18
I could quite easily run my testcase from the google groups post but I'm not sure if that's the kind of test you need.

Regarding our application the remote workers are stuck with celery 5.1.2 for now (because of python 3.6 on CentOS) and we'll be able to migrate to a more recent celery release much later to test the real business code.

On the local workers, which I can easily run against #7919, I don't have those kinds of workflows so my testcase is the only option there.

**Comment by Alexander3** [comment] 2022-11-26 13:14
I wasted a lot of hours to debug this problem, before I found this bug report @Nusnus Thanks a lot for taking care of this :hugs: 

WORKAROUND: add dummy task after group (than it is converted into chord correctly)
```
chain(
    group(test_task.si("g1.1", 1), test_task.si("g1.2", 3)),
    group(
        test_task.si("g2.1", 10),
        test_task.si("g2.2", 5),
    ),
    # test_task.si("fix", 1),  <== workaround
    chain(
        test_task.si("duplicated", 1), # executed 2 times (once parent is "g2.1" second time it's "g2.2")
    ),
)()
```

**Comment by Ixiodor** [comment] 2022-11-26 13:23
> I wasted a lot of hours to debug this problem, before I found this bug report @Nusnus Thanks a lot for taking care of this 🤗
> 
> WORKAROUND: add dummy task after group (than it is converted into chord correctly)
> 
> ```
> chain(
>     group(test_task.si("g1.1", 1), test_task.si("g1.2", 3)),
>     group(
>         test_task.si("g2.1", 10),
>         test_task.si("g2.2", 5),
>     ),
>     # test_task.si("fix", 1),  <== workaround
>     chain(
>         test_task.si("duplicated", 1), # executed 2 times (once parent is "g2.1" second time it's "g2.2")
>     ),
> )()
> ```

Yea, that is the fix I used to bypass 2 years, and used to ignore_result on dummy tasks. I suggested to remove chord upgrade feature.

**Comment by Nusnus** [comment] 2022-11-27 11:45
I've added three integration tests to the PR to ensure the fix is alright.
One test upgrades the chord entirely inside the chain; the second one is the same, just with an upgraded chord already. The last test uses that workaround to ensure it still works (sanity).

@TauPan You're welcome to check if this matches your original test case: https://github.com/celery/celery/pull/7919/files#r1032913525
@Alexander3 I'm glad I could be of help! TBH, it took me 6-8h straight debugging to find this shit!! haha, I was chasing my tail so many times trying to figure out what the hell was wrong until I pinpointed the problematic code so I could focus my analysis on the issue. But besides getting my butt hurting a bit, it was a lot of fun!! So I am glad it means something 😊 
@Ixiodor - Thanks for providing the relevant info. It was nothing more and nothing less than I needed. The test cases are based on your snippet from the beginning of the thread.

Soon we'll get the PR merged to `master`, @auvipy let's try to close it today! 💪

**Closed** 2022-11-27 12:14 UTC
Labels: Component: Canvas, Issue Type: Bug Report

**Comment by auvipy** [comment] 2022-11-27 12:16
thanks all who participated here. still will be open for any edge cases/regressions you face/figure out.

**Comment by TauPan** [comment] 2022-11-28 13:13
> @TauPan You're welcome to check if this matches your original test case: https://github.com/celery/celery/pull/7919/files#r1032913525 

Yes, it matches.

Thanks for the fix!

When we move to a more recent version of celery (hopefully much sooner than the move from 3.1 to 5.1, which took us 8 years), I'll very much appreciate being able to remove those workaround chord callback tasks.

The reason this is annoying in practice is that we have a complicated workflow and in order to manage it, we have multiple functions returning canvases and this fix will spare the developer to reason in advance if a group might end up in a chain or not.

Alternatively a simpler "fix" might be to disable the automatic chord upgrade feature and produce an error instead, as proposed by @Ixiodor,  but that might cause trouble if those workflows are truly dynamic. (So the programmer would have to reason about upgrading groups to chords **again**. It's probably better if celery decides that.)

**Comment by auvipy** [comment] 2023-11-23 05:38
> > @TauPan You're welcome to check if this matches your original test case: https://github.com/celery/celery/pull/7919/files#r1032913525
> 
> Yes, it matches.
> 
> Thanks for the fix!
> 
> When we move to a more recent version of celery (hopefully much sooner than the move from 3.1 to 5.1, which took us 8 years), I'll very much appreciate being able to remove those workaround chord callback tasks.
> 
> The reason this is annoying in practice is that we have a complicated workflow and in order to manage it, we have multiple functions returning canvases and this fix will spare the developer to reason in advance if a group might end up in a chain or not.
> 
> Alternatively a simpler "fix" might be to disable the automatic chord upgrade feature and produce an error instead, as proposed by @Ixiodor, but that might cause trouble if those workflows are truly dynamic. (So the programmer would have to reason about upgrading groups to chords **again**. It's probably better if celery decides that.)

thanks for your suggestions. do you want to share some of your views regarding this?
