### ISSUE TITLE
CELERY_TASK_DEFAULT_QUEUE is wrong

### ISSUE THREAD

**Issue by okomarov** [celery/celery#5575] opened 2019-06-08 23:23 UTC
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- https://github.com/celery/celery/issues/3772 

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: `celery:4.3.0 (rhubarb)`
<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.3.0 (rhubarb) kombu:4.6.1 py:3.7.3
            billiard:3.6.0.0 redis:3.2.1
platform -> system:Darwin arch:64bit
            kernel version:18.6.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

BROKER_URL: 'redis://localhost:6379/0'
CELERY_DEFAULT_QUEUE: 'test'
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.5.0
billiard==3.6.0.0
celery==4.3.0
kombu==4.6.1
pytz==2019.1
redis==3.2.1
vine==1.3.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery


class BaseConfig:
    BROKER_URL = 'redis://localhost:6379/0'
    CELERY_TASK_DEFAULT_QUEUE = 'test'

celery_app = Celery()
celery_app.config_from_object(BaseConfig)

@celery_app.task
def simple_task():
    raise Exception("Testing Celery exception")
```
Then run with cmd:
```
celery worker -A app:celery_app -l debug -f celery.log
```
</p>
</details>

# Expected Behavior

I expect the routing `key=test` and `exchange=test`.

# Actual Behavior

The configuration `CELERY_TASK_DEFAULT_QUEUE = 'test'` is not picked up and defaults are used instead:

```
 -------------- celery@Olegs-MBP.homenet.telecomitalia.it v4.3.0 (rhubarb)
---- **** ----- 
--- * ***  * -- Darwin-18.6.0-x86_64-i386-64bit 2019-06-09 01:15:55
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x10d316518
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . app.simple_task
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
```

Dropping the `TASK_` from the config property name to `CELERY_DEFAULT_QUEUE = 'test'` works as intended:

```
 -------------- celery@Olegs-MBP.homenet.telecomitalia.it v4.3.0 (rhubarb)
---- **** ----- 
--- * ***  * -- Darwin-18.6.0-x86_64-i386-64bit 2019-06-09 01:19:19
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x1085be2b0
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> test             exchange=test(direct) key=test
                

[tasks]
  . app.simple_task
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
```

Now, issue #3772 was reporting incorrect documentation, i.e. `CELERY_DEFAULT_QUEUE` should be `CELERY_TASK_DEFAULT_QUEUE` and so all old configs without the `TASK_` have been updated in https://github.com/celery/celery/pull/4094 to have it. However, since the fix to the docs, the code actually **regressed** and now accepts the older settings.

**Comment by auvipy** [comment] 2019-06-09 07:23
thanks for the detailed report! can you come up with code n doc fixes?

**Comment by esh-b** [comment] 2019-06-10 06:54
I think in the old setting keys, the key to set the default queue is `CELERY_DEFAULT_QUEUE` but the docs are not updated yet I guess.
Try `CELERY_DEFAULT_QUEUE=test` in your `BaseConfig` class.

Hope that solves your issue.

**Comment by okomarov** [comment] 2019-06-11 17:10
@auvipy Very tight on time but would try. Is there a centralized place where old setting names are converted to the new ones, or can you indicate a starting point in the code to look at?

**Comment by clokep** [comment] 2019-06-11 17:14
Taking a look at the code this seems to be correct (as `task_default_queue`), see https://github.com/celery/celery/blob/49f6b572e571bcb5b668ce3d25507668c877102f/celery/app/defaults.py#L259

The old setting was `CELERY_TASK_DEFAULT_QUEUE`, the new is `task_default_queue` (according to [the docs](http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings).

**Comment by okomarov** [comment] 2019-06-11 17:21
@clokep The left column of old uppercase settings are still accepted. However, `CELERY_TASK_DEFAULT_QUEUE` does not work but `CELERY_DEFAULT_QUEUE` does (as I report above). It should not accept `CELERY_DEFAULT_QUEUE` which is de facto a regression. 

We are nowhere close to migrating all of our settings to lowercase which include tons of other non-celery stuff.

**Comment by okomarov** [comment] 2019-06-11 17:28
@clokep Good code pointer thanks. However, it looks more involved than expected. 

The old namesapce is `celery_{0}` so the `task` was not present in the uppercase configs. Can't look when and where the regression happened, i.e. if the doc change got it wrong by adding `TASK` to old uppercase settings or if the code sometime later changed and mixed up the uppercase vs lowercase namespaces.

**Comment by clokep** [comment] 2019-06-11 17:38
As you said above, the documentation was changed in #4094. Looking at the [docs from 3.1](http://docs.celeryproject.org/en/3.1/configuration.html#std:setting-CELERY_DEFAULT_QUEUE) it clearly used to be `CELERY_DEFAULT_QUEUE`. So I think #4094 is incorrect and should probably be reverted.

This section of the docs seems to be very confusing to people though. (There have been a bunch of PRs/issues about these "being wrong" without understanding that the table is showing old vs. new values, not two forms of the same setting. I wonder if this section should be removed / updated.)

**Comment by okomarov** [comment] 2019-06-12 12:26
@auvipy Not sure what the conclusion.

The uppercase old settings are still supported as the NOTE says under the [New Lowercase Settings](http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings)

The `CELERY_TASK_DEFAULT_QUEUE` reported in left side of the table under New Lowercase Settings is the wrong config. Probably other settings with the `TASK_` sub-namespace suffer from the same issue. 

So, anyone who reads the settings page and still needs to stick with UPPERCASE settings will have trouble. 

Should we check the fix the `celery/celery/app/defaults.py` or the docs?

**Comment by clokep** [comment] 2019-06-12 12:29
@okomarov For what it is worth, you can just take the "new" settings names and capitalize them and it works fine. This is what we do in order to keep our settings Django-ish. (We also use a namespace of `CELERY` to separate them from our other settings.)

**Comment by auvipy** [comment] 2019-06-12 15:44
not intended to close this though

**Comment by auvipy** [comment] 2019-06-14 05:49
Older settings won't work anymore from version 5.0

**Comment by auvipy** [comment] 2019-06-14 05:56
> CELERY_DEFAULT_QUEUE

this is not a regression.

**Comment by auvipy** [comment] 2019-06-14 05:57
https://github.com/celery/celery/commit/a1a68ec1a8377bfa280dac5ec88ab2579ba656a8

**Closed by auvipy** 2019-06-14 05:57 UTC
