### ISSUE TITLE
Celery worker hangs.

### ISSUE THREAD

**Issue by cameronmaske** [celery/celery#2080] opened 2014-06-06 17:08 UTC
We are encountering an odd issue where a worker hangs. Tasks are present in our RabbitMQ queue, but the worker fails to pick them up and process them (IDLE status). Running `inspect active` reveals there are no active tasks on the worker. 
 
We are running on 3 EC2 instances, with Ubuntu `12.04`. 1 instance is our celery beat, the other two are workers . 
We are running `celery==3.1.11` and `librabbitmq==1.5.2` and our broker is `RabbitMQ 3.2.4`.  We are also using `Django 1.6.3`.

Here are our celery settings.
```
CELERYD_PREFETCH_MULTIPLIER = 1
CELERY_TIMEZONE = 'US/Eastern'
CELERYD_HIJACK_ROOT_LOGGER = False
CELERYD_MAX_TASKS_PER_CHILD = 1000
CELERY_IGNORE_RESULT = True
CELERYD_TASK_SOFT_TIME_LIMIT = 600

BROKER_POOL_LIMIT = 10
```

For each queue worker (we have about ~25) we manage them through supervisor. 
Taking the form of this...
```
[program:celery]
command=/bin/bash -c "source /home/web/www/.virtualenv/bin/activate && exec newrelic-admin run-program celery -A app.config worker -c 8 --loglevel=INFO -Q celery -n celery.%%h"
autostart=true
autorestart=true
stopsignal=KILL
stdout_logfile=syslog
stderr_logfile=syslog
user=ubuntu
directory="..."
environment="..."
killasgroup=true
stopasgroup=true
```
Across each the worker instance (specs: 16GB ram), we'll typically have a total task concurrency of ~90.  

I managed to do an strace on the stuck process. 
Sample:
```
sendto(26, "\316", 1, MSG_NOSIGNAL, NULL, 0) = 1
gettimeofday({1402061941, 289812}, NULL) = 0
gettimeofday({1402061941, 289886}, NULL) = 0
epoll_wait(3, {{EPOLLIN, {u32=25, u64=22420390710083609}}}, 1023, 1009) = 1
select(26, [25], NULL, NULL, {0, 0})    = 1 (in [25], left {0, 0})
recvfrom(25, "\1\0\2\0\0\0)\0<\0<\0012\0\0\0\0\0\34zP\0\10celeryev\20"..., 131072, 0, NULL, NULL) = 448
gettimeofday({1402061941, 295328}, NULL) = 0
epoll_ctl(3, EPOLL_CTL_DEL, 10, {EPOLLRDBAND|EPOLLWRNORM|EPOLLHUP|0x4f7020, {u32=0, u64=22420390710083584}}) = -1 ENOENT (No such file or directory)
epoll_ctl(3, EPOLL_CTL_DEL, 14, {EPOLLRDBAND|EPOLLWRNORM|EPOLLHUP|0x4f7020, {u32=0, u64=22420390710083584}}) = -1 ENOENT (No such file or directory)
epoll_ctl(3, EPOLL_CTL_DEL, 18, {EPOLLRDBAND|EPOLLWRNORM|EPOLLHUP|0x4f7020, {u32=0, u64=22420390710083584}}) = -1 ENOENT (No such file or directory)
epoll_ctl(3, EPOLL_CTL_DEL, 6, {EPOLLRDBAND|EPOLLWRNORM|EPOLLHUP|0x4f7020, {u32=0, u64=22420390710083584}}) = -1 ENOENT (No such file or directory)
select(26, [25], NULL, NULL, {0, 0})    = 0 (Timeout)
gettimeofday({1402061941, 295935}, NULL) = 0
```
More detail here: https://gist.github.com/cameronmaske/db05f4676344ceece0e8

When I manually killed the process ('kill -15 <pid>') the queue start up again.

Let me know if there are anymore details that I can provide to help diagnose this!

**Comment by schmiddy** [comment] 2015-07-29 21:11
We have also been having problems with celery workers apparently becoming stuck, with `strace` of stuck worker parent processes appearing very similar to @cameronmaske's. We're running Ubuntu 12.04 x86_64, on EC2, celery 3.1.11, Python 2.7.3, talking to a RabbitMQ broker. The worker tasks talk to a PostgreSQL RDS database, and perform network calls using Twisted.

We mainly notice the problem in production when we experience an RDS failover event, and I am able to reproduce the problem fairly consistently in a test VPC with modest load by forcing an RDS failover (`aws rds reboot-db-instance ... --force-failover`). We usually see all celery workers across many machines hang at the same time, especially if they were busy at the time of the failover.

Looking at `strace` of one of the stuck worker parent processes, it looks sort of similar to @cameronmaske's, and seem to always have a ton of `epoll_ctl` calls like so:

    epoll_ctl(3, EPOLL_CTL_DEL, 21, {EPOLLRDNORM|EPOLLWRBAND|EPOLLHUP|0x43e820,{u32=0, u64=19130720639254528}}) = -1 ENOENT (No such file or directory)

In fact, checking all those `epoll_ctl` calls in the worker parent process like:

    sudo strace -p 2959 2>&1 | grep epoll_ctl | grep -v ENOENT

returns no matches even after several minutes. The `epfd` argument to `epoll_ctl` always seems to be 3, which `lsof` reports as:

    celery  2959 ubuntu    3u  0000     0,9        0    4738 anon_inode


The process tree of one of the workers, when running normally, looks something like:
```
celery(2959)─┬─python(3030)─┬─{python}(3209)
             │              └─{python}(3217)
             ├─python(3036)─┬─{python}(3210)
             │              └─{python}(3223)
             ├─python(3050)─┬─{python}(3211)
             │              └─{python}(3222)
             ├─python(3104)─┬─{python}(3213)
             │              └─{python}(3221)
             ├─python(3126)─┬─{python}(3214)
             │              └─{python}(3220)
             ├─python(3145)─┬─{python}(3216)
             │              └─{python}(3224)
             ├─python(3155)─┬─{python}(3215)
             │              └─{python}(3218)
             └─python(3269)───{python}(3277)
```

(we specify `-c 8` for the worker, hence 8 child processes). After an RDS failover, `strace` for a child process looks like (and is stuck at):

```
$ sudo strace -p 3030
Process 3030 attached - interrupt to quit
read(5, ^C <unfinished ...>
```

According to `lsof`, fd 5 for PID 3030 is:
```
    python  3030 ubuntu    5r  FIFO     0,8      0t0 3759411 pipe
```
In `strace` logging of PID 3030 before the freeze happened, I had seen reads like this:
```
read(5, "\0\0\2\270", 4)                = 4
read(5, "\200\2K\2(M?\1Nccelery.app.trace\n_fast"..., 696) = 696
```

And here is a gdb backtrace of a [child process](https://gist.github.com/schmiddy/b519972739cb779bfdc5) while stuck, and here is the [celery worker parent process](https://gist.github.com/schmiddy/38a4c9e36edd8ef99d46). 

I haven't had much success with various tweaks in avoiding these hangs. Setting a time limit for one of those tasks to 100 seconds (via --time-limit=100), I get [log entries like this](https://gist.github.com/schmiddy/aa0e948fa81c4b2aedb2), but the task is still stuck. (At one point, `pstree` showed the parent cycling through child processes extremely quickly after the hang, all 8 child processes got cycled out in faster than 1 second, though I can't reproduce that again.)

I'm happy to provide any more information here that would be helpful in tracking this down.

**Comment by thedrow** [comment] 2015-08-09 15:15
@schmiddy Thanks for the detailed report. We'll look into it.

**Comment by kdeldycke** [comment] 2015-12-01 07:55
I'm also encountering the issue. I'm running:
* `celery >= 3.1.12`
* `amqp == 1.4.7`
* `billiard == 3.3.0.21`
* `kombu == 3.0.29`
* Ubuntu 14.04.1 LTS

An `strace` on my stucked proccess returns:
```
epoll_ctl(11, EPOLL_CTL_DEL, 12, {EPOLLRDNORM|EPOLLWRNORM|EPOLLHUP|EPOLLRDHUP|EPOLLONESHOT|0x1de6c800, {u32=32635, u64=22396489217113979}}) = -1 ENOENT (No such file or directory)
wait4(15368, 0x7fff57d7ca00, WNOHANG, NULL) = 0
epoll_wait(11, {}, 1023, 4999)          = 0
epoll_ctl(11, EPOLL_CTL_DEL, 12, {EPOLLRDNORM|EPOLLWRNORM|EPOLLHUP|EPOLLRDHUP|EPOLLONESHOT|0x1de6c800, {u32=32635, u64=22396489217113979}}) = -1 ENOENT (No such file or directory)
wait4(15368, 0x7fff57d7ca00, WNOHANG, NULL) = 0
epoll_wait(11, {}, 1023, 4999)          = 0
epoll_ctl(11, EPOLL_CTL_DEL, 12, {EPOLLRDNORM|EPOLLWRNORM|EPOLLHUP|EPOLLRDHUP|EPOLLONESHOT|0x1de6c800, {u32=32635, u64=22396489217113979}}) = -1 ENOENT (No such file or directory)
wait4(15368, 0x7fff57d7ca00, WNOHANG, NULL) = 0
```

I have dozen of other processes running on other machines with the exact same version of Celery and frozen dependencies. None seems to gets stuck as the one above. A significant difference: the stuck worker is running periodic tasks while others don't.

**Comment by ask** [comment] 2015-12-01 19:27
@kdeldycke Periodic tasks are not special in any way, they're just regular tasks sent by the beat service, so I would look into if the tasks themselves are running for too long.

I'm not sure what significance `EPOLL_CTL_DEL` has here, it does seem rather suspicious but it could also be normal.

**Comment by ask** [comment] 2016-06-23 23:41
Closing this, as we don't have the resources to complete this task.

**Closed by ask** 2016-06-23 23:41 UTC
Labels: Issue Type: Bug, Worker Hangs
