### ISSUE TITLE
Workers hangs unexpectedly after running 5 10 min.

### ISSUE THREAD

**Issue by harikishan** [celery/celery#2844] opened 2015-10-09 06:21 UTC
Hi,
I am using celery as backend asynchronous task processing, I am facing issue as celery workers stops picking tasks after few minutes ~5-10 min.
I tried scalling up workers, routing tasks to queues etc but nothing helps me out. below is my settings.

<pre>
BROKER_URL = 'amqp://****@fast-polar-bear.rmq.cloudamqp.com/***'
CELERY_DEFAULT_QUEUE = 'proj.env.defaultnew'
CELERY_QUEUES = (
    Queue(
        'proj.env.defaultnew',
        Exchange('proj.env.defaultnew'),
        routing_key='proj.env.defaultnew'),)
CELERY_DEFAULT_EXCHANGE_TYPE = 'direct'
CELERY_ROUTES = {
    # High priority tasks maping
    'datasync.tasks.api_push_ship_status': {
        'queue': 'proj.env.priority_queue',
    },
    'datasync.tasks.api_push_pack_status': {
        'queue': 'proj.env.priority_queue',
    },
    'gmflow.tasks.post_activity_call': {
        'queue': 'proj.env.priority_queue',
    },
    'ims.tasks.create_item_history': {
        'queue': 'proj.env.priority_queue',
    },
    'remarks.tasks.insert_remaks_task': {
        'queue': 'proj.env.priority_queue',
    },
    'ims.tasks.sync_items_task': {
        'queue': 'proj.env.priority_queue',
    },
    'datasync.tasks.file_datasync_task': {
        'queue': 'proj.env.priority_queue',
    },
    # Low priority tasks maping
    'wms.tasks.queue_report': {
        'queue': 'proj.env.low_priority',
    },
    'oms.tasks.update_order_status_task': {
        'queue': 'proj.env.low_priority',
    },
    'datasync.tasks.datasync_task': {
        'queue': 'proj.env.low_priority',
    },
}
</pre>

Number of workers per queue
proj.env.low_priority - 10 workers - time consuming tasks with low frequency
proj.env.default - 10 workers - normal tasks normal frequency
proj.env.priority_queue - 10 workers - very less time consuming high frequency

Consumer settings
<pre>
--without-gossip
--without-heartbeat
--without-mingle
--loglevel=info
</pre>

Celery versions
<pre>
django1.8.1
celery==3.1.18
django-celery==3.1.10
amqp==1.4.7
kombu==3.0.26
</pre>

Consumer Command
<pre>
python manage.py celery worker -n priority_queue:%n -Q proj.env.priority_queue --settings=settings.prod  --without-gossip --without-heartbeat --without-mingle --loglevel=info
</pre>

please help and suggest the changes if required

**Comment by mverrilli** [comment] 2015-10-10 01:33
Hi, I had a similar bug that someone patched recently for when --without-gossip is used.  See #2823.

**Comment by ask** [comment] 2015-12-12 00:31
Please upgrade to celery 3.1.19, where the issue was fixed.

Duplicate of #1847

**Closed by ask** 2015-12-12 00:31 UTC
