### ISSUE TITLE
Basic Django config files break upgrading from 4.4.6 to 4.4.7

### ISSUE THREAD

**Issue by chrisconlan** [celery/celery#6285] opened 2020-08-04 03:03 UTC
The basic tutorial setup outlined here: https://docs.celeryproject.org/en/latest/django/first-steps-with-django.html now fails to locate set the `broker` or `CELERY_BROKER_URL` parameter. Celery just ignores the settings and defaults to searching for a host at `amqp://guest:**@127.0.0.1:5672//:`, which is not my host of choice.

I'm ignoring the issues template because this is a very basic regression that the last committor can fix quickly.

**Comment by pg1671** [comment] 2020-08-04 03:59
4.4.7 broke my django site.  Just reverted to 4.4.6.

Did not investigate further but jobs were not being processed. Assume it is related to this issue.

**Comment by rdmrocha** [comment] 2020-08-04 06:48
Another confirmation for this issue. Django3 project stoped being able to connect by ignoring settings.

**Comment by yoch** [comment] 2020-08-04 06:56
Same issue for me (no Django, but settings was ignored as well).

**Comment by kptac** [comment] 2020-08-04 09:46
Same here. Reverting back to 4.4.6

**Comment by thedrow** [comment] 2020-08-04 15:24
@auvipy Please address this.
Did we do something I'm not aware of?

**Comment by dratchkov** [comment] 2020-08-04 21:27
The symptom in my case is that messages are received, but rejected because the called task is not registered.
What was really confusing is that 'flower', sees the list of tasks.

But yes, 4.4.6 resolves this.

**Comment by nkuttler** [comment] 2020-08-05 21:32
The pre 4.0 style config doesn't seem to be supported any more in 4.4.7, despite the docs saying otherwise. We also reverted.

**Comment by gargantuanprism** [comment] 2020-08-06 16:59
confirmed, but not with django. if i have env vars set in my shell, then run `celery worker` interactively, it's fine. as soon as i add `--detach`, it seems to ignore my broker URL env var. downgraded to 4.4.6 and it works again.

**Comment by fnk0c** [comment] 2020-08-06 20:41
Same here. Whenever I add `-D` it simple ignores configuration file. Also when running `celery worker --help` it ignores the `--help` and starts Celery.

**Comment by auvipy** [comment] 2020-08-07 11:28
> @auvipy Please address this.
> Did we do something I'm not aware of?

I dont think so but will look into it on next Monday Hopefully.

**Comment by auvipy** [comment] 2020-08-07 11:30
> The basic tutorial setup outlined here: https://docs.celeryproject.org/en/latest/django/first-steps-with-django.html now fails to locate set the `broker` or `CELERY_BROKER_URL` parameter. Celery just ignores the settings and defaults to searching for a host at `amqp://guest:**@127.0.0.1:5672//:`, which is not my host of choice.
> 
> I'm ignoring the issues template because this is a very basic regression that the last committor can fix quickly.

Try to check the commit logs to see which commit could cause the apparent regression

**Comment by nickdibari** [comment] 2020-08-10 00:08
As a starting point, perhaps https://github.com/celery/celery/pull/6223 is somehow related? Looking at the changelog from 4.4.6 -> 4.4.7 this is the one change that is related to argument parsing. This totally a guess on my part but it seems like a good place to start at least.

**Comment by ShaheedHaque** [comment] 2020-08-10 06:18
Unable to start as per other reports. After reverting to Celery 4.4.6:
```
2020-08-10 06:09:50,469 [INFO] MainProcess: Connected to amqp://<some username>:**@127.0.0.1:5672/celery
2020-08-10 06:09:50,495 [INFO] MainProcess: mingle: searching for neighbors
2020-08-10 06:09:51,527 [INFO] MainProcess: mingle: all alone
2020-08-10 06:09:51,546 [INFO] MainProcess: celery@ip-172-31-10-102 ready.
```
With Celery 4.4.7:
```
[2020-08-10 06:11:51,832: CRITICAL/MainProcess] Unrecoverable error: AccessRefused(403, 'ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.', (0, 0), '')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.8/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/dist-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/dist-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/consumer/connection.py", line 23, in start
    c.connection = c.connect()
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/consumer/consumer.py", line 405, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/consumer/consumer.py", line 411, in connection_for_read
    return self.ensure_connected(
  File "/usr/local/lib/python3.8/dist-packages/celery/worker/consumer/consumer.py", line 437, in ensure_connected
    conn = conn.ensure_connection(
  File "/usr/local/lib/python3.8/dist-packages/kombu/connection.py", line 389, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kombu/connection.py", line 441, in _ensure_connection
    return retry_over_time(
  File "/usr/local/lib/python3.8/dist-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kombu/connection.py", line 874, in _connection_factory
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/kombu/connection.py", line 809, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/amqp/connection.py", line 320, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/usr/local/lib/python3.8/dist-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.8/dist-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.8/dist-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.8/dist-packages/amqp/connection.py", line 520, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/usr/local/lib/python3.8/dist-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.8/dist-packages/amqp/connection.py", line 650, in _on_close
    raise error_for_code(reply_code, reply_text,
amqp.exceptions.AccessRefused: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
```
And from the broker log file:
```
2020-08-10 06:11:51.830 [info] <0.993.0> accepting AMQP connection <0.993.0> (127.0.0.1:44638 -> 127.0.0.1:5672)
2020-08-10 06:11:51.832 [error] <0.993.0> Error on AMQP connection <0.993.0> (127.0.0.1:44638 -> 127.0.0.1:5672, state: starting):
AMQPLAIN login refused: user 'guest' - invalid credentials
```
Note that it is trying to use the `guest` accout istead of our `<some username>`. So 4.4.7 is - as others have said - not reading the established configuration, but instead applying some defaults.

**Comment by auvipy** [comment] 2020-08-12 16:49
commit log https://github.com/celery/py-amqp/commit/9e9f4c0b97ef6d4fbb3243f1511939d132810236

**Comment by diemuzi** [comment] 2020-08-14 12:09
I too have a similar problem but I also noticed something I did not see posted here about this issue. When starting the multi worker I can see this running for example: <code>/home/gwhcp/api.gwhcp.dev/venv/bin/python -m celery worker -Q 10.2.1.1 --loglevel=DEBUG --time-limit=300 --concurrency=2 --logfile=/var/log/celery/worker.log</code>

This was supposed to also contain the <code>-A application</code> option. Downgrading to 4.4.6 fixes the entire problem for me and now shows: <code>/home/gwhcp/api.gwhcp.dev/venv/bin/python -m celery worker -Q 10.2.1.1 -A application --loglevel=DEBUG --time-limit=300 --concurrency=2 --logfile=/var/log/celery/worker.log</code>

With 4.4.7 the entire Django settings are completely ignored which is also why it is trying to connect as guest to the amqp server. I believe it may have something to do with this recent patch [#6223 ](https://github.com/celery/celery/pull/6223)

**Comment by auvipy** [comment] 2020-08-14 12:23
> I too have a similar problem but I also noticed something I did not see posted here about this issue. When starting the multi worker I can see this running for example: `/home/gwhcp/api.gwhcp.dev/venv/bin/python -m celery worker -Q 10.2.1.1 --loglevel=DEBUG --time-limit=300 --concurrency=2 --logfile=/var/log/celery/worker.log`
> 
> This was supposed to also contain the `-A application` option. Downgrading to 4.4.6 fixes the entire problem for me and now shows: `/home/gwhcp/api.gwhcp.dev/venv/bin/python -m celery worker -Q 10.2.1.1 -A application --loglevel=DEBUG --time-limit=300 --concurrency=2 --logfile=/var/log/celery/worker.log`
> 
> With 4.4.7 the entire Django settings are completely ignored which is also why it is trying to connect as guest to the amqp server. I believe it may have something to do with this recent patch [#6223 ](https://github.com/celery/celery/pull/6223)

@JulienPalard would you mind checking this?

**Comment by thenewguy** [comment] 2020-08-16 16:26
I have also had to revert to 4.4.6 on some projects using django with the redis broker.  Oddly, there are no logs from celery on the projects when using 4.4.7 so I cannot be more specific other than all works well under 4.4.6.

**Comment by garw** [comment] 2020-08-17 22:12
I can confirm that commit e3ac73b6fbe2d996070b90833c23a3b336cd4ac6 (#6223) introduces the issue. Just reverting this makes celery multi behave in the old way and pass the -A option on to the worker. Otherwise v4.4.7 just doesn't pass the -A option to the worker and some default configuration seems to be loaded as consequence.

**Comment by auvipy** [comment] 2020-08-17 22:23
> I can confirm that commit [e3ac73b](https://github.com/celery/celery/commit/e3ac73b6fbe2d996070b90833c23a3b336cd4ac6) (#6223) introduces the issue. Just reverting this makes `celery multi` behave in the old way and pass the -A option on to the worker. Otherwise v4.4.7 just doesn't pass the -A option to the worker and some default configuration seems to be loaded as consequence.

if you can provide an integration test with a failing unit test it would be easier to find a fix rather then reverting that fix

**Comment by garw** [comment] 2020-08-18 00:24
> > I can confirm that commit [e3ac73b](https://github.com/celery/celery/commit/e3ac73b6fbe2d996070b90833c23a3b336cd4ac6) (#6223) introduces the issue. Just reverting this makes `celery multi` behave in the old way and pass the -A option on to the worker. Otherwise v4.4.7 just doesn't pass the -A option to the worker and some default configuration seems to be loaded as consequence.
> 
> if you can provide an integration test with a failing unit test it would be easier to find a fix rather then reverting that fix

See PR #6305 

I took a deeper look into the situation. The problem seems to arise from the following sequence of events:
The `celery` command implementation `CeleryCommand` calls `execute_from_commandline` from `Command` in base.py. This in turn, calls `setup_app_from_commandline` and passes the return value of this function as arguments to `handle_argv`. 

The behavior of `setup_app_from_commandline` has changed in #6223 so that it only returns those parameters that cannot be parsed already by `parse_preload_options`. Consequently, all global options are now gone from `argv`. 

The actual implementation of `CeleryCommand` from this point onwards uses only the (already filtered) `argv`. In the case of `multi`, it just passes the (filtered) argv into the `multi` command that then instaniates a `MultiTool` and calls `execute_from_commandline` on this with the filtered commandline. It is also not connected to the instance of the `CeleryCommand` that previously read the application information somewhere. So at this point the information which application to start seems lost to me.

Sorry for not actually providing a fix but I feel a bit lost in the huge code base. If other commands than `multi` also need the global options still in `argv`, they will have a similar problem right now and it is probably easiest to change the behavior of `setup_app_from_commandline` back. This, however, seems to also reintroduce the issue to be fixed by #6223. 
If `multi` is special, it might be possible to change the `run_from_argv` to pass the arguments closer to sys.argv. However, there was also previously some filtering be done to argv. Thus, I cannot really judge if this will then pass too many parameters.


The regression test that I provided in #6305 just checks if the parameter still ends up in run_from_argv of the `multi` command. So any solution approach that just feeds in the argument again from sys.argv there invalidates this test-case. It already makes a bit of an assumption how this can be solved. It just illustrates the problem. It passes in v4.4.6 and fails in v4.4.7. 
If one changes `setup_app_from_commandline` back so that it does not filter the general arguments out, this test passes. However, then `test_short_and_long_arguments_be_the_same` fails.

**Comment by auvipy** [comment] 2020-08-19 03:43
> > > I can confirm that commit [e3ac73b](https://github.com/celery/celery/commit/e3ac73b6fbe2d996070b90833c23a3b336cd4ac6) (#6223) introduces the issue. Just reverting this makes `celery multi` behave in the old way and pass the -A option on to the worker. Otherwise v4.4.7 just doesn't pass the -A option to the worker and some default configuration seems to be loaded as consequence.
> > 
> > 
> > if you can provide an integration test with a failing unit test it would be easier to find a fix rather then reverting that fix
> 
> See PR #6305
> 
> I took a deeper look into the situation. The problem seems to arise from the following sequence of events:
> The `celery` command implementation `CeleryCommand` calls `execute_from_commandline` from `Command` in base.py. This in turn, calls `setup_app_from_commandline` and passes the return value of this function as arguments to `handle_argv`.
> 
> The behavior of `setup_app_from_commandline` has changed in #6223 so that it only returns those parameters that cannot be parsed already by `parse_preload_options`. Consequently, all global options are now gone from `argv`.
> 
> The actual implementation of `CeleryCommand` from this point onwards uses only the (already filtered) `argv`. In the case of `multi`, it just passes the (filtered) argv into the `multi` command that then instaniates a `MultiTool` and calls `execute_from_commandline` on this with the filtered commandline. It is also not connected to the instance of the `CeleryCommand` that previously read the application information somewhere. So at this point the information which application to start seems lost to me.
> 
> Sorry for not actually providing a fix but I feel a bit lost in the huge code base. If other commands than `multi` also need the global options still in `argv`, they will have a similar problem right now and it is probably easiest to change the behavior of `setup_app_from_commandline` back. This, however, seems to also reintroduce the issue to be fixed by #6223.
> If `multi` is special, it might be possible to change the `run_from_argv` to pass the arguments closer to sys.argv. However, there was also previously some filtering be done to argv. Thus, I cannot really judge if this will then pass too many parameters.
> 
> The regression test that I provided in #6305 just checks if the parameter still ends up in run_from_argv of the `multi` command. So any solution approach that just feeds in the argument again from sys.argv there invalidates this test-case. It already makes a bit of an assumption how this can be solved. It just illustrates the problem. It passes in v4.4.6 and fails in v4.4.7.
> If one changes `setup_app_from_commandline` back so that it does not filter the general arguments out, this test passes. However, then `test_short_and_long_arguments_be_the_same` fails.
> 
> This behavior seems to be also the origin of #6287. The argument parser in `_parse_preload_options` accepts `--help` as valid option and thus doesn't return it as unknown argument. Consequently, `--help` is also stripped and will not be passed on to the individual commands to be handled.
> 
> Additionally, adding a `CELERY_APP` environment variable provides a **workaround** for this issue on my end. Can be added to a systemd service file by adding `Environment="CELERY_APP=myapp"` line

thanks a lot for the test and te detail observation. someone will provide a fix for sure.

**Comment by leonardoarroyo** [comment] 2020-08-19 23:24
> Additionally, adding a `CELERY_APP` environment variable provides a **workaround** for this issue on my end. Can be added to a systemd service file by adding `Environment="CELERY_APP=myapp"` line

Thanks for the workaround. This fixes the issue for me after upgrading from 4.4.6 to 4.4.7.

**Comment by JulienPalard** [comment] 2020-08-20 21:12
> If other commands than multi also need the global options still in argv, they will have a similar problem right now and it is probably easiest to change the behavior of setup_app_from_commandline back.

I agree.

> This, however, seems to also reintroduce the issue to be fixed by #6223.

Which is not a big deal. https://github.com/celery/celery/issues/4558 can be reopened. I don't think there's a clean fix: Celery argument parsing is just too complicated and does not have enough tests. I think the sane way is to deprecate odd usages (like giving subcommands arguments before subcommands), which will break a lot of things.

**Comment by ShaheedHaque** [comment] 2020-09-08 16:08
I suggest that the correct way to handle both #4558 while not causing *this* regression is separate the handling of global options from command-specific options. The standard `argparse` is perfectly happy to do this simply by declaring stuff in the natural order, i.e. with all the global options first, followed by the command verb, followed by command-specific options. For example, one of my CLIs does this (`-v` or `--verbose` is a global option):
```
$ ./deploy.py list -v
usage: deploy.py [-h] [-v] {archive,create,dbdump,delete,list,restore,upgrade,who} ...
```
while also doing this:
```
$ ./deploy.py -v list --help
usage: deploy.py list [-h]

optional arguments:
  -h, --help  show this help message and exit

$ ./deploy.py -v dbdump -h
usage: deploy.py dbdump [-h] [--old-prefix OLD_PREFIX] old-sha1 identity tgzfile
...
```
This suggests that simply by getting rid of the attempt to reorder options to after the verb would work just fine, provided the global options are set up first, and the commands handled using subparsers. OTOH, I have no idea if/how that might be made to work while using `click`.

**Comment by thedrow** [comment] 2020-09-10 10:17
@auvipy Any updates?

**Comment by auvipy** [comment] 2020-09-13 01:20
It is a regression, I know which commit cause this but still not getting time to revert that & create a new release

**Comment by bsolomon1124** [comment] 2020-09-30 00:59
This is not a Django issue. As reported in https://github.com/celery/celery/issues/6370 it is reproducible with a 25-line module with no dependencies.

It may be helpful to create a pinned issue marking 4.4.7 as a bad release. This is a regression that truly breaks Celery and makes it unusable.

**Comment by ogai** [comment] 2020-10-23 12:39
> Additionally, adding a `CELERY_APP` environment variable provides a **workaround** for this issue on my end. Can be added to a systemd service file by adding `Environment="CELERY_APP=myapp"` line

In my case, it also fixed it but only after removing the parameter `-A myapp`

**Comment by mensachan** [comment] 2020-11-16 11:00
Does this Issue affects only 4.4.7 or also all versions above (Including 5.0+)?

**Comment by bsolomon1124** [comment] 2020-12-13 17:53
@mensachan according to https://github.com/celery/celery/issues/6370#issuecomment-728883661, this issue isn't present in 5.0.2+. (I haven't verified that, though.)

**Comment by auvipy** [comment] 2021-09-16 13:55
the issues doesn't exist in celery v5 as the CLI was completely rewritten.

**Closed by auvipy** 2021-09-16 13:55 UTC
Labels: Issue Type: Bug Report, Issue Type: Regression

**Comment by vishalnagda1** [comment] 2024-09-27 13:46
I'm still facing the same issue with the latest version of Celery:

```
Traceback (most recent call last):
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/utils/functional.py", line 30, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vishal/dev/ecbe-n/website/report/backend.py", line 277, in compile
    compile_report.delay(report.pk, language=language)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/celery/app/task.py", line 579, in apply_async
    **options
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/celery/app/base.py", line 788, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/celery/app/amqp.py", line 519, in send_task_message
    **properties
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/messaging.py", line 180, in publish
    exchange_name, declare, timeout
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/connection.py", line 523, in _ensured
    return fun(*args, **kwargs)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/messaging.py", line 186, in _publish
    channel = self.channel
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/utils/functional.py", line 32, in __call__
    value = self.__value__ = self.__contract__()
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/messaging.py", line 225, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/connection.py", line 895, in default_channel
    self._ensure_connection(**conn_opts)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/connection.py", line 437, in _ensure_connection
    callback, timeout=timeout
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/connection.py", line 877, in _connection_factory
    self._connection = self._establish_connection()
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/connection.py", line 812, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/kombu/transport/pyamqp.py", line 201, in establish_connection
    conn.connect()
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/amqp/connection.py", line 330, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/amqp/connection.py", line 526, in drain_events
    while not self.blocking_read(timeout):
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/amqp/connection.py", line 532, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/amqp/method_framing.py", line 53, in on_frame
    callback(channel, method_sig, buf, None)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/amqp/connection.py", line 539, in on_inbound_method
    method_sig, payload, content,
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/amqp/abstract_channel.py", line 156, in dispatch_method
    listener(*args)
  File "/home/vishal/dev/ecbe-n/.venv/lib/python3.7/site-packages/amqp/connection.py", line 669, in _on_close
    (class_id, method_id), ConnectionError)
amqp.exceptions.AccessRefused: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.```
