### ISSUE TITLE
Using a class based task as errback results in AttributeError '_header_'

### ISSUE THREAD

**Issue by stevenwbe** [celery/celery#4377] opened 2017-11-09 08:45 UTC
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
[celery-report.txt](https://github.com/celery/celery/files/1456808/celery-report.txt)
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Create a tasks file:
```
from celery import Celery,Task
celery = Celery('tasks', broker='redis://localhost:6379/6',backend='redis://localhost:6379/6')

@celery.task
def ErrTask1(req):
    print('failure')

class CustomTask(Task):
    def run(self,var):
        print('running %s' % var)
        if var == "err":
            raise Exception("err")
CustomTask = celery.register_task(CustomTask())

class ErrTask2(Task):
        def run(self):
                    print('failure')
ErrTask2 = celery.register_task(ErrTask2())

```
start celery with it:
`celery worker -A tasks:celery -l info`

Start a python shell and start the CustomTask with an error callback:

```
from tasks import CustomTask,ErrTask1,ErrTask2
a = CustomTask.apply_async(['err'],link_error=ErrTask1.s())
a.result
b = CustomTask.apply_async(['err'],link_error=ErrTask2.s())
b.result
```
## Expected behavior
When running with ErrTask1 as error callback ( the one with the decorator) we get the expected result:
```
>>> a = CustomTask.apply_async(['err'],link_error=ErrTask1.s())
>>> a.result
Exception(u'err',)
```
## Actual behavior
When running with ErrTask2 as error callback ( the one that is defined classbased) we get the Attributeerror:
```
>>> b = CustomTask.apply_async(['err'],link_error=ErrTask2.s())
>>> b.result
AttributeError(u"'ErrTask2' object has no attribute '__header__'",)
```
It seems the changed behaviour on the error callback in celery 4 has something to do with it. The class based tasks miss some attributes which doesn't seem to be an issue for normal execution but only for the error callback. Probably there is a difference in initialization between `celery.register_task()` and the decorator.

Workaround is to define the error callbacks with the task decorator.

**Comment by auvipy** [comment] 2017-12-20 16:19
@AlexHill @georgepsarakis could you check

**Comment by WoaDmulL** [comment] 2018-04-03 12:51
I see that this issue #3723 is related too.

**Comment by livenson** [comment] 2018-05-21 21:40
Hi,

is there any resolution to this issue? We are facing it on 4.1.0 (and 4.1.1). I see that the task is closed but couldn't find any code related to it.

**Comment by auvipy** [comment] 2018-05-21 21:48
@livenson this should be on master 4.2rc versions

**Comment by auvipy** [comment] 2018-05-21 21:51
https://github.com/celery/celery/pull/4545

**Comment by livenson** [comment] 2018-05-21 22:14
@auvipy thanks for reply, but I still don't get it –– #4545 adds additional handling but still expects __header__ to be there, which is not happening for class-based Tasks, at least I could only find a single place where it is set in Celery - https://github.com/celery/celery/blob/2636251a1249634258c1910c6400bf2ccf28b8ed/celery/app/base.py#L445 . I.e. only in function decorator.

**Comment by auvipy** [comment] 2018-05-21 23:11
reopening, could you plz dig bit more and let us know? could you try master?

**Comment by auvipy** [comment] 2018-05-23 08:07
anyone up for a PR? with @maximprokopenko proposed solution?

**Comment by livenson** [comment] 2018-05-23 08:27
PR could be made if you think it makes sense -- basically, our problem in Waldur was that we are  still using "legacy" base Task class with self-registration. So the question is if it's a correct workaround to apply -- or perhaps it should rather be fixed in self-registration of legacy class. @auvipy , any feelings about it?

**Comment by auvipy** [comment] 2018-05-23 09:58
which version of celery are you using? is you code open sourced?

**Comment by livenson** [comment] 2018-05-23 10:02
4.1.0 (tried with 4.1.1 -- but it's the same for that part of the code).

Yes. @maximprokopenko actually linked to our project.

**Comment by auvipy** [comment] 2018-05-24 07:57
@thedrow @georgepsarakis whats yours thoughts on this guys?

**Comment by AmbientLighter** [comment] 2018-06-21 08:16
@ask Could you please validate proposed fix?

**Comment by georgepsarakis** [comment] 2018-06-21 16:48
@auvipy @livenson @stevenwbe just tested the given example with 4.2.0rc3+ and it seems to work, as it has the expected behavior, both the error callback is executed on the worker and the result property contains `Exception('err')` . Can you please cross-check again?

**Comment by sbj-ss** [comment] 2018-09-19 19:50
The issue is back in 4.2.1.

**Comment by thedrow** [comment] 2018-09-20 09:47
@sbj-ss If you claim we have a regression, we'll need you to provide a test case in order for us to verify it.

**Comment by sbj-ss** [comment] 2018-09-20 12:44
@thedrow you can use the test case from the 1st post.

**Comment by AmbientLighter** [comment] 2018-12-13 20:14
FYI: Pull request with fix has been submitted.

https://github.com/celery/celery/pull/5232

**Closed** 2018-12-14 04:07 UTC
Labels: Issue Type: Task, Status: Needs Verification ✘
