### ISSUE TITLE
Unrecoverable socket closed error

### ISSUE THREAD

**Issue by iivvaall** [celery/celery#4876] opened 2018-07-03 15:21 UTC
## Celery report

    software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:3.6.4
                billiard:3.5.0.3 py-amqp:2.3.2
    platform -> system:Linux arch:64bit imp:CPython
    loader   -> celery.loaders.app.AppLoader
    settings -> transport:amqp results:rpc:///

    broker_url: 'amqp://guest:********@localhost:5672//'

the issue exists on **4.2.0** and **master** and **not  on 4.1.1**

## Steps to reproduce
    docker run  -p 127.0.0.1:5672:5672 rabbitmq

    cat >bug_sample.py <<EOF
    import os
    import time
    import sys
 
    import celery
    import logging
    logging.basicConfig(level=logging.INFO, stream=sys.stdout)

    app = celery.Celery(broker='amqp://', backend='rpc://')
   
 
    @app.task(name='ping')
    def ping():
        return 'pong'

    def ping_pong():
        time_start = time.time()
        while True:
            try:
                logging.info('ping %s', time.time() - time_start)
                ping.delay().get()
            except Exception:
                logging.exception('first exception')
                break

        logging.info('one more try')
        try:
            ping.delay().get()
        except Exception:
            logging.exception('second exception %s', time.time() - time_start)

    if __name__ == '__main__':
        ping_pong()
    EOF
    
    celery -A bug_sample.app worker

    python ./bug_sample.py

## Expected behavior
The sample loops forever
## Actual behavior
After three minutes the OSError (socket closed) exception is raised. 
After three minutes after that the same error raised again

    INFO:root:ping 180.05654120445251
    INFO:root:ping 180.05895519256592
    INFO:root:ping 180.06122303009033
    INFO:root:ping 180.06365275382996
    ERROR:root:first exception
    Traceback (most recent call last):
      File "./bug_sample.py", line 20, in ping_pong
        ping.delay().get()
      File "/home/ivanov/files/cwd/celery/celery/result.py", line 224, in get
        on_message=on_message,
      File "/home/ivanov/files/cwd/celery/celery/backends/async.py", line 188, in wait_for_pending
        for _ in self._wait_for_pending(result, **kwargs):
      File "/home/ivanov/files/cwd/celery/celery/backends/async.py", line 255, in _wait_for_pending
    on_interval=on_interval):
      File "/home/ivanov/files/cwd/celery/celery/backends/async.py", line 56, in drain_events_until
        yield self.wait_for(p, wait, timeout=1)
      File "/home/ivanov/files/cwd/celery/celery/backends/async.py", line 65, in wait_for
        wait(timeout=timeout)
      File "/home/ivanov/files/cwd/celery/celery/backends/rpc.py", line 63, in drain_events
        return self._connection.drain_events(timeout=timeout)
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/kombu/connection.py", line 301, in drain_events
        return self.transport.drain_events(self.connection, **kwargs)
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
        return connection.drain_events(**kwargs)
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/amqp/connection.py", line 491, in drain_events
        while not self.blocking_read(timeout):
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/amqp/connection.py", line 496, in blocking_read
        frame = self.transport.read_frame()
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/amqp/transport.py", line 243, in read_frame
        frame_header = read(7, True)
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/amqp/transport.py", line 426, in _read
        raise IOError('Socket closed')
    OSError: Socket closed
    INFO:root:one more try
    ERROR:root:second exception 360.07977294921875
    Traceback (most recent call last):
      File "./bug_sample.py", line 27, in ping_pong
        ping.delay().get()
      File "/home/ivanov/files/cwd/celery/celery/result.py", line 224, in get
        on_message=on_message,
      File "/home/ivanov/files/cwd/celery/celery/backends/async.py", line 188, in wait_for_pending
        for _ in self._wait_for_pending(result, **kwargs):
      File "/home/ivanov/files/cwd/celery/celery/backends/async.py", line 255, in _wait_for_pending
        on_interval=on_interval):
      File "/home/ivanov/files/cwd/celery/celery/backends/async.py", line 56, in drain_events_until
        yield self.wait_for(p, wait, timeout=1)
      File "/home/ivanov/files/cwd/celery/celery/backends/async.py", line 65, in wait_for
        wait(timeout=timeout)
      File "/home/ivanov/files/cwd/celery/celery/backends/rpc.py", line 63, in drain_events
        return self._connection.drain_events(timeout=timeout)
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/kombu/connection.py", line 301, in drain_events
        return self.transport.drain_events(self.connection, **kwargs)
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
        return connection.drain_events(**kwargs)
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/amqp/connection.py", line 491, in drain_events
        while not self.blocking_read(timeout):
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/amqp/connection.py", line 496, in blocking_read
        frame = self.transport.read_frame()
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/amqp/transport.py", line 243, in read_frame
        frame_header = read(7, True)
      File "/home/ivanov/files/opt/miniconda3/envs/mlservice/lib/python3.6/site-packages/amqp/transport.py", line 426, in _read
        raise IOError('Socket closed') 
    OSError: Socket closed

**Comment by iivvaall** [comment] 2018-07-04 09:46
setting ` app.conf.broker_heartbeat = 1`  speeds up the fail to 3 seconds
It seems the bug was introduced by this 
[commit](https://github.com/celery/celery/commit/22adf673e9f6e920ddf559b57bd18baf186b692e)

**Comment by iivvaall** [comment] 2018-07-04 15:49
celery as a client library does not have ability to call heartbeat_check periodically. So, the setting introduced by #4148 seems to be useless. 

3*heartbeat_interviews is the interval after which rabbit  closes a connection. Celery does not recognize this case and continue reusing the broken connection over and over again. 

More over it is not a heartbeat case. Sometimes celery does not recognize rabbit restart which  happens when client code does not use celery.

**Comment by auvipy** [comment] 2018-08-12 11:15
can you open a PR to fix the regression?

**Comment by p2k** [comment] 2018-08-12 21:18
I'd like to suggest a little workaround (not 100% sure if this issue is the right place for it):

On any method that offers `on_interval` as parameter (e.g. AsyncResult's get() or ResultSet's iter_native) set this parameter to a lambda (or function) with that body:

```
obj.backend.result_consumer._connection.heartbeat_check()
```

In the above example this would be:

```
result = ping.delay()
result.get(on_interval=lambda: result.backend.result_consumer._connection.heartbeat_check())
```

I'm afraid this is a hack and might only work with amqp, but I hope it might inspire somebody who's working on celery to add a feature like that.

PS: If you wanted me to fix/add this at the various places where I believe it makes sense and create a PR, I'd need more information about the internals of celery so this won't be a hack. Maybe a chat somewhere would light things up; just point me to an IRC or Slack or Discord or anything.

**Comment by iivvaall** [comment] 2018-08-14 11:03
> can you open a PR to fix the regression?

No, I can't.

**Comment by soulrebel** [comment] 2018-08-30 10:01
Would it be better to just start a thread to manage the connection to rabbit and send the heartbeats?

**Comment by thedrow** [comment] 2018-08-30 12:01
#4148 did not introduce the `broker_heartbeat` option.
It merely ensured it is being used.

Can you please explain why do you consider using the correct `broker_heartbeat` value from the configuration a bug?

**Comment by iivvaall** [comment] 2018-08-30 12:32
> Can you please explain why do you consider using the correct broker_heartbeat value from the configuration a bug?

If you send broker_heartbeat to rabbit, you are expected to send heartbeats periodically. You must arrange your application (not celery) code to do so. It is not a good idea for a default case. AFAIU the setting is rather for a worker, not a client.

**Comment by soulrebel** [comment] 2018-08-30 12:35
@thedrow The bug is that heartbeats are supported only in the worker. It does say so in the docs as well.
So it breaks when they are enabled because in the client there is no thread that sends them periodically.

Contrary to @iivvaall, I think it's Celery's responsability to send them and keep the connection healthy in the client as well.

**Comment by soulrebel** [comment] 2018-08-30 16:16
I spent some time trying to implement a thread that handles heartbeats on active connections.
I got stuck when I could not find a way to acquire exclusively each connection in the pool, one by one, but only in LIFO order.

So there is no way to be thread safe, unless the pool is acquired fully, which is absolutely crazy. Possibly it can work well for a single connection.

**Comment by soulrebel** [comment] 2018-08-31 08:15
I wrote a Thread that sends the hearbeats while the connection is free. It seems to work for a pool of 1.
I welcome comments:

```python
import time
import threading
import logging
import socket
from kombu.exceptions import ConnectionLimitExceeded

logger = logging.getLogger(__name__)

class AmqpHeartBeatThread(threading.Thread):

    def __init__(self, pool):
        super().__init__()
        self.setDaemon(True)
        self.pool = pool
        if pool.limit != 1:
            raise ValueError('Pool must be limited to 1 connection')
        self.name = 'AmqpHeartBeatThread'

    def run(self):
        logger.debug('Starting heartbeat thread')
        try:
            while True:
                starttime = time.time()
                self._send_heartbeats()
                time.sleep(max(0, 1.0 - (time.time() - starttime)))
        except Exception: # pylint: disable=broad-except
            logger.fatal('Heartbeat thread terminating on exception', exc_info=True)

    def _send_heartbeats(self):
        connection = None
        try:
            connection = self.pool.acquire(block=False)
            if not getattr(connection, 'connected', False):
                return
            connection.heartbeat_check()
            connection.drain_events(timeout=0)
        except (socket.timeout, ConnectionLimitExceeded):
            pass
        except Exception as exc: # pylint: disable=broad-except
            logger.warning('Closing connection %r on heartbeat error: %s', connection, exc)
            connection._connection.close() # pylint: disable=protected-access
        finally:
            if connection is not None:
                connection.release()
```
Must be started with the producer connections pool: `AmqpHeartBeatThread(APP.producer_pool.connections).start()`

This is limited to pools of size 1, because there is no way to choose which connection to acquire and acquire them one by one to do the heartbeat.

**Comment by last-partizan** [comment] 2019-01-09 13:31
Hello.

I see only one solution here:

1. Revert pull request https://github.com/celery/celery/pull/4148 - broker_heartbeat is worker-only option and should not be used for client connections. It fixes this issue.
2. If someone needs client-side broker heartbeat - it must be separate option and with heartbeat_check.

**Comment by last-partizan** [comment] 2019-04-04 18:59
@thedrow 
the problem as i see it - client connections uses broker_heartbeat, becouse https://github.com/celery/celery/pull/4148/files sets heartbeat and does not differentiate between client and broker connections.
heartbeat from `conf.broker_heartbeat` must be set only for broker connections.

You are more familiar with the code, probably you can fix it.
Or take a look at  https://github.com/celery/celery/blob/master/celery/app/base.py#L829, confirm my suspicions and i will try to fix it myself and make pull-request.

**Comment by last-partizan** [comment] 2019-04-05 07:52
btw, what was original bug https://github.com/celery/celery/pull/4148 tried to fix? i don't see any in pull-request description

**Comment by matteius** [comment] 2019-06-17 06:04
@neg3ntropy  Okay I am going to weigh in here -- we use 4.3.0 and heartbeats and Rabbit MQ and they work just fine in a high volume setting.  It is true that telling Celery to use heartbeats requires the worker to receive heartbeats and two missed means that it lost its connection.  We did not implement a separate thread to send or manage heartbeats, instead the Rabbit MQ broker must support heatbeats and negotiates that when the client connects.    This is from the Rabbit MQ Docs:

Low Timeout Values and False Positives
Setting heartbeat timeout value too low can lead to false positives (peer being considered unavailable while it is not really the case) due to transient network congestion, short-lived server flow control, and so on.

This should be taken into consideration when picking a timeout value.

Several years worth of feedback from the users and client library maintainers suggest that values lower than 5 seconds are fairly likely to cause false positives, and values of 1 second or lower are very likely to do so. Values within the 5 to 20 seconds range are optimal for most environments.

https://www.rabbitmq.com/heartbeats.html

We use a value of 30 and it works on these versions.  What version of the Rabbit MQ server are you running for your broker?

**Comment by matteius** [comment] 2019-06-17 06:05
Perhaps this is related to using the results backend?  We technically have that disabled and it works -- and both bug reports mention using the results backends.

**Comment by martinmaillard** [comment] 2019-06-17 07:28
@matteius the issue is not between the workers and RabbitMQ, but between the Celery client and RabbitMQ. A use case where it can be an issue is if you're waiting for the results of a group of tasks:
```python
results = celery.group(my_tasks)().get()
```
Since the client is not sending heartbeats, if the tasks take longer than the heartbeat value to finish, your connection to RabbitMQ will be closed and your code will crash.

**Comment by matteius** [comment] 2019-06-17 12:31
@martinmaillard  -- The workers utilize the AMQP client -- the heartbeat is an AMQP protocol that bypasses TCPI/IP.  From the celery docs:  https://docs.celeryproject.org/en/latest/userguide/configuration.html#broker-heartbeat

Default: 120.0 (negotiated by server).

**Note: This value is only used by the worker, clients do not use a heartbeat at the moment.**

It’s not always possible to detect connection loss in a timely manner using TCP/IP alone, so AMQP defines something called heartbeats that’s is used both by the client and the broker to detect if a connection was closed.

If the heartbeat value is 10 seconds, then the heartbeat will be monitored at the interval specified by the broker_heartbeat_checkrate setting (by default this is set to double the rate of the heartbeat value, so for the 10 seconds, the heartbeat is checked every 5 seconds).
------

So I guess my question is what are you calling the Celery client?  The only thing I can think to call the Celery client is the master process that talks to the other forked celery workers which is still outside the scope of heartbeats.

**Comment by matteius** [comment] 2019-06-17 12:51
FWIW -- We too have the problem where if we restart the Rabbit MQ server the workers are unable to reestablish connection until we restart them, but it has nothing to do with heartbeats.  We have been running on Celery 4.2.1 as of currently.   I will take a moment to diff the two versions you mention and try your sample test case.

**Comment by matteius** [comment] 2019-06-17 14:29
OK Well I do concede that it is technically a heartbeat issue, as I have explored the provided test case from @iivvaall some.  I experience the issue in my QA environment unless I run the celery worker flag --without-heartbeat AND have the setting broker_heartbeat set to 0.  If I run the worker flag --without-heartbeat and leave a broker_heartbeat setting of 30 then the timeout happens at exactly 90 seconds which is the time for 3 missed heartbeats.   It was our reliance on heartbeats to keep the connections alive for idle workers and the fact that we did not use the results backend that lead to us disabling the results backend when we saw these same type of connection errors back upon upgrading to 4.2.1 -- I recall this now.

I will now downgrade to the version that supposedly works fine and run my same series of tests to see if I can learn some more about the issue.

**Comment by matteius** [comment] 2019-06-17 21:24
Ok technically its 1 line change that introduced this bug in celery 4.2.0 -- technically this PR will fix the issue, but I learned that means in 4.1.0 and prior it was not using heartbeats even if you had it configured:

2019-06-17 17:17:27,337 12291 MainProcess celery.app.base _connection
    INFO Heartbeat is None
2019-06-17 17:17:27,338 12291 MainProcess celery.app.base _connection
    INFO Self.conf.broker_heartbeat is 3
2019-06-17 17:17:27,338 12291 MainProcess celery.app.base _connection
    INFO conf.broker_heartbeat is 3
2019-06-17 17:17:27,338 12291 MainProcess celery.app.base _connection
    **INFO heartbeat will be None**

But when the in base,py line was changed from in the PR that @iivvaall  mentioned to consider the heartbeat value from the conf it began using them (https://github.com/celery/celery/pull/4148/files#diff-31172810badb4671ba4d870da5f86550)

2019-06-17 17:13:42,497 12273 MainProcess celery.app.base _connection
    INFO Heartbeat is None
2019-06-17 17:13:42,498 12273 MainProcess celery.app.base _connection
    INFO Self.conf.broker_heartbeat is 3
2019-06-17 17:13:42,498 12273 MainProcess celery.app.base _connection
    INFO conf.broker_heartbeat is 3
2019-06-17 17:13:42,498 12273 MainProcess celery.app.base _connection
    **INFO heartbeat will be 3**

All of this proves to me that heartbeats have never worked right in conjunction with listening for results or using the results backend.  I assume we want to figure out how to make that work right for future releases.

**Comment by matteius** [comment] 2019-06-18 02:36
I may stare at this some other time, but what I think is happening (because I reported the errors to our QA sentry and saw the variable values in the stack trace) that when heartbeats are disabled and the broker_heartbeat is configured to be 0, then when py-amqp calls socket.settimeout it uses 0 and that according to the Python docs it will use non-blocking mode but setting it to a timeout value of something like 1 (which is what py-amqp uses if the broker_heartbeats pass in a timeout value) and this also calls socket.settimeout which sets the socket into time out mode.   It seems to timeout at 3* the value specified for broker_heartbeat -- so I think something is missing a heartbeat and closing the socket that is assigned to in the AsyncResult object -- any attempt I made to recreate the connection did not work because it seemed to rely on the original socket not timing out.
https://docs.python.org/3/library/socket.html#notes-on-socket-timeouts
socket.settimeout is called in a few places here:  https://github.com/celery/py-amqp/blob/master/amqp/transport.py

**Comment by thedrow** [comment] 2019-06-21 07:23
So if we normalize timeouts with a value of `0` to `None` everything will be fine?

**Comment by matteius** [comment] 2019-06-21 11:38
@thedrow From my experience supporting Celery in a high volume transactional environment that uses queues and celery tasks for some things is that the most critical bugs right now all stem from SocketTimeouts.   I do not know the intended design of py-amqp though I've begun learning that code base more in an attempt to understand it.  What I do know is that Celery workers hang after certain SocketTimeout exception and are unable to properly recover from it, even with the results backend disabled.  We have seen this be caused by a number of events such as temporary DNS resolution failure, pulling Rabbit MQ out of the elb, or in the case of people that use the results backend like this ticket I've seen some of those test cases totally hang the client in a similar way where after the Socket Error the client is done with getting results and enqueing tasks -- the worker may resume if the client restarts in that case unless it too gets an unrecoverable Socket Error.

Worth noting that in that py3 link on sockets above that setting 0 is a different behavior than setting None.  My understanding of the python doc is:
0 -- Socket is put into non-blocking mode
None -- Socket is put into blocking mode
positive floating point number -- Socket is put into timeout mode

I would definitely like some feedback regarding what the core developers what the intended socket modes are and why?  It seems to be true that when using heartbeats the socket is set to timeout mode.  In the failing test case I explored here -- the Timeout is a predictable 3*the heartbeat value configured or if you set that to 0 and run worker with heartbeats-disabled then it can run indefinitely in what appears to be non-blocking mode.  

Indefinitely until a SocketError is eventually reached--and that can send the worker fatal.  I have a ticket in my work backlog about this because they want to be able to remove Rabbit MQ from the elb and add it back without restarting all the workers.   I have been looking for and testing logical places in celery, or kombu or py-amqp and even billiard to look for where the connection is made, before or after forking, and most importantly to try and add logic to make it recover from such a connection error by opening a new connection.  So far I have been unsuccessful at that specifically but would love to keep learning more so that maybe I can get a bit further on it.

**Comment by thedrow** [comment] 2019-06-21 15:33
I'm positive we should not set the socket into non-blocking mode.
When we initialize it, we set it to blocking mode and passing a timeout of zero to set the socket into non-blocking mode is not something we intended to support.
Can you try that patch and see if it helps in any way?

**Comment by matteius** [comment] 2019-06-22 02:11
@thedrow Sorry I may have sent you down the wrong path with some bad info -- what I saw ended up being that the broker heartbeat conf value getting passed down and in a later in amqp-py frame it uses timeout of 1 which also isn't what we call sock.settimeout with.   There are 4 spots in py-amqp where we call settimeout on a socket and so I instrumented it with logging and ran your patch version and some prior versions and always saw the same thing, it does not get set to non-blocking -- it gets set to timeout mode multiple times and then blocking mode.   The result is the same between versions:

Instrumenting the 4 places we call settimeout in py-amqp and starting up a worker with the new py-amqp patch  (heartbeats disabld and broker_heartbeat set to 0)
2019-06-21 21:36:56,987 26179 MainProcess amqp.transport _connect
    INFO Calling sock.settimeout C with timeout 4
2019-06-21 21:36:57,028 26179 MainProcess amqp.transport _init_socket
    INFO Calling sock.settimeout D with timeout None
2019-06-21 21:36:57,029 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:36:57,174 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:36:57,174 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:36:57,213 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:36:57,214 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:36:57,354 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:36:57,354 26179 MainProcess celery.worker.consumer.connection start
    INFO Connected to amqp://****:****@*******:5672//qa
2019-06-21 21:36:57,367 26179 MainProcess amqp.transport _connect
    INFO Calling sock.settimeout C with timeout 4
2019-06-21 21:36:57,404 26179 MainProcess amqp.transport _init_socket
    INFO Calling sock.settimeout D with timeout None
2019-06-21 21:36:57,405 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:36:57,546 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:36:57,547 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:36:57,586 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:36:57,586 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:36:57,719 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:36:58,147 26179 MainProcess celery.apps.worker on_consumer_ready
    INFO celery@user-VirtualBox ready.
2019-06-21 21:36:58,186 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 0.1
2019-06-21 21:36:58,288 26179 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None


Instrumenting the 4 places we call settimeout in py-amqp and starting up a worker with the celery 4.1 prior amqp==2.5.0
    INFO Calling sock.settimeout C with timeout 4
2019-06-21 21:41:09,014 26196 MainProcess amqp.transport _init_socket
    INFO Calling sock.settimeout D with timeout None
2019-06-21 21:41:09,016 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:41:09,156 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:41:09,157 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:41:09,195 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:41:09,196 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:41:09,329 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:41:09,330 26196 MainProcess celery.worker.consumer.connection start
    INFO Connected to amqp://****:****@*******:5672//qa
2019-06-21 21:41:09,344 26196 MainProcess amqp.transport _connect
    INFO Calling sock.settimeout C with timeout 4
2019-06-21 21:41:09,383 26196 MainProcess amqp.transport _init_socket
    INFO Calling sock.settimeout D with timeout None
2019-06-21 21:41:09,383 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:41:09,533 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:41:09,534 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:41:09,573 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:41:09,574 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 4
2019-06-21 21:41:09,708 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None
2019-06-21 21:41:10,153 26196 MainProcess celery.apps.worker on_consumer_ready
    INFO celery@user-VirtualBox ready.
2019-06-21 21:41:10,192 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout A with timeout 0.1
2019-06-21 21:41:10,294 26196 MainProcess amqp.transport having_timeout
    INFO Calling sock.settimeout B with timeout None

**Comment by auvipy** [comment] 2019-06-27 05:01
https://github.com/celery/celery/pull/5622 does revert this help? please check

**Comment by matteius** [comment] 2019-06-29 09:20
Its not going to help @auvipy  because all it does is disable heartbeats when you think you have enabled them in the config.  It doesn't actually fix the issue of preventing this bug when running with heartbeats enabled, it will just become as prior -- you won't actually be using heartbeats.

**Comment by last-partizan** [comment] 2019-06-29 09:32
@matteius what heartbeats you are talking about?

Workers will use heartbeats as expected. Clients will not use heartbeats (becouse client does not have thread to send heartbeats anyway). So this bug is fixed.

**Comment by matteius** [comment] 2019-06-29 09:47
@last-partizan Ok that totally makes sense and I missed some of the earlier points somehow but now I see what we are calling the client is jut an application using celery to enque tasks and possibly wait for results.  I agree that nothing is managing heartbeats there, so in that case the historical behavior was to create a blocking socket instead of a timeout socket because nothing would refresh that timeout as you said, no other thread.   I agree too with wondering what the intention of the original PR was to start using the value from configuration there.

**Comment by last-partizan** [comment] 2019-06-29 10:02
I just checked if bug exists using code from first message (Using broker_timeout=10, and default settings).
Bug is fixed now.

**Closed** 2019-06-29 10:10 UTC
Labels: Component: RPC Results Backend, regression

**Comment by venu13** [comment] 2020-09-13 12:21
> @matteius the issue is not between the workers and RabbitMQ, but between the Celery client and RabbitMQ. A use case where it can be an issue is if you're waiting for the results of a group of tasks:
> 
> ```python
> results = celery.group(my_tasks)().get()
> ```
> 
> Since the client is not sending heartbeats, if the tasks take longer than the heartbeat value to finish, your connection to RabbitMQ will be closed and your code will crash.

Any solution to this issue, I am facing same problem
