### ISSUE TITLE
Error exception when load keras model deep learning by celery

### ISSUE THREAD

**Issue by trangtv57** [celery/celery#4172] opened 2017-07-28 03:57 UTC
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
I want to load model i have trained it before in keras by celery. But in tensorflow( backend of keras) its just accept for load only 1 model on same session( can say is same thread). So problem here is, how can i saparate each thread in celery (can just how to make each thread have it's own each object model keras) to can run.
## Expected behavior
Can run api of deep learning( keras) with celery

**Comment by niteeshm** [comment] 2017-08-07 06:32
@trangtv57 Can you post some logs or explain what error is there if any ? Load the model in our main celery app and use it everywhere else required. All workers will have separate object.s

**Comment by trangtv57** [comment] 2017-08-08 01:56
Sorry if my question have some confuse. I have object graph: is tensorflow.get_default_graph(). this object need share separate on all threads like this: In Celery I run with mode debugging but nothing so error ( note: I have same problem (with nothing error show, its just stuck when running) when I run load my model on multi process, so I can understand why celery don't show any thing and just stuck).
In my sample when I load model in multi thread, my model can run:

`    graph = tf.get_default_graph()
    print(id(graph))
    for i in range(n_threads):
        o_worker_dga = WorkerABC(queue_dm, model, graph)
        o_worker_dga.start()
        l_threads.append(o_worker_dga)

    for e_thread in l_threads:
        e_thread.join()`
AND File worker thread:
`class WorkerABC(threading.Thread):
    dga_o = None
    queue_dm = None
    graph = None

    def __init__(self, queue_dm, model_dga, graph):
        threading.Thread.__init__(self)
        self.queue_dm = queue_dm
        self.model = model_dga
        self.graph = graph

    def run(self):
        self.abc_o = ABC()
        self.abc_o.set_model(self.model)

        # global graph
        # with graph[0].as_default():
        with self.graph.as_default():
            while True:
                if not self.queue_dm.empty():
                    dm_next = self.queue_dm.get()
                    self.abc_o.set_omain(dm_next)
                    print(self.abc_o.predict_probability_domain())
                else:
                    break`

**Comment by godelstheory** [comment] 2017-08-28 13:55
The issue is `get_session` from the _TensorFlow_ library: this will hang across processes. It is not recommended to utilize `multiprocess` (see the last comment of https://github.com/tensorflow/tensorflow/issues/8220).

A workaround is that all imports to _Tensorflow_ (including _keras_) occur only in the child, spawned processes. This has allowed me to effectively load and utilize serialized _TensorFlow_ models across child process using _keras_. see https://github.com/tensorflow/tensorflow/issues/5448

**Comment by auvipy** [comment] 2017-12-19 11:18
closing as not a bug, if any documentation or code fixes are suggested plz send a pr

**Closed by auvipy** 2017-12-19 11:18 UTC
Labels: Status: Not a Bug
