### ISSUE TITLE
Release version 4.3 of Celery

### ISSUE THREAD

**Issue by auvipy** [celery/celery#5180] opened 2018-11-16 05:34 UTC
@thedrow @georgepsarakis It would be great if we can release the beta version of 4.3 by December 1st. before that, we need to release py-amqp. kombu and other dependencies first though. it's a soft reminder 

### If you are using Celery to create a commercial product, please consider becoming our [backer](https://opencollective.com/celery#backer) or our [sponsor](https://opencollective.com/celery#sponsor) to ensure Celery's future.

**Comment by guyisra** [comment] 2018-11-16 14:54
@auvipy @thedrow @georgepsarakis  can we quick release 4.2.2 just for the redis limitation ? as it currently clashes with the latest redis which has incompatible changes

**Comment by thedrow** [comment] 2018-11-19 11:03
I'm not sure if I'll have the time. I'll try to do so.

**Comment by auvipy** [comment] 2018-11-19 11:41
I can release this time but need some clear instructions

**Comment by MeTaNoV** [comment] 2018-11-19 16:05
It would indeed be gr8 to get a 4.2.2 including the redis dependency fix, because I spent too much time already to find the source of the issue, and would be good for any person jumping into it!

**Comment by alexandre-paroissien** [comment] 2018-11-20 04:32
I'm looking forward for python redis 3.0 support too, since people who naturally updated their libraries through pip/pipenv (pypi) have to rollback python redis to 2.10.6 to make things work, and same thing with Python 3.7, people who use celery from pip/pipenv (pypi) and use the latest Python (as in arch/manjaro linux) currently have to install a previous Python version (3.6) to make things work

**Comment by WisdomPill** [comment] 2018-11-21 14:05
Will this new release support python 3.7?

**Comment by auvipy** [comment] 2018-11-21 14:35
yes

**Comment by xiantotikui** [comment] 2018-11-28 10:22
Will this new release support redis 3.0.1?

**Comment by auvipy** [comment] 2018-11-28 11:41
yes

**Comment by xirdneh** [comment] 2018-12-02 18:44
@auvipy, @thedrow, Anything I can help with for this release?

**Comment by thedrow** [comment] 2018-12-04 09:45
Issue #5212 is critical to the release.
We still need to test Celery with Python 3.7.

**Comment by xirdneh** [comment] 2018-12-04 18:53
@thedrow Looks like #5212 is fixed if we do a Kombu release, right?
IF that's correct then we need to add 3.7 testing to our CI. I can work on that.

**Comment by auvipy** [comment] 2018-12-04 18:55
py-amqp and kombu release is the pre-req, after that, I can polish my pr for 3.7 support to get it merged

**Comment by xirdneh** [comment] 2018-12-04 19:40
@auvipy You mean this PR: https://github.com/celery/celery/pull/4859 ?

**Comment by thedrow** [comment] 2018-12-06 14:51
I released Kombu 4.2.2 with that fix only.
The build should pass now.

**Comment by TheBlusky** [comment] 2018-12-14 06:50
Any idea of an ETA for this version to release ?

**Comment by thedrow** [comment] 2018-12-14 08:13
There's still some work to do. We need to fix the build for Kombu as well.
I'll go over the remaining issues.

**Comment by xirdneh** [comment] 2018-12-14 20:58
@thedrow Any issue I can take over?
Or are you going to list the remaining issues here?

**Comment by georgepsarakis** [comment] 2018-12-15 06:09
@xirdneh you can check the milestone https://github.com/celery/celery/milestone/20 .

**Comment by auvipy** [comment] 2018-12-15 14:12
I think we can remove non-blockers from this milestone. and lean down the remaining issues. releasing py-amqp and related packages to check how they work on celery 4.3 rc1

**Comment by thedrow** [comment] 2018-12-31 15:37
Right now the build for master is failing on Python 3.7.
See https://travis-ci.org/celery/celery/jobs/473236382.

**Comment by georgepsarakis** [comment] 2018-12-31 16:32
@thedrow I think this is due to Python 3.7 converting `StopIteration` exceptions raised in generators, to `RuntimeError` exceptions, see [here](https://stackoverflow.com/a/51701040/920374).

My suggestion would be to add an exception handling branch, detecting the specific type of `RuntimeError`:

https://github.com/celery/kombu/blob/e4dc1688a2bfe422813ffc79d9db50c06f38fbaf/kombu/asynchronous/hub.py#L348-L359

```python
except RuntimeError as e:
  if e.args != ('generator raised StopIteration',):
      raise e
```

Admittedly, the above could be considered somehow weak, but I think it is the only method of identifying the exception conversion, in this particular case.

**Comment by thedrow** [comment] 2018-12-31 17:09
That fix is incorrect.
See https://github.com/celery/celery/blob/master/t/unit/worker/test_loops.py#L386
According to PEP 479, generators should raise `StopIterator` anymore.

**Comment by thedrow** [comment] 2018-12-31 17:43
It seems we have uncovered a more serious issue which is a blocker in my opinion.
See https://travis-ci.org/celery/celery/jobs/473900629#L3204

**Comment by thedrow** [comment] 2018-12-31 18:31
Hopefully, https://github.com/celery/kombu/pull/972 will resolve this issue.

**Comment by thedrow** [comment] 2018-12-31 18:36
The build for kombu is broken so the entire test suite does not run.
See https://travis-ci.org/celery/kombu/jobs/472712374#L1215.

**Comment by thedrow** [comment] 2018-12-31 19:01
I can't reproduce the test failure for kombu locally :(

**Comment by matusvalo** [comment] 2019-01-03 15:05
@thedrow I have fixed failing kombu tests - see PR https://github.com/celery/kombu/pull/978. Tests were using pyamqp library from master. The tests broke PR https://github.com/celery/py-amqp/pull/221.

**Comment by MRigal** [comment] 2019-01-04 17:42
Maybe a low hanging fruit would be to fix the couple `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

**Comment by thedrow** [comment] 2019-01-13 13:30
py-amqp 2.4.0 is now released.
Next in turn is Kombu.

**Comment by halfdan** [comment] 2019-01-14 08:32
@thedrow What's missing for the 4.3 release? The Kombu PR seems to be merged already - are we waiting for a new release of Kombu? Are we waiting for fixes to everything in https://github.com/celery/celery/milestone/20?

Trying to see where I can help.

**Comment by thedrow** [comment] 2019-01-14 10:01
I need to triage the issues which are critical for Kombu 4.3.
Anything in https://github.com/celery/celery/issues?q=is%3Aopen+label%3A%22Status%3A+Needs+Test+Coverage+%E2%9C%98%22+milestone%3Av4.3 or https://github.com/celery/kombu/pull/911 will help.
I think we're pretty much ready for a release of Kombu but I need to verify.
In the meanwhile I'm working on release notes.

**Comment by thedrow** [comment] 2019-01-14 11:17
Can we also please resolve the dispute in #5259?

**Comment by larsrinn** [comment] 2019-01-16 19:48
And the same for #5206 . I opened #5289

**Comment by larsrinn** [comment] 2019-01-16 21:11
About that `StopIteration` stuff: In Kombu it was changed to not "convert" the `ValueError` to `StopIteration` https://github.com/celery/kombu/pull/972/files 

However, in celery `worker.loops.asynloop` a `StopIteration` error is catched and a new loop is created in that case. Won't the change in kombu without a change in celery cause some issues? Because now instead of creating a new loop, the existing (but broken?) loop is continued to be used? 

https://github.com/celery/celery/blob/c1d0bfea9ad98477cbc1def99157fe5109555500/celery/worker/loops.py#L92

**Comment by thedrow** [comment] 2019-01-17 21:59
@larsrinn please open an issue about it so we won't forget to look into it.

**Comment by amahlaka** [comment] 2019-01-25 02:57
Will this include fix for the async issue?
i hope this gets released as soon as possible.

**Comment by larsrinn** [comment] 2019-01-25 07:39
Yes, I'm waiting for it, too.

But I must say I'm a bit afraid about the future of celery. Python 3.7 is out for 7 months already and still not supported. I know this project is run by volunteers who probably have a ton of other things to do. But I contributed a couple of PRs in the past weeks, mostly adding test coverage and getting the CI to pass. It seems like none of them has been looked at, let alone merged, even though they are all so minor, reviews should be doable in a few minutes, if not even seconds. This is a pretty disappointing contributing experience.

**Comment by tobami** [comment] 2019-01-25 11:02
It would be a great improvement to the project to do much smaller releases. 4.3 is a big release that still needs work, and in the meantime many users have critical issues like the [severe memory leak](https://github.com/celery/celery/issues/4843), which could get fixed quickly in a 4.2.X release. Even contributing a particular fix is not very useful because it will not be released for months.

**Comment by matusvalo** [comment] 2019-01-25 20:18
@larsrinn I will review your PR if I will have time.

**Comment by halfdan** [comment] 2019-01-26 11:07
I definitely agree with the above statements. Python 3.7 support is the most important thing for me right now.

Is there an option to add additional maintainers?

**Comment by ransford** [comment] 2019-02-01 01:10
Celery is slightly broken against current pytest (another popular module); #5271 describes the problem and #5097 fixes it. Perhaps if the 4.3 release is becoming too daunting, a minor version bump to 4.2.2 could roll up several smaller fixes (#5271 and other bug fixes)? I realize this is probably easier said than done, but it might allow a bunch of us to rejoin the release cycle instead of maintaining our own forks while awaiting 4.3. Thank you for this excellent module.

**Comment by lk-geimfari** [comment] 2019-02-01 09:31
Celery exactly needs sponsorship. This is a commonly used Task Quee so it's must be maintained, but no one wants to maintain the project for free. So, maybe it makes sense to run crowdfunding or something like this to collect the money?

**Comment by auvipy** [comment] 2019-02-01 19:40
so which companies are going to sponsor our work? Is anyone interested? I will be very much interested to get some companies backing my time for working with celery part time/full time!

**Comment by antoine-gallix** [comment] 2019-02-01 19:56
I'm sure if there was a proper setup for regular donations, it would be easier for companies to just subscribe for a monthly support and forget about it. This might be the source of a more stable income than a simple paypal one-time donate button. I could easily convince my company to do so for example, than asking them to give a lot in one go, or to remember them to make a manual regular donation.

**Comment by bsod90** [comment] 2019-02-01 19:58
I think sponsorship is very possible, but you need to plant the idea in people's heads. E.g. outside of this thread, nobody even thinks that this project may need support, they just download and install celery and think it just "exists". I think, if you guys had started a fundraiser, a lot of companies would donate.
I saw the donation link in the README and contributed a bit from a personal account, but it's still too obscure for companies to notice. It should be right in front of them (at least in all the social networks) and it should have a proper call to action. E.g. if you're a developer and you know your company relies on celery, ask your manager to donate.
I can say that whenever I see organized fundraisers from the open source projects I like, I always try to donate or at least spread their social media campaign. I'm sure a lot of people do the same.

**Comment by xirdneh** [comment] 2019-02-05 15:38
@auvipy I saw most of the issues in the 4.3 milestone were moved or closed now.
Are we planning on doing a 4.3 release soon?

**Comment by auvipy** [comment] 2019-02-05 15:44
yes!!! as it's a long overdue!!

**Comment by thedrow** [comment] 2019-02-05 16:16
I'm on it. Expect an RC very soon.

**Comment by tell-k** [comment] 2019-02-05 16:23
> I ran a fundraiser and it turned to a massive failure!! we have opencollective and tide lift option open in the readme. people interested can donate/sponsor there or ping me directly in my email.

Celery authors. I have become a backer from https://opencollective.com/celery. Thank you for your awesome tool.  Your tools are helping me a lot :)

**Comment by thedrow** [comment] 2019-02-06 14:35
Anyone objecting to codename 4.3 as [Rhubarb](https://www.youtube.com/watch?v=_AWIqXzvX-U)?
It's one of my favourite tracks from Selected Ambient Works II.

If you have any other suggestions, please make note of them here.

**Comment by auvipy** [comment] 2019-02-06 14:49
I like it :)

**Comment by thedrow** [comment] 2019-02-06 16:42
Kombu 4.3 is now released!

**Comment by thedrow** [comment] 2019-02-07 15:49
Can someone please take a look at our Windows build?
Some of the tests are failing.
Also, we're missing some Python versions there, we should add them (although that's not a blocker).

**Comment by xirdneh** [comment] 2019-02-08 22:28
@thedrow Where are the Windows build running? Appveyor?

**Comment by ciarancourtney** [comment] 2019-02-09 13:54
> Can someone please take a look at our Windows build?
> Some of the tests are failing.
> Also, we're missing some Python versions there, we should add them (although that's not a blocker).

PR here https://github.com/celery/celery/pull/5329

**Comment by larsrinn** [comment] 2019-02-09 14:11
So 4.3 is good to go now?

**Comment by seirl** [comment] 2019-02-09 18:32
Hi! You closed this issue, but the version on pypi is still 4.2.1. Is there somewhere we can track the release on pypi? Thanks.

**Comment by Jamim** [comment] 2019-02-10 08:08
Hi folks,

@seirl I believe that this issue was closed accidentally due to description of #5329 contains `Fixes #5180` text.

@auvipy Could you please reopen this issue until `4.3` isn't actually released?
Thanks!

**Comment by ciarancourtney** [comment] 2019-02-10 11:23
My bad, I thought auto-close would just be an option for pullee

**Comment by auvipy** [comment] 2019-02-10 11:41
this was closed automatically by GitHub!!!

**Comment by thedrow** [comment] 2019-02-10 12:02
@xirdneh yup.

**Comment by thedrow** [comment] 2019-02-11 19:47
I'm almost done with the Changelog. I still have to elaborate on some of the items and I need to complete adding the remaining items I haven't gotten to.

The what's new section is still largely incomplete.

Feel free to help in any way possible.

**Comment by thedrow** [comment] 2019-02-13 13:54
We have a potential blocker for GA: https://github.com/celery/kombu/issues/1006
RCs will proceed as planned.
Can someone with access to a FreeBSD install debug this?

**Comment by xpyy** [comment] 2019-02-19 14:41
Hello everyone. Any ETA?

**Comment by thedrow** [comment] 2019-02-19 15:26
I just finished the release notes for the first RC.
It's going to be released today.

**Comment by xpyy** [comment] 2019-02-20 10:25
Do you have any ETA for stable release?

**Comment by thedrow** [comment] 2019-02-20 13:57
Once this has been tried in production for a couple of weeks we'll declare GA.
In the near future we will improve our release process and document it so that everything will be clearer.

**Comment by thedrow** [comment] 2019-02-20 15:11
RC1 is released. :tada: 
Please try it in your staging environments.

In the meanwhile, if someone can take a closer look at https://github.com/celery/kombu/issues/1006, https://github.com/celery/kombu/issues/1007 and https://github.com/celery/kombu/issues/1004 which are all regressions from Kombu 4.3, that will help us hit GA.

**Comment by lithammer** [comment] 2019-02-20 21:20
Since https://github.com/celery/kombu/issues/1004 seemed to be in the same area, I attempted a fix for that at as well: https://github.com/celery/kombu/pull/1010

**Comment by thedrow** [comment] 2019-02-21 07:40
Both are now merged.

**Comment by lithammer** [comment] 2019-02-21 10:27
Since this was so much fun I come bearing not one, but _two_ solution proposals for the last issue (
https://github.com/celery/kombu/issues/1006):

- Proposal 1: https://github.com/celery/kombu/pull/1011
- Proposal 2: https://github.com/celery/kombu/pull/1012

**Comment by thedrow** [comment] 2019-03-03 18:00
I took a short break from the release notes to write https://github.com/celery/py-amqp/pull/258.
I'm going to proceed with our what's new document.

**Comment by thedrow** [comment] 2019-03-03 19:47
I released Kombu 4.4 and Celery 4.3.0RC2.
Unless there's any objection or critical fix, this is going to be the last RC.

**Comment by thedrow** [comment] 2019-03-03 20:55
I just released py-amqp 1.4.3 as well.
It fixes two severe deserialization bugs. I have not heard anything about them in production.
Probably because there are no messages in the AMQP protocol with two consequent bitmaps.
The fixes are there for completeness as I guess they could crash Celery.

**Comment by olemoign** [comment] 2019-03-04 09:30
Thank you for the great work @thedrow.

**Comment by thedrow** [comment] 2019-03-06 15:30
Potential blocker for GA: https://github.com/celery/celery/issues/5371

**Comment by xirdneh** [comment] 2019-03-06 16:15
@thedrow I might have some time this week to verify this. I'll update the issue if I'm able to.

**Comment by thedrow** [comment] 2019-03-08 08:56
@xirdneh Please update if you don't and I'll take care of it.

**Comment by thedrow** [comment] 2019-03-08 08:56
@lithammer If you feel like contributing more, I'll even grant you commit rights :)

**Comment by thedrow** [comment] 2019-03-11 15:38
Definite blocker for GA: #5377

**Comment by thedrow** [comment] 2019-03-11 16:08
I have completed our [what's new document](https://github.com/celery/celery/blob/master/docs/whatsnew-4.3.rst) for this release.

Please review it and let me know if I missed anything.

**Comment by georgepsarakis** [comment] 2019-03-11 16:44
@thedrow seems quite thorough and informative! One note though, I am not sure if it is automatically included somehow, but it seems to me like the contributor list has not been yet added?

**Comment by thedrow** [comment] 2019-03-12 15:16
I haven't generated the contribution list yet.
I'm going to do so right before GA.

Here's a list of our current release blockers:
- [ ] #5377
- [ ] #5371
- [ ] #5328
- [ ] #4812

Potential Blockers:
- [ ] #5358

**Comment by georgepsarakis** [comment] 2019-03-12 18:12
@thedrow I think https://github.com/celery/celery/issues/5383 is valid as well.

**Comment by thedrow** [comment] 2019-03-21 14:19
I just released Celery 4.3.0rc3.
This includes new features and bug fixes and some resolved blockers.

**Comment by Rogalek** [comment] 2019-03-22 14:37
Do you maybe know when full version will be available?

**Comment by thedrow** [comment] 2019-03-23 09:10
When we will finish resolving all the blockers.

**Comment by thedrow** [comment] 2019-03-27 11:40
Only one blocker left and than some final documentation tasks.

**Comment by huangsam** [comment] 2019-03-27 15:38
@thedrow looks like celery/kombu#1014 has been closed by a revert-based PR. However, it doesn't show as complete on the checklist. Is it incomplete because the `unique` keyword still needs to be supported?

**Comment by thedrow** [comment] 2019-03-27 20:34
Yes. I'll do that and the final documentation tasks tomorrow.

**Closed** 2019-03-31 15:55 UTC
Labels: Category: Project Governance

**Comment by thedrow** [comment] 2019-03-31 15:57
### Released! :tada: 
### Thank you everyone for your efforts, time and skills.

The next version, Celery 5 is something to be excited about.

**Comment by auvipy** [comment] 2019-03-31 16:05
I want to start removing python2 from master

**Comment by ajaykmr2292** [comment] 2019-04-01 00:44
Can I know when will the Celery 5 be released? I am really excited to use that.

**Comment by auvipy** [comment] 2019-04-01 01:57
maybe some times before Christmas :)

**Comment by thedrow** [comment] 2019-04-01 14:14
@auvipy Can you issue a blog post about 4.3?

**Comment by auvipy** [comment] 2019-04-01 14:44
yes of course, started kast ng=ight but got busy. will complete by today.
