### ISSUE TITLE
CELERY_ALWAYS_EAGER + apply_async() fails silently if the celery worker not started

### ISSUE THREAD

**Issue by edmorley** [celery/celery#2910] opened 2015-11-04 14:38 UTC
**STR:**
1) Use `CELERY_ALWAYS_EAGER = True` in a Django management command (used for development) that ends up making `apply_async()` calls.
2) Forget to start the celery worker (ie don't run `celery -A foo worker`)
3) Run `./manage.py my_custom_command`

**Expected:**
Any of...
1. An exception in the log that says that the eager task was unable to be run, since the worker wasn't running.
2. The task gets put in the rabbitmq queue as a fallback (ie: as though `CELERY_ALWAYS_EAGER` wasn't true), so at least people can start the worker after and run the tasks then.
3. The docs warn that tasks will be silently thrown away if using CELERY_ALWAYS_EAGER and the worker isn't running, here: http://celery.readthedocs.org/en/latest/configuration.html?#celery-always-eager.

**Actual:**
No errors in the Django logs or no jobs in the rabbitmq queues.
ie: the task for which `apply_async()` was run has been silently thrown away.

**Additional info:**
Python 2.7.10
celery 3.1.18
Django 1.8.5

The management command in question:
https://github.com/mozilla/treeherder/blob/9701ea433b4f4ca5901cf0716c2d33ac596dbe70/treeherder/etl/management/commands/ingest_push.py#L37

Which indirectly calls at least this `apply_async()` (and likely others too):
https://github.com/mozilla/treeherder/blob/9701ea433b4f4ca5901cf0716c2d33ac596dbe70/treeherder/model/derived/jobs.py#L1622

The django settings file:
https://github.com/mozilla/treeherder/blob/9701ea433b4f4ca5901cf0716c2d33ac596dbe70/treeherder/config/settings.py

Many thanks :-)

**Comment by ask** [comment] 2015-12-11 21:59
I'm not sure I get what the issue is here?  CELERY_ALWAYS_EAGER executes all tasks locally, so if you set it it doesn't matter if the worker is started or not?

Tasks will not be silently thrown away, they execute immediately in the current process instead of being sent as a task message to a worker.

**Comment by ask** [comment] 2015-12-11 22:02
'1. An exception in the log that says that the eager task was unable to be run, since the worker wasn't running.'

This seems to make the confusion clear: ALWAYS_EAGER is the same as 'pretend my function isn't using celery, and just call the function directly'.  It may be useful if you have a local development setup and you don't want to install a broker, start workers etc.

If you want the behavior you describe, then you shouldn't be using ALWAYS_EAGER

**Comment by ask** [comment] 2015-12-12 00:26
Closing this, please reopen if I'm misunderstanding the issue.

**Closed by ask** 2015-12-12 00:26 UTC
Labels: Status: Not a Bug

**Comment by edmorley** [comment] 2016-07-27 09:12
Ah I see what the real issue was here:

We were only setting `CELERY_ALWAYS_EAGER` in the one Django management command process and not globally, and the codepath in question made a request to the service's own API, which was being run in the gunicorn process which did not have `CELERY_ALWAYS_EAGER` set.

Convoluted codepaths ftl! (We've since refactored to remove this unnecessary HTTP request to the service's own API, so now when running this management command in the dev environment, everything is run in the same process.)
