### ISSUE TITLE
docs site is down: https://docs.celeryproject.org/

### ISSUE THREAD

**Issue by timotei-za** [celery/celery#7353] opened 2022-03-14 17:39 UTC
documentation website is down

**Comment by CodePint** [comment] 2022-03-14 17:43
duplicate of https://github.com/celery/celery/issues/7351

**Comment by miguelrochajr** [comment] 2022-03-15 21:21
If you need to take a look at the Docs now, you can find the 5.1.0 version here in the [Web Archive](https://web.archive.org/web/20210615213743/https://docs.celeryproject.org/en/stable/)

Hope it helps :)

**Comment by lowercase00** [comment] 2022-03-15 22:47
@miguelrochajr life saver, thanks a lot.

**Comment by caffeinatedMike** [comment] 2022-03-16 13:03
Glad it's not just me. I resorted to web archive as well.

**Comment by adhy57** [comment] 2022-03-16 13:31
Ping @auvipy

**Comment by binb4sh** [comment] 2022-03-18 07:32
the site seems under attacking by somebody? The site certificate name is 4rdcom.com, this domain registered by apinheiro78@hotmail.com

**Comment by auvipy** [comment] 2022-03-18 09:50
new domain https://docs.celeryq.dev/en/stable/

**Closed by auvipy** 2022-03-18 09:50 UTC
Labels: Issue Type: Bug Report, Category: Documentation
