### ISSUE TITLE
Distributed Celery Beat 

### ISSUE THREAD

**Issue by tiagoarasilva** [celery/celery#4808] opened 2018-06-11 16:39 UTC
## Checklist

- Not able to scale up Celery Beat using Docker containers running on multiple servers without replicating the tasks. E.g: If I have 2 containers running, it would run the same task twice.

## Expected behavior
- Being able to scale up Celery Beat

**Comment by spyoungtech** [comment] 2018-06-13 00:57
Can you provide any docker/docker-compose files and tell us more about your tasks? 

Depending on the details, this may be a completely expected behavior. The periodic tasks documentation states the following:

> tasks may overlap if the first task doesn’t complete before the next. If that’s a concern you should use a locking strategy to ensure only one instance can run at a time

Additionally, if you by chance are using the `-B` option for beat, the behavior would be expected as the documentation also states:

> ... enabling the workers -B option, this is convenient if you’ll never run more than one worker node, but it’s not commonly used and for that reason isn’t recommended for production use

**Comment by xirdneh** [comment] 2018-06-18 16:52
It's usually not recommended to run multiple beat processes.
When Celery beat starts it will load the tasks into a heap in memory.
As we can see there's no distributed storage here. So, if you run two containers with celery beat all your periodic tasks will get duplicated.
There are different things you can do to mitigate this.
1) You can re-write your periodic tasks in a way that they will only be "routing tasks".
Basically every periodic task will not actually run anything but only queue tasks for other workers to execute. This way you keep celery beat simple and you allow other plain worker processes to process tasks.
2) you can implement your own scheduler and save periodic tasks into a database or any other shared storage. You can base it off of [django-celery's scheduler](https://github.com/celery/django-celery/blob/master/djcelery/schedulers.py)
3) We're trying to come into an agreement about how to implement more backends into celery beat so this kind of issues go away. In the man time you can try out something like [RedBeat](https://github.com/sibson/redbeat).

Hope this helps

**Comment by johnarnold** [comment] 2018-06-25 16:39
redbeat project:
https://github.com/sibson/redbeat

beatx project:
https://github.com/mixkorshun/celery-beatx

**Comment by auvipy** [comment] 2018-07-05 11:40
I like the beatx

**Comment by auvipy** [comment] 2018-07-05 11:46
possibly related https://github.com/celery/celery/pull/2414

**Comment by tiagoarasilva** [comment] 2018-07-06 13:45
@xirdneh thank you for your reply and for late response, actually, internally we developed a temporary solution for the beat, which means, we control that with our own dictionary settings and database checking using a randon probability but is not a safe solution thats why having celery supporting this feture would be amazing as we tend to move more and more to a containerised base system and having this functionality working and operating would be a amazing plus

**Comment by xirdneh** [comment] 2018-07-11 17:17
@tiagoarasilva Just to be sure,
What we're talking about here is to support a way to have multiple beat workers running?

**Comment by tiagoarasilva** [comment] 2018-07-17 14:03
@xirdneh ish. So basically we should be able to have multiple containers on many different servers (scalability) but those tasks should not be replicated. E.g:

1. task - container 1 - run at 10
2. task - container 2 - Should not run at 10 as there is already one schedule at 10, so that means, it should not duplicate the task and run in parallel

**Comment by xirdneh** [comment] 2018-07-17 14:42
There are many improvements we have pending for Celery Beat, having the ability to distribute celery beat is one of the hardest one to implement.
The reason why you see that behavior is not because the tasks are getting duplicated, is because celery beat is build in a way such that it assumes it's the only process taking care of the scheduled tasks. When you run multiple beat processes every one of them is going to execute the same scheduled task at (more or less) the same time. This implementation detail is there for simplicity.

In order to fix this and allow for celery beat to be more distributed we need to figure out a way to synchronize a clock between processes and have a centralized storage for scheduled tasks or else the same behavior will occur.

We are working on this at the moment (you can see more on issue #4815) but these are some major changes on how Celery Beat is implemented and we don't know if we have enough resources to finish this 100%. Any help is welcome and feel free to bring some ideas to make this implementation easier. Just want to make it clear that we know this is a draw back of Celery Beat and we are trying to figure out how to fix it for future uses, there's just no due date on this.

In the mean time I think you can use celery beat only to route tasks to other workers and that way you don't use Celery Beat as the process who actually executes the task. This technique will leverage celery beat's scheduler and the usual worker's scalability.

**Comment by xirdneh** [comment] 2018-07-20 18:12
I'm closing this since the effort to eventually add something like this is being discussed in #4815

**Closed by xirdneh** 2018-07-20 18:12 UTC
Labels: Issue Type: Feature Request
