### ISSUE TITLE
OperationFailure: Authentication failed when backends/mongodb try write result

### ISSUE THREAD

**Issue by tonal** [celery/celery#5928] opened 2020-01-20 04:24 UTC
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first. https://groups.google.com/forum/#!topic/celery-users/TBCxDemhSdE
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- #5527, #4454

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.0 

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
$ celery -A celery_tacks report

software -> celery:4.4.0 (cliffs) kombu:4.6.7 py:3.8.1
            billiard:3.6.1.0 py-amqp:2.5.2
platform -> system:Linux arch:64bit, ELF
            kernel version:4.15.0-47-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:mongodb+srv://remains:**@mongo.example.com/database_name

broker_url: 'amqp://remains:********@rabbitmq.example.com:5672//'
result_backend: 'mongodb+srv://remains:********@mongo.example.com/database_name'
include: [
  'store_remains', 'providers', 'mongo_utils', 'afinalux', 'afinalux-diff',
  'christmass', 'danio', 'danio-diff', 'elgo-msk', 'evan-diff', 'globus',
  'lightstar', 'lussole', 'mw-light', 'prorab', 'quadro-stroy', 'sds-group',
  'sonex', 'stluce', 'stluce-diff', 'technolight', 'contactplus', 'lex-c', 'lex-c-diff',
 'greentrees', 'lifan-moto', 'triumph-nord-rus', 'crawl_site', 'mail2csv', 'mail2diff',
  'rotate_mb', 'store_out_of_stock'
]
accept_content: [
 'mongo_json', 'application/x-mongo-json', 'json', 'application/json'
]
task_serializer: 'mongo_json'
result_serializer: 'mongo_json'
task_default_queue: 'remains_tasks'
worker_prefetch_multiplier: 1
worker_max_tasks_per_child: 45
worker_hijack_root_logger: False
mongodb_backend_settings: {
 'compressors': 'snappy', 'database': '********'}
CELERY_MONGO_SCHEDULER_URI: 'mongodb+srv://remains:********@mongo.example.com/database_name?ssl=false'
CELERY_MONGO_SCHEDULER_DB: 'remains'
CELERY_MONGO_SCHEDULER_ENTRIES_COL: 'schedules_entries'
CELERY_MONGO_SCHEDULER_META_COL: 'schedules_meta'
beat_schedule: {
    'afinalux': {   'args': ['afinalux'],
                    'comment': '',
                    'is_enabled': True,
                    'schedule': <crontab: 7 0 * * * (m/h/d/dM/MY)>,
                    'task': 'celery_tacks.load_link',
                    'title': 'Афина Гарден'},
    'afinalux-diff': {   'args': ['afinalux-diff'],
                         'comment': 'рассылка с изменениями прайса Афина '
                                    'Гарден',
                         'is_enabled': True,
                         'schedule': <crontab: 7 0 * * * (m/h/d/dM/MY)>,
                         'task': 'celery_tacks.load_link',
                         'title': 'Афина Гарден'},
    'allpools': {   'args': ['allpools'],
                    'comment': '',
                    'is_enabled': True,
                    'schedule': <crontab: 19 1 * * * (m/h/d/dM/MY)>,
                    'task': 'celery_tacks.load_site',
                    'title': 'Олпулс'},
    'aquapolis': {   'args': ['aquapolis'],
                     'comment': '',
                     'is_enabled': True,
                     'schedule': <crontab: 31 0 * * * (m/h/d/dM/MY)>,
                     'task': 'celery_tacks.load_site',
                     'title': 'Акваполис'},
    'aquapolis_bestway': {   'args': ['aquapolis_bestway'],
                             'comment': '',
                             'is_enabled': True,
                             'schedule': <crontab: 31 0 * * * (m/h/d/dM/MY)>,
                             'task': 'celery_tacks.load_site',
                             'title': 'Акваполис_Bestway'},
    'audiomania': {   'args': ['audiomania'],
                      'comment': '',
                      'is_enabled': True,
                      'schedule': <crontab: 17 0 * * * (m/h/d/dM/MY)>,
                      'task': 'celery_tacks.load_site',
                      'title': 'Аудиомания'},
    'christmass': {   'args': ['christmass'],
                      'comment': '',
                      'is_enabled': True,
                      'schedule': <crontab: 13-59/30 * * * * (m/h/d/dM/MY)>,
                      'task': 'celery_tacks.load_link',
                      'title': 'Актив групп'},
    'contactplus': {   'args': ['contactplus'],
                       'comment': 'Остатки Контакт Плюс',
                       'is_enabled': True,
                       'schedule': <crontab: 17-59/30 * * * * (m/h/d/dM/MY)>,
                       'task': 'celery_tacks.load_link',
                       'title': 'Контакт Плюс'},
    'danio': {   'args': ['danio'],
                 'comment': '',
                 'is_enabled': True,
                 'schedule': <crontab: 13 2 * * * (m/h/d/dM/MY)>,
                 'task': 'celery_tacks.load_link',
                 'title': 'Данио'},
    'danio-diff': {   'args': ['danio-diff'],
                      'comment': 'Рассылка с изменениями прайса Данио',
                      'is_enabled': True,
                      'schedule': <crontab: 17 2 * * * (m/h/d/dM/MY)>,
                      'task': 'celery_tacks.load_link',
                      'title': 'Данио'},
    'decomo': {   'args': ['decomo'],
                  'comment': '',
                  'is_enabled': True,
                  'schedule': <crontab: 23 0 * * * (m/h/d/dM/MY)>,
                  'task': 'celery_tacks.load_site',
                  'title': 'Декомо'},
    'delta': {   'args': ['delta'],
                 'comment': '',
                 'is_enabled': True,
                 'schedule': <crontab: 19 0 * * * (m/h/d/dM/MY)>,
                 'task': 'celery_tacks.load_site',
                 'title': 'Дельта'},
    'elgo-msk': {   'args': ['elgo-msk'],
                    'comment': 'Отключено по просьбе заказчика',
                    'is_enabled': False,
                    'schedule': <crontab: 29-59/30 * * * * (m/h/d/dM/MY)>,
                    'task': 'celery_tacks.load_link',
                    'title': 'Эгло'},
    'evan-diff': {   'args': ['evan-diff'],
                     'comment': 'Рассылка с изменениями прайса Эван',
                     'is_enabled': True,
                     'schedule': <crontab: 17 3 0 * * (m/h/d/dM/MY)>,
                     'task': 'celery_tacks.load_link',
                     'title': 'Эван'},
    'floraimport': {   'args': ['floraimport'],
                       'comment': '',
                       'is_enabled': True,
                       'schedule': <crontab: 11 0 * * * (m/h/d/dM/MY)>,
                       'task': 'celery_tacks.load_site',
                       'title': 'Флора Импорт'},
    'globus': {   'args': ['globus'],
                  'comment': '',
                  'is_enabled': True,
                  'schedule': <crontab: 5-59/30 * * * * (m/h/d/dM/MY)>,
                  'task': 'celery_tacks.load_link',
                  'title': 'Глобус'},
    'greentrees': {   'args': ['greentrees'],
                      'comment': 'Остатки Green Trees',
                      'is_enabled': True,
                      'schedule': <crontab: 37 1 * * * (m/h/d/dM/MY)>,
                      'task': 'celery_tacks.load_link',
                      'title': 'Green Trees'},
    'housetech': {   'args': ['housetech'],
                     'comment': '',
                     'is_enabled': True,
                     'schedule': <crontab: 13 0 * * * (m/h/d/dM/MY)>,
                     'task': 'celery_tacks.load_site',
                     'title': 'Домотехника'},
    'housetech_nsk': {   'args': ['housetech_nsk'],
                         'comment': '',
                         'is_enabled': True,
                         'schedule': <crontab: 23 0 * * * (m/h/d/dM/MY)>,
                         'task': 'celery_tacks.load_site',
                         'title': 'Домотехника_НСК'},
    'housetech_spb': {   'args': ['housetech_spb'],
                         'comment': '',
                         'is_enabled': True,
                         'schedule': <crontab: 31 0 * * * (m/h/d/dM/MY)>,
                         'task': 'celery_tacks.load_site',
                         'title': 'Домотехника_СПБ'},
    'huter-gmbh': {   'args': ['huter-gmbh'],
                      'comment': '',
                      'is_enabled': True,
                      'schedule': <crontab: 43 0 0 * * (m/h/d/dM/MY)>,
                      'task': 'celery_tacks.load_site',
                      'title': 'Континент ГК'},
    'iatec': {   'args': ['iatec'],
                 'comment': '',
                 'is_enabled': True,
                 'schedule': <crontab: 41 0 * * * (m/h/d/dM/MY)>,
                 'task': 'celery_tacks.load_site',
                 'title': 'Три Пятых'},
    'interinstrument': {   'args': ['interinstrument'],
                           'comment': '',
                           'is_enabled': True,
                           'schedule': <crontab: 47 0 * * * (m/h/d/dM/MY)>,
                           'task': 'celery_tacks.load_site',
                           'title': 'ИнтерИнструмент'},
    'lex-c': {   'args': ['lex-c'],
                 'comment': 'Остатки Лекс-с',
                 'is_enabled': True,
                 'schedule': <crontab: 21 2 0 * * (m/h/d/dM/MY)>,
                 'task': 'celery_tacks.load_link',
                 'title': 'Лекс-С'},
    'lex-c-diff': {   'args': ['lex-c-diff'],
                      'comment': 'Рассылка с изменениями прайса Лекс-с',
                      'is_enabled': True,
                      'schedule': <crontab: 23 2 0 * * (m/h/d/dM/MY)>,
                      'task': 'celery_tacks.load_link',
                      'title': 'Лекс-С'},
    'lifan-moto': {   'args': ['lifan-moto'],
                      'comment': 'Остатки lifan-moto',
                      'is_enabled': True,
                      'schedule': <crontab: 37 1 0 * * (m/h/d/dM/MY)>,
                      'task': 'celery_tacks.load_link',
                      'title': 'Мото северо-запад'},
    'lightstar': {   'args': ['lightstar'],
                     'comment': 'Отключено по просьбе заказчика',
                     'is_enabled': False,
                     'schedule': <crontab: 17-59/30 * * * * (m/h/d/dM/MY)>,
                     'task': 'celery_tacks.load_link',
                     'title': 'Лайтстар'},
    'lussole': {   'args': ['lussole'],
                   'comment': 'Отключено по просьбе заказчика',
                   'is_enabled': False,
                   'schedule': <crontab: 29 */2 * * * (m/h/d/dM/MY)>,
                   'task': 'celery_tacks.load_link',
                   'title': 'Lussole'},
    'mail2csv': {   'is_enabled': True,
                    'is_system': True,
                    'schedule': <crontab: 3-59/30 * * * * (m/h/d/dM/MY)>,
                    'task': 'celery_tacks.load_mail2csv',
                    'title': 'Остатки из писем'},
    'mail2diff': {   'is_enabled': True,
                     'is_system': True,
                     'schedule': <crontab: 13 * * * * (m/h/d/dM/MY)>,
                     'task': 'celery_tacks.load_mail2diff',
                     'title': 'Diff прайса из писем'},
    'mon_site': {   'args': ['poolfactory'],
                    'is_enabled': False,
                    'is_system': False,
                    'schedule': <crontab: 23 3 * * * (m/h/d/dM/MY)>,
                    'task': 'celery_tacks.load_mon_site',
                    'title': 'Мониторинг продаж с poolfactory'},
    'mw-light': {   'args': ['mw-light'],
                    'comment': 'Отключено по просьбе заказчика',
                    'is_enabled': False,
                    'schedule': <crontab: 1-59/30 * * * * (m/h/d/dM/MY)>,
                    'task': 'celery_tacks.load_link',
                    'title': 'MW-Light'},
    'novum': {   'args': ['novum'],
                 'comment': '',
                 'is_enabled': True,
                 'schedule': <crontab: 7 0 * * * (m/h/d/dM/MY)>,
                 'task': 'celery_tacks.load_site',
                 'title': 'Novum'},
    'pompina': {   'args': ['pompina'],
                   'comment': '',
                   'is_enabled': True,
                   'schedule': <crontab: 13 0 0 * * (m/h/d/dM/MY)>,
                   'task': 'celery_tacks.load_site',
                   'title': 'Саблайн сервис'},
    'price.allpools.ru': {   'args': ['allpools.ru'],
                             'comment': '',
                             'is_enabled': True,
                             'schedule': <crontab: 31 3 0 * * (m/h/d/dM/MY)>,
                             'task': 'celery_tacks.load_price_site',
                             'title': 'Цены с сайта allpools.ru'},
    'price.aquapolis.ru': {   'args': ['aquapolis.ru'],
                              'comment': '',
                              'is_enabled': True,
                              'schedule': <crontab: 29 3 0 * * (m/h/d/dM/MY)>,
                              'task': 'celery_tacks.load_price_site',
                              'title': 'Цены с сайта aquapolis.ru'},
    'price.decomo': {   'args': ['decomo'],
                        'comment': '',
                        'is_enabled': True,
                        'schedule': <crontab: 13 1 * 1 * (m/h/d/dM/MY)>,
                        'task': 'celery_tacks.load_price_site',
                        'title': 'Цены с сайта decomo'},
    'price.decomo_rrc': {   'args': ['decomo_rrc'],
                            'comment': '',
                            'is_enabled': True,
                            'schedule': <crontab: 13 1 * * * (m/h/d/dM/MY)>,
                            'task': 'celery_tacks.load_price_site',
                            'title': 'Цены с сайта decomo_rrc'},
    'price.ekopromgroup.ru': {   'args': ['ekopromgroup.ru'],
                                 'comment': 'Цены ЭкоПром',
                                 'is_enabled': True,
                                 'schedule': <crontab: 41 3 0 * * (m/h/d/dM/MY)>,
                                 'task': 'celery_tacks.load_price_site',
                                 'title': 'Цены с сайта ekopromgroup.ru'},
    'price.floraimport': {   'args': ['floraimport'],
                             'comment': '',
                             'is_enabled': True,
                             'schedule': <crontab: 11 0 0 1-7,15-21,29-31 * (m/h/d/dM/MY)>,
                             'task': 'celery_tacks.load_price_site',
                             'title': 'Цены с сайта floraimport'},
    'price.kamnirus': {   'args': ['kamnirus'],
                          'comment': 'Отключено по просьбе заказчика',
                          'is_enabled': False,
                          'schedule': <crontab: 19 3 0 * * (m/h/d/dM/MY)>,
                          'task': 'celery_tacks.load_price_site',
                          'title': 'Цены с сайта kamnirus'},
    'price.novum': {   'args': ['novum'],
                       'comment': 'Цены Novum',
                       'is_enabled': False,
                       'schedule': <crontab: 17 2 0 * * (m/h/d/dM/MY)>,
                       'task': 'celery_tacks.load_price_site',
                       'title': 'Цены с сайта novum'},
    'price.polimer-group.com': {   'args': ['polimer-group.com'],
                                   'comment': 'Цены Polimer Group',
                                   'is_enabled': True,
                                   'schedule': <crontab: 37 3 0 * * (m/h/d/dM/MY)>,
                                   'task': 'celery_tacks.load_price_site',
                                   'title': 'Цены с сайта polimer-group.com'},
    'price.prorab': {   'args': ['prorab'],
                        'comment': '',
                        'is_enabled': False,
                        'schedule': <crontab: 37 3 0 * * (m/h/d/dM/MY)>,
                        'task': 'celery_tacks.load_price_site',
                        'title': 'Цены с сайта prorab'},
    'price.unisaw': {   'args': ['unisaw'],
                        'comment': '',
                        'is_enabled': True,
                        'schedule': <crontab: 23 3 0 * * (m/h/d/dM/MY)>,
                        'task': 'celery_tacks.load_price_site',
                        'title': 'Цены с сайта unisaw'},
    'price.Домотехника': {   'args': ['Домотехника'],
                             'comment': 'Изменения в составе прайсов',
                             'is_enabled': True,
                             'schedule': <crontab: 41 3 0 * * (m/h/d/dM/MY)>,
                             'task': 'celery_tacks.load_price_site',
                             'title': 'Цены с сайта Домотехника'},
    'prorab': {   'args': ['prorab'],
                  'comment': '',
                  'is_enabled': False,
                  'schedule': <crontab: 7-59/30 * * * * (m/h/d/dM/MY)>,
                  'task': 'celery_tacks.load_link',
                  'title': 'Prorab'},
    'quadro-stroy': {   'args': ['quadro-stroy'],
                        'comment': '',
                        'is_enabled': True,
                        'schedule': <crontab: 17 1 * * * (m/h/d/dM/MY)>,
                        'task': 'celery_tacks.load_link',
                        'title': 'Квадро-Строй'},
    'rotate_mb': {   'is_enabled': True,
                     'is_system': True,
                     'schedule': <crontab: 23 0 0 * * (m/h/d/dM/MY)>,
                     'task': 'celery_tacks.rotate_mb',
                     'title': 'Очистка устаревших файлов'},
    'sds-group': {   'args': ['sds-group'],
                     'comment': '',
                     'is_enabled': True,
                     'schedule': <crontab: 29 0 * * * (m/h/d/dM/MY)>,
                     'task': 'celery_tacks.load_link',
                     'title': 'СДС-Группа'},
    'sima-land': {   'args': ['sima-land'],
                     'comment': '',
                     'is_enabled': True,
                     'schedule': <crontab: 53 0 * * * (m/h/d/dM/MY)>,
                     'task': 'celery_tacks.load_site',
                     'title': 'Сима-ленд'},
    'sonex': {   'args': ['sonex'],
                 'comment': '',
                 'is_enabled': True,
                 'schedule': <crontab: 11-59/30 * * * * (m/h/d/dM/MY)>,
                 'task': 'celery_tacks.load_link',
                 'title': 'Сонекс'},
    'stluce': {   'args': ['stluce'],
                  'comment': 'Остатки ST Luce Velante',
                  'is_enabled': True,
                  'schedule': <crontab: 19 1 * * * (m/h/d/dM/MY)>,
                  'task': 'celery_tacks.load_link',
                  'title': 'ST Luce'},
    'stluce-diff': {   'args': ['stluce-diff'],
                       'comment': 'рассылка с изменениями прайса ST Luce '
                                  'Velante',
                       'is_enabled': True,
                       'schedule': <crontab: 23 1 * * * (m/h/d/dM/MY)>,
                       'task': 'celery_tacks.load_link',
                       'title': 'ST Luce'},
    'store_outofstock': {   'is_enabled': True,
                            'is_system': True,
                            'schedule': <crontab: 49 0-20,23 * * * (m/h/d/dM/MY)>,
                            'task': 'celery_tacks.store_outofstock',
                            'title': 'Автозаливка "нет в наличии"'},
    'technolight': {   'args': ['technolight'],
                       'comment': 'Отключено по просьбе заказчика',
                       'is_enabled': False,
                       'schedule': <crontab: 19-59/30 * * * * (m/h/d/dM/MY)>,
                       'task': 'celery_tacks.load_link',
                       'title': 'Тренд Света'},
    'triumph-nord-rus': {   'args': ['triumph-nord-rus'],
                            'comment': '',
                            'is_enabled': True,
                            'schedule': <crontab: 11 1 * * * (m/h/d/dM/MY)>,
                            'task': 'celery_tacks.load_link',
                            'title': 'Триумф Норд Рус'},
    'unisaw': {   'args': ['unisaw'],
                  'comment': '',
                  'is_enabled': True,
                  'schedule': <crontab: 3 0 * * * (m/h/d/dM/MY)>,
                  'task': 'celery_tacks.load_site',
                  'title': 'Unisaw'},
    'vodalux-fontan': {   'args': ['vodalux-fontan'],
                          'comment': '',
                          'is_enabled': True,
                          'schedule': <crontab: 37 0 * * * (m/h/d/dM/MY)>,
                          'task': 'celery_tacks.load_site',
                          'title': 'Водалюкс'},
    'vodalux-prud': {   'args': ['vodalux-prud'],
                        'comment': '',
                        'is_enabled': True,
                        'schedule': <crontab: 13 0 * * * (m/h/d/dM/MY)>,
                        'task': 'celery_tacks.load_site',
                        'title': 'Водалюкс'},
    'y-skazki': {   'args': ['y-skazki'],
                    'comment': 'Отключено по просьбе заказчика',
                    'is_enabled': False,
                    'schedule': <crontab: 17 1 * * * (m/h/d/dM/MY)>,
                    'task': 'celery_tacks.load_site',
                    'title': 'Bestway Юг'}}
```
</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7.4
* **Minimal Celery Version**: 4.4.0
* **Minimal Kombu Version**: 4.6.7
* **Minimal Broker Version**: rabbitmq-server 3.6.15-1
* **Minimal Result Backend Version**: mongodb 4.2.0
* **Minimal OS and/or Kernel Version**: ubuntu 18.04
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.5.2
attrs==19.3.0
Automat==0.8.0
billiard==3.6.1.0
Brotli==1.0.7
cchardet==2.1.5
celery==4.4.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
clickhouse-cityhash==1.0.2.3
clickhouse-driver==0.1.2
constantly==15.1.0
cryptography==2.8
cssselect==1.1.0
dnspython==1.16.0
et-xmlfile==1.0.1
fake-useragent==0.1.11
fastnumbers==3.0.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.3.0
incremental==17.5.0
jdcal==1.4.1
jmespath==0.9.4
jsonlines==1.2.0
kombu==4.6.7
lxml==4.4.2
lz4==3.0.2
marshmallow==2.20.5
more-itertools==8.0.2
mysqlclient==1.4.6
natsort==7.0.0
openpyxl==3.0.3
parsel==1.5.2
pip-tools==4.3.0
Protego==0.1.16
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.19
PyDispatcher==2.0.5
PyHamcrest==1.10.1
PyICU==2.4.2
pymongo==3.10.1
pyOpenSSL==19.1.0
python-dateutil==2.8.1
python-snappy==0.5.4
pytz==2019.3
pyxlsb==1.0.6
PyYAML==5.3
queuelib==1.5.0
requests==2.22.0
Scrapy==1.8.0
sentry-sdk==0.14.0
service-identity==18.1.0
six==1.14.0
Twisted==19.10.0
txmongo==19.2.0
tzlocal==2.0.0
urllib3==1.25.7
vine==1.3.0
w3lib==1.21.0
xlrd==1.2.0
XlsxWriter==1.2.7
zipp==0.6.0
zope.interface==4.7.1
zstandard==0.13.0
zstd==1.4.4.0
```
</p>
</details>

### Other Dependencies

<details>
<p>
```
```
</p>
</details>

## Minimally Reproducible Test Case

Code for initialization celery app:
<details>
<p>

```python
from functools import partial
from bson import json_util

json_options=json_util.JSONOptions(
  json_mode=json_util.JSONMode.RELAXED, tz_aware=True, tzinfo=utc)
json_dump = partial(
  json_util.dumps, ensure_ascii=False, json_options=json_options)
json_load = partial(json_util.loads, json_options=json_options)

register(
  'mongo_json',
  encoder=(lambda obj: json_dump(obj).encode('utf-8')),
  decoder=json_load,
  content_type='application/x-mongo-json')

app = Celery(
  'remains_tasks',
  broker='pyamqp://...',
  backend = 'mongodb://...',
  include=[
    # many modules
  ]
)
app.conf.update(
  accept_content=[
    'mongo_json', 'application/x-mongo-json', 'json', 'application/json'],
  task_serializer='mongo_json',
  result_serializer='mongo_json',
  task_default_queue='remains_tasks',
  worker_prefetch_multiplier=1,
  worker_max_tasks_per_child=45,
  worker_hijack_root_logger=False,

  mongodb_backend_settings=dict(database='remains', compressors='snappy'),
)
```
Connection string look:
```
mongodb+srv://username:password@mongo.example.com/database?ssl=false
```
</p>
</details>

# Expected Behavior

No exception
# Actual Behavior

Exception after exit tack
```
KeyError: 'collection'
  File "kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'database'
  File "kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
OperationFailure: Authentication failed.
  File "billiard/pool.py", line 1791, in safe_apply_callback
    fun(*args, **kwargs)
  File "celery/worker/request.py", line 526, in on_failure
    self.task.backend.mark_as_failure(
  File "celery/backends/base.py", line 159, in mark_as_failure
    self.store_result(task_id, exc, state,
  File "celery/backends/base.py", line 406, in store_result
    self._store_result(task_id, result, state, traceback,
  File "celery/backends/mongodb.py", line 194, in _store_result
    self.collection.replace_one({'_id': task_id}, meta, upsert=True)
  File "kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "celery/backends/mongodb.py", line 291, in collection
    collection = self.database[self.taskmeta_collection]
  File "kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "celery/backends/mongodb.py", line 286, in database
    return self._get_database()
  File "celery/backends/mongodb.py", line 275, in _get_database
    if not db.authenticate(self.user, self.password, source=source):
  File "pymongo/database.py", line 1468, in authenticate
    self.client._cache_credentials(
  File "pymongo/mongo_client.py", line 754, in _cache_credentials
    with server.get_socket(all_credentials) as sock_info:
  File "contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "pymongo/pool.py", line 1138, in get_socket
    sock_info.check_auth(all_credentials)
  File "pymongo/pool.py", line 712, in check_auth
    auth.authenticate(credentials, self)
  File "pymongo/auth.py", line 564, in authenticate
    auth_func(credentials, sock_info)
  File "pymongo/auth.py", line 539, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "pymongo/auth.py", line 263, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "pymongo/pool.py", line 603, in command
    return command(self.sock, dbname, spec, slave_ok,
  File "pymongo/network.py", line 165, in command
    helpers._check_command_response(
  File "pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
```

**Comment by tonal** [comment] 2020-03-19 07:21
Also for celery 4.4.2, kombu 4.6.8

**Comment by tonal** [comment] 2020-06-06 06:44
Also for celery 4.4.4, kombu 4.6.10, pymongo 3.10.1

**Comment by auvipy** [comment] 2020-06-06 08:20
its a regression in kombu 4.6.10

**Comment by Mr-Dai** [comment] 2020-11-30 04:17
Try add the following celery app conf:

```
mongodb_backend_settings = {
    "options": {
        "authSource": "database_name",
    },
}
```

**Comment by tonal** [comment] 2020-11-30 09:26
Yes! Worked!

**Comment by thedrow** [comment] 2020-11-30 15:47
@celery/core-developers Do you guys think we should catch this exception somehow and log it instead of crashing?

**Comment by Mr-Dai** [comment] 2020-12-01 03:26
This is where the exception is raised, at line 274:

https://github.com/celery/celery/blob/ee13eae8e20896beadd89dec8f521bd781522416/celery/backends/mongodb.py#L266-L277

At line 267, `self._get_connection` is used to get a `MongoClient` instance:

https://github.com/celery/celery/blob/ee13eae8e20896beadd89dec8f521bd781522416/celery/backends/mongodb.py#L136-L163

Here at line 161, `authSource` would not be in the `conf` unless it was explicitly set in `celery_app.conf. mongodb_backend_settings.options`, corresponding to the `self.options` at line 154.

One can easily write the following code to examine `pymongo`'s behavior in such situation:

```python
from pymongo import MongoClient

conf = {'host': 'mongo.example.com:27017', 'username': 'remains', 'password': '*******'}
conn = MongoClient(**conf)
db = conn['database_name']
db.authenticate('remains', '*******', source='database_name')
```

For some reason, `pymongo` will raise the same exception when `db.authenticate` is invoked, unless `'authSource': 'database_name'` was given in the `conf` used to create `MongoClient` instance.

Hope this may help.

**Comment by thedrow** [comment] 2020-12-08 10:27
So first of all: `db.authenticate()` is deprecated starting from [pymongo 3.5](https://pymongo.readthedocs.io/en/stable/changelog.html#changes-in-version-3-5). You are using `pymongo==3.10.1` so that's the case for you as well.
However we currently support `pymongo>=3.3`.

I think that's why the current code is the way it is.

How do you suggest we change it for now?
Should we pass `authSource` to both the constructor and the authenticate method?

A full fix is proposed in #6529.

**Comment by maybe-sybr** [comment] 2021-05-09 23:35
Following up from my comment on #6662 [0], I think we should aim to get a fix which sets `self.options['authsource']` at some early stage (e.g. instance init?) so that it will be available for use in both `_get_connection()` as well as `_get_database()`. That would effectively result in us passing `authsource` to both the `MongoClient` constructor as well as the specific `Database`s `authenticate()` method.

I think we should aim to land such a change in 5.2 since the 5.1 RCs are too close, and then aim to do something more substantive for #6529 in 5.3+/Future.

* [0] https://github.com/celery/celery/pull/6662#issuecomment-835936882

**Comment by auvipy** [comment] 2021-11-04 16:26
@naomielst this is related, you can have a look as well to get some idea

**Comment by auvipy** [comment] 2021-11-04 16:27
we can ofcourse defer to 5.3 but if we can make it to 5.2 that would be great

**Comment by idanmantin** [comment] 2021-12-02 12:23
This issue was fixed by @naomielst, [Upgrade required pymongo version to 3.11.1 #7130
](https://github.com/celery/celery/pull/7130/files)

When will version **5.2.x** be released?

**Comment by thedrow** [comment] 2021-12-09 15:32
We'll try to do that soon.

**Closed by thedrow** 2021-12-09 15:32 UTC
Labels: Issue Type: Bug Report, Component: MongoDB Results Backend
