### ISSUE TITLE
CELERY_TIMEZONE and CELERY_ENABLE_UTC have no effect

### ISSUE THREAD

**Issue by lonemc** [celery/celery#2649] opened 2015-06-10 02:15 UTC
I am trying to run a  celery worker from console with a timezone different than the local timezone with no luck. No matter what I do, the logs of the worker are always shown with the local timezone (which is not UTC). Shouldn't the worker start by default in the UTC timezone? (assuming the CELERY_ENABLE_UTC is enabled by default).

Here's one possible cause: I vaguely remember this was working a few months ago, so might it be because now the Daylight Saving Time is active?

My real problem is that I have a Django app using the local timezone (which is not UTC), and a few celery tasks inside the Django app. I need those tasks to be run as celery workers that are using the  UTC timezone.

**Comment by jackyfkc** [comment] 2015-06-11 06:19
The directives CELERY_TIMEZONE and CELERY_ENABLE_UTC are worked for celery beat, not worker.

The logging in celery does not take into account CELERY_ENABLE_UTC, it just a simple wrapper to python logging module.

**Comment by thedrow** [comment] 2015-06-19 08:03
CELERY_ENABLE_UTC is not enabled by default because people might use very old Django versions (below 1.4).
Can you please provide an example?

**Comment by malinoff** [comment] 2015-06-19 08:11
@thedrow just to note, we should enable UTC by default in October, when Django 1.4 LTS support will be ended (https://www.djangoproject.com/download/)

**Comment by thedrow** [comment] 2015-06-19 08:44
Yes we probably should do it for 3.2.0.

**Comment by thedrow** [comment] 2015-07-11 08:55
Now that I checked the documentation I saw that CELERY_ENABLE_UTC is enabled by default so I think this bug is only related to logging.

**Comment by ask** [comment] 2016-06-24 00:11
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by mihai-carneylabs** [comment] 2016-07-15 18:00
As a helpful note for anyone who may stumble on this discussion, I was able to run my celery workers on a different timezone (UTC) than the Django project (EST). I gave celery a different Django settings file (i.e. celery_settings), in which I just import the original settings (`from settings import *`) and then overwrite the TIME_ZONE parameter.

**Comment by mihai-carneylabs** [comment] 2016-07-15 18:02
As a helpful note for anyone who may stumble on this discussion, I was able to run my celery workers on a different timezone (UTC) than the Django project (EST). I gave celery a different Django settings file (i.e. celery_settings), in which I just import the original settings (from settings import *) and then overwrite the TIME_ZONE parameter.

**Comment by marvelph** [comment] 2017-07-16 03:52
It seems that this problem still remains in Celery 4.0.2.
The time stamp of the standard output log is affected by Django's TIME_ZONE parameter.

**Comment by georgepsarakis** [comment] 2017-07-16 07:19
Issue #4006 suggests the opposite. @marvelph this may be fixed in current master.

**Comment by marco-silva0000** [comment] 2017-07-28 21:02
I had problems with CELERY_TIMEZONE = 'Europe/Lisbon' and django TIMEZONE = 'Europe/Lisbon' using the beat scheduler. it would wrongly calculate the dates date of the next is_due.
On the pip version I had the calculation be negative and that would lunch tasks imediatly for ever, on the current master i had it calculate to 1h+repeat time. 
setting both settings to 'UTC' fixes the problem.

**Comment by georgepsarakis** [comment] 2017-07-29 03:50
We merged #4173 to `master`. If you can use the `master` branch and check if the issue remains, it would be great, thanks.

**Comment by marco-silva0000** [comment] 2017-07-29 08:37
I tested with master, please see the latest comment here https://github.com/celery/celery/issues/4041
There is still a problem with celery timezone on the latest master, if I have both CELERY_TIMEZONE and TIMEZONE to 'Europe/Lisbon' the django celery beat schedules the next task to 1h more than the correct time

**Comment by Ken4scholars** [comment] 2017-09-29 08:22
I have both TIME_ZONE and CELERY_TIMEZONE set to Europe/Moscow in my project but Celery beat still uses UTC. I've also tried switching the CELERY_ENABLE_UTC setting but nothing changed. My system time is Europe/Moscow and this is really frustrating

**Comment by madEng84** [comment] 2017-11-22 18:38
Same problem here (CELERY_TIMEZONE = TIME_ZONE = Europe/Rome) with celery 4.1 and django 1.11.x


- My periodic_tasks are not working at expected time. (I haven't fixed it :/)
- When i retry a celery task, the calculated ETA is wrong (lesser than now) so the retry is instantaneous. For this problem I have calculated the eta passing it to my retried task, as you can seee here (https://github.com/celery/celery/issues/4221#issuecomment-324204504)

I'm in Work in Progress, if i find a better solution, i will write here

**Comment by MounirMesselmeni** [comment] 2017-12-01 14:29
I have the same issue as @madEng84 Django 1.11 and Celery 4.1, tasks retry does not work with countdown, only with eta.

**Comment by expresspotato** [comment] 2017-12-06 04:33
This is an absolute f*** ing joke. All celery is supposed to do is task -> run it on time. Why the hell do these developers waste all their time adding exotic feature xyz that no one gives a sh*t about when it can't even do what's its designed to! Holy crap!

CELERY_TIMEZONE = 'US/Eastern'

Tasks run at completely the wrong time on 4.1, was okay back on 3. whatever

**Comment by thedrow** [comment] 2017-12-06 08:12
@expresspotato If you are not happy about the work we do FOR FREE go fork celery. 
You can also pay us to fix your problems.
Otherwise self-entitlement is not welcome. Consider this your last warning before I ban you.

**Comment by Jamim** [comment] 2017-12-06 10:58
As far as I know this issue was fixed in [master](https://github.com/celery/celery/tree/master) few months ago. I used master branch pinned to be55de622381816d087993f1c7f9afcf7f44ab33 instead of release to avoid this and it worked as expected.
So, it's a great question why is it still not released? It's incomprehensible.

**Comment by thedrow** [comment] 2017-12-06 17:16
@Jamim We have a few more pull requests to merge before releasing. See the milestone.

**Comment by auvipy** [comment] 2018-01-13 12:26
https://github.com/celery/celery/commit/be55de622381816d087993f1c7f9afcf7f44ab33

**Closed by auvipy** 2018-01-13 12:26 UTC
Labels: Issue Type: Bug, Priority: Major, Severity: Trivial, Status: Feedback Needed ✘

**Comment by zhangchmeng** [comment] 2018-04-19 11:58
set timezone 'Asia/Shanghai'.The runtime calculates the correct time,but When retry is enabled  eta don't calculate '+'  behind time. like this '''ETA:[2018-04-19 11:14:53.216361+08:06] ''''.Only the calculation sheet is not used.I'm going to add the number of seconds to the given time. He works,But what's not perfect?I hope my statement is useful.

**Comment by kylebebak** [comment] 2018-05-01 00:56
@auvipy 
It's obvious this should not have been closed.

I'm running `celery==4.1.0` and `Django==1.11.6`.

Regardless of what I set for `CELERY_TIMEZONE` and `TIMEZONE`, Celery beat uses UTC. No combination of `True` and `False` for `CELERY_ENABLE_UTC` and `USE_TZ` makes a difference.

It would be better to acknowledge this a bug than make users think it works.

**Comment by auvipy** [comment] 2018-05-16 08:06
try 4.2rc2 and report please

**Comment by trianglesis** [comment] 2018-06-21 18:20
celery (4.2.0)
```
 app.conf.update(
        enable_utc = True,
        timezone = 'Europe/London',
etc...
```
Server time Thursday 21st June 2018 19:18
Task recieved: 2018-06-21 18:19:10.474

**Comment by trianglesis** [comment] 2018-06-21 20:17
Next:

[2018-06-21 21:16:40,994: ERROR/MainProcess] Celery timezone.utc UTC
[2018-06-21 21:16:40,996: ERROR/MainProcess] Celery timezone.local <LocalTimezone: UTC+01>
[2018-06-21 21:16:40,997: ERROR/MainProcess] Celery timezone.get_timezone(conf.timezone) Europe/London
[2018-06-21 21:16:41,034: ERROR/MainProcess] beat.py default_now - > self.schedule.now() 2018-06-21 20:16:41.034214+00:00
[2018-06-21 21:16:41,035: ERROR/MainProcess] beat.py default_now - > self.schedule <crontab: 0 4
         * *
          * (m/h/d/dM/MY), UTC>

[2018-06-21 21:16:41,035: ERROR/MainProcess] beat.py default_now - > self.app.now() 2018-06-21 20:16:41.035642+00:00

**Comment by trianglesis** [comment] 2018-06-21 21:10
If anyone have an idea why datetime.utcnow() in ../celery/utils/time.py get this time - please update

**Comment by trianglesis** [comment] 2018-06-22 12:39
I can't understand what is going on with time settings in Celery, but I fixed
base.py -> now
And now it report actual time for selected timezone 'Europe/London', see log:

```
[2018-06-22 13:24:37,338: ERROR/MainProcess] <=Celery App Base=> now -> now_in_utc                      2018-06-22 12:24:37.336361+00:00
[2018-06-22 13:24:37,338: INFO/MainProcess] <=Celery App Base=> now -> self.timezone                    Europe/London
[2018-06-22 13:24:37,338: ERROR/MainProcess] <=Celery App Base=> now -> now_in_utc.astimezone(self.timezone)                            2018-06-22 13:24:37.336361+01:00
[2018-06-22 13:24:37,338: ERROR/MainProcess] <=Celery Schedules=> now -> self.app.now() 2018-06-22 13:24:37.336361+01:00
[2018-06-22 13:24:37,338: ERROR/MainProcess] <=Utils Time=> remaining -> now 2018-06-22 13:24:37.338674+01:00
[2018-06-22 13:24:42,349: ERROR/MainProcess] <=Celery Schedules=> now -> self.nowfun() 2018-06-22 13:24:42.349524+01:00
```

But task is still show time as raw UTC - 2018-06-22 12:24:42.350384

**Comment by trianglesis** [comment] 2018-06-22 13:13
Firstly, this probably should be the datetime.now instance, not datetime.utcnow(), because why would we decide to UTC already an UTC?

```
def to_utc(dt):
    """Convert naive :class:`~datetime.datetime` to UTC."""
    return make_aware(dt, timezone.utc)
```

It now allows me to set London time everywhere:
```
<=Celery App Base=> timezone_func conf.timezone: Europe/London
<=Celery App Base=> timezone_func timezone.get_timezone(conf.timezone): Europe/London
<=Celery Schedules=> now -> self.nowfun() 2018-06-22 14:11:03.625825+01:00
<=Utils Time=> to_utc -> What is dt_utc: 2018-06-22 14:11:03.626616
<=Utils Time=> remaining -> now 2018-06-22 14:11:03.629900+01:00
<=Celery Schedules=> now -> self.nowfun() 2018-06-22 14:11:03.630299+01:00

<=Utils Time=> make_aware -> _localize(dt, is_dst=None) 2018-06-22 14:11:03.630514+00:00
<=Utils Time=> to_utc -> make_aware(dt_utc, timezone.utc): 2018-06-22 14:11:03.630514+00:00
<=Utils Time=> make_aware -> What is dt: 2018-06-22 14:11:03.630514
```

But still task recieved in older time:

```
Received | 2018-06-22 13:05:02.712443 UTC
-- | --
Sent | 2018-06-22 13:05:02.707066 UTC
Started | 2018-06-22 13:05:02.716835 UTC
Succeeded | 2018-06-22 13:05:03.029372 UTC
Retries | 0
Timestamp | 2018-06-22 13:05:03.029372 UTC
```

**Comment by georgepsarakis** [comment] 2018-06-22 18:28
@trianglesis if possible, please open a PR with your changes and we can discuss it there.

**Comment by qburst-starsona** [comment] 2018-08-30 14:36
Youy can try the `nowfun` argument in `crontab` for setting different timezone

https://stackoverflow.com/questions/21827290/celery-beat-different-time-zone-per-task

**Comment by liziwl** [comment] 2019-10-19 08:17
I have the same problem that `done_date` always using UTC when I have set  
```py
cel_app.conf.timezone = 'Asia/Shanghai'
cel_app.conf.enable_utc = True
```
on v4.3.0 installed by pip, so the problem is fixed or not?

**Comment by w4230213** [comment] 2023-02-09 10:33
I got the similar problem on v5.2.3, the "date_done" record in result end was always UTC time, no matter what setting in celeryconfig.py, after some digging, here's the reason and the work round:

- REASON: I'm using Mongo as my backend, the "date_done" is generate in a method: _get_result_meta(),  provided by the  default MongoBackend, well, acutally, it's in the super class of MongoBackend: celery.backend.base: Backend. So look into the code, you'll find this line: 
                 _date_done = datetime.utcnow()_
That's the reason. 

-SOLUTION:  I just create a new subclass of the default MongoBackend, and override the method: _get_result_meta(), add some real timezone convertion logic at the last.

**Comment by Cherrymelon** [comment] 2024-11-19 03:57
@w4230213 thank for your patch code, I adjusted it and work well for my mysql db.

```
app = Celery(
    "tasks",
    broker=env.REDIS_URL+'/'+str(env.SERVER_REDIS_DB),
    backend=env.Celery_db_backend,
    broker_connection_retry_on_startup=True,

)
app.loader.override_backends['db'] = 'celery_task.patch_timezone.MyBackend'
```
 and this is my mysql class code:
```
import datetime
from typing import override
import pytz
from celery.backends.database import DatabaseBackend


def convert_timezone(origin_dt, tz='Asia/Shanghai', fmt="%Y-%m-%dT%H:%M:%S.%f"):
    as_string = False
    if isinstance(origin_dt, str):
        as_string = True
        origin_dt = datetime.datetime.strptime(origin_dt, fmt)
    origin_dt = origin_dt.replace(tzinfo=datetime.timezone.utc)
    target_tz = pytz.timezone(tz)
    converted_dt = origin_dt.astimezone(target_tz)
    if as_string:
        return converted_dt.strftime(fmt)
    else:
        return converted_dt


class MyBackend(DatabaseBackend):

    @override
    def _get_result_meta(self, result,
                         state, traceback, request, format_date=True,
                         encode=False):
        origin_meta=super()._get_result_meta(result,
                         state, traceback, request, format_date, encode)
        # tz convert
        if self.app.conf.timezone is not None:
            local_dt = convert_timezone(origin_meta['date_done'], tz=self.app.conf.timezone)
            origin_meta['date_done'] = local_dt
        return origin_meta
```
