### ISSUE TITLE
autoscaler: Scaling down -N processes

### ISSUE THREAD

**Issue by tschottdorf** [celery/celery#1967] opened 2014-04-09 05:42 UTC
I've been using the autoscaler both on two gevent workers and, as of recently, on another worker using prefork. In the logs, I see a lot of "negative scale-downs", such as:
```
 Apr 01 19:40:45 app/worker.1: [2014-04-02 02:40:45,280: INFO/MainProcess] Scaling down -9 processes.
Apr 01 21:04:38 api app/worker.1: [2014-04-02 04:04:38,253: INFO/MainProcess] Scaling up 12 processes.
```
(There are also "expected" scale-downs with the other sign)

This appears to begin with the following pattern:
The worker scales up a bunch of times as a wad of tasks comes in. After the tasks are done, it scales down but it looks like it's scaling down too much. Here's an example of the pattern:
```

Apr 08 11:11:08 api app/cpuworker.1: [2014-04-08 18:11:07,973: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:11:32 api app/cpuworker.1: [2014-04-08 18:11:32,290: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:12:28 api app/cpuworker.1: [2014-04-08 18:12:27,979: INFO/MainProcess] Scaling down -3 processes.
Apr 08 11:12:58 api app/cpuworker.1: [2014-04-08 18:12:58,199: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:13:55 api app/cpuworker.1: [2014-04-08 18:13:55,506: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:14:28 api app/cpuworker.1: [2014-04-08 18:14:28,531: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:14:46 api app/cpuworker.1: [2014-04-08 18:14:46,059: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:15:28 api app/cpuworker.1: [2014-04-08 18:15:28,779: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:15:46 api app/cpuworker.1: [2014-04-08 18:15:46,864: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:16:29 api app/cpuworker.1: [2014-04-08 18:16:28,955: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:16:37 api app/cpuworker.1: [2014-04-08 18:16:37,134: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:17:59 api app/cpuworker.1: [2014-04-08 18:17:59,078: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:18:39 api app/cpuworker.1: [2014-04-08 18:18:38,983: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:19:29 api app/cpuworker.1: [2014-04-08 18:19:29,381: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:19:34 api app/cpuworker.1: [2014-04-08 18:19:34,503: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:20:59 api app/cpuworker.1: [2014-04-08 18:20:59,888: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:21:02 api app/cpuworker.1: [2014-04-08 18:21:02,173: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:22:00 api app/cpuworker.1: [2014-04-08 18:21:59,970: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:23:28 api app/cpuworker.1: [2014-04-08 18:23:28,407: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:24:00 api app/cpuworker.1: [2014-04-08 18:24:00,201: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:25:36 api app/cpuworker.1: [2014-04-08 18:25:36,255: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:25:37 api app/cpuworker.1: [2014-04-08 18:25:37,296: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:25:37 api app/cpuworker.1: [2014-04-08 18:25:37,642: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:26:19 api app/cpuworker.1: [2014-04-08 18:26:19,528: INFO/MainProcess] Scaling down -3 processes.
Apr 08 11:27:01 api app/cpuworker.1: [2014-04-08 18:27:00,966: INFO/MainProcess] Scaling down -3 processes.
Apr 08 11:28:01 api app/cpuworker.1: [2014-04-08 18:28:00,980: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:28:40 api app/cpuworker.1: [2014-04-08 18:28:40,204: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:29:31 api app/cpuworker.1: [2014-04-08 18:29:31,344: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:30:29 api app/cpuworker.1: [2014-04-08 18:30:29,606: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:31:01 api app/cpuworker.1: [2014-04-08 18:31:01,552: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:31:50 api app/cpuworker.1: [2014-04-08 18:31:49,954: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:32:32 api app/cpuworker.1: [2014-04-08 18:32:32,133: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:32:44 api app/cpuworker.1: [2014-04-08 18:32:44,422: INFO/MainProcess] Scaling up 1 processes.
Apr 08 11:33:32 api app/cpuworker.1: [2014-04-08 18:33:32,371: INFO/MainProcess] Scaling down -4 processes.
Apr 08 11:44:51 api app/cpuworker.1: [2014-04-08 18:44:51,728: INFO/MainProcess] Scaling up 1 processes. 
```

This happens with both types of workers. I've looked a lot at any pattern of this happening - especially for the first time - but the worker just processes tasks as it should, and will, more or less randomly, scale around.
But it's clear that something is wrong as usually the worker will get stuck with too few workers, and will basically try to scale up - but instead scales down by -1. I yet have to find an error inbetween the scaling steps that could be responsible for this.

As this happens on production, I'm afraid that I can't supply much more data - everything inbetween looks like noise to me. I don't expect anyone to know what's going on from the little data I gave, but at least wanted to see if that's only happening to me.
One thing to point out: I was running the prefork worker with --maxtasksperchild=10 and a value of 30 in the config, celery flower reported the 30 for the cpuworker. Just mentioning that on the off chance that it is somehow relevant.
```
worker: celery -A app -l info -P gevent -Q celery --autoscale=250,60 worker
cpuworker: celery -A app -l info -P prefork -Q cpu --maxtasksperchild=10 --autoscale=10,5 worker
```
```
software -> celery:3.1.9 (Cipater) kombu:3.0.14 py:2.7.4
            billiard:3.3.0.16 redis:2.8.0
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis

CELERY_ROUTES: {
    'adapter.dispatch.generate_label': {   'queue': 'cpu'}}
CELERY_IGNORE_RESULT: True
CELERYD_TASK_SOFT_TIME_LIMIT: 120
BROKER_URL: 'redis://...'
BROKER_TRANSPORT_OPTIONS: {
    'max_connections': 100, 'visibility_timeout': 1800}
CELERY_TASK_RESULT_EXPIRES: 60
SERVER_EMAIL: ...'
CELERYD_TASK_TIME_LIMIT: 130
CELERY_SEND_TASK_ERROR_EMAILS: True
ADMINS: ...
CELERY_STORE_ERRORS_EVEN_IF_IGNORED: True
CELERY_RESULT_BACKEND: <redis>
```

**Comment by thedrow** [comment] 2015-06-20 07:44
@ask Some servers run more than celery and they also need file descriptors.
Since that's limited by the OS there might be value in autoscaling gevent/eventlet providing that the other services are allowed to fail (monitoring services for example)

**Comment by thedrow** [comment] 2015-06-20 07:46
I can confirm this issue myself. What's worse is that sometimes I don't see those logs even if the log level is debug.

**Comment by insertjokehere** [comment] 2015-06-28 21:20
I've been seeing a similar issue as well, and think I have a fix. Will test it out today, open a PR if it works for me

**Comment by insertjokehere** [comment] 2015-07-10 03:01
https://github.com/insertjokehere/celery/commit/5f5a973da587fcad84c0bfb47078832b71b17878 seems to fix this for us. I'm not sure if there is a deeper issue that needs to be addressed

**Comment by thedrow** [comment] 2015-07-10 06:44
I'd love to have a pull request with this change but let's ensure that it is covered with a test so we won't break this mechanism again.

**Comment by urvineet** [comment] 2015-10-12 11:23
please let me know fix merge or not because i am getting same issue v3.1.18

**Comment by thedrow** [comment] 2015-10-13 07:09
@insertjokehere did you create the PR yet?

**Comment by insertjokehere** [comment] 2015-10-19 19:56
@thedrow I have not. If I get some time in the next few weeks I will look at writing a test case

**Comment by komuW** [comment] 2016-03-14 09:53
@insertjokehere hi, did you make a PR?

**Comment by insertjokehere** [comment] 2016-03-14 19:43
@komuW no, I haven't had the time, and TBH I'm not really sure where to start trying to write a test case for this

**Comment by komuW** [comment] 2016-03-17 22:08
This seems to have been fixed by: https://github.com/celery/celery/commit/fe3838cb006de3606fd38d03ac168f09dc5b0507 

I also added a testcase for this scenario here; https://github.com/celery/celery/pull/3120 (the testcase fails for versions of celery older than the above commit)

@tschottdorf @PhilipGarnero @insertjokehere @ask @thedrow ; could you comment and possibly close this issue if my assertions are true.

Thanks,

**Comment by komuW** [comment] 2016-04-03 11:03
following the merge of the testcase; https://github.com/celery/celery/pull/3120 
I think that this issue should now be closed. @thedrow

**Closed** 2016-04-03 12:07 UTC
Labels: Component: Autoscaling, Component: Gevent Workers Pool, Component: Prefork Workers Pool, Status: Needs Testcase
