### ISSUE TITLE
Celery worker hangs when invoking skimage transform as celery task

### ISSUE THREAD

**Issue by srawat** [celery/celery#2659] opened 2015-06-16 04:30 UTC
I am trying to run image resizing task as a celery task. Here's my tasks.py

tasks.py

```
from celery import Celery
from skimage import io, transform

app = Celery('tasks', broker='amqp://guest@server//', backend='redis://server')

@app.task
def transform(filename):
    img = io.imread(filename)
    print img.shape
    img = transform.resize(img,(256,256))
    print img.shape
```

celery -A tasks worker -c 5 -l info

ipython
```
In [1]: from tasks import transform
In [2]: transform('image.jpg')
(1508, 2011, 3)
(256, 256, 3)
In [3]: r = transform.delay('image.jpg')
In [4]: r.ready()
Out[4]: False
```

Worker Log
```
[2015-06-15 21:26:58,947: WARNING/MainProcess] celery@server ready.
[2015-06-15 21:27:32,515: INFO/MainProcess] Received task: tasks.tranform[0383dc0b-0c17-413f-a360-b1e4301b35ba]
[2015-06-15 21:27:32,664: WARNING/Worker-2] (1508, 2011, 3)
```

Worker hangs at this point

**Comment by averwind** [comment] 2015-06-16 17:07
Can you try  starting your worker with "-P solo" ?

**Comment by srawat** [comment] 2015-06-16 18:03
Yes. It does work with the -P solo option. 
Also i noticed that my other machines are not getting above errors. I am not sure what setup is causing this issue

**Comment by averwind** [comment] 2015-06-16 18:18
Likely caused by the module you are using (perhaps a shared variable which gets copied to every sub process with the pool).

move
from skimage import io, transform

to your function/task, likely that will fix the problem.

**Comment by srawat** [comment] 2015-06-16 18:36
Does that imply that we can not have shared variables across tasks. 
In my case, i want a class to be initialized (in my case a machine learned model that has initialization overhead) only once when the worker process is started. 
All subsequent tasks submitted to celery should use the preinitialized class object to perform operations.
Is this something i can achieve

**Comment by thedrow** [comment] 2015-06-16 19:34
The problem is that by default Celery preforks. Preforking copies all the process' state to the children processes.
If you have a module that doesn't work when you prefork there will be unexpected consequences regardless if you use Celery or not.
What happens if you directly use the multiprocessing module?

On a different note, skimage might be releasing the GIL so it's worth trying the thread pool worker pool because that means that jobs using skimage will execute in parallel. You do have to ensure that nothing else runs on that worker since running pure python code with threads will degrade performance unless I/O is performed (in which case you should be using an async I/O library instead of threads) or if you have a C component that releases the GIL like I mentioned above.
@srawat Can you please try what @averwind suggested and tell me if it fixes the problem.
If it does, can you please file an issue upstream and reference it here?

**Comment by thedrow** [comment] 2015-06-19 08:15
@srawat Hanging workers can be debugged using SIGUSR1 on a child process.
That will print the current process' traceback.

**Comment by ask** [comment] 2016-06-24 00:17
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Closed by ask** 2016-06-24 00:17 UTC
Labels: Issue Type: Bug, Status: Feedback Needed, Worker Hangs
