### ISSUE TITLE
Worker shutdown creates duplicate messages in SQS broker

### ISSUE THREAD

**Issue by pgeez** [celery/celery#4002] opened 2017-04-27 20:32 UTC
## Checklist

I'm `pip` installing Celery from `master`.

## Steps to reproduce

Submit a task to an SQS broker and verify that there are 1 messages available and 0 messages "in flight" (total messages: 1). Launch a worker connected to that broker and now verify that there are 0 messages available and 1 messages "in flight" (total messages: 1). Shutdown the worker before the task completes (via Ctrl + C). The task will then be resubmitted with the following message:

```Restoring 1 unacknowledged message(s).```

Verify that the total number of messages in SQS is now 2 (1 available and 1 "in flight").

Repeat.

## Expected behavior

I expect the total number of messages in the SQS broker to remain constant, as is the behavior I observe when I perform the repro with a Redis broker.

## Actual behavior

Messages are duplicated, which can cause the queue to grow in an unbounded way.

Adding to this, I have long-running tasks (~45 min) and notice that I quite frequently see this error message 

`[INFO] botocore.vendored.requests.packages.urllib3.connectionpool: Resetting dropped connection: sqs.us-west-2.amazonaws.com`

in conjunction with `Restoring N unacknowledged messages.`

It seems that dying SQS connections are causing workers to restart, which is in turn causing my queue to grow. (FYI: overnight, it grew from ~10 jobs to 13,000 because of this behavior when running a cluster of ~20 machines)

**Comment by georgepsarakis** [comment] 2017-05-01 16:52
This is probably caused by the [visibility timeout](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html). You can check the following references:
- http://stackoverflow.com/questions/41300209/celery-sqs-duplication-of-tasks-sqs-visibility-timeout
- http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html?highlight=sqs#visibility-timeout

**Comment by pgeez** [comment] 2017-05-01 17:03
@georgepsarakis So, are you suggesting setting `visibility_timeout` to 0? It seems like incorrect behavior for the workers to be creating multiple copies of the same message on the broker. I tested this with the Redis broker and the behavior is as expected; messages that have been fetched are resubmitted, but are not duplicated.

**Comment by georgepsarakis** [comment] 2017-05-01 17:13
I understand. Perhaps this is the same issue as [this](https://github.com/celery/celery/issues/3796)?

**Comment by pgeez** [comment] 2017-05-01 17:17
@georgepsarakis These issues seem similar, indeed. As for the exact nature of this issue, I'm not certain; it is a huge deal breaker though and I can't use Celery until this is fixed.

**Comment by maroux** [comment] 2017-09-05 17:59
Running into a similar (same?) issue. Even without worker shut down, it appears that if you manually raise a retry exception, there's exponential growth on SQS messages with each message spawning one duplicate message in the queue. This has rendered SQS backend useless for us. I'm trying to figure out the problem from celery/kombu, haven't nailed it down yet.

**Comment by lovemyliwu** [comment] 2018-03-29 03:39
@pgeez I just do a tricky work and fixed this problem, please check

https://gist.github.com/lovemyliwu/af5112de25b594205a76c3bfd00b9340

**Comment by georgepsarakis** [comment] 2018-03-29 19:31
@lovemyliwu thanks for sharing your solution. Could you please explain the logic there?

**Comment by lovemyliwu** [comment] 2018-03-30 01:47
@georgepsarakis hook warm shutdown and task success signal, if everything ok, then mark consumer default channel **not** do restore.

**Comment by auvipy** [comment] 2018-08-10 11:39
Can anyone send the solution as PR?

**Comment by mintusah25** [comment] 2018-10-07 13:34
I have created a PR: https://github.com/celery/kombu/pull/926/files. Have a look. 
If required, I can fix test case too.

**Comment by auvipy** [comment] 2018-10-13 11:27
please install kombu and celery from master and report the result

**Comment by jainraj** [comment] 2018-11-15 09:31
I have 

1. Kombu at 94227bbc43b182477d37be30b881b065489ce833 commit id (commit id of the above merge) 
2. Celery at celery==4.2.1

This issue is 99% solved. When I run with tasks having ETA. 

**Exact Scenario:**
Made 100 tasks with eta > 1 hr
Started celery. It fetched all the 100 tasks - When I check SQS here, it shows 100 tasks in flight.
Warm shutdown celery
It prints "Restoring 100 unacknowledged message(s)"
And after celery has completely shutdown, I check SQS - I have 99 in ready and 1 in flight. 

Any idea why that 1 task would be still in flight??!

**Comment by jainraj** [comment] 2018-11-15 12:16
On further analysis, this seems to be happening when we have high number of tasks. When I try this with 5 tasks, all is well. 

@auvipy can we add some status check of the ChangeMessageVisibility API call. That should be failing for the missed message. If it is not so, then this might be an SQS issue :(

**Comment by auvipy** [comment] 2018-11-18 15:40
I would request you to come with a probable solution :) otherwise, have to wait for next major release

**Comment by jainraj** [comment] 2018-11-21 10:53
@auvipy Tried to see if the status message from the ChangeMessageVisibility call can give anything. It gives 200 even for the failed message. Seems like some issue in SQS. I am out of my depth here :(

As you suggested, waiting for next major release :)

**Comment by thedrow** [comment] 2018-12-18 15:21
Any reason this is still open? We merged https://github.com/celery/kombu/pull/926.
Is there anything else to do?

**Comment by jainraj** [comment] 2018-12-19 09:40
> @auvipy Tried to see if the status message from the ChangeMessageVisibility call can give anything. It gives 200 even for the failed message. Seems like some issue in SQS. I am out of my depth here :(
> 
> As you suggested, waiting for next major release :)

@thedrow What do you suggest for this?

**Comment by thedrow** [comment] 2018-12-19 12:59
If it's an issue in SQS, open a support ticket with AWS.

**Closed by thedrow** 2018-12-19 12:59 UTC
Labels: Component: Amazon SQS Broker, Issue Type: Bug
