### ISSUE TITLE
ETA Memory Usage is too high leading to out of memory exceptions.

### ISSUE THREAD

**Issue by nicolasbaer** [celery/celery#2218] opened 2014-08-28 08:54 UTC
Is there any way to reduce the memory consumption of ETA tasks? In case a queue holds thousands of ETA tasks, the workers will try to load all tasks into memory possibly leading to OOM situations. I looked into the `prefetch` option, but apparently this is not applicable for ETA tasks.

**Comment by djsmith42** [comment] 2015-02-09 19:07
By my measurements, each ETA task uses 11KB of memory. For my production system, we have 80,000 ETA tasks in Rabbit. This results in 800MB of memory used on the master worker process. Every time a child process is recycled and a new one forked, it inherits this memory usage. With CELERYD_CONCURRENCY = 10, this results in 8GB of memory being used. The higher the concurrency, the higher the memory usage. I expected copy-on-write to save us, but it does not. We are hitting OOM often as a result.

**Comment by ask** [comment] 2016-06-23 23:50
Closing this, as we don't have the resources to complete this task.

**Closed by ask** 2016-06-23 23:50 UTC
Labels: Issue Type: Feature Request

**Comment by dhui** [comment] 2016-06-29 21:32
I'm hitting the same problem. Is there any other way to solve this besides throwing hardware at it?
It's curious that COW doesn't isolate the large RSS memory usage to just the master worker.

**Comment by djsmith42** [comment] 2016-06-29 21:40
@dhui We worked around it by putting ETA tasks on a separate queue and running a separate instance of Celery with concurrency set to 1 to consume tasks from that queue. This seems to have worked just fine. We run it on the same box as the regular Celery instance with a higher concurrency (10).

**Comment by dhui** [comment] 2016-06-29 23:54
Thanks for sharing @djsmith42 !

We have multiple queues setup as well, but we want a bunch of workers consuming off of the ETA queue since lot of our tasks have the same ETA and we want our task latencies to be low. So I guess hardware will have to be our solution for now...

**Comment by bartdag** [comment] 2016-06-30 00:26
We are working on a different workaround. Basically we:

1. Store task information with eta time in a db.
2. Have a celery periodic task that checks every minute if there are tasks due.
3. If such due tasks exist, launch the tasks. The task will use the appropriate routing and will be added to the same queue as if it had been initially launched with a standard eta.

Tasks thus no longer linger in the workers, do not consume memory (only disk/db space), we can schedule tasks a long time in advance, and we can easily manage them (e.g., cancel tasks).

It's not a general solution because:

1. It uses our extension of django db result (https://github.com/resulto-admin/django-celery-fulldbresult) to store all the parameters necessary to launch the task later.
2. We relax the guarantees usually provided by rabbitmq/celery: we can make sure that a task is never launched twice, but it may never launch if a crash happens at a very bad time. It's possible though to identify those tasks that were never processed.
3. Depending on the kind of ETA and task volume, it would be wise to adopt a less naive approach than our single periodic task running every minute.

We'll publish this workaround in django-celery-fulldbresult once we are satisfied with the implementation.

**Comment by djsmith42** [comment] 2016-06-30 00:48
Cool idea. I've thought about a DB solution as well, but never implemented it. Surely there must be a way to reduce the memory usage of each ETA task, or even a way to prevent the memory from being copied to child processes. I've tried to find a smoking gun in the code with no luck.

The other memory usage problem I've encountered is caused by revoked ETA tasks, which your solution probably also addresses.

**Comment by bartdag** [comment] 2016-07-28 23:47
We just released our [alternate solution](https://github.com/resulto-admin/django-celery-fulldbresult#alternative-celery-scheduling-eta-and-countdown), which uses task meta information stored in a Django model.

If someone is interested in the general strategy but does not want to use our result backend:

1. Here is how we [monkey patch apply_async to save tasks with ETA](https://github.com/resulto-admin/django-celery-fulldbresult/blob/master/django_celery_fulldbresult/__init__.py) and prevent them from being submitted to the workers. 

2. Here is how we [send due tasks for execution](https://github.com/resulto-admin/django-celery-fulldbresult/blob/master/django_celery_fulldbresult/tasks.py#L12).
