### ISSUE TITLE
celery.schedules.crontab is_due logic can trigger periodic celery beat tasks at arbitrary times unrelated to the crontab parameters when last_run_at value is sufficiently old

### ISSUE THREAD

**Issue by fcostin** [celery/celery#4806] opened 2018-06-09 08:44 UTC
There's an issue in the implementation of `celery.schedules.crontab` method that can cause `crontab.is_due` to claim a schedule is due at a time that is completely unrelated to the given crontab parameters. This appears to happen in cases where the `last_run_at` value is older than the most recent feasible time the schedule could have run. It looks like that this issue was introduced as part of complex logic added nearly 8 years ago to improve the accuracy of time remaining estimates for `crontab` periodic tasks: 4ed89ec49582b540149cf06047f091ebd20fb300

## Checklist
Issue first observed in a celery deployment running celery v3.1.19

From inspecting the `celery.schedules.crontab` code it appears likely that this issue is present in all celery versions as far back as v2.1.0 through to v4.1.1 .

Unit tests (please see below) confirm issue is still present in master (b599b96960be9dd42b3dee82a58bd1d711df0317 at time of writing).

## Steps to reproduce
Please apply this patch to celery master branch, remove `@skip.todo` from the first new test, run unit tests, observe the first of these added unit tests fails:

```
diff --git a/t/unit/app/test_schedules.py b/t/unit/app/test_schedules.py
index a7b3025..0340461 100644
--- a/t/unit/app/test_schedules.py
+++ b/t/unit/app/test_schedules.py
@@ -26,6 +26,18 @@ def patch_crontab_nowfun(cls, retval):
         cls.nowfun = prev_nowfun
 
 
+def is_time_feasible_wrt_crontab_schedule(t, z):
+    # z : celery.schedules.crontab instance
+    t = z.maybe_make_aware(t)
+    return (
+        t.month in z.month_of_year and
+        (t.isoweekday() % 7) in z.day_of_week and
+        t.day in z.day_of_month and
+        t.hour in z.hour and
+        t.minute in z.minute
+    )
+
+
 @skip.unless_module('ephem')
 class test_solar:
 
@@ -803,3 +815,59 @@ class test_crontab_is_due:
             due, remaining = self.yearly.is_due(datetime(2009, 3, 12, 7, 30))
             assert not due
             assert remaining == 4 * 24 * 60 * 60 - 3 * 60 * 60
+
+    @skip.todo('FIXME crontab logic is defective when last_run_at is older than the most recent feasible time wrt schedule')
+    def test_daily_execution_if_last_run_at_was_days_ago_and_current_time_does_not_match_crontab_schedule_then_execution_is_not_due(self):
+        z = self.crontab(hour=7, minute=30)
+        last_run_at = datetime(2018, 6, 1, 7, 30)
+        now = datetime(2018, 6, 9, 23, 48)
+        expected_next_execution_time = datetime(2018, 6, 10, 7, 30)
+        expected_remaining = (expected_next_execution_time - now).total_seconds()
+        # check our assumptions
+        assert is_time_feasible_wrt_crontab_schedule(last_run_at, z)
+        assert not is_time_feasible_wrt_crontab_schedule(now, z)
+        assert is_time_feasible_wrt_crontab_schedule(expected_next_execution_time, z)
+        assert now < expected_next_execution_time
+        assert expected_remaining == (7 * 60 + 30 + 12) * 60
+        # test is_due
+        with patch_crontab_nowfun(z, now):
+            due, remaining = z.is_due(last_run_at=last_run_at)
+            assert remaining == expected_remaining
+            assert not due
+
+    def test_daily_execution_if_last_run_at_was_the_most_recent_feasible_time_wrt_schedule_in_past_and_current_time_does_not_match_crontab_schedule_then_execution_is_not_due(self):
+        z = self.crontab(hour=7, minute=30)
+        last_run_at = datetime(2018, 6, 9, 7, 30)
+        now = datetime(2018, 6, 9, 23, 48)
+        expected_next_execution_time = datetime(2018, 6, 10, 7, 30)
+        expected_remaining = (expected_next_execution_time - now).total_seconds()
+        # check our assumptions
+        assert is_time_feasible_wrt_crontab_schedule(last_run_at, z)
+        assert not is_time_feasible_wrt_crontab_schedule(now, z)
+        assert is_time_feasible_wrt_crontab_schedule(expected_next_execution_time, z)
+        assert now < expected_next_execution_time
+        assert expected_remaining == (7 * 60 + 30 + 12) * 60
+        # test is_due
+        with patch_crontab_nowfun(z, now):
+            due, remaining = z.is_due(last_run_at=last_run_at)
+            assert remaining == expected_remaining
+            assert not due
+
+    def test_daily_execution_if_last_run_at_was_more_recent_than_the_most_recent_feasible_time_wrt_schedule_in_past_and_current_time_does_not_match_crontab_schedule_then_execution_is_not_due(self):
+        z = self.crontab(hour=7, minute=30)
+        last_run_at = datetime(2018, 6, 9, 10, 30) # not feasible wrt to current schedule. case can happen if schedule is modified after a run
+        now = datetime(2018, 6, 9, 23, 48)
+        expected_next_execution_time = datetime(2018, 6, 10, 7, 30)
+        expected_remaining = (expected_next_execution_time - now).total_seconds()
+        # check our assumptions
+        assert not is_time_feasible_wrt_crontab_schedule(last_run_at, z)
+        assert not is_time_feasible_wrt_crontab_schedule(now, z)
+        assert is_time_feasible_wrt_crontab_schedule(expected_next_execution_time, z)
+        assert now < expected_next_execution_time
+        assert expected_remaining == (7 * 60 + 30 + 12) * 60
+        # test is_due
+        with patch_crontab_nowfun(z, now):
+            due, remaining = z.is_due(last_run_at=last_run_at)
+            assert remaining == expected_remaining
+            assert not due
+
```

## Expected behavior
No matter what the value of `last_run_at` is, `crontab.is_due(last_run_at)` should never return `schedstate(True, rem)` when the current time `now` is not feasible with respect to the given crontab parameters.

## Actual behavior
if `last_run_at` value is older than the most recent time that is feasible with respect to the given crontab parameters then `crontab.is_due(last_run_at)` returns `schedstate(True, rem)`  when the current time is not feasible with respect to the crontab parameters.

## Comments
This behaviour is surprising as it is an undocumented departure from cron-like behaviour. This behaviour is somewhat like an undocumented variant of uncontrollable `anacron` behaviour. "Uncontrollable" in the sense that unlike `anacrontab`'s `START_HOURS_RANGE` parameter - there is no control at all over when tasks will be run when a scheduled execution is missed.

We experience this issue in production using the venerable Celery version of 3.1.19 : we have a celery beat process that is backed by a database using custom scheduler code that is derived from the django-celery-beat scheduler. Suppose we stop this celery beat process for some reason such as scheduled maintenance or during a deployment that needs to redeploy code to our celery cluster. When we later restart celery beat again then some or all `celery.schedules.crontab` scheduled tasks may immediately execute if there was a time during the celery beat downtime period that matches the crontab parameters.

One hack that can mitigate this behaviour is updating the "last_run_at" value for all celery crontab scheduled periodic tasks to the current time when celery beat starts, before celery beat makes any calls to the `celery.schedules.crontab.is_due` method.

**Comment by fcostin** [comment] 2018-06-09 08:50
I am in the process of rewriting the `celery.schedules.crontab` logic to fix this cleanly, if i can get the green light from my client to release a fix upstream i will submit a pull request with a proposed patch to fix this within the next week or two.

**Comment by fdemmer** [comment] 2019-05-02 13:47
@fcostin did you ever complete your `crontab` rewrite and/or (not) get permission to release?

**Comment by auvipy** [comment] 2019-05-02 13:56
Can you send a PR with proposed fix?

**Comment by fcostin** [comment] 2019-05-02 18:47
@fdemmer -

One crude way to fix this is to simply revert the old change that introduced this issue: https://github.com/celery/celery/commit/4ed89ec49582b540149cf06047f091ebd20fb300

This would have downside of breaking the logic that estimates when the next scheduled task is due, and causing the scheduler to need to poll every second to re-check if a task is due yet. But it would fix this issue.

I wrote a better patch for fixing this last year (that didn't rely on polling every 1 second, and could estimate remaining time until the next scheduled task) but finished up my contract shortly after and ran out of time to lobby for permission to release the fix upstream. I'll reach out and see if anyone there is willing to work with me to get the patch released (chances of this are low, but worth a try...).

**Comment by fdemmer** [comment] 2019-05-02 19:04
thanks for the response @fcostin :)

my requirement is adding tz support. i thought about rewriting/fixing/adding to celery's crontab, but decided it would be better to not hack around in that code or pile up on top, so i wrote my own using [tzcron](https://github.com/bloomberg/tzcron) to parse the cron expression and calculate the next event.

https://gist.github.com/fdemmer/7551bff2bab80b56aac5018060aded55

it hasn't been used a lot and has no tests, but seems to work and is licensed under MIT like all my gists.

**Comment by fcostin** [comment] 2019-05-02 22:03
hi @fdemmer -- adding timezone support sounds like a great idea, as does your implementation that avoids using the existing celery crontab scheduler logic completely.

Your `pytzcrontab` implementation looks pretty good . If i was aware of this last year that would have likely been a cleaner fix than my patch. thanks for sharing!

> it hasn't been used a lot and has no tests, but seems to work and is licensed under MIT like all my gists.

Sounds promising!

I have subjected your `pytzcrontab` class to the existing unit tests for the crontab scheduler -- with some patches to those unit tests to fix up timezones as necessary -- including adding three new tests from my patch in this issue.

here are my experimental patches, including adding `celery-tzcron.py` from your gist as `celery/scheduler_tzcron.py`:

https://github.com/fcostin/celery/commits/scheduler_tzcron_experiments

the results are fairly good:

1. `pytzcrontab` appears to fix this issue, as you predict. this makes sense.
2. with a small patch for compatibility with the existing `crontab` scheduler to define `hour` ... `day_of_year` properties, `pytzcrontab` passes most of the old unit tests
3. with some more patches to your `is_due` and `remaining_estimate` logic, the `pytzcrontab` implementation behaves in a closer way to how the existing `crontab` class decides when things are due. This change appears to be necessary so that `pytzcrontab` does not say the schedule is due when the schedule last ran a very short time ago (e.g. 0 seconds ago!). i am not completely happy with my proposed change here, it doesn't seem completely clean, maybe you can think of a nicer way to do it.
3. `pytzcrontab` introduces one regression that the existing celery unit tests can detect-- it goes into an infinite loop if we try to schedule something on an impossible day (31st of april) . I looked for an obvious way to avoid this but didn't find a good one so i've marked the test as skipped, but this would be good to fix. I guess it could be fixed by additional up-front validation logic, but there is still some risk that a gap between validation and the behaviour of the `tzcron` library might lead to an infinite loop.

```
   @pytest.mark.skip("broken - pytzcrontab goes into an infinite loop here")
    def test_invalid_specification(self):
        # *** WARNING ***
        # This test triggers an infinite loop in case of a regression
        with pytest.raises(RuntimeError):
            self.next_ocurrance(
                self.pytzcrontab(day_of_month=31, month_of_year=4),
                datetime_utc(2010, 1, 28, 14, 30, 15),
            )
```

What do you think?

Would it make sense to contribute something like this as a pull request into celery itself?

**Comment by minsis** [comment] 2020-12-07 23:39
This issue is fairly old is there a fix or a work around for this? I see the gist above but I'd rather not have to maintain some other version of celery.

Right now I'm facing an issue with duplicate ETL imports because of this. I run all crontab schedules but if I make an on the fly change, either adding a new periodic task or changing the schedule of one, it will trigger ALL of my tasks to run.

**Comment by thedrow** [comment] 2020-12-08 13:31
That's very unfortunate. We're sorry that this is happening.
I'm unaware of a workaround for this issue.

Unfortunately, we never received a PR which fixes this issue.
If you'd like to help, please take the patch above and do the work necessary to get it merged.

**Comment by minsis** [comment] 2020-12-14 20:23
In all honesty this seems like its been an issue for a very long time and frankly surprised its not a much higher priority bug to be fixed. For a scheduling app to incorrectly schedule a task seems like a pretty big issue.

Anyways, I appreciate you taking the time to respond. I can try to look at the code, but in all honesty I'm not very good with following large projects like Celery. If I get some time over Christmas holiday I will have a go at trying to see where it can be fixed.

Stay safe and have a wonderful holiday!

**Comment by auvipy** [comment] 2020-12-15 03:37
> In all honesty this seems like its been an issue for a very long time and frankly surprised its not a much higher priority bug to be fixed. For a scheduling app to incorrectly schedule a task seems like a pretty big issue.
> 
> Anyways, I appreciate you taking the time to respond. I can try to look at the code, but in all honesty I'm not very good with following large projects like Celery. If I get some time over Christmas holiday I will have a go at trying to see where it can be fixed.
> 
> Stay safe and have a wonderful holiday!

if you can take the lead we could help you guide you through all the way

**Comment by minsis** [comment] 2020-12-16 20:56
So now I'm not sure if my issue is related to this. I was trying to reproduce this with my app and wasn't able to reproduce it until today.

The way it triggered wasn't by adding/removing/updating a periodic task, but by adding a new schedule and then assigning that to a newly created periodic task. I don't know if this is due to the library I'm using to store it in a database or relating to this issue. I'll have to dig a bit deeper when I can.

**Comment by binu-mobiux** [comment] 2020-12-31 06:59
We ran into this issue on our production setup and charged our subscription customers ahead of schedule when we restarted the services with a slight change in the scheduled time. This should be a higher priority bug.

I will try and post the steps to reproduce this reliably.

**Comment by minsis** [comment] 2021-02-10 16:34
As a work around: since I'm using an external scheduler library for managing the beat schedules I just simply have an event listener on beat startup null out the last_run_at field for each schedule in the database. This will prevent beat from running any of the schedules prematurely.

**Comment by thedrow** [comment] 2021-03-29 09:31
> 
> 
> In all honesty this seems like its been an issue for a very long time and frankly surprised its not a much higher priority bug to be fixed. For a scheduling app to incorrectly schedule a task seems like a pretty big issue.

This is not a priority as none of us needs to fix this and no one is paying us to do so.

**Comment by latusaki** [comment] 2021-05-18 09:10
I am not sure if we are experiencing this same issue, here is what the celerybeat-schedule looks like:

```
>>> schedule = shelve.open("celerybeat-schedule", writeback=True)
>>> task = schedule["entries"]["My task"]
>>> task.last_run_at
datetime.datetime(2021, 5, 18, 8, 36, 0, 99, tzinfo=<UTC>)
>>> task.is_due()
schedstate(is_due=True, next=48.84625)
>>> task.schedule
<crontab: * 8 * * * (m/h/d/dM/MY)>
>>> datetime.now()
datetime.datetime(2021, 5, 18, 8, 39, 36, 601785)
```
The above task runs continously between 8am and 9 am __sometimes__ but not always... Using `celery==5.0.5`

**Comment by thedrow** [comment] 2021-05-19 07:08
@latusaki Do you feel like investigating further?
Our capacity is already maxed out with the 5.1 release.

**Comment by thedrow** [comment] 2021-05-19 07:09
@binu-mobiux Do you have a way to reproduce this issue?

**Comment by latusaki** [comment] 2021-05-19 07:12
@thedrow I can't commit as I don't have enough time, not expecting a fix, was just unsure if this bug is the same described above. I have now changed my crontab from 8am to 7:59 and waiting to see if the problem resurfaces.

**Comment by dangell7** [comment] 2021-06-01 13:34
I have the same issue. I use crontab(hour='*/3') and once the top of the hour hits, it runs on an infinite loop.

**Comment by thedrow** [comment] 2021-08-17 12:39
@dangell7 Do you have time to investigate or contribute a PR?

**Closed** 2022-12-15 07:51 UTC
Labels: Component: Celerybeat, Issue Type: Bug Report
