### ISSUE TITLE
Celery lost / hanging messages without feedback (?)

### ISSUE THREAD

**Issue by davidmir** [celery/celery#4840] opened 2018-06-22 10:32 UTC
Hi,

I'm using Celery with RabbitMQ broker and I'm having the following problem: Messages are being published to the RabbitMQ queue, these messages are queued and consumed, but then the Celery process does not perform the task., however other times it processes the messages. My tasks can execute for a while (like 2 hours).

**DEBUG**
**celery logs:**
 I can't see nothing useful in the Celery logs (loglevel is in debug).

**rabbitmq-logs:**

> =WARNING REPORT==== 22-Jun-2018::10:17:07 ===
> closing AMQP connection <0.2349.660> (172.17.0.1:38740 -> 172.17.0.2:5672, vhost: '/', user: 'guest):
> client unexpectedly closed TCP connection

**celery report:**

> software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:2.7.9
>             billiard:3.5.0.3 py-amqp:2.2.2
> platform -> system:Linux arch:64bit, ELF imp:CPython
> loader   -> celery.loaders.app.AppLoader
> settings -> transport:amqp results:rpc:///

**celery inspect status:**
-> celery@6bd749f44e90: OK

>     {
>         "broker": {
>             "alternates": [
>                 "amqp://guest:guest@rabbit1",
>                 "amqp://guest:guest@rabbit2"
>             ],
>             "connect_timeout": null,
>             "failover_strategy": "round-robin",
>             "heartbeat": 120.0,
>             "hostname": "rabbit1",
>             "insist": false,
>             "login_method": "AMQPLAIN",
>             "port": 5672,
>             "ssl": false,
>             "transport": "amqp",
>             "transport_options": {},
>             "uri_prefix": null,
>             "userid": "guest",
>             "virtual_host": "/"
>         },
>         "clock": "48155359",
>         "pid": 10,
>         "pool": {
>             "max-concurrency": 2,
>             "max-tasks-per-child": "N/A",
>             "processes": [
>                 15,
>                 16
>             ],
>             "put-guarded-by-semaphore": false,
>             "timeouts": [
>                 0,
>                 0
>             ],
>             "writes": {
>                 "all": "33.33%, 66.67%",
>                 "avg": "44.44%",
>                 "inqueues": {
>                     "active": 0,
>                     "total": 2
>                 },
>                 "raw": "3, 6",
>                 "strategy": null,
>                 "total": 9
>             }
>         },
>         "prefetch_count": 8,
>         "rusage": {
>             "idrss": 0,
>             "inblock": 24,
>             "isrss": 0,
>             "ixrss": 0,
>             "majflt": 0,
>             "maxrss": 79736,
>             "minflt": 32998,
>             "msgrcv": 0,
>             "msgsnd": 0,
>             "nivcsw": 74723,
>             "nsignals": 0,
>             "nswap": 0,
>             "nvcsw": 544907,
>             "oublock": 752,
>             "stime": 19.364,
>             "utime": 206.084
>         },
>         "total": {
>             "my-task": 9
>         }
>     }

And sometime I see this:

> celery@6bd749f44e90: OK
>     {
>         "broker": {
>             "alternates": [
>                 "amqp://guest:guest@rabbit1:5672/",
>                 "amqp://guest:guest@rabbit2:5672/",
>                 ""
>             ],
>             "connect_timeout": 4,
>             "failover_strategy": "round-robin",
>             "heartbeat": 120.0,
>             "hostname": "rabbit1",
>             "insist": false,
>             "login_method": "AMQPLAIN",
>             "port": 5672,
>             "ssl": false,
>             "transport": "amqp",
>             "transport_options": {},
>             "uri_prefix": null,
>             "userid": "guest",
>             "virtual_host": "/"
>         },
>         "clock": "48176688",
>         "pid": 7,
>         "pool": {
>             "max-concurrency": 1,
>             "max-tasks-per-child": "N/A",
>             "processes": [
>                 42
>             ],
>             "put-guarded-by-semaphore": false,
>             "timeouts": [
>                 0,
>                 0
>             ],
>             "writes": {
>                 "all": "100.00%",
>                 "avg": "100.00%",
>                 "inqueues": {
>                     "active": 0,
>                     "total": 1
>                 },
>                 "raw": "1",
>                 "strategy": null,
>                 "total": 1
>             }
>         },
>         "prefetch_count": 4,
>         "rusage": {
>             "idrss": 0,
>             "inblock": 0,
>             "isrss": 0,
>             "ixrss": 0,
>             "majflt": 0,
>             "maxrss": 313496,
>             "minflt": 928413,
>             "msgrcv": 0,
>             "msgsnd": 0,
>             "nivcsw": 341332,
>             "nsignals": 0,
>             "nswap": 0,
>             "nvcsw": 8188755,
>             "oublock": 29512,
>             "stime": 111.844,
>             "utime": 549.348
>         },
>         "total": {
>             "celery.backend_cleanup": 1
>         }
>     }

**strace:**

> epoll_ctl(5, EPOLL_CTL_DEL, 16, 0x7fff97a45ae0) = -1 ENOENT (No such file or directory)
> epoll_ctl(5, EPOLL_CTL_DEL, 21, 0x7fff97a45ae0) = -1 ENOENT (No such file or directory)
> fcntl(26, F_GETFL)                      = 0x2 (flags O_RDWR)
> fcntl(26, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
> recvfrom(26, 0x7fad09548924, 7, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)

This is strange. It says that have a total of 9 messages but Celery's processes are not processing these messages. CPU and Memory is stable.

## Steps to reproduce
Publish message with apply_asyc()

## Expected behavior
The message is consumed from the RabbitMQ and the Celery worker process the message.

## Actual behavior
The message is consumed from the RabbitMQ and the Celery worker does not process the message.

**Comment by mliudev** [comment] 2018-06-23 14:57
Not sure if this is related but I'm also seeing certain tasks not getting processed by the worker at all. After some fiddling around I narrowed it down to the return value of tasks in a `chain.apply_async(tasks)` call. If I remove the return value at the end of the task (the return value isn't necessary for these tasks and we only use it in testing) then the chain completes successfully.

For example:

```
class FooTask(Task):
    def run(self, arg1):
        # do stuff
        try:
            ...
        except:
            ...
        else:
            return ret_arg
```

Causes the task to disappear. Removing the `else:` clause lets the task complete successfully.

**Comment by davidmir** [comment] 2018-06-25 13:51
I noticed that when I have the Celery workers turned off and I do an apply_async for the RabbitMQ broker some of the messages are not being queued (or are being discarded or lost). This may explain why I have nothing in the Celery workers' logs. But the RabbitMQ logs are also reporting no errors.

**Comment by mliudev** [comment] 2018-06-25 13:55
Yes that is the behavior that I'm seeing. Our code works in `celery==4.1.0` so, presumably, something is broken in 4.2.0.

**Comment by georgepsarakis** [comment] 2018-06-25 14:11
@mliudev can you give a more complete example of the tasks you are running? Also which result backend and broker (RabbitMQ also?) are you using?

**Comment by mliudev** [comment] 2018-06-25 19:38
@georgepsarakis Sure.

```
$ celery --version
4.2.0 (windowlicker)
$ rabbitmqctl status
...
{rabbit,"RabbitMQ","3.7.6"}
...
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.5
BuildVersion:   17F77
```

No result backend and I'm using RabbitMQ. Here's an example of the way we're calling tasks:

```
    def celery_start(self):

        tasks = [
            CreateTask.subtask((str(self.uuid), ), immutable=True),
            WaitForRunningTask.subtask(
                (str(self.uuid), ), immutable=True),
        ]

        if should_update:
            tasks.append(
                UpdateRecordsTask.subtask(
                    (str(self.uuid), 'CREATE', ), immutable=True), )

        tasks.append(MarkRunningTask.subtask(
            (str(self.uuid), ), immutable=True))

        chain(tasks).apply_async()
```

Example Task:

```
class UpdateRecordsTask(Task):

    def run(self, uuid, record_action):

        try:
            session = Session.objects.get(uuid=uuid)

            try:
                do_stuff(session)
                time.sleep(60)

            except Exception as e:
                raise self.retry(
                    max_retries=settings.UPDATE_MAX_RETRIES,
                    countdown=settings.UPDATE_BACKOFF_SECONDS)

            else:
                return session

        except MaxRetriesExceededError:
            logger.error(
                "UpdateRecordsTask for Session {0} reached "
                "max_retries and was failed.".format(uuid))
```

MarkRunningTask:
```
class MarkRunningTask(Task):

    def run(self, uuid):

        try:
            session = Session.objects.get(uuid=uuid)

            try:
                session.run()

            except Exception as e:

                raise self.retry(
                    max_retries=settings.MARK_RUNNING_MAX_RETRIES,
                    countdown=settings.MARK_RUNNING_BACKOFF_SECONDS)

            else:
                return session

        except MaxRetriesExceededError:
            logger.error(
                "MarkRunningTask for Session {0} reached "
                "max_retries and was failed.".format(uuid))
```

This is a Django project that uses celery to make API calls to AWS.

**Comment by davidmir** [comment] 2018-06-26 09:32
In my case:

> celery.py

`# set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myapp.settings.local')

app = Celery('myapp')

# Using a string here means the worker doesn't have to serialize
# the configuration object to child processes.
# - namespace='CELERY' means all celery-related configuration keys
#   should have a `CELERY_` prefix.
app.config_from_object('django.conf:settings', namespace='CELERY')

# Load task modules from all registered Django app configs.
# A common practice for reusable apps is to define all tasks in a separate tasks.py module,
# and Celery does have a way to auto-discover these modules
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)`

> tasks.py

```
from myapp.celery import app

@app.task(bind=True)
def mytask(self, pk):
    (make some work, like database operations)
    return result
```

> api.py
```
from myapp.app.tasks import mytask
mytask.apply_async(args=[self.pk], queue='thequeue')
```

**Comment by mliudev** [comment] 2018-06-26 14:43
Interestingly our production server which runs RHEL6 does not have this issue with `celery==4.2.0`. The same code on RHEL6 behaves as expected but not locally on OSX. Production configuration:

```
$ cat system-release
Red Hat Enterprise Linux Server release 6.9 (Santiago)
$ celery --version
windowlicker (4.2.0)
$ rabbitmqctl status
...
{rabbit,"RabbitMQ","3.7.5"}
...
```

**Comment by davidmir** [comment] 2018-06-26 16:53
Can't reproduce this issue on OSX.

**Comment by davidmir** [comment] 2018-06-27 11:10
Any idea how to debug between who publishes the message and RabbitMQ?
Thanks

**Comment by mliudev** [comment] 2018-06-27 15:38
I put a breakpoint in the task that's successful using `from celery.contrib import rdb; rdb.set_trace()` and walking the call stack. There are no errors popping up in the canvas code that calls `apply_async` after marking the previous task completed. However, I have noticed that the worker appears to die right after completing the task. I'm not sure if this is the reason why the subsequent tasks aren't executed. Flower and the worker both do not show that the next task has been received at all.

**Comment by davidmir** [comment] 2018-06-29 15:33
I was able to confirm that the task does not reach the worker (with Flower).

**Comment by davidmir** [comment] 2018-07-03 16:08
Can this make a difference?

`@app.task() vs @app.task`

**Comment by davidmir** [comment] 2018-07-03 17:07
I think that this problem is not a infrastructure problem (eg network), because I can reproduce this behaviour in my development environment, which leads me to want to be an application problem. But... Nothing in the logs.

**Comment by davidmir** [comment] 2018-07-04 10:16
@thedrow Do you have any tips on how to debug the problem?

Thanks.

**Comment by davidmir** [comment] 2018-07-04 16:20
@mliudev Did you find the cause of the problem?

Thanks

**Comment by thedrow** [comment] 2018-07-05 12:17
The symptoms you guys are describing are inconsistent.
@davidmir Cannot reproduce this issue on OSX but can reproduce this issue on Linux.
@mliudev Cannot reproduce this issue on REHL but can on OSX.
I suggest that you'll attach breakpoints on the main process and not the worker processes.
This is as not actionable as #4820 is unfortunately.
I'm not saying there is no bug but I have no way to reproduce it as of now.

I can only suggest that the companies you work for will hire one of us (by donation or personally) for a few hours to debug this issue. This will require access to your environments.

I'm going to close this issue for now. If anyone has more information, please comment here.
I'm sorry I cannot be more helpful.

**Closed by thedrow** 2018-07-05 12:17 UTC

**Comment by davidmir** [comment] 2018-07-05 14:12
I already put a breakpoint and the call is made. And what I see in strace is this:

> sendto(27, "\1\0\1\0\0\0T\0<\0(\0\0\0Kmyqueue\0\316\2\0\1\0\0\1\237\0<\0\0\0\0\0\0\0\0\0Q\366\0\20application/json\5utf-8\0\0\1+\6originS\0\0\0\22gen13@9a50e237eb93\7root_idS\0\0\0$bf5dfa35-e849-443c-a2ee-d7ca2caef4e3\7expiresV\6shadowV\2idS\0\0\0$bf5dfa35-e849-443c-a2ee-d7ca2caef4e3\nkwargsreprS\0\0\0\2{}\4langS\0\0\0\2py\7retriesI\0\0\0\0\4taskS\0\0\0.mytask\5groupV\ttimelimitA\0\0\0\2VV\tparent_idV\10argsreprS\0\0\0\6[3329]\3etaV\2$bf5dfa35-e849-443c-a2ee-d7ca2caef4e3$2c2afc0f-7213-346e-b890-677003789329\316\3\0\1\0\0\0Q[[3329], {}, {\"chord\": null, \"callbacks\": null, \"errbacks\": null, \"chain\": null}]\316", 604, 0, NULL, 0) = 604

Could the problem be on the RabbitMQ side? But the logs do not report anything ... BROKER_URL can be defined as follows: amqp://user:pass@host1:port; amqp://user:pass@host2: port

Thanks.

**Comment by davidmir** [comment] 2018-07-06 16:44
I removed the use of the celery task and did an implementation of a consumer (bootsteps.ConsumerStep) and started publishing with basic_publish. So far the problem has not been repeated.

**Comment by thedrow** [comment] 2018-07-07 11:05
So the problem is somewhere in Celery and not RabbitMQ?
I suspect that a timeout should occur somewhere but we don't use it.

**Comment by davidmir** [comment] 2018-07-09 10:30
Yes, I also suspect it to be something with celery. Where is this timeout? Is it possible to send as a parameter?

**Comment by thedrow** [comment] 2018-07-09 11:35
You should debug and see where exactly in the code the master process is hanging.
When you have that information, we'll be able to deduct more conclusions.

**Comment by myesn** [comment] 2025-05-28 07:17
same problem with `celery==5.5.1` on Windows 21H2 (22000.376)

**Comment by auvipy** [comment] 2025-05-28 08:58
please check, if you are following windows specific suggestions.
