### ISSUE TITLE
Not setting task priority or app.conf.task_default_priority results in a raised exception

### ISSUE THREAD

**Issue by bjackson** [celery/celery#5340] opened 2019-02-14 17:55 UTC
If `app.conf.task_default_priority` is not set, I get an exception raised by librabbitmq-c, as `None` is passed as `priority` but an int is expected:
```py
    def basic_publish(self, body, exchange='', routing_key='',
                      mandatory=False, immediate=False, **properties):
        if isinstance(body, tuple):
            body, properties = body
        elif isinstance(body, self.Message):
            body, properties = body.body, body.properties
        return self.connection._basic_publish(
            self.channel_id, body, exchange, routing_key, properties,
>           mandatory or False, immediate or False,
        )
E       TypeError: an integer is required (got type NoneType)
``` 
`options[priority] = None` when called.

Am I doing this correctly, or is the bug somewhere else? I also experienced this with celery 4.2.1, and I'm running on master to produce this bug.

I'm not sure what the proper solution is. Should we set app.conf.task_default_priority to a default integer value?

I believe this may have been introduced by this commit: https://github.com/celery/celery/commit/7018d9ed76ec4a36a4feb8cd2d044b78bf3f987e

I'll create a PR if this is indeed the case.

**Comment by auvipy** [comment] 2019-02-22 05:56
@madprogrammer could you share some insight in this regard?

**Comment by madprogrammer** [comment] 2019-02-22 08:03
@auvipy this might be caused by https://github.com/celery/celery/pull/5313/commits/0b6d5b4551df0e1389057908b88be460ee692695#diff-463f5e07a1bd887d6739c65bf47b6cbcR425 and similar lines below, which add `priority` kwarg to all tasks, even if no priority was set (`priority=None`)... cause i thought `None` was a safe default :) apparently some rmq backend libs don't like it. Though, it's better to do some testing to make sure I correctly identified the source of the problem.

**Comment by madprogrammer** [comment] 2019-02-22 08:06
Found the timing doesn't match: the PR which introduced above change was merged 3 days ago, and this issue is 8 days old, so the problem must be somewhere else. Need further investigation

**Comment by madprogrammer** [comment] 2019-02-22 08:48
Reverting changes introduced in 7018d9e still leaves `priority=None` in `options`, because https://github.com/celery/celery/blob/master/celery/app/task.py#L34 `extract_exec_options`, which have been there for years. This kind of makes me confused, since I thought the problem was in `priority` making it into `options` when it shouldn't. Also, as can be seen here, no additional `NoneType` checking is performed when converting to `basic_properties` https://github.com/celery/librabbitmq/blob/fb0a2f914dd764bc83afa2b6d1b85b66e397a5a6/Modules/_librabbitmq/connection.c#L517. Help appreciated. @bjackson could you test whether this bug still exists without 7018d9e ?

**Comment by vzhadeyev** [comment] 2019-03-06 10:03
@madprogrammer Faced the same problem with celery 4.2.1 release and librabbitmq, so
[7018d9e](https://github.com/celery/celery/commit/7018d9ed76ec4a36a4feb8cd2d044b78bf3f987e) doesn't seem to be the origin of this bug. Btw setting `priority` for each task works but doesn't look like acceptable solution.

**Comment by madprogrammer** [comment] 2019-03-06 17:18
@vzhadeyev the thing is that release 4.2.1 doesn't contain any of my priority-related changes, so I have no idea of what might be causing this.

**Comment by auvipy** [comment] 2019-03-10 07:16
could you try 4.3rc2?

**Comment by vzhadeyev** [comment] 2019-03-13 06:37
@auvipy, tried 4.3rc2 - the same error. Can't provide more information because I can't debug `librabbitmq-c` wrapper or even build and install `librabbitmq` on MacOS Mojave.

**Comment by vzhadeyev** [comment] 2019-03-13 06:59
@auvipy, is the usage of `librabbitmq` still actual optimization tip? (in [4693](https://github.com/celery/celery/issues/4693) you said it's not true)

**Comment by thedrow** [comment] 2019-04-04 09:27
This probably happens since the frame contains the priority property.
Naturally, if it does, it has to be an integer.

See below:
https://github.com/celery/librabbitmq/blob/3fa1d38c4e66e6efdbdc7d584abe0a59857bef29/Modules/_librabbitmq/connection.c#L739

The fix is probably omitting the priority key from the properties dictionary:
https://github.com/celery/kombu/blob/675216fe98945c923ef904e53a3d1098f15b5a6c/kombu/transport/librabbitmq.py#L53-L62

**Comment by thedrow** [comment] 2019-04-04 09:30
@bjackson @madprogrammer @vzhadeyev Could any of you try the PR above and see if that fixes the issue?

**Closed** 2019-05-22 09:25 UTC
Labels: Status: Needs Verification ✘
