### ISSUE TITLE
celery worker hangs and goes offline after basic.qos prefetch_count log

### ISSUE THREAD

**Issue by wavenator** [celery/celery#3134] opened 2016-03-28 21:35 UTC
we have 100 hosts that each one runs a worker with autoscaling of 0,3
the operating system is Arch linux, inside a docker container.
our backend is a single Redis server.
after about 3-5 minutes, about 5-20 server goes offline(flower dashboard).
after connecting to the servers and look at the logs(debug), the last log line on all the offline workers was `[2016-03-28 20:16:29,449: DEBUG/MainProcess] basic.qos: prefetch_count->40`

the worker's process is up, but the forked processes are down.
after tracing the "scaling down X processes" and "Scaling up X processes", at the end there was 1 process that should run.

**Comment by ask** [comment] 2016-06-24 01:48
We are aware of the problem, but we don't have the resources to work on it atm :(

**Comment by miraculixx** [comment] 2016-11-26 17:41
I seem to run into the same problem. Is there a known fix for this?

on a side noe, @ask closing issues for "no resources atm" IMHO is not a good practice. A closed issue means "has been solved" or "is not an issue". It also means that no one will work on it, quite simply because working on a closed issue is not motivating -- a PR to a closed issue would likely be refused. Could you re-open this issue please?

**Comment by alexsv** [comment] 2016-12-15 17:28
Did you try to monitor number of opened connections to the redis?

**Comment by imanhodjaev** [comment] 2016-12-15 17:47
I can confirm that after some time when scaling up and scaling down happens workers just stop reacting and hang. Trying to go more deep and debug processes.

**Comment by auvipy** [comment] 2017-12-19 14:56
can you check on master

**Comment by auvipy** [comment] 2017-12-19 14:57
4.1 fixes a lot of this issues, so try the latest master and report again.

**Closed by auvipy** 2017-12-19 14:57 UTC
Labels: Issue Type: Bug, Worker Hangs
