### ISSUE TITLE
Tasks are not allowed to start subprocesses

### ISSUE THREAD

**Issue by aromanovich** [celery/celery#1709] opened 2013-11-29 08:44 UTC
Starting with Celery 3.1.0 the processes pool (`celery.concurrency.prefork`, former `celery.concurrency.processes`) uses daemon processes to perform tasks.

Daemon processes are not allowed to create child processes and, as a result, tasks that use `multiprocessing` package are not working:

```
[2013-11-29 14:27:48,297: ERROR/MainProcess] Task app.add[e5d184c0-471f-4fc4-804c-f760178d4847] raised exception: AssertionError('daemonic processes are not allowed to have children',)
Traceback (most recent call last):
  File "/Users/aromanovich/Envs/celery3.1/lib/python2.7/site-packages/celery/app/trace.py", line 218, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/aromanovich/Envs/celery3.1/lib/python2.7/site-packages/celery/app/trace.py", line 398, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/aromanovich/Projects/celery/app.py", line 10, in add
    manager = multiprocessing.Manager()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 524, in start
    self._process.start()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 124, in start
    'daemonic processes are not allowed to have children'
```

**Comment by xiaods** [comment] 2015-01-26 09:28
@frodopwns  use ENV 
export PYTHONOPTIMIZE=1
to remove this assert.  you need handle all things.

**Comment by frodopwns** [comment] 2015-01-26 21:10
@xiaods I think I solved that issue with something like this:
```
@worker_process_init.connect
def configure_workers(sender=None, conf=None, **kwargs):
    Crypto.Random.atfork()
```

**Comment by ostrokach** [comment] 2015-07-18 01:47
### Problem

I have a task which calculates some data and loads a scikit-learn classifier to make predictions based on that data. When I run the task by itself, everything is OK, but when I run it using Celery, I get an error when the task attempts to load the pickled classifier:

	[2015-07-17 21:23:51,299: ERROR/MainProcess] Task app.f[329d0da4-2e0e-4e1f-8148-d64f47750b1f] raised unexpected: AttributeError("'Worker' object has no attribute '_config'",)
	Traceback (most recent call last):
	  File "/home/username/anaconda3/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
		R = retval = fun(*args, **kwargs)
	  File "/home/username/anaconda3/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
		return self.run(*args, **kwargs)
	  File "/home/username/working/playground/celery/app.py", line 11, in f
		clf = pickle.load(open('clf.pickle', 'rb'))
	  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/ensemble/__init__.py", line 6, in <module>
		from .base import BaseEnsemble
	  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/ensemble/base.py", line 13, in <module>
		from ..externals.joblib import cpu_count
	  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/__init__.py", line 112, in <module>
		from .parallel import Parallel
	  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/parallel.py", line 23, in <module>
		from ._multiprocessing_helpers import mp
	  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py", line 25, in <module>
		_sem = mp.Semaphore()
	  File "/home/username/anaconda3/lib/python3.4/multiprocessing/context.py", line 81, in Semaphore
		return Semaphore(value, ctx=self.get_context())
	  File "/home/username/anaconda3/lib/python3.4/multiprocessing/synchronize.py", line 127, in __init__
		SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX, ctx=ctx)
	  File "/home/username/anaconda3/lib/python3.4/multiprocessing/synchronize.py", line 59, in __init__
		kind, value, maxvalue, self._make_name(),
	  File "/home/username/anaconda3/lib/python3.4/multiprocessing/synchronize.py", line 117, in _make_name
		return '%s-%s' % (process.current_process()._config['semprefix'],
	AttributeError: 'Worker' object has no attribute '_config'

### To reproduce

Create an empty classifier and save it as a pickle:

    import pickle
    from sklearn.ensemble import GradientBoostingClassifier
    clf = GradientBoostingClassifier()
    pickle.dump(clf, open('clf.pickle', 'wb'))

Create a simple app (`app.py`):

	import pickle
	import sklearn
	from celery import Celery

	app = Celery(__name__, broker='amqp://localhost//')

	@app.task
	def f():
		print('hello')
		clf = pickle.load(open('clf.pickle', 'rb'))
		print(clf)

Start the celery worker:

    celery -A app worker --loglevel=debug

Run the app:

    python -c "from app import f; f.delay()"

Error message:

    ...
    AttributeError: 'Worker' object has no attribute '_config'


### Solution

I think there should be an option to "monkeypatch" Celery to allow tasks to start sub-processes, especially if such a "feature" existed in the past. Right now, people are simply moving away to other frameworks when they encounter this problem: http://stackoverflow.com/questions/27904162/using-multiprocessing-pool-from-celery-task-raises-exception. Here is another example of this error: http://stackoverflow.com/questions/22674950/python-multiprocessing-job-to-celery-task-but-attributeerror.

This issue should be re-opened...

**Comment by martinth** [comment] 2015-08-03 13:59
I just ran into the same problem. I'm using `nltk` inside one of my workers which in turn imports `scikit-learn` which leads to the same error @ostrokach showed.

It seems that I'm able to work around this with the following code:
```
from celery.signals import worker_process_init

@worker_process_init.connect
def fix_multiprocessing(**kwargs):
    from multiprocessing import current_process
    try:
        current_process()._config
    except AttributeError:
        current_process()._config = {'semprefix': '/mp'}
```

This obviously is a very crude hack and I don't know what would happen if I would really use multiprocessing (heck I don't even know what `semprefix` is) but it is enough to make `scikit-learn` work again. 

I'm leaving this here for other people who stumble over the same problem until this issue is fixed.

**Comment by thedrow** [comment] 2015-08-03 15:43
Could this be some kind of incompatibility with billiard on Python 3? Or is it reproducible on Python 2 as well?

**Comment by gilinson** [comment] 2015-08-04 14:00
Is the original issue of celery processes not being able to create subprocesses still an Issue? Looking back through the comments, it was was fixed with e6bb0f744e97bd9acc560788a1b6152bc9ba48c3 for version 3.3. However a later commit (c7eedbd0ee1498e76d4fa1affac5b1a275660ee7) reintroduced a very similar assert statement into the start method for 3.4. No issue for me since I am on 3.3, but just wanted to point it out if it could create problems in the future.

**Comment by ostrokach** [comment] 2015-08-04 17:18
@martinth Thanks, this hack works for me too!

**Comment by machinefixer** [comment] 2015-09-05 08:53
@xiaods Thank you! Your solution works for me! Thanks!

**Comment by Templarrr** [comment] 2015-09-24 15:27
@gilinson  it's still an issue and export PYTHONOPTIMIZE=1 still "kinda fixes" it. 
Just ran into the same problem, trying to run ansible playbook in Celery task

**Comment by cmdelatorre** [comment] 2015-11-30 21:05
@martinth Thanks for the hack! I'm running into the same issue with:
 * celery==3.1.18
 * scikit-learn==0.17

**Comment by SwedishBotMafia** [comment] 2016-02-11 22:18
@martinth's hack doesn't work for me, ran into this trying to use multiprocessing to speed up some computation. Used the threading module instead and it seems to relieve this error for me while still breaking up my processing.

**Comment by razzius** [comment] 2016-04-09 00:27
Using the thread-based [multiprocessing.dummy[(https://docs.python.org/3.5/library/multiprocessing.html#module-multiprocessing.dummy) worked in celery for me:

`from multiprocessing.dummy import Pool`

**Comment by fyb3r** [comment] 2016-04-29 23:08
This error is still occurring in python 2.7.5 as well. I'm not sure if it is intended to ever address it, but this makes using saltstack's salt-ssh un-usable with celery.

**Comment by ask** [comment] 2016-06-23 23:34
Closing this, as we don't have the resources to complete this task.

**Closed by ask** 2016-06-23 23:34 UTC
Labels: Issue Type: Bug, Priority: Critical, Severity: Critical, Status: Has Testcase, Status: Needs Verification

**Comment by orzel** [comment] 2016-06-26 11:20
Possible "solution"

I had such a task that was trying to create threads and this would fail. I managed to have it working by : forking to a bash script that itself forks to a python interpreter that does the same exact code (and hence could create threads, which was critical for my use case).

**Comment by orzel** [comment] 2016-06-26 11:22
I dont understand why the ticket is closed. If you dont have resource for that, you might make a comment about this, but this doesn't close the ticket. You're just hiding the bug doing so.

**Comment by Templarrr** [comment] 2016-06-26 12:49
@orzel +1.
Priority: Critical
Severity: Critical
Closing this, as we don't have the resources to complete this task.

That is a joke. If you don't have resources now - then don't fix it now. Fix it when you will have resources. Closing the ticket will not remove the problem

**Comment by thedrow** [comment] 2016-06-26 17:44
@orzel @Templarrr I labeled this ticket as Critical so @ask is not to blame here.
You might be unhappy about this, but protesting won't help.
We need to groom our backlog based on what's actionable and what isn't and currently this isn't.
It's a tough call to make but someone has to make it.
If this issue is in your way, try to fix it. I promise that if the fix is correct and has the appropriate tests I'll merge it.

**Comment by orzel** [comment] 2016-06-28 07:49
@thedrow 
You misunderstood. Twice.
Our concern is not that you dont have the resource (this is perfectly understandable, and, sadly, a very common case in free software). Our concern is that the ticket is closed because of that, this is not how tickets work.
We are not 'unhappy', we are shocked.

**Comment by martinth** [comment] 2016-06-28 09:16
I also completely disagree with closing this. 

 I think we can all agree that this _is_ indeed a bug. And while it's indeed sad that there are not enough resources closing a _definite_ bug won't help this. You can't possibly know if maybe tomorrow someone comes a long and thinks "lets fix some bugs in Celery" just to look through the open issues and thinks "Well, there isn't any interesting work to do here...let's work on _OtherProject_ instead". 
Additionally, closing this issue will make it harder to find it. I don't know how you use Github, but when I discover a potential problem I first search the issue tracker for open issue. Commonly there is a lot of discussion and more the never there is also a workaround (like in this case) I can use for now. Only if I get _really_ desperate I start looking through the closed issues.

This is not "backlog grooming" it's number tweaking. If I look at things to use I _do_ look at the open issue count but I also always look at the star count (which is pretty high for celery). I understand that is desirable to have a low bug count for public appeal but also for your own sake. Honestly, I understand that seeing "250 open issues" is not a nice number and sounds overwhelming.

If you don't have the manpower to work on this in the next month (or even year) *this is fine*. Just don't close. A close should only happen if the issue is either done or it's *absolutely clear* that it will _never_ be done. Both are not the case here.

Just remove the "Critical" flags and add a "Postponed" flag for anything that can't handled now but should be handled if the resource *are* available.

**Comment by ask** [comment] 2016-06-28 09:47
I'm not sure we can actually fix the issue.  We cannot change how unix works but we could submit a patch upstream to lift the restriction? 

Maybe there are platform specific solutions in Linux, but that would have to be researched.  It's been open for 2 years without anyone having the incentive to fix it, so it's unlikely to be fixed in the near feature.

I closed 200+ issues and marked well over 30k emails as read, so some of them are bound to be contentious, and we may have to reopen these.  I completely expect that, but then it would be nice if we could also contribute to a solution,  e.g. by helping to document the defect if that is the only known option.

We are swamped with work, trying to operate a huge project with no resources.  We are unable to triage issues or to find out what issues have been fixed already.

**Comment by martinth** [comment] 2016-06-28 10:14
Well..okay. But could the fact that "You can't use multiprocessing if you write code for a celery worker" at least be documented? I mean...there will always be people who don't read it but at least you can point towards it and say "See, it's documented. We can't change it. Deal with it."

**Comment by ask** [comment] 2016-06-28 11:11
My todo list is gigantic, you can edit the documentation directly on github now so it's really easy to contribute changes like these :(

I don't do this to hide issues, I'm doing this to whip people into action precisely because I want to see it improved.

**Comment by abhisheksachan** [comment] 2016-08-03 11:18
@ask Can we apply multiprocessing inside task using celery in django ?
Is there any alternative to do so ?

**Comment by cmdelatorre** [comment] 2016-08-03 13:39
@abhisheksachan you should read all this issue before posting such a question

**Comment by wkschwartz** [comment] 2016-08-03 18:17
@abhisheksachan I haven't tried this in a couple of years, but I had gotten it working using https://pypi.python.org/pypi/billiard because it allows daemonization of subprocesses.

**Comment by ask** [comment] 2016-08-04 00:31
Yeah, you have to replace imports from 'multiprocessing' with 'billiard', for example:

```py
from multiprocessing import Process
```

->

```
from billiard import Process
```

There's no way for us to disable the multiprocessing limitation, but we argue there shouldn't be a limitation anyway so our multiprocessing fork allows it.

**Comment by sebastroy** [comment] 2016-10-04 21:59
For anyone, who like me, invested in developing a queueing system _BEFORE_ finding out about that limitation and needs a different workaround until they can migrate to a more useable rabbitMQ python wrapper, I managed to work around the issue by calling an external subprocess that can fork itself cleanly. That forked process is now outside the celery sandbox and things work as it should.

In the OP example, replace:

    app = Celery(__name__, broker='amqp://192.168.33.40') 
    @app.task
    def f():
        manager = multiprocessing.Manager()

with:

    app = Celery(__name__, broker='amqp://192.168.33.40')
    @app.task
    def f():
        process = subprocess.Popen(["program"]) # or the newer post 3.5 run version
        process.wait()
        # analyze exit code

and the "program" will look like (under POSIX unix/linux platform)

    import os

    def main():
          manager = multiprocessing.Manager()

    # this is equivalent to "(cmd )&" under bash
    pid = os.fork()
    if pid == 0:
        cpid = os.fork()
        if cpid == 0:
            main()
        else:
            exit(0)
    else:
        os.wait(pid)

Bear in mind that CPU managment escapes the scope of celery which kinda goes against the idea of using celery, but given you were going to use multiprocessing, you probably want to handle CPU usage outside from celery anyway.

At the very least that limitation should be documented. I looked around in the doc and couldn't find.

**Comment by thedrow** [comment] 2016-10-05 06:50
Again, feel free to submit a pull request with the documentation changes.

**Comment by miraculixx** [comment] 2016-11-19 12:21
following up on @martinth's [commen]t(https://github.com/celery/celery/issues/1709#issuecomment-127246663), on Python 3.5.2, Celery 4.0.0 and billiard 3.5.0 his solution did not work, as multiprocessing checks on the process being daemonized and stops it from starting a child. 

I was able to lift the restriction by resetting the worker's daemon flag. I'm pretty sure that's a bad idea, but it allows starting multiprocessing.Pools from within a celery task.

```
@worker_process_init.connect
def fix_multiprocessing(**kwargs):
    # don't be a daemon, so we can create new subprocesses
    from multiprocessing import current_process
    current_process().daemon = False
```

That said, IMHO Celery should add a documented option to configure whether it starts workers as deamons. Note I'm using celery in a k8 pod so celery is started as a foreground process using `celery worker`, and I really don't ~~need~~ want daemonized workers.

**Comment by thedrow** [comment] 2016-11-20 10:10
@miraculixx The problem with this suggestion is that we'll have more fail modes to handle and more issues to address. We'd rather avoid those.

**Comment by dimrozakis** [comment] 2017-02-12 14:03
Though using multiprocessing fails in combination with the prefork pool, it seems to work when using the solo pool. So I guess a workaround would be to spawn multiple celery workers with the solo pool, instead of one with multiple children in prefork pool. Does this sound legit? Of course that way some options such as max-mem-per-child won't work.

**Comment by rapliandras** [comment] 2017-03-16 12:08
I think this is basically an application design issue. It's a special pain facing `daemonic processes are not allowed to have children`, because you know, you reached a point when you have to redesign the whole application. But it's an OS level limitation, you can't circumvent it without serious side effects.  Daemonic processes also can't have children in C. This is not Python-specific stuff. There used to be a debate about thread vs process performance, and as conclusion turned out that none of them is significantly better or worse than the other. 

I suggest two options (and talking in general, not about celery here)

* Use `subprocess.Popen` to spawn an independent process, which can have children
* Is it really neccessary for the threads to be spawned by a forked process and not your main process?

**Comment by sebastroy** [comment] 2017-03-16 12:34
For what it's worth, my use case back then was that I wanted to launch a long running subprocess that would often crash quickly because of non-trivial (and non security sensitve) input issues. So the idea was to at least make sure the process launched successfully.

It turned out in the long term to be a poor design for various reasons so the new architecture naturally reverted to the "natural" use of async celery workers. So I agree with the idea of questioning if forking is really necessary; the task _is_ the fork.

**Comment by miraculixx** [comment] 2017-03-16 22:40
for what it's worth, my use case was to launch scikit-learn processes which uses multiprocessing (through joblib). I have since developed a celery backend to joblib which means scikit-learn launches parallel processes using celery and my above hack is no longer required. This is in a POC stage, not ready for prime-time just yet.

**Comment by pgeez** [comment] 2017-05-02 22:52
@miraculixx Do you have this hosted somewhere? I'd like to take a look and/or try it out. I'm running into the same issue as you -- sklearn spawning subprocesses -- and I have basically given up on Celery.

**Comment by jennaliu** [comment] 2017-05-03 01:21
@pgeez If you don't care about using subprocesses in sklearn, you can set the environment JOBLIB_MULTIPROCESSING=0

**Comment by pgeez** [comment] 2017-05-03 01:34
@jennaliu thanks for the thought, but like @miraculixx, I need multiprocessing enabled.

**Comment by pirate** [comment] 2017-05-04 00:39
Have you guys tried the old [Unix double-fork trick](http://code.activestate.com/recipes/66012-fork-a-daemon-process-on-unix/) to disown children from celery's daemon process?  @pgeez @miraculixx @sebastroy

**Comment by sebastroy** [comment] 2017-05-04 01:15
Did you read the title of this thread?!?!?

**Comment by pirate** [comment] 2017-05-04 01:19
@sebastroy obviously, I've been following this thread for years.  I just discovered the *double* fork though,  but I now see my confusion was thinking that daemon forks were being *killed* by celery, not being that they were being prevented outright.

**Comment by sebastroy** [comment] 2017-05-04 01:24
Gotcha. Yeah in my previous life I was using C so this was like bread and butter.

The workaround I am using is subprocess.Popen which works fine but then you need to reimplement some logic (and make a shell version of the program) that is what celery should be doing in the first place. But I fixed it by changing the behavior of the top level API implementation. It is more aligned with celery's purpose I think. Simplify some logic too that the low level.

**Comment by HeartUnchange** [comment] 2017-08-25 01:48
Fortunately，I find this issue when I am trying to run ansible playbook in Celery task. 
The method provided by @martinth  has not worked for me. I print the `current_process()._config` and get 
` {'authkey': b"y&e\x8d'\xcb\xd4\r\xd2\x86\x06\xe7\x9e\x14\xaf \xbc\xc4\x95\xa5G\xec&[i\x19\xf3G-\x06\xac\x19", 'semprefix': '/mp', 'daemon': True}` .
Then I reassign field `daemon` to `False`, and it works.

But I confused why use pool implemented with `gevent` and `eventlet` will `PENDING`, `solo` and `prefork` not. `prefork` cannot get right result, but `solo` works.Is there some magic?

Is there some solutions or other implementetion to allow running multiprocess in task?

**Comment by VisionUnchange** [comment] 2017-09-13 06:48
@HeartUnchange :  recently we are hard working on a big data project, that we wish to use celery as the distributed component. and wish your guide ,we are so lucky to solve the problem. see the task configuration:
```
     @app.task
    def handleBigZipfile(filename,nid):
    current_process()._config['daemon'] = False
    logger.info('{} begin handle!'.format(filename))
    handleAll(filename,nid)
     logger.info('{} is done!'.format(filename))
```
   The solution is ok! we begin the project at 2017.1 and now the prototype is finished! nine months have passed!  I own my thanks to you !  and my thanks is beyond expression! 
     would you please describe more about how you figure out the problem!  we are eager to know that !

**Comment by induser** [comment] 2017-09-29 04:05
Hi ,

I have a pretty standard set-up: Django + Rabbitmq + celery-4.0.2 + python-2.7 + centOS-7

I am trying to spawn a process using standard python multiprocessing module in celery.

Daemon processes are not allowed to create child processes and, as a result, tasks that use multiprocessing package are not working:
Command used to run : celery worker -B -A celery_task -l debug
Traceback Logs:
```

[2017-09-26 23:27:08,838: WARNING/PoolWorker-2] ERROR
[2017-09-26 23:27:08,839: WARNING/PoolWorker-2] Traceback (most recent call last):
[2017-09-26 23:27:08,839: WARNING/PoolWorker-2] File "/home/induser/config.py", line 612, in main
[2017-09-26 23:27:08,840: WARNING/PoolWorker-2] mylog_process = mp.Process(target=test_logger_process, args=(myqueue,))
[2017-09-26 23:27:08,840: WARNING/PoolWorker-2] File "/usr/lib64/python2.7/multiprocessing/process.py", line 98, in __init__
[2017-09-26 23:27:08,841: WARNING/PoolWorker-2] self._authkey = _current_process._authkey
[2017-09-26 23:27:08,841: WARNING/PoolWorker-2] AttributeError: 'Process' object has no attribute '_authkey'
```
What could be the reason for not spawning the process?
Here is the code:

```
import multiprocessing as mp
from celery.schedules import crontab
from celery.decorators import periodic_task

@periodic_task(run_every=crontab(minute='*/1'), name='test_process_celery')
def main():
data = config_read()
try:
    myqueue = mp.Queue(-1)
    mylog_process = mp.Process(target=test_logger_process, args=(myqueue,))
    mylog_process.start()
    . . .
    . . .
except Exception as e:
    raise
finally:
    mylog_process.join()
```

Thanks you.

**Comment by auvipy** [comment] 2017-12-19 15:18
try master and report if it's still the issue

**Comment by Kurara** [comment] 2018-03-13 11:14
It still has the error. I tried to use a subprocess with:

```
from multiprocessing import Process, Value
import ctypes

[...]
        result = Value('i', 0)
        text = Value(ctypes.c_char_p, fail_string.encode())
        p = Process(target=reader.find_text_async, args=(result, text, ))
        p.start()
        p.join(5)

        if p.is_alive():
            logging.WARNING("Manual terminating the process 'find_text_async'")
            p.terminate()
```

but with celery **master branch** it sais:

> File "/usr/lib/python3.5/multiprocessing/process.py", line 103, in start
>     'daemonic processes are not allowed to have children'
> AssertionError: daemonic processes are not allowed to have children

So this will be always imposible for us to do? I really need to stop that function if it takes too much u.u

I think i'm going to try with @martinth hack. I hope it doesn't creates problems.
