### ISSUE TITLE
Celery restarting for no reason

### ISSUE THREAD

**Issue by kaldown** [celery/celery#6502] opened 2020-11-25 18:40 UTC
```
systemd[1]: celery.service start operation timed out. Terminating.
celery[9700]: worker: Warm shutdown (MainProcess)
systemd[1]: Failed to start Celery Service.
systemd[1]: Unit celery.service entered failed state.
systemd[1]: celery.service failed.
systemd[1]: celery.service holdoff time over, scheduling restart.
systemd[1]: Starting Celery Service...
celery[9731]: -------------- celery@ip***.ec2.internal v5.0.2 (singularity)
celery[9731]: --- ***** -----
celery[9731]: -- ******* ---- Linux-4.14.192-147.314.amzn2.x86_64-x86_64-with-glibc2.2.5 2020-11-25 18:33:15
celery[9731]: - *** --- * ---
celery[9731]: - ** ---------- [config]
celery[9731]: - ** ---------- .> app:         ***
celery[9731]: - ** ---------- .> transport:   sqs://:**@localhost//
celery[9731]: - ** ---------- .> results:     disabled://
celery[9731]: - *** --- * --- .> concurrency: 1 (prefork)
celery[9731]: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
celery[9731]: --- ***** -----
celery[9731]: -------------- [queues]
celery[9731]: .> celery           exchange=celery(direct) key=celery
celery[9731]: [tasks]
celery[9731]: . check_for_new_podcasts
celery[9731]: . generate_update_push_notifications
celery[9731]: . send_level_up_push_notifcation
celery[9731]: . send_update_push_notifcation
celery[9731]: . test_celery
celery[9731]: [2020-11-25 18:33:15,976: INFO/MainProcess] Connected to sqs://:**@localhost//
celery[9731]: [2020-11-25 18:33:16,090: INFO/MainProcess] celery@ip.ec2.internal ready.
```

There is no much information, it just happened.

```
[Unit]
Description=Celery Service
After=network.target

[Service]
Type=forking
User=ec2-user
Group=ec2-user
WorkingDirectory=/var/app/current
ExecStart=/var/app/venv/stage/bin/celery -A campus.tasks.celery worker --loglevel=INFO
EnvironmentFile=/opt/elasticbeanstalk/deployment/env
Restart=always

[Install]
WantedBy=multi-user.target
```

Systemd example from here https://docs.celeryproject.org/en/stable/userguide/daemonizing.html?highlight=systemd#service-file-celery-service

`systemctl restart celery` hangs until failed, but! `systemctl status celery` is in START state, but again. Restarts every time

celery --version
5.0.2 (singularity)

**Comment by thedrow** [comment] 2020-11-29 16:29
I am sorry but I can't help you debug this without a way to reproduce the issue.
You must provide a minimally reproducible test case.

I'm closing this issue for now. If you can reproduce this with a sample project, please let us know and we'll reopen.

**Comment by kaldown** [comment] 2020-11-29 17:07
That's the exact reason.
How could I understand what's the problem with celery, if it continues restarting giving no output?

I've recently found a problem.
During the investigation, I've found this particular instance can't connect to the SQS.
Giving more permissions solves that problem and Celery begin to work correctly.

BUT! There was no output about the problem.
How could I know next time something bad happens, Celery wouldn't be silent about that?
What to do to take more information?

`--loglevel=DEBUG` is not the answer.

**Comment by thedrow** [comment] 2020-11-30 13:12
You can open an issue about that with a reproducible test case.
We'll take a look.

**Comment by kaldown** [comment] 2020-11-30 13:17
Lets clarify, you do want me to open up and Easter with a question "how to debug celery"?

Who is the test case of what?

**Comment by thedrow** [comment] 2020-11-30 15:12
> During the investigation, I've found this particular instance can't connect to the SQS.
> Giving more permissions solves that problem and Celery begin to work correctly.
> 
> BUT! There was no output about the problem.
We shouldn't fail silently. If you can reproduce this failure and prove that the process exits, we may be able to provide a fix for it.

**Comment by kaldown** [comment] 2020-11-30 16:41
> We shouldn't fail silently. 
But you are.
This is an example of a repeated filing. Exactly this pice of output repeating each second consuming 50% of CPU.
Can you see anything in log? Me either.

What's the matter with "reproducing" the failure, it is happening.
Okay:
1) create elastic beanstalk instance with no permission to access `ListQueue` with any task context whatsoever.
2) use example of Systemd Unit from above.
3) `systemctl start celery`
4) `journalctl -u celery -f`
5) watch this output repeatedly
```
systemd[1]: celery.service start operation timed out. Terminating.
celery[9700]: worker: Warm shutdown (MainProcess)
systemd[1]: Failed to start Celery Service.
systemd[1]: Unit celery.service entered failed state.
systemd[1]: celery.service failed.
systemd[1]: celery.service holdoff time over, scheduling restart.
systemd[1]: Starting Celery Service...
celery[9731]: -------------- celery@ip***.ec2.internal v5.0.2 (singularity)
celery[9731]: --- ***** -----
celery[9731]: -- ******* ---- Linux-4.14.192-147.314.amzn2.x86_64-x86_64-with-glibc2.2.5 2020-11-25 18:33:15
celery[9731]: - *** --- * ---
celery[9731]: - ** ---------- [config]
celery[9731]: - ** ---------- .> app:         ***
celery[9731]: - ** ---------- .> transport:   sqs://:**@localhost//
celery[9731]: - ** ---------- .> results:     disabled://
celery[9731]: - *** --- * --- .> concurrency: 1 (prefork)
celery[9731]: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
celery[9731]: --- ***** -----
celery[9731]: -------------- [queues]
celery[9731]: .> celery           exchange=celery(direct) key=celery
celery[9731]: [tasks]
celery[9731]: . check_for_new_podcasts
celery[9731]: . generate_update_push_notifications
celery[9731]: . send_level_up_push_notifcation
celery[9731]: . send_update_push_notifcation
celery[9731]: . test_celery
celery[9731]: [2020-11-25 18:33:15,976: INFO/MainProcess] Connected to sqs://:**@localhost//
celery[9731]: [2020-11-25 18:33:16,090: INFO/MainProcess] celery@ip.ec2.internal ready.
```

**Comment by 3krishna** [comment] 2021-01-06 04:20
using periodic_task then error is come to solve this error please anyone
from celery.task.schedules import crontab
ModuleNotFoundError: No module named 'celery.task'

**Comment by thedrow** [comment] 2021-01-06 14:17
> using periodic_task then error is come to solve this error please anyone
> from celery.task.schedules import crontab
> ModuleNotFoundError: No module named 'celery.task'

@3krishna This is very offtopic. It's rude to comment on unrelated issues asking for help.
Please next time refer to the mailing list.

Please refer to the [release notes ](https://docs.celeryproject.org/en/stable/whatsnew-5.0.html#removed-deprecated-modules) of Celery 5 and make sure to read it, along with the rest of the documentation.
You can and should search the issues list since this was raised before.

**Comment by pcastro93** [comment] 2023-07-25 03:30
@thedrow this is expected when using systemd with the `Restart=always` configuration:
```
systemd[1]: celery.service failed.
systemd[1]: celery.service holdoff time over, scheduling restart.
```
More info: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=


It is not an issue with celery but the expected behaviour of systemd.

**Comment by pcastro93** [comment] 2023-07-25 15:01
@auvipy That's right. It is not an issue with celery nor systemd but the expected behaviour.

**Closed** 2023-07-26 04:42 UTC
Labels: Status: Not a Bug, Component: Amazon SQS Broker, Category: Deployment
