### ISSUE TITLE
celery process is hanged and not restarting

### ISSUE THREAD

**Issue by ssatturi** [celery/celery#2181] opened 2014-08-05 02:40 UTC
Hi All,

i am using celery 3.1.2(ciaper) with kombu 3.0.21. WHen I tried to restart celery as it was in hung state, it printed below output in log, later it stopped responding, Can anyone please advice how to start celery without killing it.

[2014-08-04 22:48:53,979: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/python/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/python/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/python/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/python/lib/python2.7/site-packages/kombu/async/hub.py", line 267, in create_loop
    tick_callback()
  File "/usr/local/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 940, in on_poll_start
    [add_reader(fd, on_readable, fd) for fd in cycle.fds]
  File "/usr/local/python/lib/python2.7/site-packages/kombu/async/hub.py", line 201, in add_reader
    return self.add(fds, callback, READ | ERR, args)
  File "/usr/local/python/lib/python2.7/site-packages/kombu/async/hub.py", line 152, in add
    self.poller.register(fd, flags)
  File "/usr/local/python/lib/python2.7/site-packages/kombu/utils/eventio.py", line 78, in register
    self._epoll.register(fd, events)
IOError: [Errno 9] Bad file descriptor
[2014-08-04 22:48:53,997: WARNING/MainProcess] Restoring 45 unacknowledged message(s).

Srikanth

**Comment by thedrow** [comment] 2015-06-19 10:26
This appears to be a duplicate of #1845.
I'm going to close this now since there hasn't been any feedback from @ssatturi for a very long time.

**Closed by thedrow** 2015-06-19 10:26 UTC
Labels: feedback-needed, Worker Hangs
