### ISSUE TITLE
docs.celeryproject.org and celeryproject.org are down

### ISSUE THREAD

**Issue by colons** [celery/celery#7351] opened 2022-03-14 14:26 UTC
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- celery/celeryproject#50
- celery/celeryproject#47

# Description

The Celery website (celeryproject.org) and the Celery documentation website (docs.celeryproject.org) no longer seem to have A DNS records. I've checked this by running `dig celeryproject a` and `dig docs.celeryproject.org a` on computers with internet connections in various places in the world, and nowhere seems able to load the website any more.

# Suggestions

I'm not sure. Has the domain ownership lapsed, or is there just an issue with your DNS provider?

**Comment by justin-f-perez** [comment] 2022-03-14 16:25
I am experiencing the same problem using Google DNS
```bash
❯ nslookup celeryproject.org 8.8.8.8
❯ nslookup docs.celeryproject.org 8.8.8.8
❯ nslookup docs.celeryproject.org 8.8.4.4
❯ nslookup celeryproject.org 8.8.4.4
```

All give the same error:
```
** server can't find celeryproject.org: SERVFAIL
```

**Comment by clokep** [comment] 2022-03-14 16:29
Maybe see celery/celeryproject#21 also?

**Comment by woodruffw** [comment] 2022-03-14 16:43
I can't reproduce this:

```console
dig +short docs.celeryproject.org
readthedocs.io.
104.17.33.82
104.17.32.82
```

**Comment by clokep** [comment] 2022-03-14 16:46
I'm able to reproduce on non-Google DNS. Getting a `SERVFAIL`  also.

**Comment by CodePint** [comment] 2022-03-14 17:37
+1 also down for me

failing with:
```bash
$ nslookup celeryproject.org 9.9.9.9   # Quad9DNS
$ nslookup celeryproject.org 208.67.222.222 # OpenDNS
$ nslookup celeryproject.org 8.8.8.8  # GoogleDNS

** server can't find celeryproject.org: SERVFAIL

$ dig +short docs.celeryproject.org
# empty
```

**Comment by CodePint** [comment] 2022-03-14 17:43
+1 also down for me

failing with nslookup and dig:
```bash
nslookup celeryproject.org 9.9.9.9   # Quad9DNS
nslookup celeryproject.org 208.67.222.222 # OpenDNS
nslookup celeryproject.org 8.8.8.8  # GoogleDNS
# ** server can't find celeryproject.org: SERVFAIL

dig docs.celeryproject.org 
# QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
```

**Comment by CodePint** [comment] 2022-03-14 20:58
If anyone needs access to the docs in a pinch...
There is a version of the celery 5 docs archived on [wayback machine](https://web.archive.org/web/20210615214611/https://docs.celeryproject.org/en/stable/history/whatsnew-5.0.html#upgrading-from-celery-4-x).

**Comment by thedrow** [comment] 2022-03-15 13:45
As far as I can see, I can't register the domain name myself so it's not expired.

**Comment by thedrow** [comment] 2022-03-15 16:50
WHOIS doesn't reveal the owner of the domain.
Should we register a different domain address?

**Comment by LordNoteworthy** [comment] 2022-03-16 01:26
I am using the latest snapshot captured from web archive: https://web.archive.org/web/20220313093531/https://docs.celeryproject.org/en/stable/

**Comment by auvipy** [comment] 2022-03-16 06:03
> WHOIS doesn't reveal the owner of the domain. Should we register a different domain address?

I am seriously considering registering a new domain and start working on github page based website, later can deploy it to some VPS, I can do it. It's a long overdue

**Comment by levrik** [comment] 2022-03-16 10:15
It seems quite crazy that the owner of the domain seems to be completely unknown to maintainers...

**Comment by thedrow** [comment] 2022-03-16 12:13
Unfortunately, there wasn't a proper hand-off when @ask left the project.

**Comment by ThiefMaster** [comment] 2022-03-16 15:16
You should really consider getting the original domains back before they fully expire (and thus can be grabbed by someone else) - otherwise there's a good chance they'll be abused for spam or worse.

**Comment by robmello** [comment] 2022-03-17 13:32
For anyone here who needs Celery doc while this gets worked out:

https://docs.celeryq.dev/en/stable/

**Comment by mrmonkington** [comment] 2022-03-17 15:48
Does controlling the celeryproject.org domain give control of any email addresses that could be used to recover passwords on e.g. Github or PyPI?

**Comment by mastacheata** [comment] 2022-03-17 16:40
> Does controlling the celeryproject.org domain give control of any email addresses that could be used to recover passwords on e.g. Github or PyPI?

The public email on the github profile of @ask is [ask@celeryproject.org](mailto:ask@celeryproject.org), so at least someone could impersonate her. Whether or not her github account would be at risk is impossible to tell.

PyPi doesn't disclose any emails connected to the user accounts. She is still listed as a maintainer over there, but the main contact email is that of auvipy.

**Comment by shaggyloris** [comment] 2022-03-18 14:50
It seems that the DNS for docs.celeryproject.org may have been compromised or at least the site shouldn't be trusted at this point? The DNS is now resolving to a Russian hosting company and the certificate is for a different domain:

DNS response:
```
dig @8.8.8.8 +short docs.celeryproject.org
45.130.41.26
```
Whois info:
```
inetnum:        45.130.41.0 - 45.130.41.255
netname:        BEGET-NET-89
country:        RU
admin-c:        DUMY-RIPE
tech-c:         DUMY-RIPE
status:         ASSIGNED PA
mnt-by:         BEGET-MNT
created:        2019-10-10T10:18:07Z
last-modified:  2019-10-10T10:18:07Z
```

Cert info:
```
Issuer: C=US, O=Let's Encrypt, CN=R3
Validity
    Not Before: Feb 22 10:30:38 2022 GMT
    Not After : May 23 10:30:37 2022 GMT
Subject: CN=4rdcom.com
```

**Comment by infinitewarp** [comment] 2022-03-18 22:19
From my end, it also looks like the hosting company has dropped the site. 😕 

![Screen Shot 2022-03-18 at 6 14 34 PM 6 16 29 PM](https://user-images.githubusercontent.com/1472326/159091937-9970e744-1c34-486b-bc25-b81bb5bb6dfd.png)

**Comment by auvipy** [comment] 2022-03-19 05:14
he is not active anymore from late 2016, so we bought some new domains, and using https://docs.celeryq.dev/en/stable/.

**Closed by auvipy** 2022-03-19 05:14 UTC
Labels: Issue Type: Bug Report, Category: Documentation

**Comment by coderanger** [comment] 2022-03-19 05:18
@auvipy I don't think that's a great long term plan, leaving broken links is bad but worse is if they potentially go somewhere hostile now. I can get in contact with Ask if that's the limiting factor.

**Comment by auvipy** [comment] 2022-03-19 05:21
US is Hostile to many, so embrace it. you can try, as I am trying for last 6 years. good luck with that.

**Comment by coderanger** [comment] 2022-03-19 05:22
Not sure how that's related? I'm not talking about politically hostile, I mean like infosec hostile.

**Comment by auvipy** [comment] 2022-03-19 05:30
OK, but good luck mate.
