### ISSUE TITLE
Celery is hitting some recursive condition that triggers "maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by k1p0d** [celery/celery#3825] opened 2017-02-10 23:55 UTC
## Checklist

- [x] Verified that this issue persist on the master version(4.0.2)

## Symptom
What i'm trying to achieve is have celery logging be sent to a slack channel. I'm trying to do so using the handler from _slacker_log_handler_. But what i expereince is celery triggering a recursion loophole that eventually kills the whole process. here is the code to reproduce: 

    from celery.signals import after_setup_logger
    from slacker_log_handler import SlackerLogHandler

    def initialize_slack_logger(logger=None, loglevel=None,
                               logfile=None, format=None,
                               colorize=None, **kwargs):
        # Create slack handler
        slack_handler = SlackerLogHandler(slack_token, slack_channel)

        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        # Add the handler to logger
        slack_handler.setFormatter(formatter)
        slack_handler.setLevel(logging.DEBUG)
        logger.addHandler(slack_handler)

    after_setup_logger.connect(initialize_slack_logger)`

The output result is as following:

  

> [2017-02-10 23:33:25,682: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
> [2017-02-10 23:33:25,686: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,687: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,688: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,689: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,690: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,691: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,693: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,694: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,695: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,696: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,697: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,698: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,699: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,700: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,701: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,702: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,703: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,704: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,705: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,706: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,707: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,709: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,710: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,711: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,712: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,713: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,714: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,715: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,716: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,717: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,718: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,719: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,720: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,721: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,722: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,723: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,724: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,727: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,728: INFO/MainProcess] Starting new HTTPS connection (1): slack.com
> [2017-02-10 23:33:25,731: CRITICAL/MainProcess] Unrecoverable error: RuntimeError('maximum recursion depth exceeded in cmp',)
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/celery/worker/worker.py", line 203, in start
>     self.blueprint.start(self)
>   File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 119, in start
>     step.start(parent)
>   File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 370, in start
>     return self.obj.start()
>   File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer/consumer.py", line 318, in start
>     blueprint.start(self)
>   File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 119, in start
>     step.start(parent)
>   File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer/connection.py", line 22, in start
>     info('Connected to %s', c.connection.as_uri())
>   File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
>     self._log(INFO, msg, args, **kwargs)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
>     self.handle(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
>     self.callHandlers(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
>     hdlr.handle(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
>     self.emit(record)
>   File "/usr/local/lib/python2.7/dist-packages/slacker_log_handler/__init__.py", line 62, in emit
>     attachments=attachments,
>   File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 287, in post_message
>     'icon_emoji': icon_emoji
>   File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 71, in post
>     return self._request(requests.post, api, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 57, in _request
>     **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
>     timeout=timeout
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 583, in urlopen
>     conn = self._get_conn(timeout=pool_timeout)
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 257, in _get_conn
>     return conn or self._new_conn()
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 805, in _new_conn
>     self.num_connections, self.host)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
>     self._log(INFO, msg, args, **kwargs)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
>     self.handle(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
>     self.callHandlers(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
>     hdlr.handle(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
>     self.emit(record)
>   File "/usr/local/lib/python2.7/dist-packages/slacker_log_handler/__init__.py", line 62, in emit
>     attachments=attachments,
>   File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 287, in post_message
>     'icon_emoji': icon_emoji
>   File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 71, in post
>     return self._request(requests.post, api, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 57, in _request
>     **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
>     timeout=timeout
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 583, in urlopen
>     conn = self._get_conn(timeout=pool_timeout)
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 257, in _get_conn
>     return conn or self._new_conn()
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 805, in _new_conn
>     self.num_connections, self.host)
> ....
> ....
> ....
> 
>    self.num_connections, self.host)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
>     self._log(INFO, msg, args, **kwargs)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
>     self.handle(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
>     self.callHandlers(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
>     hdlr.handle(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
>     self.emit(record)
>   File "/usr/local/lib/python2.7/dist-packages/slacker_log_handler/__init__.py", line 62, in emit
>     attachments=attachments,
>   File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 287, in post_message
>     'icon_emoji': icon_emoji
>   File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 71, in post
>     return self._request(requests.post, api, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/slacker/__init__.py", line 57, in _request
>     **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 55, in request
>     with sessions.Session() as session:
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 346, in __init__
>     self.mount('https://', HTTPAdapter())
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 123, in __init__
>     self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 159, in init_poolmanager
>     block=block, strict=True, **pool_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/poolmanager.py", line 121, in __init__
>     dispose_func=lambda p: p.close())
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/_collections.py", line 47, in __init__
>     self._container = self.ContainerCls()
>   File "/usr/lib/python2.7/collections.py", line 52, in __init__
>     self.__update(*args, **kwds)
>   File "/usr/lib/python2.7/abc.py", line 151, in __subclasscheck__
>     if subclass in cls._abc_cache:
>   File "/usr/lib/python2.7/_weakrefset.py", line 75, in __contains__
>     return wr in self.data
> **RuntimeError: maximum recursion depth exceeded in cmp**

I suspect it has to do something with the recursion at - 

>   File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 119, in start
>     step.start(parent)
>   File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 370, in start
>     return self.obj.start()

Since its the only recursion i see around this stack-trace. it belongs to a class called _Blueprint_

**Comment by georgepsarakis** [comment] 2017-02-14 20:53
This does not seem like a Celery issue, but I think it is caused by the logging configuration.

If you check the requests library, it emits a [debug-level message](https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/connectionpool.py#L817) for new connections, which you are seeing multiple times displayed.

I think that what happens is this:

1. Log Record emitted
2. Post to Slack
3. Initialize HTTPS connection from Requests package
4. Emit debug-level message for the new connection 
5. Log record from Requests must be sent to Slack
6. New HTTPS connection
7. New Log record
8. ...
9. Maximum recursion

I believe if you simply increase the log level to `INFO`, your code will run. Does this sound logical?

**Comment by georgepsarakis** [comment] 2017-02-25 16:37
@k1p0d can this issue be closed?

**Comment by k1p0d** [comment] 2017-02-25 19:54
I haven't tested the offered solution. I just figured I don't wanna risk
the whole process in a case slack logging would fail. and so I ended up
writing the log to a file and then reading it from another process to slack.

So we can close this from my perspective.

**Comment by georgepsarakis** [comment] 2017-03-19 20:00
@k1p0d thanks, closing for now.

**Closed by georgepsarakis** 2017-03-19 20:00 UTC
