### ISSUE TITLE
redis.exceptions.InvalidResponse: Protocol Error: b'3b'

### ISSUE THREAD

**Issue by lx-rookie** [celery/celery#6344] opened 2020-09-09 09:14 UTC
我在使用cerely4.4.7+redis3.5.3的时候，单独一个线程进行测试使用.get()能正常取到返回值，

**Comment by lx-rookie** [comment] 2020-09-09 09:15
然而在进行并发测试的时候，会出现如下报错：
Traceback (most recent call last):
  File "C:\Users\lx\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\lx\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:/工作/celery_redis/celery_excemple/CeleryTask/test_main.py", line 43, in a
    a = r.get()
  File "C:\Users\lx\anaconda3\lib\site-packages\celery\result.py", line 237, in get
    on_message=on_message,
  File "C:\Users\lx\anaconda3\lib\site-packages\celery\backends\asynchronous.py", line 200, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File "C:\Users\lx\anaconda3\lib\site-packages\celery\backends\asynchronous.py", line 268, in _wait_for_pending
    on_interval=on_interval):
  File "C:\Users\lx\anaconda3\lib\site-packages\celery\backends\asynchronous.py", line 55, in drain_events_until
    yield self.wait_for(p, wait, timeout=interval)
  File "C:\Users\lx\anaconda3\lib\site-packages\celery\backends\asynchronous.py", line 64, in wait_for
    wait(timeout=timeout)
  File "C:\Users\lx\anaconda3\lib\site-packages\celery\backends\redis.py", line 160, in drain_events
    message = self._pubsub.get_message(timeout=timeout)
  File "C:\Users\lx\anaconda3\lib\site-packages\redis\client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "C:\Users\lx\anaconda3\lib\site-packages\redis\client.py", line 3505, in parse_response
    response = self._execute(conn, conn.read_response)
  File "C:\Users\lx\anaconda3\lib\site-packages\redis\client.py", line 3479, in _execute
    return command(*args, **kwargs)
  File "C:\Users\lx\anaconda3\lib\site-packages\redis\connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "C:\Users\lx\anaconda3\lib\site-packages\redis\connection.py", line 331, in read_response
    raise InvalidResponse("Protocol Error: %r" % raw)
redis.exceptions.InvalidResponse: Protocol Error: b'3b'



请问这个是什么原因导致的

**Comment by HosseyNJF** [comment] 2020-09-09 09:50
Possible duplicate of #6335

**Comment by thedrow** [comment] 2020-09-10 10:47
Yes, it is.

**Closed by thedrow** 2020-09-10 10:47 UTC
Labels: Issue Type: Bug Report
