### ISSUE TITLE
Error on terminating Pool: AttributeError("'error' object has no attribute 'errno'",)

### ISSUE THREAD

**Issue by AvnerCohen** [celery/celery#4513] opened 2018-01-30 14:35 UTC
We are seeing the above mentioned error.
Coming from: 
https://github.com/celery/celery/blob/master/celery/concurrency/asynpool.py#L182

A quick test on this test in the REPL reproduces this error:

```py
Python 2.7.13 (default, Apr  4 2017, 08:46:44)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import select
>>> select.error
<class 'select.error'>
>>> moshe = select.error()
>>> moshe.errorno
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'error' object has no attribute 'errorno'
```

With the *socket* class however, this works just fine:
```py
>>> import socket
>>> socket.error
<class 'socket.error'>
>>> moshe = socket.error()
>>> moshe.errno
```

Given that this code is in place since 2013, maybe I am doing something wrong here?

**Comment by AvnerCohen** [comment] 2018-02-18 14:44
@ask Anything I can help to resolve this?
Will a patch to remove `select.error` make sense?

**Comment by thedrow** [comment] 2018-02-18 16:09
What you are experiencing doesn't make sense. On Python 2.7.x [select.error()](https://docs.python.org/2/library/select.html#select.error) has an `errno` attribute available. On Python>=3.3 [select.error](https://docs.python.org/3/library/select.html#select.error) is aliased to [OSError](https://docs.python.org/3/library/exceptions.html#OSError.errno) which also has `errno` attribute.

Notice the typo you made. You called `error.errorno` instead of `error.errno`. The `errno` attribute should be available and it is indeed the one used by the code.

The fact that you guys are getting this error makes me suspect some sort of monkeypatching is involved. It may or may not be gevent but [latest master](https://github.com/gevent/gevent/blob/master/src/gevent/select.py#L42) aliases `gevent.select.error` to `select.error` so there should be no difference.

Further investigation on your part is needed to figure out who is at fault. Check the type of the 'error' object.

**Comment by AvnerCohen** [comment] 2018-02-19 09:52
See this fix please:
https://github.com/pexpect/pexpect/pull/38

Full description of the fix is this comment:
https://github.com/pexpect/pexpect/pull/38#issuecomment-34127762

You can see this behavior in the Apple python compilation, no custom changes or any monkey patching:

```py
Python 2.7.13 (default, Apr  4 2017, 08:46:44)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import select
>>> moshe = select.error(99, "Some Error")
>>> moshe.args[0]
99
>>> moshe.errno
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'error' object has no attribute 'errno'
```

Indeed, I don't see this behavior in python 3.
You can see this exact behavior on this online pyton REPL:
https://www.tutorialspoint.com/execute_python_online.php

**Comment by thedrow** [comment] 2018-02-19 11:49
This is either a documentation bug in Python 2 or an actual bug since the documentation explicitly specifies that the `errno` attribute exists on `select.error`.

I can confirm that this problem reproduces itself in Python 2.7.14 on Linux as well.

**Comment by thedrow** [comment] 2018-02-19 11:55
Right this should be fixed. I'll see if anything else is needed to workaround this problem.

**Closed** 2018-02-19 11:54 UTC
Labels: Issue Type: Bug, Status: Has Testcase ✔

**Comment by AvnerCohen** [comment] 2018-02-19 13:14
Thanks!! 👍
