### ISSUE TITLE
Release version 4.2.0

### ISSUE THREAD

**Issue by georgepsarakis** [celery/celery#4387] opened 2017-11-14 19:21 UTC
I think that it would be a good idea to release a new version that includes all bug fixes so far. @thedrow @auvipy thoughts?

I can help with the changelog.

**Comment by auvipy** [comment] 2017-11-15 04:49
I am always in favor of releasing smaller bug fixe release as early as possible. I prefer django style release

**Comment by thedrow** [comment] 2017-11-16 10:48
There is at least one new feature in master https://github.com/celery/celery/commit/0d5b840af1890a9a499a339aa3256445b43837dc
We'll need to cherry-pick all the bug fixes.

**Comment by thedrow** [comment] 2017-11-16 10:48
I really want to release a new version with https://github.com/celery/celery/pull/4358 but it needs test coverage.

**Comment by georgepsarakis** [comment] 2017-11-17 06:47
@thedrow I would suggest that we avoid the complexity of a release branch. Let's simply go to the next minor version (4.2.0), in order to be compliant with semantic versioning. What do you think?

**Comment by thedrow** [comment] 2017-11-17 07:21
Yeh let's do that.

**Comment by auvipy** [comment] 2017-11-18 13:12
considering the low resource and time we have, that should be the best fit

**Comment by Fokko** [comment] 2017-11-29 13:54
Any estimate when 4.2 will be released?

**Comment by johnarnold** [comment] 2017-12-11 19:22
Any updates on 4.2?  The time / timezone / eta bugfixes seem critical...

**Comment by thedrow** [comment] 2017-12-12 09:52
There is one PR that we have to merge which causes memory leaks when using the Redis results backend.
Check [the milestone ](https://github.com/celery/celery/milestone/19) is a for progress. We're almost there.

**Comment by thedrow** [comment] 2017-12-14 08:18
FYI, I'm getting married at the 28th of December so I don't think we'll be able to release before that.
I'd like us to get a release out the door by the 7th of January.
@georgepsarakis @auvipy Please prepare a rolling PR with the release notes for pyamqp, kombu, and celery before that.

**Comment by thedrow** [comment] 2017-12-14 08:28
@Fokko @johnarnold If you'd like to help we still have [4 pull requests which require test coverage](
https://github.com/celery/celery/pulls?q=is%3Apr+is%3Aopen+label%3A%22Status%3A+Needs+Test+Coverage+%E2%9C%98%22+milestone%3Av4.2) and/or rebasing before we release 4.2.

**Comment by AlexHill** [comment] 2017-12-14 08:40
I've just added #4369 to the 4.2 milestone as I think I'll be able to get to it in the next week or so.

**Comment by Skeen** [comment] 2018-01-08 10:52
Milestone 4.2 is passed it's due date and several issues are still open (33/98 issues are still open (33%)).
I'm new to the project and therefore have a question regarding this.

Usually projects utilize one of two models, with regards to milestones, either:
1. Push the due date until all milestone issues have been resolved, or
2. To release whatever is ready on the due date, and trim the rest?

What is the Celery approach to milestones?

**Comment by thedrow** [comment] 2018-01-12 05:31
The only blocker to the release currently is https://github.com/celery/celery/issues/4423 because we added a new feature which needs documentation.
@georgepsarakis Can you start working on the release notes please?

**Comment by georgepsarakis** [comment] 2018-01-12 21:06
@thedrow I will try to start it shortly.

**Comment by auvipy** [comment] 2018-01-13 12:33
i have updated the milestone issues

**Comment by georgepsarakis** [comment] 2018-01-14 13:35
@auvipy @thedrow if possible, let's please freeze the merging of Pull Requests. What do you think?

**Comment by auvipy** [comment] 2018-01-14 14:10
yes no more pr atm.

**Comment by auvipy** [comment] 2018-01-14 16:29
https://github.com/celery/celery/pull/4481 one last merge. and locked

**Comment by thedrow** [comment] 2018-01-16 10:54
We should finish #4423 before the release but it doean't apply to the release notes.

**Comment by rsyring** [comment] 2018-01-27 14:26
Would love to see this get released soon.  I just spent time trying to figure out why automatic retries weren't working (#4341).

**Comment by georgepsarakis** [comment] 2018-01-28 06:54
Reportedly there is an issue with `master` after (probably) merging [this PR](https://github.com/celery/celery/pull/4381):
- https://github.com/celery/celery/issues/4498
- https://github.com/celery/celery/issues/4041

**Comment by thedrow** [comment] 2018-01-28 13:15
Where do you see the reports regarding master?

**Comment by georgepsarakis** [comment] 2018-01-28 16:20
In #4498 :

> **Expected behavior** 
On the master branch it doesn't work at all. You get this:

And in #4041 https://github.com/celery/celery/issues/4041#issuecomment-359845025

**Comment by pachewise** [comment] 2018-01-28 19:00
@georgepsarakis that error happens when the method is called from the Class object, instead of an instance... my guess is this issue happens when `apply_async` is called on unbound Tasks (haven't confirmed it yet).

**Comment by thedrow** [comment] 2018-01-31 06:45
Is anyone addressing the release blockers?

**Comment by thedrow** [comment] 2018-02-06 06:59
What's the status of the blockers?

**Comment by auvipy** [comment] 2018-02-06 10:18
one docs update and one bug report which could be fixed after 4.2 release as 4.2.1 IMHO

**Comment by thedrow** [comment] 2018-02-06 11:24
I'm not going to release a regression into the wild. Maybe we should revert the offending change and re-create the PR?

**Comment by auvipy** [comment] 2018-02-06 14:26
this is actually very old issue https://github.com/celery/celery/issues/3723 plz check

**Comment by thedrow** [comment] 2018-02-06 15:32
I was talking about #4198 and #4041 that @georgepsarakis mentioned.
If I'm wrong, this is not a blocker and we need to close issues as duplicates.

**Comment by auvipy** [comment] 2018-02-06 16:34
yes this are not blocker

**Comment by mikegrima** [comment] 2018-02-06 20:26
It looks like I spoke too soon on #4041.  Should we try running the latest master to see if the issues are fully resolved?

**Comment by thedrow** [comment] 2018-02-06 20:28
Please do.

**Comment by mikegrima** [comment] 2018-02-06 22:31
It appears to still be broken for cron tasks.

**Comment by VictorLeP** [comment] 2018-02-07 10:54
Issue https://github.com/celery/celery/issues/3808 is also still broken for me on master.

**Comment by brabiega** [comment] 2018-02-07 13:45
I'd bet that fix for #3723 would be quite small if someone with celery internals knowledge could take a look. It's easy to reproduce. 

Unfortunately I didn't dig enough on my own...

**Comment by xeor** [comment] 2018-02-21 19:48
#3808 have a `5.0` milestone.. Same with #3723

The only one that is left before release if we follow the milestone (https://github.com/celery/celery/milestone/19) is #4423

Are the milestones incorrect?

**Comment by auvipy** [comment] 2018-02-22 04:17
I updated the milestone

**Comment by johnarnold** [comment] 2018-02-27 19:17
@auvipy @georgepsarakis @thedrow @ask 

#4041 is making no progress and blocking release of a ton of other fixes.  If this is a pre-existing bug and not a regression, can we get a release of what is already done?

**Comment by dwrpayne** [comment] 2018-03-04 07:35
Trying to get more visibility on the last 4.2 blocker: I think #4041 is a duplicate of #4184 as they have the same symptoms and workaround. What's the decision process around that?

**Comment by thedrow** [comment] 2018-03-04 11:34
@johnarnold There's one regression we need to fix or revert https://github.com/celery/celery/issues/4041#issuecomment-359875276 and another issue that is yet unclear if it is caused by Celery 4.2.
We need to fix the regression first and see if we can still reproduce the issue on Celery 4.2.

**Comment by browniebroke** [comment] 2018-03-08 14:39
Given how big this release has become, would it make sense to make an alpha/beta pre-release fairly soon? I think that would enable some users to do more real-world testing? I'd be happy to put an alpha release on our test systems!

On the other hand, I appreciate it represents work for the maintainers, so feel free to say no 😄

**Comment by thedrow** [comment] 2018-03-09 05:25
I think we'll start with a beta release, yes.

**Comment by auvipy** [comment] 2018-03-09 05:40
that will be great

**Comment by georgepsarakis** [comment] 2018-03-13 06:00
@thedrow @auvipy let me know if you want me to resume efforts on the Changelog. I agree that a release should take place as soon as possible.

**Comment by auvipy** [comment] 2018-03-13 06:06
yes plz resume the work on changelog

**Comment by georgepsarakis** [comment] 2018-03-13 06:51
@auvipy @thedrow I will submit a Pull Request today probably.

**Comment by georgepsarakis** [comment] 2018-03-22 06:24
@thedrow is there anything pending for the release? If you need any help, let me know.

**Comment by thedrow** [comment] 2018-03-22 09:06
No there isn't. I will release today.

**Comment by sfdye** [comment] 2018-03-23 01:13
Please make a release. That would make my week.

**Comment by thedrow** [comment] 2018-03-23 07:43
Wrote the release announcement yesterday. I'm going to tag today.

**Comment by thedrow** [comment] 2018-03-23 12:25
Turns out we lack proper documentation for the Redis Sentinel results backend.
This is not a blocker for the release since we're going to release an RC first but let's open an issue about it and fix it before GA.

**Comment by thedrow** [comment] 2018-03-23 13:18
I just released 3.1.26 containing https://github.com/celery/celery/pull/4357.
This fix is crucial for people to migrate to Celery 4.x so I created a special 3.x release just for it.

**Comment by auvipy** [comment] 2018-03-23 13:36
awesome

**Comment by thedrow** [comment] 2018-03-23 15:42
First RC was released.
I'll create issues for documentation blockers later, possibly tomorrow.

**Comment by auvipy** [comment] 2018-03-23 16:30
you might forgot about pyamqp and kombu releases?

**Comment by thedrow** [comment] 2018-03-24 09:22
I haven't. I just didn't have time to get to it. I need to prepare the release notes for them as well.

**Comment by auvipy** [comment] 2018-03-24 09:35
oh sorry. thanks for the rc

**Comment by thedrow** [comment] 2018-03-25 17:03
Turns out we have a compatibility issue with flower because we released an RC. See https://github.com/mher/flower/issues/791
It's a very easy fix. Any volunteers?

**Comment by pachewise** [comment] 2018-03-25 20:29
gave it a try: https://github.com/mher/flower/pull/792; let me know what you guys think

**Comment by thedrow** [comment] 2018-04-02 08:47
I just released Celery 4.2.0RC2.

**Comment by auvipy** [comment] 2018-04-02 11:39
thanks! can we expect the other dependencies new release if you could manage time of course

**Comment by thedrow** [comment] 2018-04-02 13:33
If someone makes the release notes I can release them.

**Comment by johnarnold** [comment] 2018-04-09 21:17
@thedrow Can we get a final release?

**Comment by sfdye** [comment] 2018-04-10 02:14
Yes new version please!

**Comment by TheBuky** [comment] 2018-04-10 15:36
Hi, thank for the new version. 

I install it: `pip install celery==4.2.0RC2`
I run it => `celery@mountain v4.2.0rc2`

But the Scheduler always send old tasks who was removed from the periodic tasks entries.

**Comment by thedrow** [comment] 2018-04-16 11:52
It seems that #3812 can be reproduced with https://github.com/celery/celery/issues/3812#issuecomment-381554599.
We're going to fix that before GA if that's really the case.

**Comment by thedrow** [comment] 2018-04-29 06:31
I've released our last RC. If no problems are found we'll release the GA soon.
The only thing that is really missing now are the release process document and #4679.

**Comment by auvipy** [comment] 2018-04-29 07:01
I will be able to complete those after getting the release docs

**Comment by georgepsarakis** [comment] 2018-05-15 04:32
Hello @xirdneh . There are many ways you can contribute:
- Kombu changelog for 4.2 has not been constructed yet I think: https://github.com/celery/kombu/issues/849
- Celery changelog may not be finalized too
- We have a required, pending documentation change: https://github.com/celery/celery/issues/4721
- Stable release also depends on the resolution of https://github.com/celery/celery/issues/4731
- Beta test the RC3 version (e.g. on your staging environment) if you have the capacity and time to do so.

Let me know if you need more pointers and help, thank you!

**Comment by xirdneh** [comment] 2018-05-15 16:25
Awesome,
I'll see what I can do for #4731 and documentation.
Thanks.

**Comment by thedrow** [comment] 2018-05-21 09:54
I have released 4.1.1 and I urge everyone to upgrade.
@auvipy Please issue a blog post about this.

**Comment by auvipy** [comment] 2018-05-21 11:49
OK sure

**Comment by xirdneh** [comment] 2018-05-21 17:15
Is it possible to get permissions on the IRC Freenode #celery channel to change the topic?
Some people are confused about the versioning and I can keep that updated.
My IRC handle is `josuebc`
Thanks.

**Comment by auvipy** [comment] 2018-05-21 17:29
can we release another RC?

**Comment by thedrow** [comment] 2018-05-22 05:36
@xirdneh I'll have to ping @ask about it.
Can you open a new issue?
@auvipy Yes, of course.

**Comment by thedrow** [comment] 2018-05-22 06:28
I just released Celery 4.2.0RC4.
We still need to resolve #4731 and #4721.

**Comment by xirdneh** [comment] 2018-05-24 18:27
https://github.com/celery/celery/pull/4762 fixes #4731

**Comment by thedrow** [comment] 2018-05-27 12:10
New blocker #4768 :(

**Comment by thedrow** [comment] 2018-05-27 13:28
I just released amqp 2.3.0.
Please test it and let us know if there are any problems.

**Comment by georgepsarakis** [comment] 2018-05-28 05:03
@thedrow also possible blocker https://github.com/celery/celery/pull/4770#issuecomment-392419237

**Comment by thedrow** [comment] 2018-05-28 06:45
Looks like one.
Shame we caught it so late.
Any volunteers to fix this? I'll release a Bugfix version.

**Comment by thedrow** [comment] 2018-05-28 13:34
I released the fix in amqp 2.3.1.

**Comment by auvipy** [comment] 2018-05-29 16:47
plz look into it @xirdneh

**Comment by xirdneh** [comment] 2018-06-02 16:39
Might be a blocker: https://github.com/celery/celery/issues/4791
I can probably finish writing the tests on Monday.

**Comment by thedrow** [comment] 2018-06-10 13:16
I merged out last PR.
As far as I'm concerned master is now frozen.

I am going to complete the release notes and release today.

**Comment by xirdneh** [comment] 2018-06-10 15:52
Awesome!
:metal:

**Comment by thedrow** [comment] 2018-06-10 18:31
Released.
There are a few things left to do:
We need to issue an announcement on our website and ensure that the documentation website updates to version 4.2.0.

Thank you very much for your time and effort everyone.
This has been a huge release with a lot of complex issues to resolve and we stood up to the challenge.
Awesome work!

**Comment by auvipy** [comment] 2018-06-13 19:29
I have issued a blog post. can we close this?

**Comment by thedrow** [comment] 2018-06-15 17:46
Yes.

**Closed by thedrow** 2018-06-15 17:46 UTC
Labels: Category: Project Governance
