### ISSUE TITLE
worker documentation for --queues doesn't match behaviour

### ISSUE THREAD

**Issue by acdha** [celery/celery#2318] opened 2014-10-15 22:06 UTC
The docs for `celery worker` currently state:

```
.. cmdoption:: -Q, --queues
List of queues to enable for this worker, separated by comma.
By default all configured queues are enabled.
Example: `-Q video,image`
```

This implies that queues which are not listed will not be enabled. In practice, workers will accept tasks from every configured queue no matter what value --queues has unless you use the `--exclude-queues` option.

Is this behaviour intentional? If so I can submit a pull request for the documentation.

**Comment by thedrow** [comment] 2015-06-19 11:04
This also works for me.
I'm gonna close this but if you have a way to reproduce it with the latest version of Celery please comment.

**Comment by alanhamlett** [comment] 2015-07-07 21:29
Same problem here. The docs are unclear on the `-Q` argument.

The [docs on Queues](http://celery.readthedocs.org/en/latest/userguide/workers.html#queues) sound like the `-Q` argument will limit the queues for the current worker to only those listed on the command line. They should specifically say the `-Q` command does not limit the queues, but appends to `CELERY_QUEUES`.

**Comment by thedrow** [comment] 2015-07-08 05:55
You are right. Pull requests are welcome. :)

**Comment by alanhamlett** [comment] 2015-07-09 00:20
I'll look into the source code and tests to make sure I know the correct behavior of the `-Q` and `-X` args, then I'll submit a pull request.

**Comment by thedrow** [comment] 2015-07-09 05:52
Wonderful :)

**Comment by ask** [comment] 2016-06-23 23:56
Closing this, as we don't have the resources to complete this task.

**Closed by ask** 2016-06-23 23:56 UTC
Labels: Issue Type: Documentation
