### ISSUE TITLE
SQS Broker using EC2 Instance Profile auth instead of django conf

### ISSUE THREAD

**Issue by pztrick** [celery/celery#2487] opened 2015-02-06 05:01 UTC
I recently migrated an app from an Ansible deployment on EC2 to an ElasticBeanstalk deployment.

I had been passing in the AWS SQS IAM user credentials using env vars `AWS_BROKER_USER` and `AWS_BROKER_PASSWORD`. This worked fine before EB. I would create a new IAM user for each Celery queue/environment.

`AWS_SQS_BROKER = 'sqs://%s:%s@' % (AWS_BROKER_USER, AWS_BROKER_PASSWORD)`

Unfortunately, ElasticBeanstalk adds an Instance Profile with an IAM Role. Attempting to connect to the settings-defined `AWS_SQS_BROKER` will raise an error because Celery/Kombu/Boto attempts to use the built-in instance profile's IAM role for authentication instead of the credentials defined in `AWS_SQS_BROKER`.... which results in a failed authentication when the IAM Role is trying to access a different IAM User's SQS queue.

Is there any way to trap this error and warn users that their Instance Profile IAM Role mismatches the target AWS SQS broker URL?  Or anyway to continue using the credentials baked into the URL instead of the instance profile?

**Comment by thedrow** [comment] 2015-07-11 09:14
Sorry for such a delayed response. To be honest I'm not sure. I haven't looked into the SQS broker internals yet.

**Comment by hankjin** [comment] 2015-09-12 19:43
The instance profile role is only used by the ELB instance to record the deploy process etc, it is unlikely to have this account information in your service.

The problem may be caused by special characters in password, like '/' which usually appear in IAM user secret access key. The below snippet will resolve that problem:
```
AWS_SQS_BROKER = 'sqs://%s:%s@' % (
    urllib.quote(AWS_BROKER_USER, safe=''),
    urllib.quote(AWS_BROKER_PASSWORD, safe='')
    )
```

**Comment by hankjin** [comment] 2015-09-13 06:29
I just tried in elastic beanstalk, you are right, it will get the ec2-role if the access-key is not specified, I created a patch in kombu and hope it may help:
https://github.com/celery/kombu/pull/512

**Comment by pztrick** [comment] 2015-09-14 03:11
Thanks for the kombu patch @hankjin. I do remember spending a lot of time troubleshooting this error and which IAM key was actually being used.

**Comment by ask** [comment] 2015-12-11 00:53
Kombu patch was merged!

**Closed by ask** 2015-12-11 00:53 UTC
Labels: Category: Deployment, Component: Amazon SQS Broker
