### ISSUE TITLE
Celery workers silently fail when using MySQL Galera cluster for result backend on desync.

### ISSUE THREAD

**Issue by tomasz-kuzemko** [celery/celery#2656] opened 2015-06-15 09:03 UTC
Galera has a "feature" that during problems with synchronization of the cluster it returns error 1047 `Unknown command` in response to every client command. In case a Celery worker tries to store a result during this time, it will fail and **stop processing further tasks** until the parent process is restarted. It's hard to detect this situation because the worker's child processes are still running.

Below is a sample log file when this happened (I can provide more details if needed):
```
[2015-06-12 12:09:08,665: ERROR/Worker-86] Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2354, in do_rollback
    dbapi_connection.rollback()
OperationalError: (1047, 'Unknown command')
[2015-06-12 12:09:08,665: ERROR/Worker-87] Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2354, in do_rollback
    dbapi_connection.rollback()
OperationalError: (1047, 'Unknown command')
[2015-06-12 12:09:08,669: WARNING/Worker-87] Failed operation _store_result. Retrying 2 more times.
```

**Comment by thedrow** [comment] 2015-06-16 20:41
I'm not familiar with Galera unfortunately and I'm not sure if SQLAlchemy supports it.
Are you suggesting that we need to catch OperationalErrors raised from SQLAlchemy or do you have any other fix in mind?
If possible I'd like to see what the system is doing.
If the problem happens often you might want to try to debug why the process is freezing with [sysdig](http://www.sysdig.org/) or alternatively running it in debug mode and setting a breakpoint at sqlalchemy/dialects/mysql/base.py line 2354.
I don't think I can do anything to reproduce this easily though.

**Comment by tomasz-kuzemko** [comment] 2015-06-16 21:42
An optimal solution would be to make the worker's child processes die on such exceptions so the parent can restart them. I will have a closer look at this soon.

**Comment by thedrow** [comment] 2015-06-17 05:51
The problem is that this solution is very specific. We can't die on all OperationalErrors.

**Comment by tomasz-kuzemko** [comment] 2015-06-17 08:28
The biggest problem is that the child worker stops processing tasks and does not die so the parent cannot restart it. In what case is this a desired outcome?

**Comment by thedrow** [comment] 2015-06-17 08:34
The child process should not stop processing tasks.
If the process does not die that's a good thing because that means we can debug what's going on.
strace or sysdig it and upload the file with the output to somewhere.

**Comment by thedrow** [comment] 2015-06-19 08:09
@tomasz-kuzemko SIGUSR1 will give you the traceback of the running celery process. This can also be used to debug stuck workers.

**Comment by tomasz-kuzemko** [comment] 2015-07-07 10:15
My team-mate managed to recreate this bug in a repeatable fashion.

When Galera is desynchronized, the main process gets this in logs when trying to store result:
```
[2015-07-07 09:04:06,390: INFO/MainProcess] Received task: test.fail[6fa3552e-a898-45fa-95d1-19997ed64e70] 
[2015-07-07 09:04:06,391: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fcbc6a28578> (args:(u'test.fail', u'6fa3552e-a898-45fa-95d1-19997ed64e70', [], {}, {u'utc': True, u'is_eager': False, u'chord': None, u'group': None, u'args': [], u'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'celery', u'exchange': u'celery'}, u'expires': None, u'hostname': 'celery@test.host.net:test', u'task': u'test.fail', u'callbacks': None, u'correlation_id': u'6fa3552e-a898-45fa-95d1-19997ed64e70', u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'reply_to': u'60ea6aa7-a236-3904-960a-b72757a2f916', u'id': u'6fa3552e-a898-45fa-95d1-19997ed64e70', u'headers': {}}) kwargs:{}) 
[2015-07-07 09:04:09,830: DEBUG/MainProcess] Task accepted: test.fail[6fa3552e-a898-45fa-95d1-19997ed64e70] pid:27554 
[2015-07-07 09:04:19,028: ERROR/Worker-2] Exception during reset or similar 
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy 
    fairy._reset(pool) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 701, in _reset 
    pool._dialect.do_rollback(self) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2354, in do_rollback 
    dbapi_connection.rollback() 
OperationalError: (1047, 'Unknown command') 
[2015-07-07 09:04:19,042: WARNING/Worker-2] Failed operation _store_result. Retrying 2 more times. 
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/database/__init__.py", line 63, in _inner 
    return fun(*args, **kwargs) 
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/database/__init__.py", line 130, in _store_result 
    return result 
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__ 
    self.gen.throw(type, value, traceback) 
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/database/__init__.py", line 49, in session_cleanup 
    session.rollback() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 740, in rollback 
    self.transaction.rollback() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 403, in rollback 
    transaction._rollback_impl() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 431, in _rollback_impl 
    t[1].rollback(] 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1322, in rollback 
    self._do_rollback() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1360, in _do_rollback 
    self.connection._rollback_impl() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 509, in _rollback_impl 
    self._handle_dbapi_exception(e, None, None, None, None) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1152, in _handle_dbapi_exception 
    self._autorollback() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 614, in _autorollback 
    self._rollback_impl() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 509, in _rollback_impl 
    self._handle_dbapi_exception(e, None, None, None, None) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1093, in _handle_dbapi_exception 
    exc_info 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause 
    reraise(type(exception), exception, tb=exc_tb) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 507, in _rollback_impl 
    self.engine.dialect.do_rollback(self.connection) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2354, in do_rollback 
    dbapi_connection.rollback() 
OperationalError: (OperationalError) (1047, 'Unknown command') None None 
[2015-07-07 09:04:19,049: INFO/Worker-2] /usr/local/lib/python2.7/dist-packages/celery/app/trace.py:364: RuntimeWarning: Exception raised outside body: OperationalError(1047, 'Unknown command'): 
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 235, in trace_task 
    request=task_request, 
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 248, in store_result 
    request=request, **kwargs) 
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/database/__init__.py", line 63, in _inner 
    return fun(*args, **kwargs) 
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/database/__init__.py", line 120, in _store_result 
    task = list(session.query(Task).filter(Task.task_id == task_id)) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2438, in __iter__ 
    return self._execute_and_instances(context) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2451, in _execute_and_instances 
    close_with_result=True) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2442, in _connection_from_session 
    **kw) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 854, in connection 
    close_with_result=close_with_result) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 858, in _connection_for_bind 
    return self.transaction._connection_for_bind(engine) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 322, in _connection_for_bind 
    conn = bind.contextual_connect() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1798, in contextual_connect 
    self.pool.connect(), 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 338, in connect 
    return _ConnectionFairy._checkout(self) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 644, in _checkout 
    fairy = _ConnectionRecord.checkout(pool) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 440, in checkout 
    rec = pool._do_get() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1057, in _do_get 
    return self._create_connection() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 285, in _create_connection 
    return _ConnectionRecord(self) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 416, in __init__ 
    exec_once(self.connection, self) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/attr.py", line 250, in exec_once 
    self(*args, **kw) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/attr.py", line 260, in __call__ 
    fn(*args, **kw) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 157, in on_connect 
    do_on_connect(conn) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2302, in connect 
    self.set_isolation_level(conn, self.isolation_level) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2320, in set_isolation_level 
    cursor.execute("COMMIT") 
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute 
    self.errorhandler(self, exc, value) 
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler 
    raise errorclass, errorvalue 
OperationalError: (1047, 'Unknown command') 

  exc, exc_info.traceback))) 
[2015-07-07 09:04:19,060: CRITICAL/MainProcess] Task test.fail[6fa3552e-a898-45fa-95d1-19997ed64e70] INTERNAL ERROR: OperationalError(1047, 'Unknown command') 
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 235, in trace_task 
    request=task_request, 
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 248, in store_result 
    request=request, **kwargs) 
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/database/__init__.py", line 63, in _inner 
    return fun(*args, **kwargs) 
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/database/__init__.py", line 120, in _store_result 
    task = list(session.query(Task).filter(Task.task_id == task_id)) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2438, in __iter__ 
    return self._execute_and_instances(context) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2451, in _execute_and_instances 
    close_with_result=True) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2442, in _connection_from_session 
    **kw) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 854, in connection 
    close_with_result=close_with_result) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 858, in _connection_for_bind 
    return self.transaction._connection_for_bind(engine) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 322, in _connection_for_bind 
    conn = bind.contextual_connect() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1798, in contextual_connect 
    self.pool.connect(), 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 338, in connect 
    return _ConnectionFairy._checkout(self) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 644, in _checkout 
    fairy = _ConnectionRecord.checkout(pool) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 440, in checkout 
    rec = pool._do_get() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1057, in _do_get 
    return self._create_connection() 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 285, in _create_connection 
    return _ConnectionRecord(self) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 416, in __init__ 
    exec_once(self.connection, self) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/attr.py", line 250, in exec_once 
    self(*args, **kw) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/attr.py", line 260, in __call__ 
    fn(*args, **kw) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 157, in on_connect 
    do_on_connect(conn) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2302, in connect 
    self.set_isolation_level(conn, self.isolation_level) 
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2320, in set_isolation_level 
    cursor.execute("COMMIT") 
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute 
    self.errorhandler(self, exc, value) 
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler 
    raise errorclass, errorvalue 
OperationalError: (1047, 'Unknown command') 
```

Sending SIGUSR1 to the parent process does not make it log anything to the log files. After sending SIGUSR1 to the child process we get this:
```
[2015-07-07 09:05:08,051: ERROR/Worker-2] Pool process <Worker(Worker-2, started daemon)> error: SoftTimeLimitExceeded() 
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 291, in run 
    sys.exit(self.workloop(pid=pid)) 
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 352, in workloop 
    req = wait_for_job() 
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 443, in receive 
    ready, req = _receive(1.0) 
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 415, in _recv 
    return True, loads(get_payload()) 
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 231, in soft_timeout_sighandler 
    raise SoftTimeLimitExceeded() 
SoftTimeLimitExceeded: SoftTimeLimitExceeded() 
[2015-07-07 09:05:08,070: ERROR/MainProcess] Process 'Worker-2' pid:27554 exited with 'exitcode 1' 
```

**Comment by thedrow** [comment] 2015-07-07 11:33
So the hard time limit is not being hit.
Can you try to decrease the hard time limit and see if the task is being released?
This is a workaround but it might be a viable one.

**Comment by klaudiuszmrosek** [comment] 2015-07-09 07:05
Hi, I'm a part of the @tomasz-kuzemko team.
After decrease the hard time limit to 20 seconds, the task isn't being released.
After sending SIGUSR1 to the child process after time expired, we get again SoftTimeLimitExceeded.

**Comment by thedrow** [comment] 2015-07-09 09:29
I'll need to reproduce this somehow.
Can you please instruct me how to set up an environment like the one you have using docker/vagrant and simulate desynchronization in Galera?

**Comment by klaudiuszmrosek** [comment] 2015-07-09 10:55
I have 3 database hosts with Ubuntu 14.04 Server. On this hosts is created galera cluster(with MySQL database).
I find a video where is creating galera cluster on docker:
http://www.severalnines.com/blog/how-deploy-galera-cluster-mysql-using-docker-containers
Db hosts are blocking all traffic, except to each other and all my other hosts(i.e. celery host). I have set rules in iptables.
I have one host(celery host) on which I start celery task.

Cluster is synced and all 3 hosts are in cluster (show status like 'wsrep%';).
On each database host I'm checking in mysql: 'show processlist;' and looking for an active connection with user from celery host. This on which an active connection with celery host I don't touch iptables.
On one database host I comment rules in iptables to all cluster hosts and restart iptables (and if need be restart mysql).
Now cluster is still synced with two hosts.
I'm start running task in loop on celery host.
On second database host I comment rules in iptables to all cluster hosts and restart iptables (and if need be restart mysql).
After some time galera will be desynced and have status 'Initialized' and for now celery workers will be suspend.
When I send SIGUSR1 from celery host to celery workers I receives SoftTimeLimitExceeded.

If you need more information let me know.

**Comment by ask** [comment] 2016-06-24 00:16
Closing this, as we don't have the resources to support MySQL.

**Closed by ask** 2016-06-24 00:16 UTC
Labels: Component: SQLAlchemy, Status: Needs Testcase, Worker Hangs
