### ISSUE TITLE
Arguments fail to pass to chained members of a group

### ISSUE THREAD

**Issue by Chris7** [celery/celery#4430] opened 2017-12-09 15:52 UTC
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.3
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:rpc:///

BROKER_URL: 'amqp://guest:********@rabbit:5672//'
CELERYD_PREFETCH_MULTIPLIER: 10
CELERY_ENABLE_UTC: True
CELERY_QUEUES: [<unbound Queue high-pri -> <unbound Exchange ''(direct)> -> high-pri.#>,
 <unbound Queue low-pri -> <unbound Exchange ''(direct)> -> low-pri.#>]
CELERY_RESULT_BACKEND: 'rpc:///'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_TASK_SERIALIZER: 'json'
CELERY_TIMEZONE: None
CELERY_WORKER_DIRECT: True
Queue: <class 'kombu.entity.Queue'>
os: <module 'os' from '/usr/local/lib/python3.6/os.py'>
```
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Here is a minimal test to reproduce:
```
from celery import Celery, group
app = Celery('tasks')

@app.task
def pre():
  print('in pre')
  return 30

@app.task
def post1(arg1=None):
  print('arg1={}'.format(arg1))
  return arg1 + 1e1

@app.task
def post2(arg2=None):
  print('arg2={}'.format(arg2))
  return arg2 + 1e2

@app.task
def post3(arg3=None):
  print('arg3={}'.format(arg3))
  return arg3 + 1e3

@app.task
def post4(arg4=None):
  print('arg4={}'.format(arg4))
  return arg4 + 1e4

def wf():
  return pre.s() | group([post1.s(), post2.s() | group([post3.s(), post4.s()])])
```

Run `wf().apply_async()`

## Expected behavior

`post2` receives the arguments from `pre.s()`.

## Actual behavior

`post2` receives no arguments

**Comment by p-himik** [comment] 2017-12-29 21:21
I believe this is a duplicate of #3968

**Comment by auvipy** [comment] 2018-01-13 14:34
closing in favor of the older issue

**Closed by auvipy** 2018-01-13 14:34 UTC
