### ISSUE TITLE
Integration Test failure

### ISSUE THREAD

**Issue by auvipy** [celery/celery#5757] opened 2019-09-30 13:58 UTC
@matteius could you look into it?

**Comment by matteius** [comment] 2019-09-30 14:18
I already did help you look into it when you asked me to add the test way back when and then when I opened https://github.com/celery/celery/issues/5711 which has more detail than that ticket.  The reality is I have done a lot to get it that far and some other folks from the community need to value the test I added and try to help me understand why it doesn't work (in appveyor it has to do with windows crap) but anyway, I actually have no real time right now to contribute because I have a lot of weatherization/before-winter projects to tackle and a full time job.

**Comment by auvipy** [comment] 2019-09-30 15:15
thanks for the quick reply. I will investigate it further

**Comment by thedrow** [comment] 2019-10-02 12:51
@auvipy The issue isn't descriptive enough and if we leave it open eventually we'll forget what it's all about.
Please edit the issue's description.

**Comment by auvipy** [comment] 2019-10-02 13:16
OK

**Comment by matteius** [comment] 2019-10-02 15:52
Why not just close this ticket and update the project labels on the one I made that describes the issue?  https://github.com/celery/celery/issues/5711

**Comment by auvipy** [comment] 2019-10-02 15:56
eventually, this will be closed. currently, I am looking into all the backlogs for 4.4.0 stable release.

**Comment by matteius** [comment] 2019-10-03 04:44
@auvipy  Sounds good -- someone has to do it, and I am super busy right now.  Thanks for taking this on and sorry for being short the other day.

**Comment by thedrow** [comment] 2019-10-03 08:49
Yes, unfortunately 5.0 takes a lot of my time these days.
I'm also handling canvas failures when using the cache backend (and possibly other key value stores).

We really need to stabilize the build ASAP since another RC should be released before GA.

**Comment by auvipy** [comment] 2019-10-05 14:22
yes

**Comment by auvipy** [comment] 2019-11-11 03:38
with celery==4.4.0rc4 and kombu 4.6.6 all the old integration tests are passing except the cache one. @thedrow can you handle the cache integration test failure?

**Comment by thedrow** [comment] 2019-11-13 12:30
I'm on it but I can't figure out the reason for the failure.

**Comment by thedrow** [comment] 2019-11-18 13:06
I have a fix but I'm currently verifying it.

**Comment by auvipy** [comment] 2019-11-18 13:10
that's great!

**Comment by thedrow** [comment] 2019-11-18 13:35
The fix I have fails another integration test :(
I'm investigating.

**Comment by thedrow** [comment] 2019-11-25 15:41
The following patch fixes the test but it's the wrong fix:
```diff
diff --git a/celery/backends/cache.py b/celery/backends/cache.py
index a3e7c317d..6af89c4cd 100644
--- a/celery/backends/cache.py
+++ b/celery/backends/cache.py
@@ -137,7 +137,10 @@ class CacheBackend(KeyValueStoreBackend):
             header_result, body, **kwargs)
 
     def incr(self, key):
-        return self.client.incr(key)
+        try:
+            return self.client.incr(key)
+        except:
+            return self.client.set(key, 1)
 
     def expire(self, key, value):
         return self.client.touch(key, value)
diff --git a/celery/canvas.py b/celery/canvas.py
index 39ec3425a..315223d9d 100644
--- a/celery/canvas.py
+++ b/celery/canvas.py
@@ -1079,6 +1079,7 @@ class group(Signature):
         results = list(self._apply_tasks(tasks, producer, app, p,
                                          args=args, kwargs=kwargs, **options))
         result = self.app.GroupResult(group_id, results, ready_barrier=p)
+        result.save()
         p.finalize()
 
         # - Special case of group(A.s() | group(B.s(), C.s()))
```

We don't need to save each and every `GroupResult`. Only chord headers should be saved.
The cause of the bug is that we're calling `on_chord_part_return` for the second group since the `chord` key is present in the task's option.
https://github.com/celery/celery/blob/c8d24248ac9aa4d5b178569d10012e6e0f325239/celery/backends/base.py#L145-L151
and as a result we're trying to restore a group that was never saved.
https://github.com/celery/celery/blob/c8d24248ac9aa4d5b178569d10012e6e0f325239/celery/backends/base.py#L775-L837

This does not reproduce if the header does not contain any task other than the group.
This does not fail:
```python
chain(
            add.si(1, 0),
            group(
                chain(
                    add.si(1, 200),
                    group(
                        add.si(1, 1000),
                        add.si(1, 2000),
                    ),
                ),
            ),
            add.si(1, 10),
        )
```
and this also fails (in addition to our original test case):
```python
chain(
            add.si(1, 0),
            group(
                chain(
                    add.si(1, 200),
                    group(
                        add.si(1, 1000),
                        add.si(1, 2000),
                    ),
                ),
                add.si(1, 100),
            ),
            add.si(1, 10),
        )
```

Any idea?

**Comment by thedrow** [comment] 2019-11-25 19:41
Even with this fix (or another one I came up with) the chord's body is called twice which is not what we want.
If I somehow disable this behavior using a condition, the canvas hangs.

This is the reason I spent more than two weeks debugging this bug.

**Comment by thedrow** [comment] 2019-11-27 13:40
@celery/core-developers I'd like some assistance here since I'm stuck.

**Closed** 2019-12-01 21:55 UTC
Labels: Category: Project Governance, Category: Tests, Issue Type: Bug Report, Priority: Blocker, Severity: Blocker
