### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ju5t** [celery/celery#4544] opened 2018-02-19 14:06 UTC
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue: unable to.
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

`celery -A proj report` is sufficient for us to reproduce it.

We're on `celery==4.1.0`. I was unable to generate any output.

## Expected behavior

Normal output.

## Actual behavior

We get an endless loop

```
  File "/Users/ju5t/workspace/api/env/bin/../lib/python2.7/UserDict.py", line 36, in __getitem__
    if key in self.data:
  File "/Users/ju5t/workspace/api/env/lib/python2.7/site-packages/celery/utils/collections.py", line 130, in __getattr__
    return self[k]
```

We run the same code in a Docker container and that has no problems. I'm not sure if this is a bug in Celery or if we have done something wrong.

**Comment by thedrow** [comment] 2018-02-19 15:22
Since it works for everyone else, I'd suggest you to verify this on another computer. Try to reinstall your Python.

If this problem can be reproduced on another computer we'll need a test case that will help us debug this problem since it's very specific to your code or configuration.

I'm going to close this issue as I cannot reproduce the problem as of yet. If and when you provide us with a way to reproduce this, comment on this issue and we will reopen.

**Closed by thedrow** 2018-02-19 15:22 UTC

**Comment by ju5t** [comment] 2018-02-19 15:43
@thedrow this was 100% PEBKAC. The problem was with Sentry where we left out RAVEN_DSN for development environments and forgot that Celery was configured with it too. The container was started with a different flag which shoved the problem under the carpet. Sorry to have opened up an issue for nothing. Hopefully this explanation may be of use for someone in the future.
