### ISSUE TITLE
Celery upgrade (3.1->4.1) - Connection reset by peer

### ISSUE THREAD

**Issue by itayB** [celery/celery#4226] opened 2017-08-24 06:46 UTC
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Actual behavior
We are working with celery at the last year, with ~15 workers, each one defined with concurrency between 1-4.

Recently we upgraded our celery from v3.1 to v4.1

Now we are having the following errors in each one of the workers logs, any ideas what can cause to such error?

    2017-08-21 18:33:19,780 94794  ERROR   Control command error: error(104, 'Connection reset by peer') [file: pidbox.py, line: 46]
    Traceback (most recent call last):
      File "/srv/dy/venv/lib/python2.7/site-packages/celery/worker/pidbox.py", line 42, in on_message
        self.node.handle_message(body, message)
      File "/srv/dy/venv/lib/python2.7/site-packages/kombu/pidbox.py", line 129, in handle_message
        return self.dispatch(**body)
      File "/srv/dy/venv/lib/python2.7/site-packages/kombu/pidbox.py", line 112, in dispatch
        ticket=ticket)
      File "/srv/dy/venv/lib/python2.7/site-packages/kombu/pidbox.py", line 135, in reply
        serializer=self.mailbox.serializer)
      File "/srv/dy/venv/lib/python2.7/site-packages/kombu/pidbox.py", line 265, in _publish_reply
        **opts
      File "/srv/dy/venv/lib/python2.7/site-packages/kombu/messaging.py", line 181, in publish
        exchange_name, declare,
      File "/srv/dy/venv/lib/python2.7/site-packages/kombu/messaging.py", line 203, in _publish
        mandatory=mandatory, immediate=immediate,
      File "/srv/dy/venv/lib/python2.7/site-packages/amqp/channel.py", line 1748, in _basic_publish
        (0, exchange, routing_key, mandatory, immediate), msg
      File "/srv/dy/venv/lib/python2.7/site-packages/amqp/abstract_channel.py", line 64, in send_method
        conn.frame_writer(1, self.channel_id, sig, args, content)
      File "/srv/dy/venv/lib/python2.7/site-packages/amqp/method_framing.py", line 178, in write_frame
        write(view[:offset])
      File "/srv/dy/venv/lib/python2.7/site-packages/amqp/transport.py", line 272, in write
        self._write(s)
      File "/usr/lib64/python2.7/socket.py", line 224, in meth
        return getattr(self._sock,name)(*args)
    error: [Errno 104] Connection reset by peer

BTW: our tasks in the form:

    @app.task(name='EXAMPLE_TASK'],
              bind=True,
              base=ConnectionHolderTask)
    def example_task(self, arg1, arg2, **kwargs):
        # task code

ref to stackoverflow question: https://stackoverflow.com/questions/45803728/celery-upgrade-3-1-4-1-connection-reset-by-peer

**Comment by thedrow** [comment] 2017-09-19 12:48
The answer on StackOverflow implies that something is wrong with the broker pool under high load?
Can you please describe your usecase in greater detail?

**Comment by thedrow** [comment] 2017-11-12 16:52
@itayB Is this problem no longer relevant?

**Comment by itayB** [comment] 2017-11-12 19:55
@thedrow Hi,
I added the `broker_pool_limit = None` and those errors stopped. Sometimes individual works change their state to offline but I'm not sure it related to this original issue.

**Comment by thedrow** [comment] 2017-11-13 13:44
It seems that what you are describing is indeed a network issue.
Setting `broker_pool_limit` to `None` means that every time a connection is used it will be established and disconnected.
Workers change their state to off-line because they temporarily cannot connect to the broker.
Maintaining long running connections fails because of such networking issues.

I'm going to close this issue because it's simply too hard to debug this without further information that disproves the theory I described above. Perhaps there is a flaw in the broker connection pool but the test case you provided doesn't reproduce it.

**Comment by thedrow** [comment] 2017-12-14 06:51
@sils Please let me know if you find any additional data that will allow us to reproduce the issue.

**Comment by len-thomas** [comment] 2017-12-21 19:29
Using Redis through stunnel seems to have the same, or similar, problem.  The problem seems to happen when stunnel `TIMEOUTidle` closes the stunnel connection.  Still haven't figured out the solution to this:

```
[2017-12-21 14:15:35,105: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/redis/connection.py", line 390, in read_response
    bufflen = recv_into(self._sock, self._buffer)
  File ".../lib/python3.6/site-packages/redis/_compat.py", line 82, in recv_into
    return sock.recv_into(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/redis/client.py", line 2408, in _execute
    return command(*args)
  File ".../lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File ".../lib/python3.6/site-packages/redis/connection.py", line 403, in read_response
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/redis/connection.py", line 390, in read_response
    bufflen = recv_into(self._sock, self._buffer)
  File ".../lib/python3.6/site-packages/redis/_compat.py", line 82, in recv_into
    return sock.recv_into(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File ".../lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File ".../lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File ".../lib/python3.6/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
  File ".../lib/python3.6/site-packages/kombu/async/hub.py", line 354, in create_loop
    cb(*cbargs)
  File ".../lib/python3.6/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File ".../lib/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File ".../lib/python3.6/site-packages/kombu/transport/redis.py", line 667, in _receive
    ret.append(self._receive_one(c))
  File ".../lib/python3.6/site-packages/kombu/transport/redis.py", line 678, in _receive_one
    response = c.parse_response()
  File ".../lib/python3.6/site-packages/redis/client.py", line 2430, in parse_response
    return self._execute(connection, connection.read_response)
  File ".../lib/python3.6/site-packages/redis/client.py", line 2419, in _execute
    return command(*args)
  File ".../lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File ".../lib/python3.6/site-packages/redis/connection.py", line 403, in read_response
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
```

**Comment by AvnerCohen** [comment] 2018-01-17 16:28
We see a similar behavior. 
I suspect `broker_pool_limit = None` is a workaround to the core underline issue.
Quite clearly we have seen this coming up just after the upgrade to 4.1.

This is not related in any way to a long running process, We see this 10 seconds after running the worker.
We use rabbit as the broker, and I see this happening on redis for @len-thomas , So I assume it's something on the celery infra.

If any additional info is needed, I am happy to provide that.

My recreation steps:
1. Start worker
2. Send some message.
3. Broad cast random command via `celery inspect stats`
Repeating this 2-3 times seems to be enough to cause the error to show up.

**Comment by trianglesis** [comment] 2018-03-19 11:38
Having the same:
Connection reset by peer on web page by gjango.
Upgrade from 4.1.0 to 4.2.0.
RabbitMQ was refreshed and configured anew.

**Comment by cockcrow** [comment] 2018-04-26 10:11
Also stuck in this issue.

```
[2018-04-26 16:48:21,230: DEBUG/MainProcess] | Consumer: Restarting event loop...
[2018-04-26 16:48:21,230: DEBUG/MainProcess] | Consumer: Restarting Control...
[2018-04-26 16:48:21,230: DEBUG/MainProcess] | Consumer: Restarting Tasks...
[2018-04-26 16:48:21,230: DEBUG/MainProcess] Canceling task consumer...
[2018-04-26 16:48:21,230: DEBUG/MainProcess] | Consumer: Restarting Heart...
[2018-04-26 16:48:21,231: DEBUG/MainProcess] | Consumer: Restarting Gossip...
[2018-04-26 16:48:21,231: DEBUG/MainProcess] | Consumer: Restarting Mingle...
[2018-04-26 16:48:21,231: DEBUG/MainProcess] | Consumer: Restarting Events...
[2018-04-26 16:48:21,231: DEBUG/MainProcess] | Consumer: Restarting Connection...
[2018-04-26 16:48:21,231: DEBUG/MainProcess] | Consumer: Starting Connection
[2018-04-26 16:48:21,252: DEBUG/MainProcess] Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.na
ck': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to'
: True}, 'cluster_name': 'rabbit@rabbit', 'copyright': 'Copyright (C) 2007-2018 Pivotal Software, Inc.', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/',
 'platform': 'Erlang/OTP 20.3', 'product': 'RabbitMQ', 'version': '3.7.4'}, mechanisms: [b'PLAIN', b'AMQPLAIN'], locales: ['en_US']
[2018-04-26 16:48:21,257: INFO/MainProcess] Connected to amqp://test:**@172.16.33.170:5672//test
[2018-04-26 16:48:21,257: DEBUG/MainProcess] ^-- substep ok
[2018-04-26 16:48:21,257: DEBUG/MainProcess] | Consumer: Starting Events
[2018-04-26 16:48:21,271: DEBUG/MainProcess] Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.na
ck': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to'
: True}, 'cluster_name': 'rabbit@rabbit', 'copyright': 'Copyright (C) 2007-2018 Pivotal Software, Inc.', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/',
 'platform': 'Erlang/OTP 20.3', 'product': 'RabbitMQ', 'version': '3.7.4'}, mechanisms: [b'PLAIN', b'AMQPLAIN'], locales: ['en_US']
[2018-04-26 16:48:21,275: DEBUG/MainProcess] ^-- substep ok
[2018-04-26 16:48:21,275: DEBUG/MainProcess] | Consumer: Starting Mingle
[2018-04-26 16:48:21,275: INFO/MainProcess] mingle: searching for neighbors
[2018-04-26 16:48:21,276: DEBUG/MainProcess] using channel_id: 1
[2018-04-26 16:48:21,280: DEBUG/MainProcess] Channel open
[2018-04-26 16:50:55,250: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/proj/proj_venv/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 38, in start
    self.sync(c)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 42, in sync
    replies = self.send_hello(c)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 55, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/home/proj/proj_venv/lib/python3.6/site-packages/celery/app/control.py", line 129, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/celery/app/control.py", line 81, in _request
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/celery/app/control.py", line 81, in _request
    timeout=self.timeout, reply=True,
  File "/home/proj/proj_venv/lib/python3.6/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/home/proj/proj_venv/lib/python3.6/site-packages/kombu/pidbox.py", line 321, in _broadcast
    channel=chan)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/kombu/pidbox.py", line 360, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events
    return connection.drain_events(**kwargs)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/amqp/connection.py", line 471, in drain_events
    while not self.blocking_read(timeout):
  File "/home/proj/proj_venv/lib/python3.6/site-packages/amqp/connection.py", line 476, in blocking_read
    frame = self.transport.read_frame()
  File "/home/proj/proj_venv/lib/python3.6/site-packages/amqp/transport.py", line 236, in read_frame
    payload = read(size)
  File "/home/proj/proj_venv/lib/python3.6/site-packages/amqp/transport.py", line 401, in _read
    s = recv(n - len(rbuf))
ConnectionResetError: [Errno 104] Connection reset by peer
```

Seems reconnect to broker in endless loop unless we restart the worker manually.

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.5
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
```

Also the MainProcess consumes **800M+** memory in the node.

**Comment by cockcrow** [comment] 2018-04-27 04:53
Even in 128G node, it also consumes almost all CPU and memory.

It may could be reproduced via: **Keep celery worker running and restart rabbitmq-server.**

If the rabbitmq-server is running and start celery worker, it seems work fine.

**Comment by ewjoachim** [comment] 2018-07-20 06:51
I’ve tried setting broker pool limit to none, it got rid of errors, I’m getting better stats on my broker (CPU, Ram) and quite unexpectedly, on my workers too, with seemingly the same task competion rate. Not sure why, but, just reporting here.

(Might be a case of [random feedback misinterpeted](https://xkcd.com/1457/))

**Comment by auvipy** [comment] 2018-07-23 12:24
thanks @ewjoachim

**Comment by davidhalter** [comment] 2018-07-23 13:08
@auvipy IMO this is not a solved issue. You can close it, but it will pop up again and again. If he is disabling the broker pool limit then this issue still persists with the default installation of Celery. The only action that would IMO justify closing this issue (apart from fixing it or at least improving the error message) would be to set the broker pool limit to 0 and warn about using it.

I have tested Celery 4.1 with a small workload (a few messages per second) and was running into this, I don't see why this should fail by default.

BTW: We haven't upgraded to `Celery 4*`, because of this and other issues.

**Comment by shhaumb** [comment] 2018-09-18 10:05
We were facing the same issue in production with celery 4.2.1. I tried to figure out the issue and have come up with this workaround after which I am not getting this issue anymore in production:

Put `retry=True` in function call of `self.mailbox._publish_reply` in https://github.com/celery/kombu/blob/942a6daba91be2b29863417739c5fcf3511250b8/kombu/pidbox.py#L133

I don't know whether this is the right way or not, but it's better than making `broker_pool_limit = None`.

**Comment by thedrow** [comment] 2018-09-20 09:59
@shhaumb That's interesting, I don't see why we shouldn't retry publishing messages in the mailbox.
I think I can resolve this once I'll have the time to write a PR for it.
Retry should be added in https://github.com/celery/kombu/blob/942a6daba91be2b29863417739c5fcf3511250b8/kombu/pidbox.py#L260 and https://github.com/celery/kombu/blob/942a6daba91be2b29863417739c5fcf3511250b8/kombu/pidbox.py#L286

**Comment by auvipy** [comment] 2018-09-20 11:17
@thedrow @shhaumb  I have opened a PR. https://github.com/celery/kombu/pull/920, please suggest the changes needed in the test if any.

**Comment by thedrow** [comment] 2018-09-20 12:49
@itayB Does https://github.com/celery/kombu/pull/920 solve your issue?

**Comment by auvipy** [comment] 2018-09-21 03:13
could you try this PR https://github.com/celery/kombu/pull/920 ?

**Comment by jaydesl** [comment] 2018-09-26 09:01
> could you try this PR [celery/kombu#920](https://github.com/celery/kombu/pull/920) ?

Just to chip in - this PR solved my issue (same as originally reported). Thanks!

**Comment by auvipy** [comment] 2018-09-26 09:17
thanks! was waiting for such feedback!

**Closed by auvipy** 2018-09-26 09:17 UTC
Labels: Component: Kombu, DCUS2018: Sprint Candidate, Issue Type: Bug

**Comment by sdrew71** [comment] 2018-10-16 18:37
Is this going fix going to be available in a release of celery soon?  I am experiencing this every since upgrading to Celery 4.2.1 and it is a pretty major issue - as we typically experience it in calls to revoke() a task.

**Comment by auvipy** [comment] 2018-10-18 06:00
that is going to be part of celery 4.3, you could install it from master, and kombu from master.

**Comment by grayguest** [comment] 2020-05-14 05:06
Although add "retry=True" can solve the problem by reconnecting the broker, celery worker will receive repeated tasks.
```
[2020-05-13 23:24:59] [INFO]    - missed heartbeat from git_repo_fingerprint_worker@VM_9_196_centos (gossip.py:148)
[2020-05-14 05:51:36] [INFO]    - missed heartbeat from period_external_nascan_worker1@VM_9_196_centos (gossip.py:148)
[2020-05-14 05:51:36] [INFO]    - missed heartbeat from git_repo_fingerprint_worker@VM_9_196_centos (gossip.py:148)
[2020-05-14 05:51:36] [INFO]    - missed heartbeat from git_repo_fingerprint_worker@xxx.com (gossip.py:148)
[2020-05-14 05:51:36] [INFO]    - missed heartbeat from celery@xxx.com (gossip.py:148)
[2020-05-14 05:52:26] [WARNING] - consumer: Connection to broker lost. Trying to re-establish the connection... (consumer.py:340)
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/kombu/transport/base.py", line 238, in on_readable
    reader(loop)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/kombu/transport/base.py", line 220, in _read
    drain_events(timeout=0)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 505, in drain_events
    while not self.blocking_read(timeout):
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 511, in blocking_read
    return self.on_inbound_frame(frame)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 518, in on_inbound_method
    method_sig, payload, content,
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 646, in _on_close
    self._x_close_ok()
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 661, in _x_close_ok
    self.send_method(spec.Connection.CloseOk, callback=self._on_close_ok)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/abstract_channel.py", line 59, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/method_framing.py", line 172, in write_frame
    write(view[:offset])
  File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/transport.py", line 284, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
[2020-05-14 05:52:45] [INFO]    - Connected to amqp://xiaopo:**@10.26.9.233:5672/asset (connection.py:24)
[2020-05-14 05:52:45] [INFO]    - mingle: searching for neighbors (mingle.py:43)
[2020-05-14 05:52:46] [INFO]    - mingle: all alone (mingle.py:52)
[2020-05-14 05:52:46] [INFO]    - Received task: period_external_nascan.nascan[388fa489-07f5-44b5-bc9a-8cc04614812d]   (strategy.py:157)
[2020-05-14 05:52:46] [INFO]    - Received task: period_external_nascan.nascan[aa8e1690-3c73-4a83-9229-2e005280a6dd]   (strategy.py:157)
[2020-05-14 05:52:46] [INFO]    - Received task: period_external_nascan.nascan[e23db4fe-7c98-468e-b06e-7b9ef452c010]   (strategy.py:157)
[2020-05-14 05:52:46] [INFO]    - Received task: period_external_nascan.nascan[710f637d-3d82-4f68-827a-695b3e45b1cb]   (strategy.py:157)
```

**Comment by auvipy** [comment] 2020-05-14 05:38
> Although add "retry=True" can solve the problem by reconnecting the broker, celery worker will receive repeated tasks.
> 
> ```
> [2020-05-13 23:24:59] [INFO]    - missed heartbeat from git_repo_fingerprint_worker@VM_9_196_centos (gossip.py:148)
> [2020-05-14 05:51:36] [INFO]    - missed heartbeat from period_external_nascan_worker1@VM_9_196_centos (gossip.py:148)
> [2020-05-14 05:51:36] [INFO]    - missed heartbeat from git_repo_fingerprint_worker@VM_9_196_centos (gossip.py:148)
> [2020-05-14 05:51:36] [INFO]    - missed heartbeat from git_repo_fingerprint_worker@xxx.com (gossip.py:148)
> [2020-05-14 05:51:36] [INFO]    - missed heartbeat from celery@xxx.com (gossip.py:148)
> [2020-05-14 05:52:26] [WARNING] - consumer: Connection to broker lost. Trying to re-establish the connection... (consumer.py:340)
> Traceback (most recent call last):
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
>     blueprint.start(self)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
>     step.start(parent)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 599, in start
>     c.loop(*c.loop_args())
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/celery/worker/loops.py", line 83, in asynloop
>     next(loop)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
>     cb(*cbargs)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/kombu/transport/base.py", line 238, in on_readable
>     reader(loop)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/kombu/transport/base.py", line 220, in _read
>     drain_events(timeout=0)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 505, in drain_events
>     while not self.blocking_read(timeout):
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 511, in blocking_read
>     return self.on_inbound_frame(frame)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/method_framing.py", line 55, in on_frame
>     callback(channel, method_sig, buf, None)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 518, in on_inbound_method
>     method_sig, payload, content,
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
>     listener(*args)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 646, in _on_close
>     self._x_close_ok()
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/connection.py", line 661, in _x_close_ok
>     self.send_method(spec.Connection.CloseOk, callback=self._on_close_ok)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/abstract_channel.py", line 59, in send_method
>     conn.frame_writer(1, self.channel_id, sig, args, content)
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/method_framing.py", line 172, in write_frame
>     write(view[:offset])
>   File "/root/.local/share/virtualenvs/asset-ar0OxIPP/lib/python3.7/site-packages/amqp/transport.py", line 284, in write
>     self._write(s)
> ConnectionResetError: [Errno 104] Connection reset by peer
> [2020-05-14 05:52:45] [INFO]    - Connected to amqp://xiaopo:**@10.26.9.233:5672/asset (connection.py:24)
> [2020-05-14 05:52:45] [INFO]    - mingle: searching for neighbors (mingle.py:43)
> [2020-05-14 05:52:46] [INFO]    - mingle: all alone (mingle.py:52)
> [2020-05-14 05:52:46] [INFO]    - Received task: period_external_nascan.nascan[388fa489-07f5-44b5-bc9a-8cc04614812d]   (strategy.py:157)
> [2020-05-14 05:52:46] [INFO]    - Received task: period_external_nascan.nascan[aa8e1690-3c73-4a83-9229-2e005280a6dd]   (strategy.py:157)
> [2020-05-14 05:52:46] [INFO]    - Received task: period_external_nascan.nascan[e23db4fe-7c98-468e-b06e-7b9ef452c010]   (strategy.py:157)
> [2020-05-14 05:52:46] [INFO]    - Received task: period_external_nascan.nascan[710f637d-3d82-4f68-827a-695b3e45b1cb]   (strategy.py:157)
> ```
> 
> the last 4 tasks is being executed in another celery worker.

provide us appropriate failing test case please

**Comment by ba1dr** [comment] 2020-10-02 09:32
For me I had the same issue recently with celery 4.4.7 with connection dropped after 25  minutes with the long running task. This looked similar for both parties - RabbitMQ and celery reported that another peer reset the connection.
Finally I've discovered that this was related to Docker (I run my celery inside Docker). Quick workaround was to run containers with `--net host` and it seems to work now.

For additional info see your `net.ipv4.tcp_keepalive_time` setting (sysctl) and the following article: https://success.mirantis.com/article/ipvs-connection-timeout-issue

**Comment by cabal-daniel** [comment] 2021-02-22 20:49
`broker_pool_limit = None` solved this problem for me

```
celery==5.0.5
kombu==5.0.2
```

I saw this issue with Redis initially and the advice had been to switch over to RabbitMQ, which I did. Happened on Rabbit as well. It started appearing when started running my containers with `--pool=solo`. Before I was forced to put that flag, I never saw this issue. 🤷

**Comment by ba1dr** [comment] 2021-02-22 21:01
@cabal-daniel could you clarify it a bit? You've had this with celery 5.0.x, right? But after applying `broker_pool_limit = None` it is gone? With RabbitMQ and Redis it is ok for several hours along? Do you run celery or brokers in containers?
Hell so many issues linked to this "Closed" issue and people still complain.. Lets hope your solutions could help, but would be interesting to hear the explanation from maintainers maybe...

**Comment by cabal-daniel** [comment] 2021-02-22 22:24
@ba1dr

Actually `broker_pool_limit` was insufficient, i just encountered the error again. Based on some investigations online I'm now testing with 

```
broker_pool_limit = None
task_acks_late = True
broker_heartbeat = 0
worker_prefetch_multiplier = 1
```

And so far there are no errors after 3 hours of testing. I run both the celery workers and the broker (RabbitMQ) in a bare-metal kube environment. I had tried multiple versions of celery 4.x and kombu 4.x versions and they all had this issue. Initially I was using redis as the broker, I got a similar error and the recommendation was to switch to rabbit. Alas, the problem still happened, but only for really large jobs. My workers have tasks that take 35 - 50seconds and are running on  `-pool solo`.

**Comment by ba1dr** [comment] 2021-02-22 22:33
Hmm, I have different projects and I've just realized that I have one with very long tasks (up to 7 days) and it works without issues inside docker container with RabbitMQ and without `--net=host` hack.. Celery 4.3 is there.
And I have another that was upgraded to celery 4.4 and was not able to run more than hour without that hack... Settings are almost the same.
