### ISSUE TITLE
SSl cert missing in documentation

### ISSUE THREAD

**Issue by xirdneh** [celery/celery#5432] opened 2019-04-03 14:37 UTC
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

# Description
The SSL certs in the [documentation](https://docs.celeryproject.org) are missing. Not sure if this is on read the docs or us.

# Suggestions
Check read the docs config?

**Comment by thedrow** [comment] 2019-04-04 07:47
Duplicate of https://github.com/celery/celeryproject/issues/24.

**Closed by thedrow** 2019-04-04 07:47 UTC

**Comment by fechnert** [comment] 2019-04-29 09:21
This problem still exists, visiting `https://docs.celeryproject.org/en/latest/` with Firefox 66.0.3 (64-bit):

![Screenshot_2019-04-29_11-19-26](https://user-images.githubusercontent.com/1409863/56887043-bc53ca00-6a70-11e9-88db-859fd427f444.png)

**Comment by davidfischer** [comment] 2019-05-08 01:27
Read the Docs can issue this SSL cert once the DNS is updated. To get this certificate issued:

* Change the CNAME for docs.celeryproject.org ([docs](https://docs.readthedocs.io/en/stable/custom_domains.html)):

  ```
  $ dig CNAME +short docs.celeryproject.org
  celery.readthedocs.org.
  # This should return "readthedocs.io"
  ```

* Once you've updated the CNAME, some one with access to the project on Read the Docs needs to go to https://readthedocs.org/dashboard/celery/domains/, edit the domain (make sure HTTPS is checked) and save it. This will cause Read the Docs to revalidate and issue the SSL cert.
