### ISSUE TITLE
Celery 5.2.7 + SQS: messages are not processed by worker when internet connection is lost and recovered

### ISSUE THREAD

**Issue by yurif-freitas** [celery/celery#8350] opened 2023-06-30 14:23 UTC
# Checklist
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information
- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- https://github.com/celery/kombu/issues/931
- https://github.com/celery/celery/issues/6210
- https://github.com/celery/celery/issues/8242

#### Possible Duplicates

- None

## Environment & Settings
**Celery version**: 5.2.7
<details>
<summary><b><code>Output</code> </b></summary>

```
celery software -> celery:5.2.7 (emerald-rush) kombu:5.3.1 py:3.10.7
billiard:4.1.0 py-amqp:5.1.1
platform -> system:Linux arch:64bit, ELF
kernel version:6.2.6-76060206-generic imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:redis://:**@redis:6379/0
```

```
broker_url = "sqs://"
    result_backend: str = os.environ.get("RESULT_BACKEND")
    task_default_queue: str = SQS_DEFAULT_QUEUE_NAME
    broker_connection_retry: bool = True
    broker_connection_retry_on_startup: bool = True
    broker_transport: str = "sqs"
    broker_transport_options: dict = {
        "region": "us-east-1",
        "visibility_timeout": 3600,
        "max_retries": 3,
        "polling_interval": 2,
        "wait_time_seconds": 10,
        "predefined_queues": {
            task_default_queue: {
                "url": SQS_DEFAULT_QUEUE_URL,
                "access_key_id": aws_access_key_id,
                "secret_access_key": aws_secret_access_key,
            }
        },
    }
    broker_heartbeat: int = 90
    task_acks_late: bool = True
    task_soft_time_limit: int = 120
```
<p></p></details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages
```fastapi = "==0.95.0"
uvicorn = "==0.21.1"
nltk = "==3.8.1"
pinecone-client = "==2.2.1"
alembic = "==1.11.1"
gunicorn = "==20.1.0"
python-dotenv = "==1.0.0"
mysqlclient = "==2.1.1"
boto3 = "==1.26.126"
sqlalchemy = "==2.0.7"
pyarrow = "==11.0.0"
compress-json = "==1.0.8"
mysql-connector-python = "==8.0.32"
transformers = "==4.27.4"
onnxruntime = "==1.14.1"
urlextract = "==1.8.0"
celery = {version = "==5.2.7", extras = ["sqs"]}
newrelic = "==8.8.0"
structlog = "==23.1.0"
redis = "==4.5.1"
```

### Other Dependencies
<details>
<summary><b>entrypoint.sh</b>:</summary>

```sh
#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

: "${GUNICORN_CONF:=gunicorn_conf.py}"
: "${WORKER_CLASS:=uvicorn.workers.UvicornWorker}"
: "${APP_MODULE:=project.main:app}"
: "${MYSQL_HOST:=mysql}"
: "${MYSQL_PORT:=3306}"
: "${MYSQL_USER:=admin}"
: "${MYSQL_PASSWORD:=admin}"
: "${MYSQL_DATABASE:=populate}"

mysql_ready() {
python << END
import sys

import mysql.connector
from mysql.connector import Error

try:
    connection = mysql.connector.connect(host="${MYSQL_HOST}",
                                        database="${MYSQL_DATABASE}",
                                        user="${MYSQL_USER}",
                                        password="${MYSQL_PASSWORD}")
except:
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
    >&2 echo 'Waiting for Mysql to become available...'
    sleep 1
done
>&2 echo 'Mysql is available'

if [ "${POD_TYPE}" = 'worker' ]; then
    echo 'Starting Worker'
    if [ $WITH_NEW_RELIC == "true" ] ; then
        echo 'Starting New Relic Celery Agent...'
        newrelic-admin run-program celery \
            -A project.main.celery worker \
                -l 'INFO' \
                -c "${WORKER_CONCURRENCY:-2}" \
                -E \
                --without-gossip \
                --without-mingle
    else
        echo 'Starting Celery Worker...'
        celery \
            -A project.main.celery worker \
                -l 'INFO' \
                -c "${WORKER_CONCURRENCY:-2}" \
                -E \
                --without-gossip \
                --without-mingle
    fi
else
    echo 'Starting FastAPI Web Application...'
    if [ $WITH_NEW_RELIC == "true" ] ; then
        alembic upgrade head
        echo "Database UP"
        newrelic-admin run-program gunicorn \
            -c "${GUNICORN_CONF}" \
            -w "${GUNICORN_CONCURRENCY:-2}" \
            -k "${WORKER_CLASS}" \
            "${APP_MODULE}"
    else
        alembic upgrade head
        echo "Database UP"
        gunicorn \
            -c "${GUNICORN_CONF}" \
            -w "${GUNICORN_CONCURRENCY:-2}" \
            -k "${WORKER_CLASS}" \
            "${APP_MODULE}"
    fi
fi
```
</details>

<details>
<summary><b>creating celery app</b>:</summary>

```python
from fastapi import FastAPI
from celery import current_app as current_celery_app
from project.config import get_settings
from project.app.routers import health_check_router

def create_celery():
    settings = get_settings()
    celery_app = current_celery_app
    celery_app.config_from_object(settings, namespace=settings.SQS_DEFAULT_QUEUE_URL)

    return celery_app

def create_app() -> FastAPI:
    app = FastAPI()
    app.celery_app = create_celery()
    app.include_router(event_router)

    return app
```
</details>

The application is run in a container using Docker and Docker compose.

# Expected Behavior
The tasks are sent through a **FastAPI** endpoint and are processed normally by both the web and the worker pods. However, if the internet connection is lost and then reestablished, the worker pod should be able to process the messages without any errors.

# Actual Behavior
Despite the web pod continuing to receive new messages, the worker does not process them. The messages are sent to the queue but accumulate in the **'Available messages'** stage in **SQS** and are only processed when the application is restarted. No error message is provided when this bug occurs.

**Comment by luhn** [comment] 2023-07-20 16:06
Possible duplicate of #8243

**Closed** 2023-07-25 08:12 UTC
