### ISSUE TITLE
Celery worker doesn't consume last task when an exception raise

### ISSUE THREAD

**Issue by fatihsucu** [celery/celery#2693] opened 2015-07-07 11:23 UTC
I hope this sample would be understandable.

I am using more complex structure according to this sample but main thing is same.
`task_assigner` is running periodically and when an exception raises inside `task_assigner`, worker doesn't consume last assigned task. It is just receiving nothing more.

I think it could be rabbitmq thing.

    @app.task
    def some_task(arg):
        # do something
        return

    @app.task
    def task_assigner():
        argList = [arg1, arg2, arg3]
        for arg in argList:
            some_task.apply_async(
                args=[arg],
                eta= datetime.datetime.now(),
                queue='worker_queue',
                routing_key='routing_key'
               )

Here is the log sample.

    [2015-07-03 19:03:37,226: INFO/MainProcess] Received task: question.task_assigner[537e3761-e73e-40af-be24-84f2d512fb20]
    [2015-07-03 19:03:37,226: INFO/MainProcess] Received task: question.some_task[d8c4ae8c-c641-4b5e-b76e-a1195ab2c993] eta:[2015-07-04 10:00:00+00:00]
    [2015-07-03 19:03:37,235: ERROR/MainProcess] Task qustion.task_assigner[537e3761-e73e-40af-be24-84f2d512fb20] raised unexpected: Exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
     # Bla bla some exception in here

Then worker doesn't consume task which has `d8c4ae8c-c641-4b5e-b76e-a1195ab2c993` id. It is just receiving and its status is always `PENDING`

**Comment by thedrow** [comment] 2015-07-08 09:57
What have you configured to be your results backend?

**Comment by fatihsucu** [comment] 2015-07-08 10:50
it is mongodb

**Comment by thedrow** [comment] 2015-07-08 13:19
I'll try to reproduce this over the weekend.

**Comment by jackyfkc** [comment] 2015-07-10 08:57
@fatihsucu: I could not reproduce it.  What command you are using to start the worker. If it is okay, could you give a tiny demo that could reproduce the issue.

**Comment by ask** [comment] 2016-06-24 00:21
Closing this, as we don't have the resources to support MongoDB.

May be fixed in master, let's see if comes back after 4.0 release.

**Closed by ask** 2016-06-24 00:21 UTC
Labels: Component: Celerybeat, Component: MongoDB Results Backend, Component: RabbitMQ Broker, Status: Has Testcase, Worker Hangs
