### ISSUE TITLE
SIGTERM does not do a warm shutdown.

### ISSUE THREAD

**Issue by feanil** [celery/celery#2700] opened 2015-07-08 20:09 UTC
According to the documentation here: http://celery.readthedocs.org/en/latest/userguide/workers.html#process-signals

I should be able to send a SIGTERM to my running worker process and have it finish the task it is currently working on before it shuts down.  However when I call sigterm the process exits immediately with the following traceback.

```
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/billiard/pool.py", line 1171, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM).
```

I'm using Celery 3.1.18 with django 1.4, is there something special that has to be done to integrate the signal handlers with django?

Also posted here on the mailing list: https://groups.google.com/forum/#!topic/celery-users/t8g5KvIvQZ8

**Comment by ask** [comment] 2016-06-24 00:19
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by feanil** [comment] 2016-06-27 20:40
@ask any suggestions on where to start with trying to fix this?  I'm happy to try to dig into it if you can provide me a starting point.

**Comment by ask** [comment] 2016-06-27 23:53
I'm not sure, are you running on Heroku perhaps?  TERM does not propagate to child processes, so I'm unsure why this would happen.

**Comment by feanil** [comment] 2016-06-28 15:43
We are running in ec2 and in vagrant, the signal is sent from supervisord to the celery process.

**Comment by mverrilli** [comment] 2016-06-28 15:56
Are you using stopasgroup or killasgroup in your supervisor config?  If so, you may not want to do that.

**Comment by feanil** [comment] 2016-06-28 20:46
We are doing that.  What's the reason why that would be causing issues?

**Comment by mverrilli** [comment] 2016-06-28 21:18
Supervisor will send the SIGTERM down to all the forks which I doubt would handle the shutdown that way.  I have tried in the past (unsuccessfully) to catch the SIGTERM for gracefully exiting long operations, however I haven't had time to dig into why I had trouble doing so. 

If the work itself only gets the SIGTERM, it will wait for the forks to complete their tasks before exiting I think.

**Comment by ask** [comment] 2016-06-28 22:05
If you want the worker to drop currently executing tasks you should send SIGQUIT, not send TERM to child processes.

**Comment by mverrilli** [comment] 2016-06-28 23:05
@ask Thanks :-)  I'll play with that to see the behavior of it.  

As for this issue, I think it is solved really. Having supervisor set to stopasgroup will cause the described problem and @feanil says they are doing that. Best, I think, would be just to set to stopasgroup back to false and be done as the SIGTERMed worker will get will wait on all tasks to complete (what he was looking for).

**Comment by ask** [comment] 2016-06-28 23:09
Thanks! Then I guess we can close again until further information :)

**Comment by nedbat** [comment] 2016-06-29 21:19
I'm looking into this problem with @feanil, and I am mystified about the right way to get the behavior we want.
What we want: for "supervisor restart" to restart celery workers, but let them finish their current task.
We found that the default supervisor signal (TERM) will restart the workers, but will cause them to abort their current task.
Changing the signal to INT makes the worker restart if it is idle, but if busy, will finish its task and then restart.
Does this match your understanding of how celery workers behave?

What we are trying to debug is a situation where workers (even idle workers) get stuck in a supervisor STOPPING state.  We don't know why it is.  Switching back to TERM for the stop signal seems to fix the problem, but aborts in-progress tasks.  Is there a way to get what we need?

**Comment by ask** [comment] 2016-06-29 21:23
I guess I would need to know more about your configuration first, but sending TERM to the master/parent process initiates a warm shutdown sequence.  It closes the connection to the broker, waits for all currently executing tasks to finish and then terminates.

Currently executing tasks, means any task in the 'active' state,  tasks merely reserved by the worker
is left unacknowledged so that the broker resends them as soon as the worker closes the broker connection.

**Comment by nedbat** [comment] 2016-06-29 21:33
I am definitely seeing celery tasks aborting when supervisor sends TERM.  I don't know how to figure out why that is different than your description.

**Comment by mverrilli** [comment] 2016-06-29 21:33
@nedbat When you have stopasgroup enabled, this will send a TERM signal to the worker plus all worker forks causing the forks to abort. You want to turn off stopasgroup (and update supervisor) and the TERM signal will only get sent to the worker.

**Comment by mverrilli** [comment] 2016-06-29 21:35
Apologies if I am not understanding the issue properly. I use supervisor with celery very often, though. If you want to post a gist to your supervisor config I'll be happy to look at it.

**Comment by ask** [comment] 2016-06-29 21:36
The TERM signal being sent to the process *group* would certainly explain what you're seeing!

**Comment by nedbat** [comment] 2016-06-29 21:44
@ask @mverrilli thanks for walking me through it.  Removing stopasgroup, and using the default signal of TERM seems good. :)

**Comment by rocksfrow** [comment] 2016-11-05 20:27
@ask so I came across this issue when trying to come up with a one-liner to gracefully kill celery from a bash script.

So you confirmed that sending the kill signal to the entire process group would be problematic because it's going to kill the children process directly rather than letting parent handle the kill and do a warm shutdown.

When looking for examples of how to do a warm shutdown from CLI, I came across somebody saying they were quoting the celery doc with a solution like below, and so I search that solution and see a ton of 'answers' all of the place suggesting to do a warm shutdown like this (with slight variations):

````ps auxww | grep 'celery worker' | awk '{print $2}' | xargs kill -9````

But, basically, they're sending the kill signal to all of the children too. Isn't that basically the same behavior as killing the entire processgroup when using supervisor -- and as you said, problematic?

Can you confirm something like this makes a lot more sense?

````kill -TERM $(ps aux | grep 'celery worker' | head -1 | awk '{print $2}')````

That's the one-liner i use from bash to do a warm-shutdown.

Sorry to hop on this issue but this answer I suspect to be incorrect is all over stackoverflow and such so I wanted to confirm my understanding before correcting them.

**Comment by rocksfrow** [comment] 2016-11-05 20:44
@ask ahh, yes I see this in the 'workers guide' -- but you're only referencing it when killing worker who hasn't shutdown gracefully.

It looks like people are confusing that with a warm shudown. I'm going to go ahead and correct this answer I ran into because a bunch of ppl marked it correct and it's the top ranked page.

NVM.

**Comment by carn1x** [comment] 2016-11-10 15:09
I am finding celery multi is exiting immediately on SIGTERM rather than waiting for tasks to finish, is that case applicable to this issue? Also I'm sending SIGTERM to all processes as reported by `ps aux`, should we perhaps only send to the root process or something?

**Comment by rocksfrow** [comment] 2016-11-10 15:16
@carn1x you should only be sending the SIGTERM signal to the parent process, not the child threads.

Something like this would probably work for you -- it's been working for me.

````
# find parent celery process id                                                                                                                                                                             
CELERY_PID=$(ps aux --sort=start_time | grep 'celery worker' | grep 'bin/celery' | head -1 | awk '{print $2}')

# warm shutdown builder via SIGTERM signal to parent celery process                                                                                                                                         
kill -TERM $CELERY_PID
````

I use this in a bash script before doing some cleanup maint. I actually wait to confirm the thread stopped before continuing:

````
while kill -0 $CELERY_PID 2> /dev/null; do
  #make sure you're not waiting forever
done
````

If you read the comments above by @ask, he clarified that the process group shouldn't get killed, just the parent. I can confirm the code above works great for me on production systems. I hope this helps.

**Comment by rocksfrow** [comment] 2016-11-10 15:19
BTW, that above assumes you only have one worker running -- with a set of threads. If you have multiple workers, you'll have to adjust that to parse out the correct parent process ID. The main point is that you need to kill the parent (the first celery worker thread).

**Comment by carn1x** [comment] 2016-11-10 15:27
thanks @rocksfrow, working great :)

**Comment by fjsj** [comment] 2017-07-27 14:18
@ask current [supervisord/celeryd.conf](https://github.com/celery/celery/blob/master/extra/supervisord/celeryd.conf) uses `killasgroup=true`. Maybe the default should be false?

**Comment by dtheodor** [comment] 2018-10-01 07:59
Great comment @brianwawok, warm shutdown with acks_late looks broken. The task being immediately reassigned does not meet any definition of warm shutdown. Although this should not cause correctness issues because acks_late tasks are supposed to be idempotent.

**Comment by namevic** [comment] 2019-03-27 13:14
I have small workaround to fix it now
```python
import signal

from celery import Celery, Task

class MyBaseTask(Task):
`logger = get_task_logger('my_logger)`
    def __call__(self, *args, **kwargs):
        signal.signal(signal.SIGTERM,
                      lambda signum, frame: self.logger.info('SIGTERM received, wait till the task finished'))
        return super().__call__(*args, **kwargs)

app = Celery('my_app')
app.Task = MyBaseTask

For me it worked
````

**Comment by auvipy** [comment] 2019-04-01 16:06
could you please add a pr with your some proposed fix? @namevic

**Comment by auvipy** [comment] 2019-06-10 09:55
the unit test was failing after merging the PR. sorry guys.

**Comment by auvipy** [comment] 2019-06-13 06:09
sorry this was unrelated to failures... merged again.

**Closed by auvipy** 2019-06-13 06:09 UTC
Labels: Issue Type: Bug Report

**Comment by ohyang326** [comment] 2019-07-10 09:30
stopwaitsecs is also a import param.

stopwaitsecs -- "The number of seconds to wait for the OS to return a SIGCHLD to supervisord after the program has been sent a stopsignal. If this number of seconds elapses before supervisord receives a SIGCHLD from the process, supervisord will attempt to kill it with a final SIGKILL"

so if you want to wait for worker finish, set as large as possible.

**Comment by ma-kadri** [comment] 2021-03-02 16:25
> @carn1x you should only be sending the SIGTERM signal to the parent process, not the child threads.
> 
> Something like this would probably work for you -- it's been working for me.
> 
> ```
> # find parent celery process id                                                                                                                                                                             
> CELERY_PID=$(ps aux --sort=start_time | grep 'celery worker' | grep 'bin/celery' | head -1 | awk '{print $2}')
> 
> # warm shutdown builder via SIGTERM signal to parent celery process                                                                                                                                         
> kill -TERM $CELERY_PID
> ```
> 
> I use this in a bash script before doing some cleanup maint. I actually wait to confirm the thread stopped before continuing:
> 
> ```
> while kill -0 $CELERY_PID 2> /dev/null; do
>   #make sure you're not waiting forever
> done
> ```
> 
> If you read the comments above by @ask, he clarified that the process group shouldn't get killed, just the parent. I can confirm the code above works great for me on production systems. I hope this helps.

I was about to pull out few last remaining hair on my head!  and  ur comment came along and saved!  This works like a charm , thanks a TON

**Comment by malcolmtank** [comment] 2024-10-17 18:12
FYI to future readers of this thread: @auvipy 's fix was reverted in https://github.com/celery/celery/pull/5797 due to https://github.com/celery/celery/issues/5775
