### ISSUE TITLE
Celery Received unregistered task of type

### ISSUE THREAD

**Issue by awais786** [celery/celery#6485] opened 2020-11-16 14:27 UTC
Python3.8
Celery 4.4.7

Our app is running fine but after migrating to 4.4.7 some times we receive issue `unregistered tasks`. This issue is so flaky and have no proper steps to reproduce. 

Some one guide me how to debug this issue or point out where to add logs in celery to check the issue ?

One of the reason we found is restarting workers multiple times reproduce this issue some times.

**Comment by xirdneh** [comment] 2020-11-16 18:17
The error message should say which task is the one that's marked as unregistered

Are you using Canvas (Workflows) or just calling tasks directly?

**Comment by awais786** [comment] 2020-11-16 18:34
Yes, it shows the task name but the error occurrence is flaky.  
Importing them via `CELERY_IMPORTS` from settings.  As i told earlier its works fine but whenever there is some change related with celery this issue appear in some of the workers.

**Comment by xirdneh** [comment] 2020-11-16 21:38
What do you mean by "some change related with celery"
Do you mean adding new tasks?
Or just updating Celery?

**Comment by awais786** [comment] 2020-11-23 09:18
Registry map is showing all tasks are registered except few tasks. But those task are working fine. Why task registry missing those ?

**Comment by georgedorn** [comment] 2020-11-24 05:30
I have a similar issue, except that I have zero registered tasks - they do not show up in flower and trying to run one yields a NotRegistered exception.  Downgrading to 4.4.6 fixes it.

I'm using `@app.task()` and `app.autodiscover_tasks()` to register my (django) tasks using the cookbook nearly verbatim, nothing fancy.  I'm starting celery workers via systemd and `celery multi`.

**Comment by awais786** [comment] 2020-12-03 13:42
Any one tell me how to debug this issue. This issue appears whenever we do some kind of deploy on prod but not each time.
We are trying to add logs in side celery fork but its not looking helpful. We have class base tasks and only this app shows error each time. Other 200+ tasks seems fine.

**Comment by thedrow** [comment] 2020-12-15 15:29
Since we can't reproduce your issue, we'll have a hard time helping you debug it.

**Comment by auvipy** [comment] 2021-11-06 17:04
closing for now.

**Closed by auvipy** 2021-11-06 17:04 UTC
Labels: Status: Cannot Reproduce ✘, Issue Type: Bug Report
