### ISSUE TITLE
celery makes the django stuck

### ISSUE THREAD

**Issue by dongshengYoung** [celery/celery#4571] opened 2018-03-06 03:04 UTC
## Checklist

software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:3.6.3
            billiard:3.5.0.3 redis:2.10.6
platform -> system:Windows arch:64bit, WindowsPE imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:django-db

CELERY_BROKER_URL: 'redis://localhost:6379/4'
CELERY_RESULT_BACKEND: 'django-db'

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
i use django rest_framework,and the django_celery_results,i have an regular expression path 
the proj's urls.py
`re_path(r'^server/', include('servermanager.urls'))`
the servermanager's urls.py
`re_path(r'^test/(?P<para>[a-z]+)/$', Testcelery.as_view()),`

so  the path is `localhost:8000/server/test/<para>`
the views.py

![image](https://user-images.githubusercontent.com/31365352/37012110-f4d12b80-212d-11e8-949a-cd43931d362c.png)

celery_test() in tasks.py

![image](https://user-images.githubusercontent.com/31365352/37011925-34094892-212d-11e8-9348-898741112cbc.png)

## Expected behavior
the console:
![image](https://user-images.githubusercontent.com/31365352/37011810-c340dba2-212c-11e8-89d8-e90f9ccd2765.png)

the web:
![image](https://user-images.githubusercontent.com/31365352/37011902-1fa9a07c-212d-11e8-9c78-deb282b846b6.png)

i get this by remove the `@shared_task()` decorator

## Actual behavior
the web:
![image](https://user-images.githubusercontent.com/31365352/37011852-f48bdb9e-212c-11e8-8721-9e3c37e0f0bc.png)

the console:
![image](https://user-images.githubusercontent.com/31365352/37011877-0600b386-212d-11e8-9502-1a277da314d9.png)

the request seems stucked

**Comment by dongshengYoung** [comment] 2018-03-06 03:30
when i debug the django, it seems somthing wrong with 
`    def __call__(self, *a, **kw):
        return self._get_current_object()(*a, **kw)`

**Comment by thedrow** [comment] 2018-03-06 10:25
From what you are describing it sounds unlikely that Celery is the cause of your issue.
The Celery task is run synchronously so there's no communication with the broker.
We need more information to debug this problem.
Do you have a stack trace or a reproducible test case I can use? Does this problem only reproduce on Windows?

**Comment by thedrow** [comment] 2018-03-19 09:13
Since we got no reply I'm going to close this issue.
If you still require assistance please comment here and we'll reopen.

**Closed by thedrow** 2018-03-19 09:13 UTC
Labels: Operating System: Windows, Status: Feedback Needed ✘
