### ISSUE TITLE
Celery do not trigger tasks when multiples instances on same machine

### ISSUE THREAD

**Issue by debnet** [celery/celery#2625] opened 2015-05-20 12:49 UTC
It's hard to explain even more when you are not familar with english language but I'll try.

I have a specific case in my deployment: the same project basecode is on the same machine on different unix accounts (one per customer), each project has a celery worker which share the same Redis instance.

The problem is the following: when the customer A launches a task, this tasks should be taken by the worker A, and same behavior for a customer B on worker B. But currently, worker A and B doesn't trigger any task when executed together.

When restarting only one worker, it takes __all__ tasks from customer A and B.

Each worker is started as the following:

```exec $PYENV/celery worker -A nouvelleoffre -B -Q $DJANGO_QUEUE_NAME --loglevel=INFO --logfile=$DJANGODIR/logs/worker.log --hostname $NAME.%h```

$DJANGO_QUEUE_NAME and $NAME are different for each customer. For example, DJANGO_QUEUE_NAME = 'customer_a' and NAME = 'customer_a'. DJANGO_QUEUE_NAME affects the default queue name of celery worker.

Here the Django configuration of the worker, common for each customer:

```
    # Celery configuration
    BROKER_URL = 'redis://localhost:6379/0'
    BROKER_TRANSPORT_OPTIONS = {
        'visibility_timeout': 3600,
        'fanout_prefix': True,
        'fanout_patterns': True,
    }
    CELERY_TASK_SERIALIZER = 'pickle'
    CELERY_RESULT_SERIALIZER = 'pickle'
    CELERY_RESULT_BACKEND = 'redis'
    CELERY_TASK_RESULT_EXPIRES = 3600
    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
    CELERY_DISABLE_RATE_LIMITS = True
    CELERY_CHORD_PROPAGATES = True
    CELERY_ALWAYS_EAGER = False
    CELERY_DEFAULT_QUEUE = values.Value('celery', environ_name='QUEUE_NAME')
```

Thanks for any help provided. ;)

**Comment by PMickael** [comment] 2015-05-20 13:08
Hi, why did you let CELERY_DEFAULT_QUEUE ? Try to only use the -Q option.
Also -B ? for --beat but you don't have any CELERYBEAT_SCHEDULE ?
Make sure that task go in the good queue and not in celery queue (default)

**Comment by debnet** [comment] 2015-05-20 13:13
-B option is not relevant in my example, I could delete it without harm.
With CELERY_DEFAULT_QUEUE I create a specific queue for each customer application, normally each tasks in Django should be sent to this queue, right?

**Comment by debnet** [comment] 2015-05-20 13:16
Here the worker start for customer A:

```
(nouvelleoffre) [dsn@GLaDOS ~]$ ./start_worker.sh

 -------------- celery@dsn.GLaDOS v3.1.18 (Cipater)
---- **** -----
--- * ***  * -- Linux-2.6.32-504.16.2.el6.x86_64-x86_64-with-centos-6.6-Final
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         nouvelleoffre:0x7f652ef32550
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> dsn              exchange=dsn(direct) key=dsn


[tasks]
  . common.log_delete
  . common.log_m2m
  . common.log_save
  . common.notify_changes
  . dsn.import
  . merge
```

and for the customer B:

```
(nouvelleoffre) [demo@GLaDOS ~]$ ./start_worker.sh

 -------------- celery@demo.GLaDOS v3.1.18 (Cipater)
---- **** -----
--- * ***  * -- Linux-2.6.32-504.16.2.el6.x86_64-x86_64-with-centos-6.6-Final
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         nouvelleoffre:0x7fe37edae780
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> demo             exchange=demo(direct) key=demo


[tasks]
  . common.log_delete
  . common.log_m2m
  . common.log_save
  . common.notify_changes
  . dsn.import
  . imports.adresses
  . imports.caisses_assurance
  . imports.contrats_collectifs
  . imports.contrats_individuels
  . imports.domiciliations_bancaires
  . imports.entreprises
  . imports.liens_caisse_personne
  . imports.numeros_insee
  . imports.organismes
  . imports.parametres_personnes
  . imports.personnes
  . imports.populations
  . imports.produits
  . imports.verifier_personnes
  . merge
  . service.maj_personne_mutcim
```

**Comment by PMickael** [comment] 2015-05-20 13:22
> With CELERY_DEFAULT_QUEUE I create a specific queue for each customer application, normally each tasks in Django should be sent to this queue, right?

Not sur about this, but I think yes :).

But are you sure that the triggered task (where it's called) is in the right worker ? because default queue is define by the worker/process who launch the task, try to force a queue like this
```python
tasks.my_task.apply_async(kwargs={"ok": "ok"}, queue='customer_a')
```

**Comment by thedrow** [comment] 2015-07-13 07:01
The queues should be defined in CELERY_QUEUES. I'm not sure that -Q binds the tasks to the queues. I think it just declares the queue.
Can you please verify?

As far as I'm concerned this is not a bug and I'm gonna close this issue.
This won't mean we won't help so feel free to comment further.

**Closed** 2015-07-13 07:01 UTC
Labels: Status: Not a Bug
