### ISSUE TITLE
Celery 4.1: Logging task state is missing

### ISSUE THREAD

**Issue by stufan** [celery/celery#4734] opened 2018-05-15 09:08 UTC
I upgraded my celery from 3.1.25 to 4.1.0. The upgrade was fluent and required no changes inside my tasks code or settings. The only thing I observed which somehow is blocking my task debugging is that with version 4.1 (it could be event in 4.0) their is no more log record for the completion state of the task. In particular:

- On 3.1.25: [2018-05-15 07:48:16,876: INFO/MainProcess] Received task: flipps.celery.debug_task[e42312c8-2bc6-4de7-b54b-ea5de490ed65] [2018-05-15 07:48:16,921: INFO/MainProcess] Task flipps.celery.debug_task[e42312c8-2bc6-4de7-b54b-ea5de490ed65] succeeded in 0.02095658498001285s: Non
- On 4.1.0: [2018-05-15 07:49:54,928: INFO/MainProcess] Received task: flipps.celery.debug_task[30a0a7cb-8b88-48b6-abd2-52de5d92aba9]

i.e. there is not the "suceeded" message. 

I managed to show the "succeeded" message on 4.1 by doing a very ugly hack inside celery/app/trace.py:info() function adding:
`logger.disabled = False`

For some reason the logger ('celery.app.task') is disabled and thus filters all the log messages regardless I start the celery with loglevel=DEBUG. Here is my celery startup command:

`celery worker -A flipps -Q heavy,celery,messaging,reporting,kinesis -l DEBUG -c 1 -Ofair -E --purge`

For development I start it on command line. My python is 3.5.5

It is also missing the log that the worker is ready - on 3.1.25 it is: [2018-05-15 07:47:26,005: WARNING/MainProcess] celery@Stefans-MacBook-Pro.local ready. while on 4.1.0 there isn't such a log message.

**Comment by stufan** [comment] 2018-06-18 15:33
Just managed to test against the 4.2 release and issue still persists.

**Comment by johnarnold** [comment] 2018-06-29 17:39
I definitely don't have this problem in my environment so I don't think it's systemic...

[2018-06-28 17:48:30,126] {trace.py:124} INFO - Task net_task.device.create_tac_case[fd887582-2fe5-427c-a4aa-a236600b2dfc] succeeded in 33.961548024002695s:

can you run a celery -A app_name report   so we can see what options you have configured?

**Comment by stufan** [comment] 2018-07-08 23:49
Please, find attached the the celery.report file.
[celery.report.txt](https://github.com/celery/celery/files/2174228/celery.report.txt)

**Comment by lucheol** [comment] 2018-07-14 16:39
Hi @stufan, I have this same issue. Tested on mac os and ubuntu dev enviroments.
The task is executed, but no log.

**Comment by johnarnold** [comment] 2018-08-08 03:02
@stufan it looks like you have a ton of custom logging configured.  I would start troubleshooting by running on a test server with minimal/default logging config, and see if you get the expected logs.  I will commonly run celery worker in pycharm and set breakpoints so I can inspect vars and walk the code.

We (also) run some custom logging, and we found this config setting pretty useful:

worker_hijack_root_logger = True  # enables per task logging

**Comment by stufan** [comment] 2018-08-08 18:42
@johnarhold according to celery docs (http://docs.celeryproject.org/en/latest/userguide/configuration.html#logging) this settings is already on by default. So I guess it is not helping at all

**Comment by willemt** [comment] 2019-02-05 06:14
I had the same issue when upgrading. I'm using Django and had to add this to my `LOGGING` dict for it to work again.

```python
LOGGING['loggers'] = {
    'celery.app.trace': {
        'handlers': [],
        'level': 'INFO',
        'propagate': True,
    },
}
```

**Comment by auvipy** [comment] 2019-02-05 11:03
@willemt which version of celery are you using?

**Comment by auvipy** [comment] 2019-02-05 11:32
could you try a newer version of celery? till then I am going to close this

**Comment by willemt** [comment] 2019-02-06 00:54
@auvipy I upgraded to Celery 4.2.1 and have reproduced this issue (ie. missing the "succeeded in" message). The message returns when I apply the `celery.app.trace` fix in my comment above.

It might be worth mentioning that I'm running my celery worker like this:
`celery worker -A project.celery_app -Q default -c 1 -l INFO --logfile=../log/celery-default.log  -n 1`

 It could be that the `--logfile` handler is not being applied to the logger inside `celery.app.trace`. The `propagate: True` setting fixes this by causing the message to be emitted through the root logger.

**Comment by auvipy** [comment] 2019-02-06 06:46
could you send that as docs improvement?

**Comment by willemt** [comment] 2019-02-06 09:20
@auvipy I'll give it a go 👍

**Closed** 2019-02-07 05:48 UTC
Labels: Issue Type: Documentation, Status: Needs Verification ✘

**Comment by auvipy** [comment] 2022-05-15 10:22
> @stufan Not sure if it makes sense to reply here on closed issue, but I think problem with disabled logger lies in the fact that you use `disable_existing_loggers=True` in the LOGGING config. This way all not mentioned loggers in configuration will be disabled. Take a look on https://docs.python.org/3/howto/logging.html#configuring-logging.
> 
> Maybe it is also something to mention in the documentation @auvipy ?

additional clarification is wellcome
