### ISSUE TITLE
Any plan to support redis cluster

### ISSUE THREAD

**Issue by RyanKung** [celery/celery#3479] opened 2016-09-27 18:58 UTC
Any plan to support redis-cluster?

I think redis-cluster can be simply implement by inheriting `celery.backend.redis.RedisBackend`, Is there any plan to do that?

**Comment by ask** [comment] 2016-09-30 20:34
celery.backend.redis is the result backend, the broker is in kombu.transport.redis.

I'm sure it could be possible to support this, maybe look in the Kombu issue tracker to see if anyone is already working on it.

**Comment by ztsv** [comment] 2016-10-04 10:52
related repo
https://github.com/hbasria/celery-redis-cluster-backend

**Comment by auvipy** [comment] 2018-01-19 08:20
we might get that package merged into celery

**Comment by pabloariasmora** [comment] 2018-10-24 19:28
The redis-cluster support is a good feature to have 💯

**Comment by bpereto** [comment] 2018-10-25 16:52
@auvipy why not using redis-sentinel?

**Comment by auvipy** [comment] 2018-10-25 17:09
I didn't get your point, could you elaborate more?

**Comment by bpereto** [comment] 2018-10-25 18:40
sorry, mixed up sentinel and redis-cluster.

**Comment by thedrow** [comment] 2019-01-01 16:19
This is a duplicate of #2852.

**Closed by thedrow** 2019-01-01 16:19 UTC
Labels: Issue Type: Feature Request, Status: Duplicate ✘

**Comment by Lowell-liu** [comment] 2022-12-02 02:32
Any plan to support redis-cluster? is a good feature.
