### ISSUE TITLE
celery with redis sometimes appear "Cannot route message for exchange 'default': Table empty or key no longer exists." problem

### ISSUE THREAD

**Issue by jingx2008** [celery/celery#2980] opened 2015-12-31 03:36 UTC
sometimes celery with redis appear the problem:
portal_page_handler.py:3175	ERROR	Traceback (most recent call last):
  File "/home/ixianxia/web_app_src/shanghu_wifi/handler/portal_page_handler.py", line 3123, in get
    self.cur_user.card_no)
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/celery/app/task.py", line 452, in delay
    return self.apply_async(args, kwargs)
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/celery/app/task.py", line 554, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/celery/app/base.py", line 321, in send_task
    reply_to=reply_to or self.oid, **options
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/celery/app/amqp.py", line 299, in publish_task
    **kwargs
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/kombu/messaging.py", line 166, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/kombu/connection.py", line 440, in _ensured
    return fun(*args, **kwargs)
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/kombu/messaging.py", line 182, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 524, in basic_publish
    message, exchange, routing_key, **kwargs
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/kombu/transport/virtual/exchange.py", line 60, in deliver
    for queue in _lookup(exchange, routing_key):
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 615, in _lookup
    self.get_table(exchange),
  File "/home/ixianxia/local/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 693, in get_table
    raise InconsistencyError(NO_ROUTE_ERROR.format(exchange, key))
InconsistencyError: 
Cannot route message for exchange 'default': Table empty or key no longer exists.
Probably the key ('_kombu.binding.default') has been removed from the Redis database.

**Comment by ask** [comment] 2016-01-04 21:38
This means something/someone removed the key.

Pretty common around here the last months have been people with hacked redis instances.

Duplicate of celery/kombu#236

**Closed by ask** 2016-01-04 21:38 UTC

**Comment by jingx2008** [comment] 2016-01-05 01:19
thank you for reply,i found someone hacked my redis instance yesterday

**Comment by wowkin2** [comment] 2019-07-12 10:13
@ask how to check if it was hacked?
