### ISSUE TITLE
Celery workers stuck on eta/countdown'd tasks

### ISSUE THREAD

**Issue by aehlke** [celery/celery#2731] opened 2015-07-27 16:10 UTC
We're seeing unexpected behavior that seems contrary to Celery design - when more eta/countdown'd tasks are enqueued than the worker is configured to fetch, it will fetch those eta'd tasks, and increment the `prefetch_count` accordingly, but won't actually fetch any more tasks at that point.

We're running Celery 3.1.7 with the RabbitMQ backend. (I'll try this with the latest version of Celery soon, but didn't see anything relevant in the changelogs.)

Logs from our Celery worker reproducing this issue:
```
2015-07-27 16:01:23,768: WARNING/MainProcess] celery@celery_legacy.dev ready.
[2015-07-27 16:01:23,769: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2015-07-27 16:01:23,769: DEBUG/MainProcess] celery@celery_sms.dev joined the party
[2015-07-27 16:01:23,770: DEBUG/MainProcess] celery@low_priority_low_mem.dev joined the party
[2015-07-27 16:01:23,771: INFO/MainProcess] Received task: ScheduledCommand.tq_execute[c1ce36c6-62f8-4698-bea0-ea806bd59329] eta:[2015-08-28 15:27:00+00:00]
[2015-07-27 16:01:23,775: INFO/MainProcess] Received task: ScheduledCommand.tq_execute[d51abfa0-dcbe-44bb-aff1-43de7eb66fda] eta:[2015-11-28 16:28:10+00:00]
[2015-07-27 16:01:23,778: INFO/MainProcess] Received task: ScheduledCommand.tq_execute[a15fa011-eb95-4de4-8d48-91782598a8bb] eta:[2015-09-24 15:29:00+00:00]
[2015-07-27 16:01:23,786: INFO/MainProcess] Received task: ScheduledCommand.tq_execute[e7aa6709-2da0-4d0e-a594-489a7c12c3d4] eta:[2015-09-24 15:30:10+00:00]
[2015-07-27 16:01:23,791: DEBUG/MainProcess] celery@high_priority_high_mem.dev joined the party
[2015-07-27 16:01:25,625: DEBUG/MainProcess] celery@low_priority_high_mem.dev joined the party
[2015-07-27 16:01:25,625: DEBUG/MainProcess] basic.qos: prefetch_count->8
```
And then never any `Received task`s beyond this.

The params we're using:
`/home/vagrant/venv/app_tophat/bin/python /vagrant/THM/manage.py celery worker -E -c 1 --maxtasksperchild=100 -n celery_legacy.%%h -Ofair --loglevel=DEBUG`

Screenshot of RabbitMQ admin showing the 4 fetched tasks with many more tasks waiting: https://www.dropbox.com/s/rkcaomg8kqga937/Screenshot%202015-07-27%2012.07.42.png?dl=0 This is after `prefetch_count->8` in the Celery logs.

Please let me know if any other details would help here. Thanks.

**Comment by aehlke** [comment] 2015-07-27 16:16
Ah this seems to be resolved now in the latest celery release. I'm curious if someone could point me to the actual resolved issue? I'd appreciate seeing where the fix is in the changelog or commit history. Thanks!

**Comment by chrono** [comment] 2015-07-27 16:42
could this be related to celery/kombu#339?

**Comment by vietord** [comment] 2015-07-27 18:35
Looks like the same thing as: https://github.com/celery/celery/issues/1960

Consuming ETA tasks, during worker startup, doesn't bump the prefetch count on the rabbit side?

**Comment by thedrow** [comment] 2015-08-11 06:13
Can you try to send a management command to see if this issue is a duplicate of #1960?

**Comment by ask** [comment] 2015-12-12 07:11
If it was resolved around that time, then it was most likely the incompatible RabbitMQ behavior introduced in rabbitmq 3.5.0

**Closed by ask** 2015-12-12 07:11 UTC
Labels: Worker Hangs
