### ISSUE TITLE
celery worker won't start

### ISSUE THREAD

**Issue by lynxone67** [celery/celery#3821] opened 2017-02-09 08:52 UTC
I have problem to start Celery under Windows 10
## Steps to reproduce
`celery -A epzam worker -l info`
## Expected behavior
`running worker`
## Actual behavior
celery -A epzam report
`Traceback (most recent call last):
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Peter Kops\AppData\Local\Programs\Python\Python35-32\Scripts\celery.exe\__main__.py", line 9, in <module>
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\__main__.py", line 14, in main
    _main()
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\base.py", line 285, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\base.py", line 368, in handle_argv
    return self(*args, **options)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\celery.py", line 363, in run
    self.out(self.app.bugreport())
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bin\base.py", line 388, in out
    print(s, file=fh or self.stdout)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\encodings\cp852.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe5' in position 4259: character maps to <undefined>`

celery -A epzam worker -l info
`
 -------------- celery@DEV_PK v4.0.2 (latentcall)
---- **** -----
--- * ***  * -- Windows-10-10.0.14393-SP0 2017-02-09 09:50:05
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         epzam:0x3e418b0
- ** ---------- .> transport:   amqp://pk123ab:**@10.0.0.203:5672//
- ** ---------- .> results:
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> ep.zam.applicant.changes exchange=ep.zam.applicant.changes(direct) key=ep.zam.applicant.changes

[tasks]
  . ep_zam.tasks.add
  . ep_zam.tasks.mul
  . ep_zam.tasks.xsum
  . epzam.celery.debug_task

[2017-02-09 09:50:05,288: CRITICAL/MainProcess] Unrecoverable error: AttributeError("Can't pickle local object 'Pool.__init__.<locals>.Process'",)
Traceback (most recent call last):
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\worker\worker.py", line 203, in start
    self.blueprint.start(self)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bootsteps.py", line 119, in start
    step.start(parent)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\bootsteps.py", line 370, in start
    return self.obj.start()
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\concurrency\base.py", line 131, in start
    self.on_start()
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\celery\concurrency\prefork.py", line 112, in on_start
    **self.options)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\billiard\pool.py", line 1008, in __init__
    self._create_worker_process(i)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\billiard\pool.py", line 1117, in _create_worker_process
    w.start()
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\billiard\process.py", line 122, in start
    self._popen = self._Popen(self)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\billiard\popen_spawn_win32.py", line 79, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\billiard\reduction.py", line 99, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Pool.__init__.<locals>.Process'

C:\epzam>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\billiard\spawn.py", line 165, in spawn_main
    exitcode = _main(fd)
  File "c:\users\peter kops\appdata\local\programs\python\python35-32\lib\site-packages\billiard\spawn.py", line 207, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input`

Any help appreciated, thank you

**Comment by primoz-k** [comment] 2017-03-08 10:02
Celery 4 no longer supports Windows. 
Source: http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#removed-features

**Comment by thedrow** [comment] 2017-04-16 07:28
Thanks for the bug report. We discontinued Windows support because we don't have access to Windows or time to debug issues on Windows. The tests are running on Windows but we can't ensure nothing breaks.

I'm going to leave this open for now in case someone wants to attempt to troubleshoot/debug this.

**Comment by pypetey** [comment] 2017-04-19 20:00
I could try fixing that but I might need some guidance as I never did any coding work for celery library.

**Comment by thedrow** [comment] 2017-04-20 07:42
Feel free to ask us any questions.

**Comment by SPKorhonen** [comment] 2017-06-06 07:44
I ran to the same problem when trying to update our celery to 4.x on Win10. The problem is tied to fork support (or lack thereof in Windows) which leads to pickling of Process object. I have a workaround for that which fixes the issue. Would celery team be willing to consider a pull request? I would have to modify billiard...

**Comment by SPKorhonen** [comment] 2017-06-06 07:52
It would seem that there is a multitude of issues centered on this problem, after a quick search I found at least following issues: #3780, #3655, #3551 and #3383

**Comment by SPKorhonen** [comment] 2017-06-08 12:18
Fix for this issue submitted in pull request celery/billiard#225

**Comment by SPKorhonen** [comment] 2017-06-08 12:36
Further problems under Windows: #4081 with fix: #4078

**Comment by auvipy** [comment] 2017-12-19 17:26
seems it's fixed

**Closed by auvipy** 2017-12-19 17:26 UTC
Labels: NEEDS HELP, Operating System: Windows, Priority: None (no current effort), Worker Crashes

**Comment by Gideon-Felt** [comment] 2022-03-17 20:41
Does celery require an init system to function properly?
I'm using WSL and am not getting any worker_init signal?
