### ISSUE TITLE
ready function of group task will re-raise the exception of task with Redis result backend 

### ISSUE THREAD

**Issue by fishballLin** [celery/celery#5290] opened 2019-01-17 06:52 UTC
# Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have tried reproducing the issue on more than one message broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

## Environment & Settings
**Celery version**: 4.2.1

**Report**:
software -> celery:4.2.1 (windowlicker) kombu:4.2.2-post1 py:3.6.7
            billiard:3.5.0.5 py-amqp:2.4.0
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://localhost:6379/0

broker_url: 'amqp://guest:********@localhost:5672//'
enable_utc: True
imports: ['tasks']
result_backend: 'redis://localhost:6379/0'
result_expires: 3600
task_acks_late: True
worker_disable_rate_limits: True
<details>
```
```
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: python3.6
* **Minimal Broker Version**: RabbitMQ 3.7.10
* **Minimal Result Backend Version**: redis-server 4.0.9
* **Minimal OS and/or Kernel Version**: : Ubuntu 18.04

### Python Packages

<details>

```

amqp==2.4.0
anyjson==0.3.3
APScheduler==3.2.0
apturl==0.5.2
asn1crypto==0.24.0
beautifulsoup4==4.7.1
billiard==3.5.0.5
Brlapi==0.6.6
bs4==0.0.1
CacheControl==0.12.5
cachetools==3.0.0
celery==4.2.1
certifi==2018.11.29
chardet==3.0.4
Click==7.0
command-not-found==0.3
cryptography==2.1.4
cupshelpers==1.0
defer==1.0.6
distro-info==0.18
ephem==3.7.6.0
firebase-admin==2.14.0
Flask==1.0.2
gevent==1.4.0
google-api-core==1.7.0
google-auth==1.6.2
google-cloud-core==0.29.1
google-cloud-firestore==0.31.0
google-cloud-storage==1.13.2
google-resumable-media==0.3.2
googleapis-common-protos==1.5.6
greenlet==0.4.15
grpcio==1.17.1
httplib2==0.9.2
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
joblib==0.13.1
keyring==10.6.0
keyrings.alt==3.0
kombu==4.2.2.post1
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
locustio==0.9.0
louis==3.5.0
lxml==3.7.2
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.1.0
msgpack==0.6.0
neovim==0.2.0
netifaces==0.10.4
numpy==1.16.0
oauth==1.0.1
olefile==0.45.1
opencv-python==4.0.0.21
pexpect==4.2.1
Pillow==5.4.1
protobuf==3.6.1
pyasn1==0.4.5
pyasn1-modules==0.2.3
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pygobject==3.26.1
pymacaroons==0.13.0
pymongo==3.7.2
PyNaCl==1.1.2
pyparsing==2.2.0
pyRFC3339==1.0
python-apt==1.6.3
python-dateutil==2.7.5
python-debian==0.1.32
python-memcached==1.53
python3-pika==0.9.14
pytz==2018.9
pyxdg==0.25
PyYAML==3.12
pyzmq==17.1.2
redis==3.0.1
reportlab==3.4.0
requests==2.21.0
requests-unixsocket==0.1.5
rsa==4.0
scikit-learn==0.20.2
scipy==1.2.0
SecretStorage==2.3.1
simplejson==3.13.2
six==1.12.0
skorch==0.5.0.post0
soupsieve==1.7.1
ssh-import-id==5.7
system-service==0.3
systemd-python==234
TA-Lib==0.4.17
tabulate==0.8.2
torch==1.0.0
torchvision==0.2.1
tornado==5.1.1
tqdm==4.29.1
tzlocal==1.5.1
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.24.1
usb-creator==0.3.3
vine==1.2.0
virtualenv==16.2.0
wadllib==1.3.2
Werkzeug==0.14.1
xkit==0.0.0
zope.interface==4.3.2

```
</details>

### Other Dependencies

<details>
N/A
</details>

### celery_task.py
```python
from celery import Celery

celery_app = Celery("main_process")
celery_app.config_from_object("celery_config")

@celery_app.task
def add(x, y):
  return x + y

@celery_app.task
def raise_exception():
  raise Exception("test exception")
```

### celery_test.py
```python
import time
import celery
from celery import group
import celery_task # my task

task = group([celery_task.add.s(1, 2), celery_task.raise_exception.s()])()
while not task.ready(): # there will raise a unexpected exception
  pass
# Can do something with GroupResult.
```

### Reproduce Method
```
celery -A celety_task -l Info
python3 celery_test.py
```

# Expected Behavior

 `task.ready()` will return `True` after the two tasks were finished.

# Actual Behavior

However, `task.ready()` will reraise the excpetion caused by the task `raise_exception`.
```python
Traceback (most recent call last):
  File "celery_test.py", line 7, in <module>
    while not task.ready():
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 591, in ready
    return all(result.ready() for result in self.results)
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 591, in <genexpr>
    return all(result.ready() for result in self.results)
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 311, in ready
    return self.state in self.backend.READY_STATES
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 471, in state
    return self._get_task_meta()['status']
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 410, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 404, in _maybe_set_cache
    self.on_ready(self)
  File "/home/fishball/.local/lib/python3.6/site-packages/vine/promises.py", line 170, in call
    svpending(*ca, **ck)
  File "/home/fishball/.local/lib/python3.6/site-packages/vine/synchronization.py", line 67, in call
    self.p(*self.args, **self.kwargs)
  File "/home/fishball/.local/lib/python3.6/site-packages/vine/promises.py", line 170, in call
    svpending(*ca, **ck)
  File "/home/fishball/.local/lib/python3.6/site-packages/vine/promises.py", line 163, in call
    return self.throw()
  File "/home/fishball/.local/lib/python3.6/site-packages/vine/promises.py", line 160, in call
    retval = fun(*final_args, **final_kwargs)
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 877, in _on_ready
    ResultSet._on_ready(self)
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 519, in _on_ready
    self._cache = [r.get() for r in self.results]
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 519, in <listcomp>
    self._cache = [r.get() for r in self.results]
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 213, in get
    self.maybe_throw(callback=callback)
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 329, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/home/fishball/.local/lib/python3.6/site-packages/celery/result.py", line 322, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/home/fishball/.local/lib/python3.6/site-packages/vine/promises.py", line 237, in throw
    reraise(type(exc), exc, tb)
  File "/home/fishball/.local/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
Exception: test exception
```

# Other Information
This behavior only happens when the result backend is `Redis`. I had used the `RabbitMQ` as the result backend, but the issue not occurred.

**Comment by jirik** [comment] 2019-02-28 08:15
I can report the same behaviour:
## Environment & Settings
**Celery version**: 4.2.1 (windowlicker)

<p>

software -> celery:4.2.1 (windowlicker) kombu:4.3.0 py:3.6.8 billiard:3.5.0.5 redis:3.2.0
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis:6379/0

broker_url: 'redis://redis:6379/0'
result_backend: 'redis://redis:6379/0'
include: ['topo.db']
</p>

**Comment by auvipy** [comment] 2019-03-03 00:57
I guess this also reproducible in 4.3rc1?

**Comment by dizlv** [comment] 2019-03-08 12:09
@auvipy Recently tested with 4.3.0rc2 and it works properly with Redis backend, but 4.2 version throws an error (Redis backend, RabbitMQ works fine in 4.2).

**Comment by thedrow** [comment] 2019-04-04 09:10
In that case, please upgrade to 4.3.

**Comment by ikalyvas** [comment] 2019-05-13 10:59
Same thing happens to me with 4.3 and 3.2.1 as redis.Both results.ready and waiting with join_native will reraise the exception (even in i set the propagate to false).I downgraded to 4.3.0rc2 but same behaviour

**Comment by thedrow** [comment] 2019-05-14 13:23
I'll try this now.

**Comment by ikalyvas** [comment] 2019-05-14 13:30
@thedrow should we reopen also #5511 ?

**Comment by thedrow** [comment] 2019-05-14 13:32
One moment.

**Comment by thedrow** [comment] 2019-05-14 13:51
I cannot reproduce this.
I've written the following test out of the test case above:
```python
    @flaky
    def test_ready_with_exception(self):
        g = group([add.s(1, 2), raise_error.s()])
        result = g.apply_async()
        while not result.ready():
            pass
```

I've run the test using the redis broker and backend. It passes.

**Comment by ikalyvas** [comment] 2019-05-14 13:54
> I cannot reproduce this.
> I've written the following test out of the test case above:
> 
> ```python
>     @flaky
>     def test_ready_with_exception(self):
>         g = group([add.s(1, 2), raise_error.s()])
>         result = g.apply_async()
>         while not result.ready():
>             pass
> ```
> 
> I've run the test using the redis broker and backend. It passes.

What kind of exception does raise_error raises?

**Comment by thedrow** [comment] 2019-05-14 14:19
It raises a ValueError.

**Comment by thedrow** [comment] 2019-05-14 14:41
I just tried the same with an `Exception` and the result is similar.
As you can [see](https://travis-ci.org/celery/celery/jobs/532311502#L665) the test passes.
If you have more information on how to reproduce this issue, please do share.

I'm going to close this for now.

**Closed by thedrow** 2019-05-14 14:41 UTC
Labels: Component: Redis Results Backend, Issue Type: Bug Report
