### ISSUE TITLE
Broken pipe error on Linux

### ISSUE THREAD

**Issue by rjammala** [celery/celery#3328] opened 2016-07-20 04:51 UTC
@ask 

Here is the stacktrace. After this error happens, the worker process is not able to read from the queue. Only when I restart it, the worker process seems to run properly.

Please let me know if you need anything else

```
[2016-07-20 03:51:33,401: CRITICAL/MainProcess] Couldn't ack 6843, reason:error(104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/opt/app/lib/python2.7/site-packages/kombu-3.0.35-py2.7.egg/kombu/message.py", line 93, in ack_log_error
    self.ack()
  File "/opt/app/lib/python2.7/site-packages/kombu-3.0.35-py2.7.egg/kombu/message.py", line 88, in ack
    self.channel.basic_ack(self.delivery_tag)
  File "/opt/app/lib/python2.7/site-packages/amqp-1.4.9-py2.7.egg/amqp/channel.py", line 1584, in basic_ack
    self._send_method((60, 80), args)
  File "/opt/app/lib/python2.7/site-packages/amqp-1.4.9-py2.7.egg/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/opt/app/lib/python2.7/site-packages/amqp-1.4.9-py2.7.egg/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/opt/app/lib/python2.7/site-packages/amqp-1.4.9-py2.7.egg/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
  File "/opt/app/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/socket.py", line 460, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/opt/app/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/socket.py", line 437, in send
    return sock.send(data, flags)
error: [Errno 104] Connection reset by peer
[2016-07-20 03:51:35,281: INFO/MainProcess] Task app.tasks.process_logs[a0af85d1-93f7-41c9-aff1-982c3422c599] succeeded in 43.4386788909s: None
[2016-07-20 03:51:35,287: INFO/MainProcess] Task app.tasks.process_logs[efe67ffe-fc6d-4458-ba92-84a5aa24a49e] succeeded in 45.2530826852s: None
[2016-07-20 03:51:37,014: INFO/MainProcess] Task app.tasks.process_logs[32fbeb65-de86-4c9a-a9c5-54d425a5e39e] succeeded in 42.8365496462s: None
[2016-07-20 03:51:39,296: INFO/MainProcess] Task app.tasks.process_logs[766b5d41-e202-45b1-b93a-b9144d1a966b] succeeded in 592.266472305s: None
[2016-07-20 03:51:39,684: CRITICAL/MainProcess] Couldn't ack 6844, reason:error(32, 'Broken pipe')
Traceback (most recent call last):
  File "/opt/app/lib/python2.7/site-packages/kombu-3.0.35-py2.7.egg/kombu/message.py", line 93, in ack_log_error
    self.ack()
  File "/opt/app/lib/python2.7/site-packages/kombu-3.0.35-py2.7.egg/kombu/message.py", line 88, in ack
    self.channel.basic_ack(self.delivery_tag)
  File "/opt/app/lib/python2.7/site-packages/amqp-1.4.9-py2.7.egg/amqp/channel.py", line 1584, in basic_ack
    self._send_method((60, 80), args)
  File "/opt/app/lib/python2.7/site-packages/amqp-1.4.9-py2.7.egg/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/opt/app/lib/python2.7/site-packages/amqp-1.4.9-py2.7.egg/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/opt/app/lib/python2.7/site-packages/amqp-1.4.9-py2.7.egg/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
  File "/opt/app/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/socket.py", line 460, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/opt/app/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/socket.py", line 437, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
```

**Comment by ask** [comment] 2016-07-20 17:03
It's probable that the exception is not propagated to the main loop.  I think you should try master to see if the issue is there, as the acks have been moved to the main thread in that version which means the error is handled the same way as other connection errors.

**Comment by rjammala** [comment] 2016-07-20 19:31
Thanks ask. Once we downgraded the RMQ to a previous version (it was running the latest version when we had this issue), the issue seems to have resolved. If it happens again, will try the master.

**Comment by pkethe** [comment] 2016-11-23 19:53
@rjammala which version of RMQ did you see this issue?

**Comment by rjammala** [comment] 2016-11-25 06:16
I think it was 3.6

**Comment by auvipy** [comment] 2017-12-19 15:07
closing in favor of https://github.com/celery/kombu/pull/817

**Closed by auvipy** 2017-12-19 15:07 UTC
Labels: Component: Gevent Workers Pool, Version: 3.1

**Comment by auvipy** [comment] 2017-12-20 09:57
https://github.com/celery/celery/issues/3377 last answer is most suitable diagnosis of the issue
