### ISSUE TITLE
DatabaseScheduler may don't work in celery 4.1.0 

### ISSUE THREAD

**Issue by Nonomeme** [celery/celery#4184] opened 2017-08-07 13:32 UTC
## I happened to install celery 4.1.0 with django_celey_beat 1.0.1, the DatabaseScheduler seems not working well. 

[2017-08-07 21:12:10,790: DEBUG/MainProcess] DatabaseScheduler: Fetching database schedule
[2017-08-07 21:12:10,797: DEBUG/MainProcess] Current schedule:
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4 * * * (m/h/d/dM/MY)>>
<ModelEntry: schedule GeneBank.tasks.test(*[], **{}) <crontab: * * * * * (m/h/d/dM/MY)>>
[2017-08-07 21:12:10,807: DEBUG/MainProcess] beat: Ticking with max interval->5.00 seconds
[2017-08-07 21:12:10,809: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:12:15,813: DEBUG/MainProcess] beat: Synchronizing schedule...
[2017-08-07 21:12:15,813: INFO/MainProcess] Writing entries...
[2017-08-07 21:12:15,816: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:12:20,818: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:12:25,825: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:12:30,831: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:12:35,839: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:12:40,844: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:12:45,851: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:12:50,854: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:12:55,860: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:13:00,862: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:13:05,870: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
^C[2017-08-07 21:13:10,245: INFO/MainProcess] Writing entries...
[2017-08-07 21:13:10,246: INFO/MainProcess] Writing entries...

## As u can see, the scheduler was supposed to send beat at every minute, but the beat didn't show up,  (i've set crontab to be all *, so couldn't be timezone problem)

# But in celery 4.0.2, everything goes fine! I don't know whether it is a bug or not. Maybe the django_celery_beat isn't compatible with 4.1.0.

[2017-08-07 21:18:43,339: DEBUG/MainProcess] Current schedule:
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4 * * * (m/h/d/dM/MY)>>
<ModelEntry: schedule GeneBank.tasks.test(*[], **{}) <crontab: * * * * * (m/h/d/dM/MY)>>
[2017-08-07 21:18:43,351: DEBUG/MainProcess] beat: Ticking with max interval->5.00 seconds
[2017-08-07 21:18:43,364: INFO/MainProcess] Scheduler: Sending due task schedule (GeneBank.tasks.test)
[2017-08-07 21:18:43,376: DEBUG/MainProcess] beat: Synchronizing schedule...
[2017-08-07 21:18:43,376: INFO/MainProcess] Writing entries...
[2017-08-07 21:18:43,380: DEBUG/MainProcess] GeneBank.tasks.test sent. id->9c1bdf10-0a5f-440a-98db-9eb24433a8d4
[2017-08-07 21:18:43,381: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:18:48,386: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:18:53,392: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2017-08-07 21:18:58,397: DEBUG/MainProcess] beat: Waking up in 1.59 seconds.
[2017-08-07 21:19:00,001: INFO/MainProcess] Scheduler: Sending due task schedule (GeneBank.tasks.test)

**Comment by codeadict** [comment] 2017-08-08 18:26
I'm using both and they are working just fine

**Comment by gray314** [comment] 2017-08-09 06:33
after updating to version 4.1.0 from version 4.0.2 - got a similar error, the task scheduler does not work properly

**Comment by rekale** [comment] 2017-08-09 18:55
same here, when I downgrade to 4.0.2 it works again.

**Comment by rekale** [comment] 2017-08-10 05:42
I think this bug is related timezone, when I change the timezone to UTC it works.

CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

**Comment by AyumuKasuga** [comment] 2017-08-15 08:43
I can confirm this bug in 4.1.0

in my settings:
```python
CELERY_TIMEZONE = 'Europe/Moscow'
```

**Comment by matteius** [comment] 2017-08-18 15:25
Same issue -- we have multiple projects using celery beat but one of them happened to set the CELERY_TIMEZONE to be the project timezone which was America/NewYork.   Literally I woke up with 18 million messages in the Rabbit QA server because the workers couldn't keep up with the rate they are enqueued -- hundreds a minute.   Deleting the settings and letting the project default to CELERY_TIMEZONE of None also resolved the issue.

**Comment by matteius** [comment] 2017-08-18 15:26
FWIW -- I don't think we are using the DatabaseScheduler.

**Comment by georgepsarakis** [comment] 2017-08-19 07:54
@matteius @AyumuKasuga if you can run a test with the `master` branch to verify the fix, it would be great. Sorry for the issues.

**Comment by AyumuKasuga** [comment] 2017-08-22 08:44
Hello @georgepsarakis !
I have just tested master branch and unfortunately in my setup the issue is still exists.

**Comment by 117111302** [comment] 2017-08-24 08:22
Same here!

**Comment by gehaxelt** [comment] 2017-08-28 14:08
Hi, 

I have a similar problem. I followed the django-celery-beat setup instructions from: http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html

```
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
CELERY_RESULT_BACKEND = 'django-db'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
```

Then I define a periodic task:

```
@periodic_task(run_every=timedelta(seconds=30))
def do_stuff():
   print("HI")
```

When starting celery beat, I get the following output:
```
$> DJANGO_SETTINGS_MODULE="proj.settings.dev" celery -A proj beat -l info
celery beat v4.1.0 (latentcall) is starting.
__    -    ... __   -        _
LocalTime -> 2017-08-28 15:58:44
Configuration ->
    . broker -> amqp://guest:**@localhost:5672//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> django_celery_beat.schedulers.DatabaseScheduler

    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 seconds (5s)
[2017-08-28 15:58:44,425: INFO/MainProcess] Writing entries...
[2017-08-28 15:58:45,629: INFO/MainProcess] DatabaseScheduler: Schedule changed.
[2017-08-28 15:58:45,630: INFO/MainProcess] Writing entries...
```
The periodic task exists in the database and is marked as `enabled`.

However, a celery worker does not receive or execute any periodic tasks: 

```
$> DJANGO_SETTINGS_MODULE="proj.settings.dev" celery -A proj worker -l info -E
 
 -------------- celery@proj-dev v4.0.2 (latentcall)
---- **** ----- 
--- * ***  * -- Linux-4.4.0-83-generic-x86_64-with-Ubuntu-16.04-xenial 2017-08-28 15:57:42
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         proj:0x7f89f78faeb8
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . proj.tasks.do_nothgin
  . proj.tasks.do_stuff

[2017-08-28 15:57:42,269: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2017-08-28 15:57:42,287: INFO/MainProcess] mingle: searching for neighbors
[2017-08-28 15:57:43,324: INFO/MainProcess] mingle: all alone
```

Software:
```
celery==4.1.0
django-celery-beat==1.0.1
django-celery-results==1.0.1
Django==1.8.2
```

Any ideas/help to resolving this issue is welcomed. 

Best,
Sebastian

**Comment by mchen-scala** [comment] 2017-10-03 18:07
A piece of shit. It doesn't work.

**Comment by codeadict** [comment] 2017-10-03 18:27
@mchen-scala I that OSS projects are for collaborating and objective and constructive critics. How many lines of codes have you put in the piece of shit? I actually have Celery with beat working perfectly.

**Comment by mchen-scala** [comment] 2017-10-03 18:38
I have built far more advanced systems than you will ever have. I have written operating systems and built high-frequency trading platforms and large-scale cross-datacenter DBs. And many more.

Lines of code? I only look at systems that WORK. LOC is for tyros.

I have to use Celery because the system I inherited uses it. I am going to get rid of it and write my own once we are done our first delivery.

In addition to the beat problem, asking people to use a lock to ensure at-most-once property in task execution is a GIGANTIC JOKE.

Stick to what you are good at, which is OSS since you can't get high-paying jobs.

**Comment by matteius** [comment] 2017-10-03 19:26
@mchen-scala You have never written a complex system in your life, you cannot even understand the context of this ticket, which is that in the Celery 4 series there are some versions where the CELERY_BEAT_SCHEDULE is not followed if the timezone is not UTC.  

Your points are all inaccurate and insulting on many levels.  The joke is that you come here to insult us for working on an OSS project that suites the needs of many people across many industries.   I am going to assume anything you have ever written for an employer hasn't seen as much light of day as the Celery project as you actually haven't referenced any of your prior works.  In an agile world you would be releasing every 2-4 weeks, so the fact that you are working on a project that you inherited instead of these awesome systems you supposedly built only indicates to me that you have an inflated sense of self worth.

Furthermore mchen-scala, I do encourage you to switch off celery--primarily because we don't need your attitudes in our community.  I have a high paying job because I am able to leverage OSS and provide support to fixing issues as they arise.  I suggest you follow your own mantra and stick to what you are good at, which apparently is rolling your own solutions to problems with existing solutions, and being an antisocial jerk to the rest of us.  Cya!

**Comment by matteius** [comment] 2017-10-12 03:33
I have pin-pointed the exact line of code that is converting my already timezone aware datetime to a future datetime in an offset +20 that I am sure isn't a real timezone offset.
2017-10-11 22:42:27.041931-04:00 gets converted to 2017-10-12 22:42:27.041931+20:00 at the line in my Pull Request.
Apparently in UTC mode the datetime object stays the same at this point in the code.   So what happens next is the result of remaining_delta is interpreted as being -1 day, 1:27:32.958069 behind the task schedule.   So it sends out the task and doesn't sleep long because its always behind.  It just keeps beating out the tasks, always becuase its -1 days until the task is due.  

Granted my PR is commenting out a real old line of code, and yet all the unit tests seemed to pass and it did solve this issue in my testing.  Looking from collaborator feedback.

**Comment by matteius** [comment] 2017-10-15 13:48
I have shown this to be an issue on Python 2.7 as well as Python 3.5 and 3.6 versions.

**Comment by matteius** [comment] 2017-10-18 01:53
Could this be related/the same bug?  https://github.com/celery/celery/pull/4173

**Comment by xeor** [comment] 2017-10-20 13:38
I tried to migrate from not using the database for beat, to using django-celery-beat... The day have been mostly reading github issues :(

Is there anyone else not getting this to work when using `CELERY_TIMEZONE = 'UTC'`? I'm having problems getting it to work with that set as well..

**Comment by matteius** [comment] 2017-10-20 13:52
@xeor  You may also need to be setting CELERY_ENABLE_UTC = True

The actual issue of the datetime being passed into localize() is that if you have a local not UTC timezone set for your project, then that datetime already is correct going into localize and then dt = dt.astimezone(tz) transforms that into a non-nonsensical future datetime with a timezone that makes no sense.

**Comment by fillipo** [comment] 2017-10-20 20:02
@xeor I was having the same issue even with the following settings:

`CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'`

Now, I know it seems silly, but I uninstalled both Celery and Django, and installed them again with their latest version and it worked.

**Comment by xeor** [comment] 2017-10-20 20:09
Thanks.. I have tried with all those 3 as well, without luck.
I will try it later with a clean rebuild of the environment..

**Comment by matteius** [comment] 2017-10-20 21:06
@xeor  Well it is very well possible that this issue isn't the issue you are experiencing, though maybe it is.   The advice in this ticket has been consistent for all users experiencing this issue thus far, which lead to an out of control enqueuing of scheduled tasks and those tasking building up and not being processed properly because of that.   Could you describe more your specific problem as it doesn't appear you left a lot of details about the error(s) or the unexpected outcome you are getting?   

Always happy to help.  Just noting that we had this issue without the DatabaseScheduler and fixed it by only changing the timezones.  In my testing I showed that the schedule file generated before and after this bug were identical so I really don't think the bug is about the scheduler but rather the type of datetimes being passed into localize() call.

**Comment by xeor** [comment] 2017-10-20 21:11
Thanks for the heads-up!

I wont be able to take a deeper loop before maybe late next week or the week after. I'll keep my self informed on the progress in this thread in the mean time.

I'm not sure if my setup is anything special, but I am using docker, amqp, rabbitmq and all the newest versions of celery python packages (not rabbitmq tho).. (sorry, I don't have the env here so I can check)..

**Comment by chkdmin** [comment] 2017-11-10 06:03
I have similar issue, some times celery-beat does not work ( it doesn't send task to broker ) Additionally, it sends too much tasks at every 59 minute
I made a test task to run every minute
```
[2017-11-09 20:52:00,052: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:53:00,049: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:54:00,019: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:55:00,027: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:56:00,049: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:57:00,004: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:58:00,045: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:00,032: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:00,035: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:00,037: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:00,044: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
...
[2017-11-09 20:59:59,977: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:59,979: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:59,981: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:59,986: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:59,989: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:59,994: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 20:59:59,997: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 21:00:00,000: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 21:01:00,047: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 21:02:00,047: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)
[2017-11-09 21:03:00,053: INFO/MainProcess] Scheduler: Sending due task test-task (myrics.tasks.test.test_task)

```
On minute 59, bunch of tasks starts running and when the time hits minute 0 it runs as expected again.
I have no clue about this bug..?

This is my setting in celery 4.1.0
```
timezone = 'Asia/Seoul'
enable_utc = False
```
I using file db for schedule

**Comment by dwrpayne** [comment] 2017-11-30 16:07
I have this issue as well on celery 4.1.0 and django-celery-beat 1.1.0. 

As soon as I run the beat with --scheduler django_celery_beat.schedulers:DatabaseScheduler, I get hundreds of events sent per second.

My settings are (I set everything I could find because the documentation is extremely unclear and outdated in several places):

settings.py
CELERY_TIMEZONE = 'Canada/Pacific'
CELERY_ENABLE_UTC=False
USE_TZ = True
TIME_ZONE = 'Canada/Pacific'

celery.py
app = Celery('MyApp')
app.config_from_object('django.conf:settings', namespace='CELERY')
app.conf.timezone = 'Canada/Pacific'
app.conf.enable_utc = False


In my database, when I run at 08:04:02 local time (pacific, utc-8), the last_run_at column of the table django_celery_beat_periodictask is set to 2017-11-30 16:04:02.3 -08

So it's clear what is happening is that celery runs the task at 08:04:02-08, but then when storing the last_run_time, it converts that time to UTC while maintaining the timezone info on it. The database should only contain either 08:04:02-08 or 16:04:02+00.

**Comment by matteius** [comment] 2017-12-13 17:04
Alright -- If everyone that had this bug could clone master and re-test that it fixes the issue for you.  My PR was merged in last night and I just verified that it fixed the bug but it would be good to get additional confirmation of that for those that use the DB scheduler or other backends.  Thanks!

**Comment by auvipy** [comment] 2017-12-21 04:45
976515108a4357397a3821332e944bb85550dfa2 apply this and check

**Closed** 2017-12-21 04:45 UTC
Labels: Component: Celerybeat
