### ISSUE TITLE
Does the live woker list store in redis key named “_kombu.binding.celeryev”?

### ISSUE THREAD

**Issue by Liubey** [celery/celery#7947] opened 2022-12-08 03:28 UTC
Hi everyone
I want to monitor the worker who is alive and dead.
Does the live woker list store in redis key named “_kombu.binding.celeryev”?
If confirmed, I can read the content of the key to monitor workers😄

**Comment by auvipy** [comment] 2022-12-15 03:46
closing as duplicate of https://github.com/celery/kombu/issues/1624

**Closed by auvipy** 2022-12-15 03:46 UTC
Labels: Issue Type: Enhancement
