### ISSUE TITLE
BUG: Bad page map in process celery  pte:fd20b000 pmd:16d7b08067

### ISSUE THREAD

**Issue by vallee11** [celery/celery#4577] opened 2018-03-07 06:14 UTC
Mar  6 10:13:53 h3class01 kernel: [8883126.929572] swap_free: Bad swap file entry 007e9058
Mar  6 10:13:53 h3class01 kernel: [8883126.929580] BUG: Bad page map: 31 messages suppressed
Mar  6 10:13:53 h3class01 kernel: [8883126.929583] BUG: Bad page map in process celery  pte:fd20b000 pmd:16d7b08067
Mar  6 10:13:53 h3class01 kernel: [8883126.929588] addr:00007fb3611a5000 vm_flags:08100073 anon_vma:ffff8801b4b13910 mapping:          (null) index:7fb3611a5
Mar  6 10:13:53 h3class01 kernel: [8883126.929593] file:          (null) fault:          (null) mmap:          (null) readpage:          (null)
Mar  6 10:13:53 h3class01 kernel: [8883126.929599] CPU: 38 PID: 488 Comm: celery Tainted: G    B      OE   4.1.0-generic #1
Mar  6 10:13:53 h3class01 kernel: [8883126.929601] Hardware name: New H3C Technologies Co., Ltd. UIS R390X G2/RS32M2C9S, BIOS 1.00.23P01 07/07/2017
Mar  6 10:13:53 h3class01 kernel: [8883126.929602]  0000000000000000 ffff881895aa7a50 ffffffff817ee563 ffff88109d7f0170
Mar  6 10:13:53 h3class01 kernel: [8883126.929605]  00007fb3611a5000 ffff881895aa7aa0 ffffffff811b73f5 00000020beb9a067
Mar  6 10:13:53 h3class01 kernel: [8883126.929607]  00000000fd20b000 ffff881895aa7aa0 00007fb3611a6000 ffff8816d7b08d28
Mar  6 10:13:53 h3class01 kernel: [8883126.929609] Call Trace:
Mar  6 10:13:53 h3class01 kernel: [8883126.929621]  [<ffffffff817ee563>] dump_stack+0x63/0x81
Mar  6 10:13:53 h3class01 kernel: [8883126.929628]  [<ffffffff811b73f5>] print_bad_pte+0x1e5/0x280
Mar  6 10:13:53 h3class01 kernel: [8883126.929630]  [<ffffffff811b935d>] unmap_single_vma+0x7dd/0x830
Mar  6 10:13:53 h3class01 kernel: [8883126.929635]  [<ffffffff8119834c>] ? release_pages+0x1ec/0x270
Mar  6 10:13:53 h3class01 kernel: [8883126.929638]  [<ffffffff811b9654>] unmap_vmas+0x54/0xa0
Mar  6 10:13:53 h3class01 kernel: [8883126.929640]  [<ffffffff811c287b>] exit_mmap+0x9b/0x160
Mar  6 10:13:53 h3class01 kernel: [8883126.929645]  [<ffffffff8107b5d4>] mmput+0x64/0x130
Mar  6 10:13:53 h3class01 kernel: [8883126.929649]  [<ffffffff81209628>] flush_old_exec+0x4e8/0xa10
Mar  6 10:13:53 h3class01 kernel: [8883126.929655]  [<ffffffff812578fd>] load_elf_binary+0x35d/0x1830
Mar  6 10:13:53 h3class01 kernel: [8883126.929657]  [<ffffffff811b6902>] ? get_user_pages+0x52/0x60
Mar  6 10:13:53 h3class01 kernel: [8883126.929659]  [<ffffffff81208809>] ? get_arg_page+0xa9/0xe0
Mar  6 10:13:53 h3class01 kernel: [8883126.929660]  [<ffffffff81208b8f>] search_binary_handler+0x9f/0x1e0
Mar  6 10:13:53 h3class01 kernel: [8883126.929662]  [<ffffffff8120a3de>] do_execveat_common.isra.28+0x58e/0x740
Mar  6 10:13:53 h3class01 kernel: [8883126.929663]  [<ffffffff8120a5bc>] do_execve+0x2c/0x30
Mar  6 10:13:53 h3class01 kernel: [8883126.929666]  [<ffffffff81212be2>] ? getname+0x12/0x20
Mar  6 10:13:53 h3class01 kernel: [8883126.929667]  [<ffffffff8120a84e>] SyS_execve+0x2e/0x40
Mar  6 10:13:53 h3class01 kernel: [8883126.929672]  [<ffffffff817f6915>] stub_execve+0x5/0x5
Mar  6 10:13:53 h3class01 kernel: [8883126.929674]  [<ffffffff817f65f2>] ? system_call_fastpath+0x16/0x75 
celery
execve

**Comment by thedrow** [comment] 2018-03-08 06:31
There's nothing in this issue that helps us reproduce the problem you are having.
Please provide a testcase, the Python version you are using, the OS version, the Celery version you are using etc.
Right now since there's no actionable information to go on, I'm going to close this issue.
Please comment with more information and we'll reopen.

**Closed by thedrow** 2018-03-08 06:31 UTC
Labels: Status: Feedback Needed ✘
