### ISSUE TITLE
How to troubleshoot freezing Celery workers

### ISSUE THREAD

**Issue by hheimbuerger** [celery/celery#2930] opened 2015-11-19 11:05 UTC
Ever since we went to production about three years ago with an application using Celery 3.1.x (mostly using 3.1.17 and 3.1.18, now 3.1.19), we've seen the worker process occasionally freezing.

We're running on Heroku, with a `Procfile` that describes three processes to run in the same dyno: 

    celeryd: celery beat --app=myapp --loglevel=INFO & celery worker --app=myapp --queues=priority,default --hostname=default.worker --concurrency=5 --loglevel=INFO & celery worker --app=myapp --queues=priority --hostname=priority.worker --concurrency=3 --loglevel=INFO

So there's the beat scheduler, a default worker process that processes both queues with some concurrency and a priority worker that only works the priority queue with some concurrency.

I've never had any issues with the beat scheduler process, or the priority worker, although there's very little load on either of those. (In total, we're just processing about 20 tasks per hour, all on a single dyno.)

The middle one is the problematic one. What I sometimes see is that it just stops processing new incoming tasks. There is no specific log message to this. The the other processes are working just fine, i.e. I see the priority worker still taking and happily working through tasks from the priority queue. So I can definitely say that the Heroku dyno is still running fine.

Over the last three years, this slowly started appearing. Then it once was gone for a couple of months. Then it got really bad for a month or two, freezing workers every 6–12 hours. Then we switched to IronMQ as the message queue, and it got much better, but never went away entirely (making me assume it has nothing to do with the message queue directly).

Right now, this only occurs once every week on average (with a wide spread, it might also not occur for a couple of weeks, but I also don't have a reliable way of detecting it), so I can't reproduce it on command. I therefore need to wait a long time to see if any individual change has a lasting effect (and I'm then usually unable to narrow it down to one specific change, because of course we made various updates to the app in that timeframe).  
But it's still bad enough that it's affecting our customers, of course.

I have tried a lot of things, but never could really find any pattern. It doesn't seem to be caused by a specific task of ours. I'm open for any idea you guys are having, or any advice what to look out for or what to try.

Specifically, I was wondering if somehow had an idea how to troubleshoot this, the next time I actually have this frozen worker in front of me in that state. What should I do to look into it?

An issue is probably that this only occurs in our production system on Heroku. I believe I'm not able to inspect the process in the traditional way, because they're running Docker-like containers which I can't get into. I've tried `celery status` in a new one-off dyno, but I'm always getting a `Error: No nodes replied within time constraint.`. I could find much information on this in the Celery documentation, but I guess `celery status` always has to be run on the same machine because it uses some kind of IPC to communicate with the workers? (EDIT: After reading [this table](http://docs.celeryproject.org/en/latest/getting-started/brokers/#broker-overview), I guess the issue is also that IronMQ has no "remote control" support.)

What other things could I do to get to the root of this issue?

**Comment by ask** [comment] 2015-11-25 01:13
IronMQ is not using the new async worker so it can easily deadlock if child processes are terminated.  For this reason using --time-limits is a bad idea, as that may terminate worker child processes.

**Comment by hheimbuerger** [comment] 2015-11-25 10:17
What do you mean by "using --time-limits". I've never used that, wasn't even aware that it exists in Celery. What makes you think that is related to my issues?

Do you have any advice on how to deal with that? What could make the "child processes terminate"? Is there any logging I should watch out for to investigate why this happens? (Right now, logging just stops in these situations, but maybe I just need to expand my logging config?)

Is there any other way you would recommend to monitor this? Should I just cycle my Celery workers more often?

**Comment by ask** [comment] 2015-12-02 00:48
Time limits is a feature that will terminate child processes.

The problem could also be related to your actual tasks running too long, but it's not that easy to debug without remote control support.  You would have to look at the log to see tasks that were received but have taken a long time to complete.

**Comment by Bakirelived** [comment] 2015-12-16 14:12
I have a problem with similar behaviour, but I use rabbitMQ. reported it here: https://github.com/celery/django-celery/issues/406
The traceback is logged by apache..
In my situation I have 5 workers with 5 queues and concurrency of 1. I can recreate the problem if I lunch and revoke tasks for a while, sometimes the error occurs. Do you think your problem can be caused by revoking tasks?

**Comment by hheimbuerger** [comment] 2015-12-18 13:06
@Bakirelived I am never revoking tasks and I'm not using time limits at all.

I've seen my issue both on the Django ORM broker as well as the IronMQ broker. I was gonna try RabbitMQ next, but you're not making me very hopeful that it's gonna resolve my issue.

The issue you linked to sounds like it's more related to the (MySQL) results backend than the message queue, however. The "server has gone away" is a very old and well-known (but often cryptic) MySQL error message.
I'm using PostgreSQL as my results backend. I wasn't considering that as a source of my issues yet, as most of my tasks use `ignore_result=True`, but I can't fully rule it out, of course.

**Comment by Bakirelived** [comment] 2015-12-18 14:51
@hheimbuerger I'll try and use PostrgreSQL and run my test env to try and recreate my error. ty for your reply.

I will also keep an eye on this issue to see your progress, I hope you can fix it soon.

**Comment by Bakirelived** [comment] 2015-12-22 15:33
@hheimbuerger Just finished testing an env with postgres backend, and the problem didn't occur. than swapped the settings to run the same testing with mysql DB and it happened in 30s. TY for your sugestion, it seams that using PostgreSQL solves my problem.(I still use with RabbitMQ)

**Comment by hheimbuerger** [comment] 2016-02-16 13:10
Just cross-linking here. In http://stackoverflow.com/a/17543425/6278, @amezhenin writes:

> I also had problem, when celery workers stops consuming tasks, it was caused by a bug with celery+gevent+sentry(raven) combination.

Sounds like it could have the same cause. I'm hoping he has more information to provide and maybe has already debugged this and was able to determine the cause.

**Comment by hheimbuerger** [comment] 2016-02-16 13:13
Btw., as a personal update, this has become more common again (happing almost every day/night) and now very often I see the priority worker freezing as well, something that has almost never happened before.

**Comment by ask** [comment] 2016-02-26 22:58
Are you using gevent? @amezhenin mentions that specifically and I don't see that mentioned in this issue.

**Comment by hheimbuerger** [comment] 2016-02-27 18:46
@ask I think you're right, I am not using gevent. At least I'm not using the `-P` argument on my workers right now.

I struggled a bit with understanding the pool concept, this research is what had originally spawned my other question (since answered): https://github.com/celery/celery/issues/3061

Still, I'm heavily using Sentry/Raven, so I don't want to fully rule out the connection to @amezhenin's issue.

Anyway, I'm planning to switch to RabbitMQ this weekend and I'm still keeping my hopes up that this will finally resolve my issues…

**Comment by hheimbuerger** [comment] 2016-03-03 23:01
About a week ago, I switched from IronMQ to RabbitMQ and since, I haven't encountered any issues of the kind described here. So I'm just blaming the pretty abysmal Celery support of IronMQ on this (despite their iron-celery library) and I can just highly recommend anyone not to use it with Celery.

Don't fall for their 'commercial support' promise! ;) CloudAMQP actually has really amazing support!

It was also the CloudAMQP support who first pointed out an issue with the way I ran my celery workers (see the very first code block above): if you run multiple processes on Heroku the way I did, of course it won't be able to notice when one of them dies and restart the dyno. Doesn't explain why my workers stopped (probably due to the many API error responses I received every day from IronMQ), but at least why the system didn't auto-heal itself.

As it stands, I'm considering this issue solved.

**Comment by hheimbuerger** [comment] 2016-03-16 15:58
Had a freezing worker again this morning, even though we're now using a professionally hosted RabbitMQ server with a fairly standard setup. :disappointed: 

Here's the log output from that worker host right before and after the freeze:

    Mar 16 11:50:22 myapp app/worker.1: INFO [-/-/-/-/celery.worker.job] Task myapp.recheck_api_connection[d56ec5a2-1807-4555-bd0a-57206e0819a1] succeeded in 1.35833065602s: None 
    Mar 16 11:50:22 myapp app/worker.1: INFO [-/-/-/-/celery.worker.strategy] Received task: myapp.recheck_api_connection[e1ddf5e2-a7f2-4ae1-ab59-3024d13ef4a0] 
    Mar 16 15:57:26 myapp heroku/worker.1: Restarting 
    Mar 16 15:57:26 myapp heroku/worker.1: State changed from up to starting 
    Mar 16 15:57:29 myapp heroku/worker.1: Stopping all processes with SIGTERM 
    Mar 16 15:57:29 myapp app/worker.1: worker: Warm shutdown (MainProcess) 
    Mar 16 15:57:29 myapp app/worker.1: INFO [myapp.recheck_api_connection/celery@worker/68accb16/acc0073/myapp.api] Performing API connection check

(Note that due to how the Heroku logplex works, the order of these log lines might be slightly off, specifically the ones occuring in the same second.)

So basically, it finished a task, started a new one, and then it just didn't do anything for four hours until it proceeded with its work.

It's interesting that a warm shutdown occured in the same second. I guess that is what triggered the task to wake up. If someone can explain to me why/how, that would be helpful. (Also keep in mind that due to https://github.com/celery/celery/issues/2839, we have to assume that currently, Heroku sends a SIGTERM to *all* the worker processes in that dyno.)

Looking at just the log output from another task (the one that unfroze due to the SIGTERM) gives an interesting picture into what happened:

    Mar 16 07:30:00 myapp app/worker.1: INFO [myapp.schedule_api_rechecks/celery@worker/fb5bb328/-/myapp.tasks] Scheduled task 68accb16-b869-4c59-b26e-8756a1b36292 for API connection recheck
    Mar 16 07:30:00 myapp app/worker.1: INFO [-/-/-/-/celery.worker.strategy] Received task: myapp.recheck_api_connection[68accb16-b869-4c59-b26e-8756a1b36292] 
    Mar 16 15:57:29 myapp app/worker.1: INFO [myapp.recheck_api_connection/celery@worker/68accb16/acc0073/myapp.cwapi] Performing API connection check
    Mar 16 15:57:30 myapp app/worker.1: INFO [myapp.recheck_api_connection/celery@worker/68accb16/acc0073/myapp.wslib] Received response from API
    Mar 16 15:57:32 myapp app/worker.1: INFO [-/-/-/-/celery.worker.job] Task myapp.recheck_api_connection[68accb16-b869-4c59-b26e-8756a1b36292] succeeded in 30450.4836294s: None 

Note how this task already froze at 7:30, while some others apparently kept working (and logging) until around 11:50. The worker runs with `--concurrency=6`, so I guess these tasks kept piling up until all six worker processes were frozen. Then the whole worker was inactive for four hours, until the SIGTERMs magically brought them back to life.

Reviewing the logs, I found a more tasks behaving the same: they were "received" by the worker, then didn't log anything until many hours later. Note that the "Performing API connection check" is the *very first* line in the task code. So I have to assume that it's freezing somewhere in Celery code and not my application logic.

Any help with interpreting these data point or explaining some behavior would be helpful to me. I'm still struggling to understand a lot of the details of what's going on here.

**Comment by realjackofall** [comment] 2016-06-08 10:39
@hheimbuerger I had the exact same issue where tasks were getting backed up in worker nodes that were running long running tasks. The problem surfaced after we moved from celery 3.0 to 3.1. It turned out that the backing up of tasks was related to prefetch. I was able to solve the backing up problem by disabling prefetch. See my answer here - http://stackoverflow.com/questions/16040039/understanding-celery-task-prefetching/37699960#37699960

HTH

**Comment by hheimbuerger** [comment] 2016-06-08 10:45
For the record, in the last case I described, my worker was not processing *anything* for 8h, so I'm not sure if that was related to prefetching.

**Comment by ask** [comment] 2016-06-24 01:02
Closing this, as we don't have the resources to support IronMQ.

**Closed by ask** 2016-06-24 01:02 UTC
Labels: Category: Experimental Features

**Comment by bivald** [comment] 2016-08-12 10:02
@hheimbuerger are you still experience the same issues? I'm seeing similar things, and I'm also using RabbitMQ and celery.

**Comment by hheimbuerger** [comment] 2016-08-12 14:19
@bivald I do, but it happens fairly rarely (but then rather catastrophically) and I don't have a good setup to monitor for the complete absence of activity, so it's hard to tell details.

Which issue exactly are you experiencing? My issues have changed quite a bit across this thread (that's why ask rightfully closed it, not even the title is really accurate anymore), what I have right now is what I wrote in the most recent longer post.

Is that what you have? Would help if you were really precise in what exactly you're experiencing and all the information you've already gained.

**Comment by billmccord** [comment] 2018-11-14 03:19
@bivald @hheimbuerger Are you still having this issue today? I'm seeing it frequently when using latest RabbitMQ, Erlang, on CloudAMQP with latest Celery, billiard, etc. We've followed all the recommendations from CloudAMQP and can't seem to identify the issue, but it happens nearly every evening like clockwork just after midnight.

**Comment by billmccord** [comment] 2018-11-20 09:03
@hheimbuerger Fair and thanks for the advice. I'm testing with a new configuration and will create a new ticket if I still have issues. Seems [CloudAMQP now recommends](https://www.cloudamqp.com/docs/celery.html) setting `broker_heartbeat` to None.

**Comment by auvipy** [comment] 2018-12-04 08:04
thanks for reporting!
