### ISSUE TITLE
Pickle serialization kills multiple workers

### ISSUE THREAD

**Issue by ronmorannielsen** [celery/celery#5075] opened 2018-09-26 19:49 UTC
First thing's first, the config (celery report):

```
broker_url: 'amqp://<username>:********@vlb:5672//'
result_backend: 'rpc://<username>:********@vlb:5672/'
include: [modules]
result_expires: 3600
worker_prefetch_multiplier: 1
worker_pool_restarts: True
broker_pool_limit: 700
accept_content: {'pickle'}
task_serializer: 'pickle'
result_serializer: 'pickle'
event_serializer: 'pickle'
```

When starting a celery worker on a specific amqp broker, everything starts out fine. It receives pickle-serialized tasks, returns the value and everything seems alright.
The problem arises when I start a new worker, consuming from the same broker.
Both workers nearly immediately die with a long exception (same for both):

> [2018-09-26 19:42:16,028: CRITICAL/MainProcess] Unrecoverable error: ContentDisallowed('Refusing to deserialize disabled content of type pickle (application/x-python-serialize)',)

```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 598, in start
    c.loop(*c.loop_args())
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/kombu/transport/base.py", line 236, in on_readable
    reader(loop)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/amqp/method_framing.py", line 77, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/amqp/channel.py", line 1597, in _on_basic_deliver
    fun(msg)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/celery/worker/consumer/gossip.py", line 201, in on_message
    _, event = prepare(message.payload)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/kombu/message.py", line 207, in payload
    return self._decoded_cache if self._decoded_cache else self.decode()
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/kombu/message.py", line 192, in decode
    self._decoded_cache = self._decode()
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/kombu/message.py", line 197, in _decode
    self.content_encoding, accept=self.accept)
  File "/home/ubuntu/.virtualenvs/python36/lib/python3.6/site-packages/kombu/serialization.py", line 256, in loads
    raise self._for_untrusted_content(content_type, 'disabled')
kombu.exceptions.ContentDisallowed: Refusing to deserialize disabled content of type pickle (application/x-python-serialize
```

As you can see the accept_content field is set to "pickle" and pickle alone.

Issue rises when using celery 4.2.0 and celery 4.2.1 as installed from global pypi.

It's a problem for us since JSON serialization won't work for our purposes, we're sending binary objects over celery.

## Steps to reproduce
To reproduce, simply start two workers with the same config shown above with the same broker.

Thanks!

**Comment by auvipy** [comment] 2018-10-13 18:47
could you try json serializer?

**Comment by ronmorannielsen** [comment] 2018-10-17 08:37
As I said, JSON serialization won't work for our purposes. Anyway, pickle is (supposedly) supported, so how come I keep gettings this content disallowed message?

**Comment by ronmorannielsen** [comment] 2018-11-18 14:37
Is there any solution for this? Did any of you encountered the issue?

**Comment by calhamdower** [comment] 2019-02-07 06:38
Bump also, I have ran into this issue. Anyone have a work around?

**Comment by RESHNAM** [comment] 2019-11-26 06:23
Upgrading Celery worked for me!

**Comment by auvipy** [comment] 2019-11-26 10:04
upgrading to celery 4.4.0rc4?

**Comment by hishamkaram** [comment] 2020-04-01 19:15
@auvipy still have the same issue with multiple workers celery version is: `4.4.2`

**Comment by hishamkaram** [comment] 2020-04-01 19:16
<img width="1375" alt="Screen Shot 2020-04-02 at 2 16 07 AM" src="https://user-images.githubusercontent.com/24391550/78177188-eb946780-7487-11ea-9dd1-76dbf19947ae.png">

**Comment by auvipy** [comment] 2020-04-02 04:18
its seems to be a kombu issue

**Comment by auvipy** [comment] 2020-04-02 04:19
can you dig deeper?

**Comment by hishamkaram** [comment] 2020-04-02 04:30
@auvipy sure and i will share my config

**Comment by hishamkaram** [comment] 2020-04-03 02:26
@auvipy the issue was the incorrect configuration for Exchange

**Comment by escattone** [comment] 2020-06-22 23:28
Can anyone share what they did to resolve this issue? We're seeing the same thing (using Celery 4.4.5 along with Kombu 4.6.10) when we use multiple workers. Thanks.

**Comment by auvipy** [comment] 2020-06-24 06:00
can you move to json serializer?

**Comment by escattone** [comment] 2020-06-25 16:35
@auvipy Yes, our team decided to do that yesterday, i.e. move to using the `json` serializer. It'll take some extra work, but it's not too bad. Cheers.

**Comment by kitsuyui** [comment] 2020-12-28 09:25
This seems to be caused by un-matching serialization protocol between internal-event and user-defined event.

https://github.com/celery/celery/blob/8492b75c579564c2af5c2be75fe4b2118ebd0cd1/celery/worker/consumer/gossip.py#L173-L180
`Gossip().get_consumers` receive events. but currently it doesn't take care serialization protocol.

I created this repro.

## reproduction

```python
from celery import Celery


app = Celery('example')
app.conf.update(
    backend_url='redis://localhost:6379',
    broker_url='redis://localhost:6379',
    result_backend='redis://localhost:6379',
    event_serializer='pickle',
    result_serializer='pickle',
    accept_content=['pickle', 'json'],
)
```

Running two workers in separate shell.

```sh
celery -A repro worker -n worker1 -c 2
celery -A repro worker -n worker2 -c 2
```

Following error will be appeared.

```
Refusing to deserialize disabled content of type pickle (application/x-python-serialize)
```

**Comment by Radiergummi** [comment] 2023-02-06 08:01
Is this resolved? We're experiencing the same issue. Celery is configured correctly for pickle, but workers in production only log the following, even if the queue is empty:
```
[2023-02-06 07:51:30,750: ERROR/MainProcess] Refusing to deserialize disabled content of type pickle (application/x-python-serialize)
```

**Comment by auvipy** [comment] 2023-02-06 08:25
we have an open pr for this issue, https://github.com/celery/celery/pull/6566 , can you check and verify that please?

**Comment by Radiergummi** [comment] 2023-02-06 12:46
Actually, I solved this by enabling pickle manually:

```
from kombu.serialization import registry

app = Celery("app")
registry.enable("pickle")
```

I'll see if I get around to verifying the PR locally and get back to you.

**Comment by auvipy** [comment] 2023-10-14 05:25
can you also comment about this solution, please https://github.com/celery/celery/pull/6566#issuecomment-1762375242 ?

**Comment by wlach** [comment] 2023-10-21 11:55
Just FYI in case it helps someone-- @Radiergummi's workaround above seems to work with more recent versions of celery, but not older ones (e.g. 4.4.0). This is important to bear in mind when upgrading/downgrading between them. When upgrading, you can use the workaround. When downgrading, you will need to disable gossip temporarily. This will be the case even after #6566 (which I presume will fix the problem) is merged

**Comment by auvipy** [comment] 2023-10-22 10:56
v4.4.0 is a long EOL now FYI

**Closed** 2023-11-08 10:38 UTC
Labels: Issue Type: Bug Report, serializer, Component: Task Serialization, Worker

**Comment by auvipy** [comment] 2023-11-08 10:39
we got a fix on the main branch. please test and report. this fix is going to be part of celery 5.3.5 release in this week.

**Comment by mrn-aglic** [comment] 2024-01-25 09:57
@auvipy was the fix released and working?

**Comment by auvipy** [comment] 2024-01-25 10:58
this was the prospective fix https://github.com/kitsuyui/celery/commit/c8f286b1eafdae56b9938cf9f5ea319ebd45429d

**Comment by mrn-aglic** [comment] 2024-01-25 11:33
Found it:
Fix: serialization error when gossip working by @kitsuyui in https://github.com/celery/celery/pull/6566

Thank you :-)
