### ISSUE TITLE
Celery 4: Class based tasks aren't getting registered. 

### ISSUE THREAD

**Issue by grilam14** [celery/celery#5992] opened 2020-03-06 17:06 UTC
I know there are a few other posts similar to this already, and I have copied their solutions.

```
Example = app.register_task(Example()) 
Example.apply_async()
```

But this format does not register tasks. I think there must be a simple problem with my app or celery settings. Class-based tasks are still supposed to work, right? When I run tasks.py in isolation and print tasks, I can see the class-based tasks as registered. By the time they get to the workers, they are no longer registered, but my decorator-based tasks are. 

Edit: Further work. When I run 

```
celery -A caliper.celery.celery_app:app inspect registered
```

I can actually see the QueuedOneTimeSurvey task in there, BUT the workers are - empty -. When I add a task to the queue, then all of the decorator-base tasks get added to the workers, but the lone class-based task doesn't get added. 

# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

https://github.com/celery/celery/issues/4112

https://github.com/celery/celery/issues/3874

https://github.com/celery/celery/issues/3744

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.0

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.0 (cliffs) kombu:4.6.8 py:3.7.6
            billiard:3.6.3.0 py-amqp:2.5.2
platform -> system:Linux arch:64bit, ELF
            kernel version:4.4.0-1098-aws imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

CELERYD_LOG_LEVEL: 'INFO'
CELERY_ACCEPT_CONTENT: ['pickle']
CELERY_BROKER_URL: 'amqp://staging:********@********'
CELERY_IMPORTS: ['caliper.celery.tasks',
 'caliper.celery.tasks_lambda']
CELERY_RESULT_SERIALIZER: 'pickle'
CELERY_SEND_TASK_ERROR_EMAILS: True
CELERY_TASK_DEFAULT_EXCHANGE: 'default'
CELERY_TASK_DEFAULT_EXCHANGE_TYPE: 'direct'
CELERY_TASK_DEFAULT_QUEUE: 'caliper.default'
CELERY_TASK_IGNORE_RESULT: True
CELERY_TASK_QUEUES: {
    'caliper.OneTimeSurvey': {'binding_key': '********'},
    'caliper.default': {'binding_key': '********'}}
CELERY_TASK_ROUTES:
    ('caliper.celery.routers.CaliperRouter',)
CELERY_TASK_SERIALIZER: 'pickle'
CELERY_WORKER_PREFETCH_MULTIPLIER: 4
binding: {
 'binding_key': '********'}
existing: {
 }
os: <module 'os' from '/usr/lib/python3.7/os.py'>
q: 'caliper.OneTimeSurvey'
settings: <module 'siphon.settings' from '/deploy/siphon/siphon/settings.py'>
settings_messagebroker: <module 'siphon.settings_messagebroker' from '/deploy/siphon/siphon/settings_messagebroker.py'>
task_protocol: 1
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7
* **Minimal Celery Version**: 4.4.0
* **Minimal Kombu Version**: 4.6.8
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: Ubuntu 16
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.5.2
anyjson==0.3.3
asgiref==3.2.3
backcall==0.1.0
bcrypt==3.1.7
beautifulsoup4==4.5.1
billiard==3.6.3.0
boto==2.38.0
boto3==1.4.0
botocore==1.4.93
celery==4.4.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
concurrencytest==0.1.2
cryptography==2.8
decorator==4.4.1
Django==3.0
django-localflavor==2.2
django-ses==0.8.13
django-timedeltafield==0.7.10
djorm-pgarray==1.2
docutils==0.16
dogslow==1.2
ExifRead==2.1.2
extras==1.0.0
facebook-sdk==3.1.0
fixtures==3.0.0
flickrapi==2.4.0
future==0.18.2
geographiclib==1.50
geojson==2.5.0
geopy==1.20.0
graypy==2.1.0
html2text==2019.9.26
httplib2==0.14.0
idna==2.8
importlib-metadata==1.5.0
ipython==7.10.2
ipython-genutils==0.2.0
iso8601==0.1.12
jedi==0.16.0
jmespath==0.9.4
kafka==1.3.5
kombu==4.6.8
linecache2==1.0.0
lxml==4.5.0
mock==3.0.5
nose==1.3.7
numpy==1.17.4
oauth==1.0.1
oauth2==1.9.0.post1
oauthlib==3.1.0
overpy==0.4
pandas==0.25.3
paramiko==2.7.1
parso==0.6.1
pbr==5.4.4
pexpect==4.8.0
pickleshare==0.7.5
Pillow==6.2.1
prompt-toolkit==3.0.3
psycopg2==2.7.5
ptyprocess==0.6.0
pycparser==2.19
Pygments==2.5.2
pykml==0.2.0
pylibmc==1.6.1
PyNaCl==1.3.0
python-dateutil==2.8.1
python-mimeparse==1.6.0
python-stdnum==1.13
python-subunit==1.3.0
pytz==2019.3
raven==6.10.0
requests==2.22.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
s3transfer==0.1.13
scipy==1.4.0
selenium==3.141.0
simplekml==1.3.1
six==1.14.0
SQLAlchemy==1.3.12
sqlalchemy-redshift==0.7.5
sqlparse==0.3.0
testtools==2.3.0
traceback2==1.4.0
traitlets==4.3.3
unittest2==1.1.0
urllib3==1.25.8
utm==0.5.0
vine==1.3.0
virtualenv==16.7.9
wcwidth==0.1.8
xlrd==1.2.0
xlwt==1.3.0
zipp==3.0.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```
CELERY_TASK_IGNORE_RESULT = True

CELERY_IMPORTS = ['cal.celery.tasks', 'cal.tasks_lambda']

CELERY_TASK_ROUTES = ('cal.celery.routers.Router', )

CELERY_TASK_QUEUES = {
    'caliper.OneTimeSurvey': ****,
}

for q in CELERY_TASK_QUEUES:
    existing = CELERY_TASK_QUEUES[q]
    binding = {'binding_key': q}
    CELERY_TASK_QUEUES[q] = dict(list(existing.items()) + list(binding.items()))

CELERY_TASK_DEFAULT_QUEUE = 'cal.default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_EXCHANGE_TYPE = 'direct'

CELERY_SEND_TASK_ERROR_EMAILS = True  
CELERYD_LOG_LEVEL = "INFO"

CELERY_ACCEPT_CONTENT = ['pickle']
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'

CELERY_WORKER_PREFETCH_MULTIPLIER = 4
```

```
import django
django.setup()

from siphon import settings_celery
import celery 
from celery import Celery

app = Celery(accept_content=['pickle'])
app.conf.task_protocol = 1
app.config_from_object(settings_celery, namespace='CELERY')

class QueuedOneTimeSurvey(celery.Task):
    name='QueuedOneTimeSurvey'

    def run(self):
        @transaction.atomic
        def run_inner():
            print("hello")
        return run_inner()
QueuedOneTimeSurvey = app.register_task(QueuedOneTimeSurvey())

QueuedOneTimeSurveyTask.apply_async()
```

</p>
</details>

# Expected Behavior

I expect the task to register and execute. 

# Actual Behavior

```
[2020-03-06 16:23:29,425: ERROR/MainProcess] Received unregistered task of type 'QueuedOneTimeSurvey'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'\x80\x02}q\x00(X\x04\x00\x00\x00taskq\x01X\x13\x00\x00\x00QueuedOneTimeSurveyq\x02X\x02\x00\x00\x00idq\x03X$\x00\x00\x0040f69c1a-c201-4498-9e36-43abe605a2f2q\x04X\x04\x00\x00\x00argsq\x05)X\x06\x00\x00\x00kwargsq\x06}q\x07X\x05\x00\x00\x00groupq\x08NX\x07\x00\x00\x00retriesq\tK\x00X\x03\x00\x00\x00etaq\nNX\x07\x00\x00\x00expiresq\x0bNX\x03\x00\x00\x00utcq\x0c\x88X\t\x00\x00\x00callbacksq\rNX\x08\x00\x00\x00errbacksq\x0eNX\t\x00\x00\x00timelimitq\x0fNN\x86q\x10X\x07\x00\x00\x00tasksetq\x11NX\x05\x00\x00\x00chordq\x12Nu.' (273b)
Traceback (most recent call last):
  File "/deploy/pythonenvs/env/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 559, in on_task_received
    strategy = strategies[type_]
KeyError: 'QueuedOneTimeSurvey'
```

**Comment by Alexis-Jacob** [comment] 2020-03-10 17:30
Have you tried to register your task after a hook such as 

```
from celery.signals import import_modules
@import_modules.connect
def import_modules(*args, **kwargs):
    app.register_task(QueuedOneTimeSurvey)
    
```

**Comment by aliniribeiroo** [comment] 2020-03-26 22:05
I'm facing the same problem!

**Comment by OskarPersson** [comment] 2020-03-31 16:01
I'm having a similar problem (tested with Celery 4.2.0 - 4.4.2) where I get the task listed in the startup message:

```
 -------------- celery@Oskars-PC v4.4.2 (cliffs)
--- ***** -----
-- ******* ---- Windows-10-10.0.18362-SP0 2020-03-31 17:56:17
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         myproj:0x1e18b0f7088
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery

[tasks]
  . myproj.tasks.Foo
```

and I don't get exactly the same error:

```
[2020-03-31 17:56:41,514: ERROR/MainProcess] Task handler raised error: Task of kind 'myproj.tasks.Foo' never registered, please make sure it's imported.
Traceback (most recent call last):
  File "c:\users\oskar\.virtualenvs\merged_core-yndk25vz\lib\site-packages\billiard\pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "c:\users\oskar\.virtualenvs\merged_core-yndk25vz\lib\site-packages\celery\app\trace.py", line 557, in _fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "c:\users\oskar\.virtualenvs\merged_core-yndk25vz\lib\site-packages\celery\app\registry.py", line 21, in __missing__
    raise self.NotRegistered(key)
celery.exceptions.NotRegistered: 'myproj.tasks.Foo'
```

**Comment by OskarPersson** [comment] 2020-03-31 16:03
If I inherit my task from `celery.task.base.Task` instead of `celery.Task` it works as expected

**Comment by auvipy** [comment] 2020-04-01 01:17
can you dig deeper to find out the root of the cause?

**Comment by OskarPersson** [comment] 2020-04-01 08:49
Looking at it atm.

What is the current recommended way to register class based tasks? The documentation for [`app.register_task`](https://github.com/celery/celery/blob/6957f7de13fa6925508a4c9b6e823eb11d88496c/celery/app/base.py#L510-L525) contains the following note:

> This is here for compatibility with old Celery 1.0
> style task classes, you should not need to use this for
> new projects.

I can't find anything else in the documentation, am I missing something?

**Comment by OskarPersson** [comment] 2020-04-01 14:17
It seems like the problem lies in the implementation of prefork in billiard. I've tested the setup in #5162 on Windows with the only difference being gevent instead of prefork and it seems to work as it should.

I've tried to investigate why prefork on Windows does not work and I've made some discoveries but not a complete solution.

It seems like the `initargs` [passed to `Worker` from `Pool`](https://github.com/celery/billiard/blob/644c52070b02642833b5dde759a8fbd875654d25/billiard/pool.py#L1143-L1152) doesn't arrive in the spawned [worker](https://github.com/celery/billiard/blob/644c52070b02642833b5dde759a8fbd875654d25/billiard/pool.py#L236). This is easily tested by simply adding `print(self._initargs[0].tasks)` in Pool and  `print(initargs[0].tasks)` in Worker.

I'm not sure if this has something to do with the note about subprocesses in Windows starting in Python 3.4:

> Changed in version 3.4: spawn added on all unix platforms, and forkserver added for some unix platforms. Child processes no longer inherit all of the parents inheritable handles on Windows.

https://docs.python.org/3.7/library/multiprocessing.html#contexts-and-start-methods

If it does, then Python has a note about how to "explicitly pass resources to child processes" [here](https://docs.python.org/3.7/library/multiprocessing.html#all-start-methods) but I'm not sure how that would be applied to the implementation made in billiard.

**Comment by auvipy** [comment] 2020-04-02 07:32
@georgepsarakis

**Comment by Anuj-Devrani** [comment] 2020-05-19 07:28
It seems celery removed support for **auto registry of class-based tasks in version 4**.
You can read about this [here](https://docs.celeryproject.org/en/v4.0.0/whatsnew-4.0.html#the-task-base-class-no-longer-automatically-register-tasks).

So can you try this:
```python
class Test(celery.Task):
    name = 'my_proj.app_name.tasks.Test'

    def run(self, *args, **kwargs):
        print('2 + 3 = ', 2+3)


app.register_task(Test())
```

and then run it directly ```python Test.apply_async()```

**Comment by auvipy** [comment] 2021-02-19 06:23
> It seems celery removed support for **auto registry of class-based tasks in version 4**.
> You can read about this [here](https://docs.celeryproject.org/en/v4.0.0/whatsnew-4.0.html#the-task-base-class-no-longer-automatically-register-tasks).
> 
> So can you try this:
> 
> ```python
> class Test(celery.Task):
>     name = 'my_proj.app_name.tasks.Test'
> 
>     def run(self, *args, **kwargs):
>         print('2 + 3 = ', 2+3)
> 
> 
> app.register_task(Test())
> ```
> 
> and then run it directly
> 
> ```python
> Test.apply_async()
> ```

closing as per this

**Closed by auvipy** 2021-02-19 06:23 UTC
Labels: Status: Needs Verification ✘
