### ISSUE TITLE
Celery 3.1.15 worker does not start when used with Django 1.6.7

### ISSUE THREAD

**Issue by ksze** [celery/celery#2266] opened 2014-09-17 04:31 UTC
I used to be able to start the Celery worker in the shell, with Celery 3.1.14.

I tried upgrading to Celery 3.1.15 and I now get this:
```
$ celery worker -A myproj.celery
Traceback (most recent call last):
  File "/home/kal/.virtualenvs/myproj_dev/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/bin/base.py", line 307, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/bin/base.py", line 270, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/fixups/django.py", line 69, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/celery/fixups/django.py", line 164, in validate_models
    num_errors = get_validation_errors(s, None)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/django/db/models/loading.py", line 97, in load_app
    app_module = import_module(app_name)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 6, in <module>
    from django.contrib.admin.sites import AdminSite, site
  File "/home/kal/.virtualenvs/myproj_dev/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 3, in <module>
    from django.contrib.admin import ModelAdmin, actions
ImportError: cannot import name actions
```
where `myproj` is a Django project.

**Comment by thedrow** [comment] 2015-06-19 10:54
I cannot reproduce this myself.
We also used 3.1.15 at one point and Django 1.6.
Can any of you guys provide a failing test case with the latest version of Celery?

**Comment by raphaelm** [comment] 2015-06-19 13:06
I don't have the bug any more with Django 1.7.2 and celery 3.1.17.

**Comment by shashank9487** [comment] 2015-12-30 11:38
i am using `celery==3.1.19` ,`Django==1.8.4` , `django-celery==3.1.17`, `redis==2.10.5` stack. Configured everything but when i started celery worker with this command `celery -A config worker --loglevel=INFO` 

It shows me the task name and info log:

[tasks]
  . parts.tasks.add
  . parts.tasks.debug_task

[2015-12-30 17:06:08,544: INFO/MainProcess] Connected to redis://localhost:6379/0
[2015-12-30 17:06:08,550: INFO/MainProcess] mingle: searching for neighbors
[2015-12-30 17:06:09,555: INFO/MainProcess] mingle: all alone
 
That's it, celery stopped automatically after this, don't know how to debug it

**Comment by ask** [comment] 2016-06-23 23:53
Closing this, as we don't have the resources to complete this task.

**Closed by ask** 2016-06-23 23:53 UTC
Labels: Component: Django, Issue Type: Bug, Status: Feedback Needed
