### ISSUE TITLE
Task ID is always None

### ISSUE THREAD

**Issue by Glueon** [celery/celery#2633] opened 2015-05-29 19:05 UTC
I am new to Celery and maybe it's not a bug but my misuse.

There is a task (full code [here](https://github.com/Glueon/celery_examples/blob/master/tasks.py#L64-L67)):

```python
@shared_task(bind=True, acks_late=True)
def task(self, number_of_requests, url):
    # This always gives None. Why?
    task_id = self.request.id
```

Why is it always None? I want to use it to store some task related data in redis.

Task is invoked simply by calling `delay()` method:
```python
task.delay(10, 'http://hello_wolrd.com')
```

**Comment by ask** [comment] 2016-06-24 00:12
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Closed by ask** 2016-06-24 00:12 UTC

**Comment by erickpeirson** [comment] 2016-11-04 14:20
@ask Any reason not to leave this open for future milestones? This would be nifty.

**Comment by ask** [comment] 2016-11-04 18:19
We could leave it open, but there's only one report, and we have no way to reproduce so it may just stay there indefinitely.

If this is a bug that can be reproduced in master then we should definitely reopen it.

**Comment by DoronCohen** [comment] 2017-01-12 14:46
I get this error as well and it is frustrating! The only difference is that I use a task base class but since @Glueon doesn't I guess it is irrelevant. I do get the task id in the logs: 

`[2017-01-12 16:41:37,823: INFO/MainProcess] Received task: just_a_task[8ac8d887-e93d-4190-adba-ed0b41c533d1]`

I tried to get the task id with `celery.current_task.request.id` and `self.request.id`. both doesn't work.

**Comment by densaface** [comment] 2017-03-09 08:41
I reproduced this bug on Centos 7.3 + Django 1.10.6 + django-celery 3.1.25
The same configuraion on Windows 7 sp1 works fine, reques.id isn't None

**Comment by DoronCohen** [comment] 2017-03-09 08:56
Sorry for not updating but this occurred because we had to inherit from `celery.Task` and overload it's `__call__` method. I guess the current task didn't update correctly that way. Let me just say that we didn't find an intuitive way other then overriding `__call__` to invoke some methods before and after a task is running. But we solved it for now.
Thanks @densaface for checking.

**Comment by densaface** [comment] 2017-03-10 11:20
Doron, I don't understand. This bug solved or not? Why it reproduces on Centos and not on Windows? I'd tried different versions django and celery and can't solve this issue on centos. Help, pls.

**Comment by DoronCohen** [comment] 2017-03-13 09:19
My issue is solved although we did encounter another incident where task_id became None out of nowhere. This made us rethink using Celery. We owe this framework alot of effort and time saving but the second we wanted to tweak the smallest detail we got a handful of hard to reproduce bugs.

**Comment by densaface** [comment] 2017-03-15 09:57
I did workaround for me. 
Add line args = args + (req.id, ) in celery/app/trace.py and add parameter task_id = '' as last parameter in all tasks in tasks.py of my app. 

        def __protected_call__(self, *args, **kwargs):
            stack = self.request_stack
            req = stack.top
            if req and not req._protected and \
                    len(stack) == 1 and not req.called_directly:
                req._protected = 1
                args = args + (req.id, )
                return self.run(*args, **kwargs)

**Comment by wosc** [comment] 2018-01-18 09:59
I had a similar issue, and as I understand it, it boils down to this: `Task.__call__` is **never called** in the [normal course of things](https://github.com/celery/celery/blob/master/celery/app/trace.py#L292), so if one inherits and starts overriding `__call__`, one gets strange behaviour, like `self.request` not being the actual request, because `Task.__call__` pushes another strange request thingy onto the stack.
So now I take care to _not_ call `super()` in my custom `__call__` methods, but rather `self.run`, just like app.trace does, and everything is fine.

**Comment by auvipy** [comment] 2018-01-18 18:30
I will reopen it if you can reproduce it on master

**Comment by densaface** [comment] 2018-01-18 18:48
It reproduced 100% on different ubuntu VMs.

**Comment by auvipy** [comment] 2018-01-18 18:51
celery master branch?

**Comment by densaface** [comment] 2018-01-18 18:57
yes, if command "pip install celery" installs master branch... Or wait, how i can check master branch? I install also "pip install django-celery". Maybe django-celery removes celery...

**Comment by csirmazbendeguz** [comment] 2023-06-27 18:41
I encountered the same issue on Celery 5.2.7, solution by @wosc worked 👍

**Comment by dangoriya** [comment] 2024-03-29 07:09
Getting same issue in celery  v5.3.6
@app.task(bind=True)
def initialize_cpe(self):
    task_name = current_task.name  # Get the task name
    print(f"task name : {task_name}")
    print(f"Task Request: {current_task.request}")
    task_id = current_task.request.id  # Get the task id
    print(f"task id : {task_id}")
    print(f"task id using self : {self.request.id.__str__()}")
    
 output:
[2024-03-29 15:59:34,226: WARNING/ForkPoolWorker-6] task name : tasks.initialize_cpe
[2024-03-29 15:59:34,226: WARNING/ForkPoolWorker-6] Task Request: <Context: {'args': (), 'kwargs': {}, 'headers': None}>
[2024-03-29 15:59:34,227: WARNING/ForkPoolWorker-6] task id : None
[2024-03-29 15:59:34,227: WARNING/ForkPoolWorker-6] task id using self None

**Comment by graysonpike** [comment] 2024-10-02 19:50
I am experiencing the same issue still in 2024 with v5.4.0. I am not overriding any __call__ function or inheriting tasks as described by @wosc above.
