### ISSUE TITLE
Celery backends are not thread-safe

### ISSUE THREAD

**Issue by matusvalo** [celery/celery#6414] opened 2020-10-15 16:39 UTC
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [X] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

https://github.com/celery/py-amqp/issues/330

#### Possible Duplicates

- #1779, #2066

</p>
</details>

## Minimally Reproducible Test Case
See https://github.com/celery/py-amqp/issues/330#issuecomment-706148277

# Expected Behavior
Celery should be able to be called from multiple threads - e.g. from gunicorn container

# Actual Behavior
Due race conditions inside backends, Celery serving data is stalled or it returns "0x01 while expecting 0xce" errors, or others (depends on backend) - see https://github.com/celery/py-amqp/issues/330, #1779, #2066

# Details
The issue is caused by sharing resources between threads. This issue can be broken into 2 separate sub-issues:
1. Underlying Connection is shared between threads:
When `rpc` backend is used, kombu/py-amqp backend is used. This backend supports **only one connection per thread**. Unfortunately since using single backend object in all threads, all threads shares single connections causing "0x01 while expecting 0xce" errors or other creashes:
https://github.com/celery/celery/blob/05da357502a109c05b35392391299d75d181ccab/celery/app/base.py#L1166-L1167
2. Single `oid` is shared between threads:
This unique identifier is used to define reply-to queue of `rpc` backend. Again, since the `oid` is global it is caused that **all** threads are having **single** result queue causing not receiving responses:
https://github.com/celery/celery/blob/05da357502a109c05b35392391299d75d181ccab/celery/app/base.py#L1152-L1153

# Possible solution
Store these global variables to thread local storage:
https://docs.python.org/3/library/threading.html#thread-local-data

**Comment by HosseyNJF** [comment] 2020-10-15 20:07
Possible duplicate of #4480

**Closed** 2020-11-22 15:59 UTC
Labels: Issue Type: Bug Report
