### ISSUE TITLE
Broadcast routing documentation incorrect, confusing, and incomplete

### ISSUE THREAD

**Issue by willharris** [celery/celery#4582] opened 2018-03-09 10:30 UTC
The documentation (for celery 4.1.0) surrounding broadcast routing in the "Routing Tasks" section is confusing and insufficient for real-world use. Worse, the sample configuration for **celery beat** usage is simply incorrect, and does not work.

The main problem seems to be that the key to getting broadcast working is to specify the `queue` parameter, either in the `task_routes` configuration, or in the `beat_schedule` configuration. In my experience, the `exchange` parameter does nothing. This is doubly confusing (and perhaps even a code bug?) because the name provided when declaring the broadcast queue (e.g. `broadcast_tasks` in `Broadcast('broadcast_tasks')`) is actually the name of the exchange. The queue name is then `bcast.<uuid>`, which is not known when writing the configuration of course.

In addition, the likelihood of needing *only* a broadcast queue, and not also a standard "default" queue, is miniscule. Useful documentation would provide an example of setting up broadcast tasks in addition to these default tasks.

As noted in #3949, the documentation of routing is in general confusing and could do with a brush-up. While I don't feel knowledgable enough to tackle that documentation task, I would be happy to submit a PR improving the sample code documentation for broadcast tasks -- assuming of course the code itself is not incorrect!

**Comment by btruhand** [comment] 2018-11-26 04:55
I just want to chime in also that I was left confused for several hours on the expected behaviour of broadcasting tasks

I tried to set the routing as the following:
```python
task_queues = [
	Broadcast('bcast', queue='stop-streaming', message_ttl=2.0, durable=True),
]

# # need to test this on "multiple" machines (aka Docker containers) and see what happens with no queue
# # predetermined. Guessing it would do a broadcast since multiple machines, which if that is the case we
# # want to declare static queue
task_routes = {
	'streaming.stop_stream': {
		'queue': 'stop-streaming',
		'exchange': 'bcast'
	},
}
```
I used RabbitMq backend. In the end this didn't work (only one worker will receive the task), which really in the end comes down to RabbitMq's fanout exchange behaviour. But the following does work:

```python
task_queues = [
	Broadcast('bcast'),
]

# # need to test this on "multiple" machines (aka Docker containers) and see what happens with no queue
# # predetermined. Guessing it would do a broadcast since multiple machines, which if that is the case we
# # want to declare static queue
task_routes = {
	'streaming.stop_stream': {
                 'queue': 'bcast',
		'exchange': 'bcast'
	},
}
```
which is similar to what is in the documentation yes. However I went ahead to look into `kombu.common.Broadcast` documentation [here](http://docs.celeryproject.org/projects/kombu/en/latest/reference/kombu.common.html), which states the name is for the exchange and not the queue. Moreover you do not need to have `-Q bcast` flag when running the worker with this configuration, which is also confusing.

Hope it will be of some help for future documentation direction

**Comment by auvipy** [comment] 2018-11-29 17:19
could you send a pr with your suggested docs edits?

**Comment by btruhand** [comment] 2018-11-29 22:16
I'll be willing to help in but probably around 2 weeks from now due to my current schedule. Does that sound good?

**Comment by willharris** [comment] 2018-11-30 12:35
I will also write something up, happy to collaborate with @btruhand. Is there a deadline?

**Comment by auvipy** [comment] 2018-12-04 08:15
doc contributions are not a blocker, so anytime.

**Comment by auvipy** [comment] 2019-06-29 13:01
closing as dup. but will include suggested edits from here as well.

**Closed by auvipy** 2019-06-29 13:01 UTC
Labels: Issue Type: Documentation
