### ISSUE TITLE
Eta task executed on all available threads at same time

### ISSUE THREAD

**Issue by Ixiodor** [celery/celery#7009] opened 2021-10-27 08:16 UTC
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [ ] I have verified that the issue exists against the `master` branch of Celery.
* [ ] I have included the contents of ``pip freeze`` in the issue.
* [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* None

#### Possible Duplicates
* None

## Environment & Settings

**Celery version**: 5.1.2

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
[2021-10-26 21:00:00,618: WARNING/ForkPoolWorker-1] Starting script: XXXXX
[2021-10-26 21:00:00,618: WARNING/ForkPoolWorker-1]

[2021-10-26 21:00:00,685: WARNING/ForkPoolWorker-3] Starting script: XXXXX
[2021-10-26 21:00:00,686: WARNING/ForkPoolWorker-3]

[2021-10-26 21:00:00,736: WARNING/ForkPoolWorker-2] Starting script: XXXXX
[2021-10-26 21:00:00,737: WARNING/ForkPoolWorker-2]

[2021-10-26 21:00:01,447: INFO/MainProcess] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] received
[2021-10-26 21:00:01,449: INFO/ForkPoolWorker-4] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] retry: Retry in 5s
[2021-10-26 21:00:01,470: WARNING/ForkPoolWorker-2]

[2021-10-26 21:00:01,531: INFO/MainProcess] Task execute_script[46e760cc-fd1a-4a62-bcb6-4aa4bf39d894] received
[2021-10-26 21:00:01,557: INFO/ForkPoolWorker-2] Task execute_script[46e760cc-fd1a-4a62-bcb6-4aa4bf39d894] retry: Retry in 18s: RuntimeError('Error code not 0(1).',)
[2021-10-26 21:00:06,395: WARNING/ForkPoolWorker-3]

[2021-10-26 21:00:06,437: INFO/MainProcess] Task execute_script[46e760cc-fd1a-4a62-bcb6-4aa4bf39d894] received
[2021-10-26 21:00:06,465: INFO/ForkPoolWorker-3] Task execute_script[46e760cc-fd1a-4a62-bcb6-4aa4bf39d894] retry: Retry in 18s: RuntimeError('Error code not 0(1).',)
[2021-10-26 21:00:06,478: INFO/ForkPoolWorker-2] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] retry: Retry in 5s
[2021-10-26 21:00:06,480: INFO/MainProcess] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] received
[2021-10-26 21:00:12,618: INFO/MainProcess] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] received
[2021-10-26 21:00:12,618: INFO/ForkPoolWorker-3] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] retry: Retry in 5s
[2021-10-26 21:00:17,715: INFO/ForkPoolWorker-3] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] retry: Retry in 5s
[2021-10-26 21:00:17,717: INFO/MainProcess] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] received
[2021-10-26 21:00:19,889: WARNING/ForkPoolWorker-3] Starting script: XXXX
[2021-10-26 21:00:19,889: WARNING/ForkPoolWorker-3]

[2021-10-26 21:00:20,560: WARNING/ForkPoolWorker-3]

[2021-10-26 21:00:20,570: INFO/MainProcess] Task execute_script[46e760cc-fd1a-4a62-bcb6-4aa4bf39d894] received
[2021-10-26 21:00:20,721: INFO/ForkPoolWorker-3] Task execute_script[46e760cc-fd1a-4a62-bcb6-4aa4bf39d894] retry: Retry in 15s: RuntimeError('Error code not 0(1).',)
[2021-10-26 21:00:22,832: INFO/ForkPoolWorker-3] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] retry: Retry in 5s
[2021-10-26 21:00:22,834: INFO/MainProcess] Task celery.chord_unlock[01293323-237d-412b-928c-3c8dfcd02f39] received
[2021-10-26 21:00:24,871: WARNING/ForkPoolWorker-3] Starting script: XXXXXXX
[2021-10-26 21:00:24,871: WARNING/ForkPoolWorker-3]

[2021-10-26 21:00:25,538: WARNING/ForkPoolWorker-3]

[2021-10-26 21:00:25,549: INFO/MainProcess] Task execute_script[46e760cc-fd1a-4a62-bcb6-4aa4bf39d894] received
[2021-10-26 21:00:25,594: INFO/ForkPoolWorker-3] Task execute_script[46e760cc-fd1a-4a62-bcb6-4aa4bf39d894] retry: Retry in 15s: RuntimeError('Error code not 0(1).',)

```

</p>
</details>

# Steps to Reproduce
## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```

```

</p>
</details>

### Other Dependencies

<details>
<p>
Redis as broker.
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python

```

</p>
</details>

# Expected Behavior

Taking an ETA task and executing it on first available thread.

# Actual Behavior

After worker main process took a message with ETA param, it executed it on all available threads making, in my case, with retries at 2, running the job 7 times. First was fine and other 6 times found a lock and exited with code 1. 7 fails was enought to mark workflow as failed and revoked all.

**Comment by alphavector** [comment] 2021-10-30 13:42
Please attach a code example on which I can reproduce the problem.

In order to have the task executed in one thread, you can implement a lock when one of the workers has taken the task to work.

If I understand correctly, each worker is a separate operating system process. The workers have separate memories and know absolutely nothing about each other.
These are some ideas off the top of my head, send me a code example

**Comment by Ixiodor** [comment] 2021-10-31 14:56
Hard to write a code reproduce.

> If I understand correctly, each worker is a separate operating system process. The workers have separate memories and know absolutely nothing about each other.
Nope. Same machine.

What I have is:
task1 => (on success) task2 and task3 => (on success) task4.
This works if launchd ASAP or with ETA in 2/3 minutes.

Start getting broken if called after some hours (my case even 8/9 h). And what happens is:
task1 task1 task1 task1 task1 task1 all together and forever, all with same task ID and on all possible available workers on machine.

**Comment by Ixiodor** [comment] 2021-11-15 08:36
No one tried to execute a workflow with eta=now + 8h and redis as broker? Cause I reproduced the issue on my local machine

**Comment by alphavector** [comment] 2021-11-15 10:12
> No one tried to execute a workflow with eta=now + 8h and redis as broker? Cause I reproduced the issue on my local machine. It's boring to test cause you have actually wait 8h for make it happen.

Send me your test case to reproduce the problem and we'll try to debug it together

**Comment by Ixiodor** [comment] 2021-11-15 12:41
@app.task(name="execute_script", bind=True, autoretry_for=(Exception,), retry_backoff=20, retry_backoff_max=20)
```
def execute_script_demo(self, params, max_retries):
    self.max_retries = max_retries  # Bypass setting on task creation
    print(params)


def schedule_tasks():
    dt_now = pendulum.now('UTC')
    dt_now = dt_now.add(hours=8)
    task_signature1 = execute_script_demo.signature(("1", 2), immutable=True, eta=dt_now)
    task_signature2 = execute_script_demo.signature(("2", 2), immutable=True, eta=dt_now)
    task_signature3 = execute_script_demo.signature(("3", 2), immutable=True, eta=dt_now)
    tasks = chain(task_signature1, task_signature2, task_signature3)
    tasks.delay()
```
Try something like that

**Comment by Ixiodor** [comment] 2021-11-15 21:16
Nothing, same thing.

```
[2021-11-15 22:00:00,312: WARNING/ForkPoolWorker-8] This is stdout
params: test1p
[2021-11-15 22:00:00,312: WARNING/ForkPoolWorker-8] This is stderr
[2021-11-15 22:00:00,322: WARNING/ForkPoolWorker-5] Starting script: /home/ubuntu/repos/em-sim-suitability/src/scheduler/tests/scripts/success_bash.sh  params: test1p
[2021-11-15 22:00:00,327: WARNING/ForkPoolWorker-5] This is stdout
params: test1p
[2021-11-15 22:00:00,327: WARNING/ForkPoolWorker-5] This is stderr
[2021-11-15 22:00:00,331: WARNING/ForkPoolWorker-1] Starting script: /home/ubuntu/repos/em-sim-suitability/src/scheduler/tests/scripts/success_bash.sh  params: test1p
[2021-11-15 22:00:00,336: WARNING/ForkPoolWorker-1] This is stdout
params: test1p
[2021-11-15 22:00:00,336: WARNING/ForkPoolWorker-1] This is stderr
[2021-11-15 22:00:00,339: INFO/ForkPoolWorker-8] Task execute_script[74497e42-f5ef-41cf-98bc-85ba1f5e468e] succeeded in 0.046873576000507455s: 0
[2021-11-15 22:00:00,348: INFO/ForkPoolWorker-5] Task execute_script[74497e42-f5ef-41cf-98bc-85ba1f5e468e] succeeded in 0.05595955000171671s: 0
[2021-11-15 22:00:00,356: WARNING/ForkPoolWorker-6] Starting script: /home/ubuntu/repos/em-sim-suitability/src/scheduler/tests/scripts/success_bash.sh  params: test1p
[2021-11-15 22:00:00,360: WARNING/ForkPoolWorker-6] This is stdout
params: test1p
[2021-11-15 22:00:00,360: WARNING/ForkPoolWorker-6] This is stderr
[2021-11-15 22:00:00,366: WARNING/ForkPoolWorker-4] Starting script: /home/ubuntu/repos/em-sim-suitability/src/scheduler/tests/scripts/success_bash.sh  params: test1p
[2021-11-15 22:00:00,371: WARNING/ForkPoolWorker-4] This is stdout
params: test1p
[2021-11-15 22:00:00,371: WARNING/ForkPoolWorker-4] This is stderr
[2021-11-15 22:00:00,375: WARNING/ForkPoolWorker-2] Starting script: /home/ubuntu/repos/em-sim-suitability/src/scheduler/tests/scripts/success_bash.sh  params: test1p
[2021-11-15 22:00:00,379: WARNING/ForkPoolWorker-2] This is stdout
params: test1p
[2021-11-15 22:00:00,379: WARNING/ForkPoolWorker-2] This is stderr
[2021-11-15 22:00:00,382: INFO/ForkPoolWorker-1] Task execute_script[74497e42-f5ef-41cf-98bc-85ba1f5e468e] succeeded in 0.08993997699872125s: 0
[2021-11-15 22:00:00,391: INFO/ForkPoolWorker-2] Task execute_script[74497e42-f5ef-41cf-98bc-85ba1f5e468e] succeeded in 0.09921807199862087s: 0
[2021-11-15 22:00:00,400: WARNING/ForkPoolWorker-3] Starting script: /home/ubuntu/repos/em-sim-suitability/src/scheduler/tests/scripts/success_bash.sh  params: test1p
[2021-11-15 22:00:00,405: WARNING/ForkPoolWorker-3] This is stdout
params: test1p
[2021-11-15 22:00:00,405: WARNING/ForkPoolWorker-3] This is stderr
[2021-11-15 22:00:00,413: INFO/ForkPoolWorker-4] Task execute_script[74497e42-f5ef-41cf-98bc-85ba1f5e468e] succeeded in 0.12132965400087414s: 0
[2021-11-15 22:00:00,429: INFO/ForkPoolWorker-3] Task execute_script[74497e42-f5ef-41cf-98bc-85ba1f5e468e] succeeded in 0.13653344300109893s: 0
[2021-11-15 22:00:00,442: INFO/ForkPoolWorker-6] Task execute_script[74497e42-f5ef-41cf-98bc-85ba1f5e468e] succeeded in 0.14929349000158254s: 0
[2021-11-15 22:00:00,471: WARNING/ForkPoolWorker-7] Starting script: /home/ubuntu/repos/em-sim-suitability/src/scheduler/tests/scripts/success_bash.sh  params: test1p
[2021-11-15 22:00:00,475: WARNING/ForkPoolWorker-7] This is stdout
params: test1p
[2021-11-15 22:00:00,475: WARNING/ForkPoolWorker-7] This is stderr

```

**Comment by Ixiodor** [comment] 2021-11-16 02:01
After 6h launched as debug-log.
```
[2021-11-16 03:00:00,001: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7f359b86f4c0> (args:('execute_script', '454b4c97-f1eb-4704-af9c-6e10b9113308', {'lang': 'py', 'task': 'execute_script', 'id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'shadow': None, 'eta': '2021-11-16T03:00:00+01:00', 'expires': None, 'group': '8e5689e1-9e04-4b9f-940a-bd2e39ba1339', 'group_index': 0, 'retries': 0, 'timelimit': [None, None], 'root_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'parent_id': None, 'argsrepr': "('scheduler/tests/scripts/', 'success_bash.sh', 'test1p', 2)", 'kwargsrepr': '{}', 'origin': 'gen33996@ubuntu-dev', 'ignore_result': False, 'redelivered': True, 'properties': {'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': '9afb3618-f1fd-466d-a41c-4f010a7c8ab5'}, 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'hostname': 'celery@ubuntu-dev',... kwargs:{})
[2021-11-16 03:00:00,001: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7f359b86f4c0> (args:('execute_script', '454b4c97-f1eb-4704-af9c-6e10b9113308', {'lang': 'py', 'task': 'execute_script', 'id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'shadow': None, 'eta': '2021-11-16T03:00:00+01:00', 'expires': None, 'group': '8e5689e1-9e04-4b9f-940a-bd2e39ba1339', 'group_index': 0, 'retries': 0, 'timelimit': [None, None], 'root_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'parent_id': None, 'argsrepr': "('scheduler/tests/scripts/', 'success_bash.sh', 'test1p', 2)", 'kwargsrepr': '{}', 'origin': 'gen33996@ubuntu-dev', 'ignore_result': False, 'redelivered': True, 'properties': {'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': '9afb3618-f1fd-466d-a41c-4f010a7c8ab5'}, 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'hostname': 'celery@ubuntu-dev',... kwargs:{})
[2021-11-16 03:00:00,001: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7f359b86f4c0> (args:('execute_script', '454b4c97-f1eb-4704-af9c-6e10b9113308', {'lang': 'py', 'task': 'execute_script', 'id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'shadow': None, 'eta': '2021-11-16T03:00:00+01:00', 'expires': None, 'group': '8e5689e1-9e04-4b9f-940a-bd2e39ba1339', 'group_index': 0, 'retries': 0, 'timelimit': [None, None], 'root_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'parent_id': None, 'argsrepr': "('scheduler/tests/scripts/', 'success_bash.sh', 'test1p', 2)", 'kwargsrepr': '{}', 'origin': 'gen33996@ubuntu-dev', 'ignore_result': False, 'redelivered': True, 'properties': {'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': '9afb3618-f1fd-466d-a41c-4f010a7c8ab5'}, 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'hostname': 'celery@ubuntu-dev',... kwargs:{})
[2021-11-16 03:00:00,001: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7f359b86f4c0> (args:('execute_script', '454b4c97-f1eb-4704-af9c-6e10b9113308', {'lang': 'py', 'task': 'execute_script', 'id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'shadow': None, 'eta': '2021-11-16T03:00:00+01:00', 'expires': None, 'group': '8e5689e1-9e04-4b9f-940a-bd2e39ba1339', 'group_index': 0, 'retries': 0, 'timelimit': [None, None], 'root_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'parent_id': None, 'argsrepr': "('scheduler/tests/scripts/', 'success_bash.sh', 'test1p', 2)", 'kwargsrepr': '{}', 'origin': 'gen33996@ubuntu-dev', 'ignore_result': False, 'redelivered': True, 'properties': {'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': '9afb3618-f1fd-466d-a41c-4f010a7c8ab5'}, 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'hostname': 'celery@ubuntu-dev',... kwargs:{})
[2021-11-16 03:00:00,001: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7f359b86f4c0> (args:('execute_script', '454b4c97-f1eb-4704-af9c-6e10b9113308', {'lang': 'py', 'task': 'execute_script', 'id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'shadow': None, 'eta': '2021-11-16T03:00:00+01:00', 'expires': None, 'group': '8e5689e1-9e04-4b9f-940a-bd2e39ba1339', 'group_index': 0, 'retries': 0, 'timelimit': [None, None], 'root_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'parent_id': None, 'argsrepr': "('scheduler/tests/scripts/', 'success_bash.sh', 'test1p', 2)", 'kwargsrepr': '{}', 'origin': 'gen33996@ubuntu-dev', 'ignore_result': False, 'redelivered': True, 'properties': {'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': '9afb3618-f1fd-466d-a41c-4f010a7c8ab5'}, 'reply_to': '4fc8e65e-69c6-363e-a83f-346287e244d3', 'correlation_id': '454b4c97-f1eb-4704-af9c-6e10b9113308', 'hostname': 'celery@ubuntu-dev',... kwargs:{})
[2021-11-16 03:00:00,238: DEBUG/MainProcess] basic.qos: prefetch_count->33
```

**Comment by Ixiodor** [comment] 2021-11-16 22:56
This is what is happening with my minimal test reported before:

```
[2021-11-16 17:57:51,435: INFO/MainProcess] Task execute_script_demo[fb05d6c3-7a61-4b10-a1f8-60a61f38610a] received
[2021-11-16 18:59:16,647: INFO/MainProcess] Task execute_script_demo[fb05d6c3-7a61-4b10-a1f8-60a61f38610a] received
[2021-11-16 19:59:17,215: INFO/MainProcess] Task execute_script_demo[fb05d6c3-7a61-4b10-a1f8-60a61f38610a] received
[2021-11-16 20:59:17,794: INFO/MainProcess] Task execute_script_demo[fb05d6c3-7a61-4b10-a1f8-60a61f38610a] received
[2021-11-16 21:59:18,359: INFO/MainProcess] Task execute_script_demo[fb05d6c3-7a61-4b10-a1f8-60a61f38610a] received
[2021-11-16 22:59:18,938: INFO/MainProcess] Task execute_script_demo[fb05d6c3-7a61-4b10-a1f8-60a61f38610a] received
```

**Comment by aemdy** [comment] 2021-11-17 17:24
I am facing the same issue with Redis backend and tasks with a set ETA. Just in my case it does not necessarily mean that a task is run as many times as there are workers, but they are run even more times, e.g. 1-100. I have 8 workers in total.

```
[2021-11-13 08:34:28,154: INFO/ForkPoolWorker-8] Task myapp.tasks.send_email[1501bf57-88b0-41f0-816e-a0d50880ec36] succeeded in 0.17372081987559795s: None
[2021-11-13 08:34:28,212: INFO/ForkPoolWorker-1] Task myapp.tasks.send_email[1501bf57-88b0-41f0-816e-a0d50880ec36] succeeded in 0.10270981676876545s: None
[2021-11-13 08:34:28,237: INFO/ForkPoolWorker-5] Task myapp.tasks.send_email[1501bf57-88b0-41f0-816e-a0d50880ec36] succeeded in 0.12918444350361824s: None
[2021-11-13 08:34:28,265: INFO/ForkPoolWorker-8] Task myapp.tasks.send_email[1501bf57-88b0-41f0-816e-a0d50880ec36] succeeded in 0.10595323331654072s: None
```

**Comment by auvipy** [comment] 2021-11-17 17:34
celery 4.4.6 is not supported. please try celery 5.2.1+

**Comment by Ixiodor** [comment] 2021-12-01 15:44
No one looking for that? Still in 5.2.1

**Comment by auvipy** [comment] 2021-12-12 11:31
> No one looking for that? Still in 5.2.1. Messages get duplicated based on time keep. Really need that fixed. Seems something related to timeout cause it gets same packets again each hour.

I would request you to investigate further into celery

**Comment by Ixiodor** [comment] 2021-12-12 12:40
What I found is that:
Messages on Redis have a timeout, default timeout is 3600 s. Celery will re-send back messages after 3600s without discarding the one scheduled on worker. That creates clones each hour.

**Comment by rainnnnny** [comment] 2023-08-11 08:24
> What I found is that: Messages on Redis have a timeout, default timeout is 3600 s. Celery will re-send back messages after 3600s without discarding the one scheduled on worker. That creates clones each hour.

I think that's the case.

It's [the docs here](https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/redis.html#redis-caveats) described the problem, I had an task using autoretry for 4 hours delay and 2 times retries, and it does expand to 4 tasks then 16 tasks.

Maybe it's ok to close this issue or you guys consider it a bug.

**Comment by auvipy** [comment] 2023-08-15 05:44
closing as not a bug

**Closed by auvipy** 2023-08-15 05:44 UTC
Labels: Status: Not a Bug, Component: Redis Broker, Issue Type: Bug Report

**Comment by Ixiodor** [comment] 2023-08-22 09:10
Wait, why not a BUG?
This is what happens:

- Celery gets some tasks from Redis
- Some tasks goes on timeout on Redis
- Celery will send back tasks to Redis WITHOUT deleting queue
- Celery will gets some tasks from Redis again
- Tasks duplicated

Celery SHOULD delete(or ignore) tasks with same id altredy present on own queue.
