### ISSUE TITLE
python3.11 + Celery + Redis + Gevent -> "returned NULL without setting an exception"

### ISSUE THREAD

**Issue by cunla** [celery/celery#8425] opened 2023-08-06 17:15 UTC
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected). ==> Specified version.
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation. ==> Exist only in python 3.11, downgrading solves it.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system. ==> Does not happen on mac, only on docker (particularly, `python:3.10-buster` image, so linux)
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

## Related Issues and Possible Duplicates
See [this discussion](https://github.com/celery/celery/discussions/8356) with exactly the same issue.

## Environment & Settings

**Celery version**: 5.3.1 (emerald-rush)
<details>
<summary><b><code>celery report (for py3.10, not for 3.11)</code> Output:</b></summary>
<p>

```

software -> celery:5.3.1 (emerald-rush) kombu:5.3.1 py:3.10.12
            billiard:4.1.0 redis:4.6.0
platform -> system:Linux arch:64bit, ELF
            kernel version:5.15.108 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://elasticache-redis.integration.cfasupplydevelop.com:6379/0

CeleryTask: <enum 'CeleryTask'>
CeleryTaskQueue: <enum 'CeleryTaskQueue'>
Enum: <enum 'Enum'>
Exchange: <class 'kombu.entity.Exchange'>
FunctionsConfig: <class 'app.config.config.FunctionsConfig'>
Queue: <class 'kombu.entity.Queue'>
accept_content: ['json']
broker_url: 'redis://elasticache-redis.integration.cfasupplydevelop.com:6379/0'
include: ['app.celery_app.celery_tasks']
result_backend: 'redis://elasticache-redis.integration.cfasupplydevelop.com:6379/0'
result_extended: True
result_serializer: 'json'
task_default_queue: 'default'
task_ignore_result: True
task_queues:
    (<unbound Queue default -> <unbound Exchange default(direct)> -> default>,
 <unbound Queue jdawms_order_shipload -> <unbound Exchange jdawms_order_shipload(direct)> -> jdawms_order_shipload>,
 <unbound Queue so_invoice_credit -> <unbound Exchange so_invoice_credit(direct)> -> so_invoice_credit>)
task_serializer: 'json'
task_store_errors_even_if_ignored: True
worker_hijack_root_logger: False
worker_log_format: ('[%(asctime)s] [%(levelname)s] [%(threadName)s] '
 '[%(filename)s:%(lineno)s - %(funcName)s()] '
 '%(message)s')
worker_task_log_format: ('[%(asctime)s] [%(levelname)s] [%(threadName)s] '
 '[%(filename)s:%(lineno)s - %(funcName)s()] '
 '%(message)s')
deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: 3.11
- **Minimal Celery Version**: Unknown
- **Minimal Result Backend Client Version**: Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.1.1
apispec==6.3.0
apispec-webframeworks==0.5.2
arrow==1.2.3
async-timeout==4.0.2
awswrangler==3.3.0
bcrypt==4.0.1
billiard==4.1.0
black==23.7.0
blinker==1.6.2
boto3==1.28.18
boto3-stubs==1.28.18
botocore==1.31.20
botocore-stubs==1.31.18
botoinator==0.0.6
cachetools==5.3.1
celery==5.3.1
celery-types==0.18.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
coverage==7.2.7
cryptography==41.0.3
dataclasses-json==0.5.14
decorator==5.1.1
dotty-dict==1.3.1
et-xmlfile==1.1.0
exceptiongroup==1.1.2
execnet==2.0.2
Flask==2.3.2
Flask-Cors==4.0.0
flask-swagger-ui==4.11.1
flower==2.0.0
freezegun==1.2.2
gevent==23.7.0
google-api-core==2.11.1
google-auth==2.22.0
google-cloud==0.34.0
google-cloud-pubsub==2.18.1
googleapis-common-protos==1.60.0
greenlet==2.0.2
grpc-google-iam-v1==0.12.6
grpcio==1.56.2
grpcio-status==1.56.2
gunicorn==21.2.0
humanize==4.7.0
idna==3.4
inflect==7.0.0
iniconfig==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
jsonpickle==3.0.1
kombu==5.3.1
lxml==4.9.3
MarkupSafe==2.1.3
marshmallow==3.20.1
marshmallow-toplevel==0.1.3
mock==5.1.0
moto==4.1.14
multimethod==1.9.1
mypy==1.4.1
mypy-boto3-cloudformation==1.28.16
mypy-boto3-dynamodb==1.28.16
mypy-boto3-ec2==1.28.16
mypy-boto3-lambda==1.28.16
mypy-boto3-rds==1.28.17
mypy-boto3-s3==1.28.16
mypy-boto3-sqs==1.28.16
mypy-boto3-sts==1.28.16
mypy-extensions==1.0.0
numpy==1.25.2
oauthlib==3.2.2
openpyxl==3.1.2
packaging==23.1
pandas==1.5.3
pandera==0.16.1
parameterized==0.9.0
paramiko==3.3.1
pathspec==0.11.2
platformdirs==3.10.0
pluggy==1.2.0
pprintpp==0.4.0
prometheus-client==0.17.1
prometheus-flask-exporter==0.22.4
prompt-toolkit==3.0.39
proto-plus==1.22.3
protobuf==4.23.4
psycopg2==2.9.6
psycopg2-binary==2.9.6
py==1.11.0
pyarrow==12.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==1.10.9
PyNaCl==1.5.0
pynamodb==4.4.0
pyodbc==4.0.39
pytest==7.4.0
pytest-cov==4.1.0
pytest-mock==3.11.1
pytest-split==0.8.1
pytest-xdist==3.3.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
pytz==2023.3
pytz-convert==0.2.9
pyx12==2.3.3
PyYAML==6.0.1
redis==4.6.0
requests==2.31.0
requests-oauthlib==1.3.1
requests-toolbelt==1.0.0
responses==0.23.3
retry==0.9.2
rsa==4.9
s3transfer==0.6.1
sentry-sdk==1.29.2
six==1.16.0
slack-bolt==1.18.0
slack-sdk==3.21.3
smartsheet-python-sdk==3.0.2
SQLAlchemy==2.0.19
sqs-extended-client==0.0.10
structlog==23.1.0
tabulate==0.9.0
tomli==2.0.1
tornado==6.3.2
typeguard==4.1.0
types-awscrt==0.17.0
types-beautifulsoup4==4.12.0.5
types-Flask-Cors==4.0.0.1
types-freezegun==1.1.10
types-google-cloud-ndb==2.2.0.0
types-html5lib==1.1.11.15
types-lxml==2023.3.28
types-mock==5.1.0.1
types-oauthlib==3.2.0.9
types-openpyxl==3.1.0.15
types-paramiko==3.3.0.0
types-psycopg2==2.9.21.11
types-PyMySQL==1.1.0.1
types-python-dateutil==2.8.19.14
types-pytz==2023.3.0.0
types-PyYAML==6.0.12.11
types-requests==2.31.0.2
types-retry==0.9.9.4
types-s3transfer==0.6.1
types-six==1.16.21.9
types-tabulate==0.9.0.3
types-urllib3==1.26.25.14
types-xmltodict==0.13.0.3
typing-inspect==0.9.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
wcwidth==0.2.6
Werkzeug==2.3.6
wrapt==1.15.0
XlsxWriter==3.1.2
xmltodict==0.13.0
zope.event==5.0
zope.interface==6.0
```

</p>
</details>

## Minimally Reproducible Test Case

Getting the following error in a container running celery worker

<details>
<p>

```
[2023-08-04 11:10:28,805] [WARNING] [Dummy-748] [log.py:232 - write()] Traceback (most recent call last):
[2023-08-04 11:10:28,806] [WARNING] [Dummy-748] [log.py:232 - write()]   File "src/gevent/_waiter.py", line 122, in gevent._gevent_c_waiter.Waiter.switch
[2023-08-04 11:10:28,806] [WARNING] [Dummy-748] [log.py:232 - write()] SystemError: <built-in method switch of gevent._gevent_cgreenlet.Greenlet object at 0x7fcdb37de700> returned NULL without setting an exception
[2023-08-04 11:10:28,806] [WARNING] [Dummy-748] [log.py:232 - write()] 2023-08-04T11:10:28Z
[2023-08-04 11:10:28,806] [WARNING] [Dummy-748] [log.py:232 - write()]
[2023-08-04 11:10:28,806] [WARNING] [Dummy-748] [log.py:232 - write()] <built-in method switch of gevent._gevent_cgreenlet.Greenlet object at 0x7fcdb37de700> failed with SystemError
[2023-08-04 11:10:28,806] [ERROR] [MainThread] [consumer.py:248 - perform_pending_operations()] Pending callback raised: SystemError('<built-in method switch of gevent._gevent_cgreenlet.Greenlet object at 0x7fcdb37de700> returned NULL without setting an exception')
Traceback (most recent call last):
  File "/home/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 246, in perform_pending_operations
    self._pending_operations.pop()()
  File "/home/.local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/kombu/message.py", line 131, in ack_log_error
    self.ack(multiple=multiple)
  File "/home/.local/lib/python3.11/site-packages/kombu/message.py", line 126, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/home/.local/lib/python3.11/site-packages/kombu/transport/virtual/base.py", line 670, in basic_ack
    self.qos.ack(delivery_tag)
  File "/home/.local/lib/python3.11/site-packages/kombu/transport/redis.py", line 379, in ack
    self._remove_from_indices(delivery_tag).execute()
  File "/home/.local/lib/python3.11/site-packages/redis/client.py", line 2120, in execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/.local/lib/python3.11/site-packages/redis/client.py", line 2121, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/redis/client.py", line 1975, in _execute_transaction
    self.parse_response(connection, "_")
  File "/home/.local/lib/python3.11/site-packages/redis/client.py", line 2060, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/redis/client.py", line 1286, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/redis/connection.py", line 359, in _read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/redis/connection.py", line 262, in readline
    self._read_from_socket()
  File "/home/.local/lib/python3.11/site-packages/redis/connection.py", line 212, in _read_from_socket
    data = self._sock.recv(socket_read_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.local/lib/python3.11/site-packages/gevent/_socketcommon.py", line 666, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 304, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  File "src/gevent/_waiter.py", line 122, in gevent._gevent_c_waiter.Waiter.switch
SystemError: <built-in method switch of gevent._gevent_cgreenlet.Greenlet object at 0x7fcdb37de700> returned NULL without setting an exception
```

</p>
</details>

# Expected Behavior
Error should not happen

**Comment by zyv** [comment] 2023-08-07 15:36
Also on StackOverflow: https://stackoverflow.com/questions/76848083/python3-11-celery-gevent-returned-null-without-setting-an-exception

**Comment by zyv** [comment] 2023-08-07 15:38
We are also affected on Python 3.11 - did you have any luck with downgrades, but staying with Python 3.10?

**Comment by zyv** [comment] 2023-08-07 15:44
I wonder if this has somehow to do with https://github.com/python/cpython/issues/94825 ?

**Comment by cunla** [comment] 2023-08-07 15:55
> We are also affected on Python 3.11 - did you have any luck with downgrades, but staying with Python 3.10?

With python3.10 it does not happen.

**Comment by catcombo** [comment] 2023-08-08 14:51
@cunla Do you have a reproducer that you can share with us so that we can continue to investigate this issue?

**Comment by cunla** [comment] 2023-08-08 18:42
> @cunla Do you have a reproducer that you can share with us so that we can continue to investigate this issue?

It is challenging to produce a reproducer, it does not happen on mac .

**Comment by zyv** [comment] 2023-08-08 18:44
> > @cunla Do you have a reproducer that you can share with us so that we can continue to investigate this issue?
> 
> It is challenging to produce a reproducer, it does not happen on mac .

Well, you do have it reliably hanging in Docker on Linux, right? Can you make a minimal project and push it on GitHub with a Dockerfile? Our problem is that it's not hanging reliably in Docker for us...

**Comment by danielm-cfa** [comment] 2023-08-08 18:52
Here is my `Dockerfile` (I remove company related stuff) - does this help?

```Dockerfile
FROM python:3.11-buster

RUN apt-get update -y && \
    apt-get install -y python3-pip dnsutils strace telnet && \
    apt-get install -y unixodbc

ENV PATH="/home/.local/bin:$PATH"

COPY --chown=app:app ./requirements.txt .

ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=$GITHUB_TOKEN

RUN pip3 install --upgrade pip
RUN pip3 install --user -r requirements.txt

CMD ["./run.sh"]
```

**Comment by zyv** [comment] 2023-08-08 18:56
> Here is my `Dockerfile` (I remove company related stuff) - does this help? (for the requirements.txt file, you can use the `pip freeze` in the issue)

Yes, this definitively helps a lot, but an example project that can be used to reproduce the hang is still missing. What can we run to get the crash inside this container? Our Celery app only crashes on Heroku, but not locally in Docker.

**Comment by catcombo** [comment] 2023-08-09 08:34
I tried to create a simple reproducer, but apparently I'm missing of the Celery task code that can cause the SystemError. I cannot trigger the error in my code https://github.com/catcombo/celery-system-error-reproducer

**Comment by zyv** [comment] 2023-08-09 09:12
> Can you reproduce it with `gevent==22.10.2` and `redis==4.6.0`? It seems that `gevent==22.10.2` and `redis==4.5.4` was problematic, but `gevent==22.10.2` and `redis==4.6.0` apparently solved our issue in July. We started getting problems again after upgrading to `gevent==23.7.0` like you have.

We now got a crash with `gevent==22.10.2` and `redis==4.6.0`. No idea what pin combinations can be tried still :( `redis==4.5.3`? Does this also happen with previous versions of the packages like `redis==4.5.3` and `celery==5.3`? Maybe we can isolate what change broke it. But it seems it's not `gevent`.

**Comment by dwjorgeb** [comment] 2023-08-10 11:13
we had the same issue today, and google searching the issue led me here.

However, we're not using Celery. We're using Huey, with gevent and redis.

`redis==4.6.0`
`gevent==23.7.0`
`greenlet==2.0.2`

**Comment by zyv** [comment] 2023-08-10 11:20
@dwjorgeb it looks like either it's a problem in gevent, or interaction of gevent with Redis client, or Redis client with Python 3.11. It appears to not be intrinsic to Celery.

We still are unable to isolate it and our current thinking is to move to `threads` in Celery and ditch `gevent`. If the problem will keep happening, then Redis client is at fault... but we hope we'll get rid of it this way.

**Comment by dwjorgeb** [comment] 2023-08-10 11:25
> @dwjorgeb it looks like either it's a problem in gevent, or interaction of gevent with Redis client, or Redis client with Python 3.11. It appears to not be intrinsic to Celery.
> 
> We still are unable to isolate it and our current thinking is to move to `threads` in Celery and ditch `gevent`. If the problem will keep happening, then Redis client is at fault... but we hope we'll get rid of it this way.

indeed, if it was an issue with Celery itself, it wouldn't have happened to us (unless Huey would have a similar issue).

Our system is running multiple Huey queues, 1 for IO that uses greenlets, and others that handle more CPU-intensive tasks use threads. Each queue is run on its own docker container, and the only one that failed was the greenlets one.

So this leads me to believe that the issue is probably with gevent.

**Comment by zyv** [comment] 2023-08-10 11:32
@dwjorgeb so do you have a reliable reproducer for that? I tried to cook something up yesterday, but unfortunately I'm unable to get it to crash locally in docker.

**Comment by dwjorgeb** [comment] 2023-08-10 11:39
@zyv unfortunately I can't reproduce it reliably. It crashed with this error in the middle of the night, killing the container, we restarted it and has been working fine until now.

**Comment by zyv** [comment] 2023-08-10 14:01
One more victim reports that they get it without redis, so I guess a report should be files against gevent:

https://github.com/celery/celery/discussions/8356#discussioncomment-6691270

**Comment by cunla** [comment] 2023-08-10 14:02
I'll open a report on gevent.

**Comment by zyv** [comment] 2023-08-11 08:38
I would close this issue here, since there is now an actively discussed issue in gevent.

**Comment by cunla** [comment] 2023-08-14 14:14
> I would close this issue here, since there is now an actively discussed issue in gevent.

Not sure what is the policy on this. 
I prefer to have it open as people will encounter the issue and may create a duplicate.

**Comment by auvipy** [comment] 2023-08-15 04:24
Let it keep open until the gevent issue is fixed.

**Comment by kkszysiu** [comment] 2023-08-25 00:04
Hey guys, seems like it started to happen for me as well after I upgraded urllib3 to 1.26.16, after I downgraded it back to urllib3[secure]==1.26.12 the issue is no longer happening.

**Comment by auvipy** [comment] 2023-08-31 06:23
So I think we can close it as it is not exactly a celery issue but an upstream bug.

**Closed by auvipy** 2023-08-31 06:23 UTC
Labels: Component: Gevent Workers Pool, upstream bug

**Comment by zyv** [comment] 2023-08-31 08:22
> So I think we can close it as it is not exactly a celery issue but an upstream bug.

Yes, definitively. We've switched to `threads` instead of `gevent` and since then there haven't been any crashes, so it's a problem with gevent and not it's interaction with celery / redis.

I wonder though, if there is any way for celery to mark gevent as broken on python 3.11... otherwise more people will upgrade and will start silently getting these evil crashes.

**Comment by auvipy** [comment] 2023-08-31 08:26
we can document it in celery. you can contribute the documentation

**Comment by cunla** [comment] 2023-08-31 13:28
> we can document it in celery. you can contribute the documentation

I am happy to contribute to the docs. Any direction where this could fit in the docs?
I thought to add it [here](https://docs.celeryq.dev/en/stable/userguide/concurrency/eventlet.html) as another section.
