### ISSUE TITLE
Database backend: SessionManager does not reuse engine and session when not forked.

### ISSUE THREAD

**Issue by alexander-jacob** [celery/celery#2661] opened 2015-06-17 05:42 UTC
In an application I use the database result backend.
When I get an AsyncResult of a task with the following code...

``` python
from celery.result import AsyncResult
from app import celery
async_result = AsyncResult(task_id, app=celery)
async_result.get(timeout=20)
```

... then I get 3 connects to the database with a full describe

```
150617  6:57:03    81 Connect   XXXX@localhost on XXX
                   81 Query     set autocommit=0
                   81 Query     SHOW VARIABLES LIKE 'sql_mode'
                   81 Query     SELECT DATABASE()
                   81 Query     SELECT @@tx_isolation
                   81 Query     show collation where `Charset` = 'utf8' and `Collation` = 'utf8_bin'
                   81 Query     SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
                   81 Query     SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
                   81 Query     SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8) COLLATE utf8_bin AS anon_1
                   81 Query     SELECT 'x' AS some_label
                   81 Query     rollback
                   81 Query     DESCRIBE `celery_tasksetmeta`
                   81 Query     DESCRIBE `celery_taskmeta`
                   81 Query     rollback
```

This is very expensive and results in an overall bad performance of the application.

So I took a look into 

```
SessionManager at celery/backends/database/session.py
```

Both methods

```
def get_engine(self, dburi, **kwargs):
# and 
def create_session(self, dburi, short_lived_sessions=False, **kwargs):
```

reuse engine and session when forked is set to True.

But this will never happen in an application or in our unit tests.
So we will always get the NullPool and a fresh connection on each call to

```
DatabaseBackend.ResultSession
```

So I am not sure if this is an intended behaviour by design or if it should be configurable.

**Comment by thedrow** [comment] 2015-06-19 11:30
Are you using Django or SQLAlchemy?

**Comment by smidt** [comment] 2015-06-19 11:34
We use SQLAlchemy.

**Comment by thedrow** [comment] 2015-06-19 11:37
and by not forked you mean you use either gevent or eventlet right?

**Comment by alexander-jacob** [comment] 2015-06-19 12:05
Yes, we use gunicorn together with flask/spyne.

When running our tests (pytest) it is not forked either. 
We noticed massive connects to mysql when running the test suite.
So we started to find the reason for this.

**Comment by alexander-jacob** [comment] 2015-06-23 06:59
So what I suggest is to make this behavior configurable. What do you think?

**Comment by thedrow** [comment] 2015-06-23 08:35
Yes this should indeed be configurable.
You need to keep the old behaviour though for backwards compatibility but allow users to use a pool even if celery is not running in prefork mode.

**Comment by ask** [comment] 2016-06-24 00:17
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.

**Comment by monaidu** [comment] 2019-10-20 03:28
The new connection created complete ignores the database_engine_options configured so if we have enabled the secure connection these operations will fail to connect the backend.

Do we have configuration which sets the forked to be set to true since currently we have no way of doing this which makes many of the backend task detail update failures.

`File "/home/vson/enet/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 630, in __connect
    connection = pool._invoke_creator(self)
  File "/home/vson/enet/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/vson/enet/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/vson/enet/lib/python3.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/home/vson/enet/lib/python3.7/site-packages/pymysql/connections.py", line 688, in __init__
    self.connect()
  File "/home/vson/enet/lib/python3.7/site-packages/pymysql/connections.py", line 906, in connect
    self._request_authentication()
  File "/home/vson/enet/lib/python3.7/site-packages/pymysql/connections.py", line 1114, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/vson/enet/lib/python3.7/site-packages/pymysql/connections.py", line 981, in _read_packet
    packet.check_error()
  File "/home/vson/enet/lib/python3.7/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/vson/enet/lib/python3.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user `

**Comment by auvipy** [comment] 2019-10-24 03:20
which version of celery are you using? can you provide a test case?

**Comment by auvipy** [comment] 2019-10-24 03:21
aise_mysql_exception raise errorclass(errno, errval) pymysql.err.OperationalError: (1045, "Access denied for user 

can you check the user access permission?

**Comment by auvipy** [comment] 2019-10-24 03:23
does https://stackoverflow.com/questions/50336458/pymysql-access-denied-using-password-no-but-using-password related or help to solve your problem?

**Comment by monaidu** [comment] 2019-10-24 05:36
> which version of celery are you using? can you provide a test case?

We are using the 4.3.0 version . We are trying to send the revoke signal for the worker during which the DB update is being tried and the session we are trying to create without the certs which are passed in the database_engine_options .

def get_engine(self, dburi, **kwargs):
        if self.forked:
            try:
                return self._engines[dburi]
            except KeyError:
                engine = self._engines[dburi] = create_engine(dburi, **kwargs)
                return engine
        else:
            return create_engine(dburi, poolclass=NullPool)

The creat_engine when it is not forked it is completely ignoring the certs

**Comment by monaidu** [comment] 2019-10-24 05:36
> aise_mysql_exception raise errorclass(errno, errval) pymysql.err.OperationalError: (1045, "Access denied for user
> 
> can you check the user access permission?

The user has the access we are providing the certs which are valid

**Comment by monaidu** [comment] 2019-10-24 05:37
> does https://stackoverflow.com/questions/50336458/pymysql-access-denied-using-password-no-but-using-password related or help to solve your problem?

I think it will not the issue is more with the certs not used while trying to create a session.

**Comment by auvipy** [comment] 2019-10-25 09:10
I think this is not an issue of celery

**Closed by auvipy** 2019-10-25 09:10 UTC
Labels: Component: SQLAlchemy Database Results Backend, Issue Type: Bug Report, Status: Needs Verification ✘

**Comment by monaidu** [comment] 2019-10-28 06:47
> I think this is not an issue of celery

On what basis this was concluded the issue is not from celery's engine creation ?????

**Comment by auvipy** [comment] 2019-10-28 07:21
can you discus your issue first in celery-users / #celery IRC on freenode? after getting a proper conclusion there please report it as a bug. this is the proper way to file a bug report on celery repo :)
