### ISSUE TITLE
Random task execution delays with amqp broker

### ISSUE THREAD

**Issue by 23doors** [celery/celery#3978] opened 2017-04-14 00:29 UTC
Tested with latest pypi version (4.0.2) and against master branch.

Upgraded recently from 3.1.25 as I had some issues with tasks being received but executed after a short delay (as in https://github.com/celery/celery/issues/2771). Now it got worse.

Tried using librabbitmq, but encountered: https://github.com/celery/celery/issues/3675 when I was queueing task inside a task.

## Steps to reproduce

Reproduced it with example project from: https://github.com/celery/celery/blob/master/examples/app/myapp.py 

1. Installed rabbitmq locally ({rabbit,"RabbitMQ","3.6.9"})
2. Ran `celery worker -A myapp -l debug`
3. In another process, sent task a few times: `app.send_task('myapp.add', args=(1,2))`

## Expected behavior

Tasks should be processed asap.

## Actual behavior

Sometimes there is a pretty big delay between receiving and processing a task.
```
[2017-04-14 02:18:08,889: INFO/MainProcess] Received task: myapp.add[59816272-ca82-4eee-ba95-8d71da5dca52]
[2017-04-14 02:18:08,889: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x1064d01b8> (args:('myapp.add', '59816272-ca82-4eee-ba95-8d71da5dca52', {'origin': 'gen84425@RK-MacBook.local', 'lang': 'py', 'task': 'myapp.add', 'group': None, 'root_id': '59816272-ca82-4eee-ba95-8d71da5dca52', u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'celery', u'exchange': u''}, 'expires': None, u'correlation_id': '59816272-ca82-4eee-ba95-8d71da5dca52', 'retries': 0, 'timelimit': [None, None], 'argsrepr': '(1, 2)', 'eta': None, 'parent_id': None, u'reply_to': '51344e5c-09df-31a0-bbfd-e64295f6db67', 'id': '59816272-ca82-4eee-ba95-8d71da5dca52', 'kwargsrepr': '{}'}, u'[[1, 2], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]', 'application/json', 'utf-8') kwargs:{})
[2017-04-14 02:18:10,746: DEBUG/MainProcess] Task accepted: myapp.add[59816272-ca82-4eee-ba95-8d71da5dca52] pid:84171
[2017-04-14 02:18:10,747: INFO/PoolWorker-8] Task myapp.add[59816272-ca82-4eee-ba95-8d71da5dca52] succeeded in 0.000706910970621s: 3
```

Above, between  `TaskPool: Apply` and `Task accepted:` there is a 2s delay. Usually it's smaller, like 0.5s. But it's very inconsistent.

Tried with redis broker - no delays and overall much faster. But I am hesitant to make the jump on production and I don't believe this behavior is to be expected anyway.

Tested librabbitmq - looks good, also no delays. But I am getting https://github.com/celery/celery/issues/3675 (which is closed for some reason).

**Comment by thedrow** [comment] 2017-04-15 20:29
We don't support librabbitmq anymore. The C library which it's based on is not very good and the bindings are not ported to Python 3.

Could this be related (or a duplicate of) to #3822, #3841 or #3737?

**Comment by 23doors** [comment] 2017-04-15 20:38
@thedrow It may be related partially but this bug occurs only when using amqp with pyamqp library. Which is strange.

About librabbitmq - it's not the core issue here anyway, but I had good experience so far with librabbitmq. Especially as when I switched to protocol 1, I no longer experienced https://github.com/celery/celery/issues/2771 + no strange delays like with pyamqp. And if it's not meant to be supported - why is it still a part of docs: http://docs.celeryproject.org/en/latest/userguide/optimizing.html#librabbitmq and kombu 4.x automatically picks it up when it's installed? Seems inconsistent.

**Comment by thedrow** [comment] 2017-04-16 06:58
We haven't removed support for it yet. This is an open source project and we're doing our best to maintain it but sometimes things get overlooked.

**Comment by 23doors** [comment] 2017-04-19 20:34
@thedrow 
Narrowed it down to https://github.com/celery/kombu/blob/master/kombu/async/hub.py#L284
Basically it seems that:
- when work is meant to be distributed, we register to check when queue socket is writeable
- this registration doesn't seem to be affecting currently running poll(), which will return only until timeout finishes (which is 0-2s depending on events to be fired)
- once poll() returns, it is ran again - this time returning properly event that socket is writeable and then readable - which properly propagates workload.

But this timeout (0-2s) from 2nd stage is what's causing these random delays. 

```
[2017-04-19 22:33:19,380: INFO/MainProcess] Received task: myapp.add[c1d9155d-66be-4aa4-bbb6-2fbc16967534]
[2017-04-19 22:33:19,380: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x10c737e60> (args:('myapp.add', 'c1d9155d-66be-4aa4-bbb6-2fbc16967534', {'origin': 'gen56926@RK-MacBook.local', 'lang': 'py', 'task': 'myapp.add', 'group': None, 'root_id': 'c1d9155d-66be-4aa4-bbb6-2fbc16967534', u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'celery', u'exchange': u''}, 'expires': None, u'correlation_id': 'c1d9155d-66be-4aa4-bbb6-2fbc16967534', 'retries': 0, 'timelimit': [None, None], 'argsrepr': '(1, 2)', 'eta': None, 'parent_id': None, u'reply_to': '7fe13db8-850f-3979-a51a-3665a2dcf927', 'id': 'c1d9155d-66be-4aa4-bbb6-2fbc16967534', 'kwargsrepr': '{}'}, u'[[1, 2], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]', 'application/json', 'utf-8') kwargs:{})
[2017-04-19 22:33:19,380: WARNING/MainProcess] [[[HUB]]]: (17)_event_process_exit(<Hub@0x10c86c690: R:5 W:0>, <Process(PoolWorker-1, started daemon)>)->R!, (18)_event_process_exit(<Hub@0x10c86c690: R:5 W:0>, <Process(PoolWorker-2, started daemon)>)->R!, (11)on_result_readable(11)->R!, (14)on_readable(<kombu.transport.pyamqp.Connection object at 0x10c9e7890>, <Hub@0x10c86c690: R:5 W:0>)->R!, (7)on_result_readable(7)->R!
[2017-04-19 22:33:19,922: WARNING/MainProcess] [EVENTS]:
[2017-04-19 22:33:19,923: WARNING/MainProcess] [[[HUB]]]: (17)_event_process_exit(<Hub@0x10c86c690: R:5 W:2>, <Process(PoolWorker-1, started daemon)>)->R!, (18)_event_process_exit(<Hub@0x10c86c690: R:5 W:2>, <Process(PoolWorker-2, started daemon)>)->R!, (11)on_result_readable(11)->R!, (14)on_readable(<kombu.transport.pyamqp.Connection object at 0x10c9e7890>, <Hub@0x10c86c690: R:5 W:2>)->R!, (7)on_result_readable(7)->R!, (10)<missing>->W, (6)<missing>->W
[2017-04-19 22:33:19,923: WARNING/MainProcess] [EVENTS]: schedule_writes(10)->W, schedule_writes(6)->W
[2017-04-19 22:33:19,924: WARNING/MainProcess] [[[HUB]]]: (17)_event_process_exit(<Hub@0x10c86c690: R:5 W:0>, <Process(PoolWorker-1, started daemon)>)->R!, (18)_event_process_exit(<Hub@0x10c86c690: R:5 W:0>, <Process(PoolWorker-2, started daemon)>)->R!, (11)on_result_readable(11)->R!, (14)on_readable(<kombu.transport.pyamqp.Connection object at 0x10c9e7890>, <Hub@0x10c86c690: R:5 W:0>)->R!, (7)on_result_readable(7)->R!
[2017-04-19 22:33:19,924: WARNING/MainProcess] [EVENTS]: on_result_readable(11)(11)->R, on_readable(<kombu.transport.pyamqp.Connection object at 0x10c9e7890>, <Hub@0x10c86c690: R:5 W:0>)(14)->R
[2017-04-19 22:33:19,924: INFO/PoolWorker-1] Task myapp.add[c1d9155d-66be-4aa4-bbb6-2fbc16967534] succeeded in 0.000124211073853s: 3
[2017-04-19 22:33:19,924: DEBUG/MainProcess] Task accepted: myapp.add[c1d9155d-66be-4aa4-bbb6-2fbc16967534] pid:80191
```

**Comment by 23doors** [comment] 2017-04-19 21:48
With librabbitmq, polling returns just before task is received and therefore on_poll_start tick is run. So we skip 2nd stage completely and therefore skip delay.

**Comment by 23doors** [comment] 2017-04-19 23:02
@thedrow proposed a fix in kombu repo https://github.com/celery/kombu/issues/725. Seems to be working fine so far and no issues.

**Comment by thedrow** [comment] 2017-07-18 15:25
This is fixed in https://github.com/celery/py-amqp/pull/144

**Closed by thedrow** 2017-07-18 15:25 UTC
