### ISSUE TITLE
kazoo can't work with celery

### ISSUE THREAD

**Issue by elcricwu** [celery/celery#3129] opened 2016-03-23 09:47 UTC
Kazoo is a python zookeeper client. It use threads to keep long connection with zookeeper. When using Kazoo in prefork mode, kazoo's inner threads can't keep long connection with zookeeper because of celery's thread-less feature. Is there a solution for celery with thread running in prefork mode?

**Comment by Toilet22** [comment] 2016-04-13 09:52
I have the same problem.

**Comment by kindule** [comment] 2016-04-13 23:49
What about use celery threads pool mode?

**Comment by elcricwu** [comment] 2016-04-14 10:34
We now use gevent to run celery. It works fine.In production, we compared prefork, threads, and gevent. Prefork mode is always the first choice as celery docs said, and it performed better than gevent and threads. If you encountered performance issue when using gevent, use multi processes plus gevent. But in extreme circumstance, gevent will be blocked in epoll event. See issue https://github.com/celery/celery/issues/2606.

**Comment by Toilet22** [comment] 2016-04-15 11:23
Thanks a lot! I met the same problem.

**Comment by ask** [comment] 2016-04-15 19:59
kazoo uses threads?  That's shocking to me, that would render the client pretty much useless :(

**Comment by elcricwu** [comment] 2016-04-17 13:29
@ask kazoo's  default handler is SequentialThreadingHandler. I think It's incompatible with celery. Kazoo also has a gevent handler: SequentialGeventHandler. I don't know if celery can be compatible with it.

**Comment by Toilet22** [comment] 2016-04-19 09:36
@elcricwu  using SequentialGeventHandler doesn't solve the problem because KazooClient object has a ConnectionHandler which also start a thread.

**Comment by ask** [comment] 2016-04-19 23:03
@Toilet22 the `threading` module should be patched by the gevent/eventlet monkey patches so that may not be a problem.

Note that POSIX threads are only illegal in the parent process, as for task user code you are free to use threads (i.e. saw your legs off) as you see fit.

If there's threading related problems with task user code, it will usually be caused by:

- Task code not being thread-safe/fork-safe
- Third party code used by the task not being thread-safe/fork-safe
- Threading related code/connections is initialized in the parent process and inherited by the child prefork
  processes (really a special case of the above)

Examples of the third will be:

- A database library, HTTP client or similar initializing a connection or connection pool as a side
 effect of a module being imported, or in a user worker callback executed in the child process, but forgetting to reinitialize this after fork.
- The same but with threads being created/initialized/started in the parent process and inherited by the child.


To solve that you should either initialize this lazily so that it only happens when needed (e.g. when a connection is needed), or if you must do it at module import time etc, then use `mutiprocessing.register_after_fork` to reset the state after fork.

**Comment by ask** [comment] 2016-06-24 01:34
Closing this, as we don't have the resources to support Zookeeper.

**Closed by ask** 2016-06-24 01:34 UTC
