### ISSUE TITLE
Is there a way to set -Ofair in celeryconfig.py?

### ISSUE THREAD

**Issue by hheimbuerger** [celery/celery#3080] opened 2016-02-26 14:18 UTC
Right now, it seems like the only way to set [-Ofair](http://docs.celeryproject.org/en/latest/reference/celery.bin.worker.html?highlight=fair#cmdoption-celery-worker-O) is via the command line.

Is there also a way to set this programmatically in `celeryconfig.py`, or in Django's `settings.py`?

**Comment by ask** [comment] 2016-02-26 19:25
No, there's no way to do that, but we are also moving in the direction of having less configuration options, so many of the settings you could configure are deprecated and removed in 4.0.

**Comment by dessant** [comment] 2016-02-27 11:49
Duplicate of https://github.com/celery/celery/issues/3042.

**Closed** 2016-02-29 14:52 UTC
Labels: Status: Duplicate
