### ISSUE TITLE
Worker crash on startup when specifying multiple cache result backends

### ISSUE THREAD

**Issue by mbox** [celery/celery#3068] opened 2016-02-20 15:04 UTC
Seen with Celery 3.1.20, Django 1.9

Steps to reproduce:

* Set CELERY_RESULT_BACKEND to multiple memcache servers e.g. `CELERY_RESULT_BACKEND = 'cache+memcached://127.0.0.1:11211;127.0.0.10:11211/'`
* Start a celery worker using ./manage.py celery worker

Result is a crash with stacktrace:

```
[2016-02-20 14:58:41,566: ERROR/MainProcess] Unrecoverable error: ValueError("invalid literal for int() with base 10: '11211;127.0.0.10'",)
Traceback (most recent call last):
  File "/Users/malcolmbox/dev/tellybug/webserver/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/Users/malcolmbox/dev/tellybug/webserver/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    self.on_start()
  File "/Users/malcolmbox/dev/tellybug/webserver/lib/python2.7/site-packages/celery/apps/worker.py", line 170, in on_start
    string(self.colored.cyan(' \n', self.startup_info())),
  File "/Users/malcolmbox/dev/tellybug/webserver/lib/python2.7/site-packages/celery/apps/worker.py", line 232, in startup_info
    self.app.conf.CELERY_RESULT_BACKEND or 'disabled',
  File "/Users/malcolmbox/dev/tellybug/webserver/lib/python2.7/site-packages/kombu/utils/url.py", line 63, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "/Users/malcolmbox/dev/tellybug/webserver/lib/python2.7/site-packages/kombu/utils/url.py", line 58, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "/Users/malcolmbox/dev/tellybug/webserver/lib/python2.7/site-packages/kombu/utils/url.py", line 24, in _parse_url
    return (scheme, unquote(parts.hostname or '') or None, parts.port,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '11211;127.0.0.10'
```

According to the documentation, this is a valid format for CELERY_RESULT_BACKEND, and this was working on previous versions of celery

This is happening during printing of the startup banner, so completely prevents the worker from starting.

**Comment by mbox** [comment] 2016-02-20 15:07
The bug is using kombu's `maybe_sanitize_url` to sanitize a value that isn't a single URL.

**Comment by ask** [comment] 2016-02-25 21:02
Different backend, but can be classified as duplicate of #3045 I believe

**Closed by ask** 2016-02-25 21:02 UTC
Labels: Component: Memcached Results Backend, Issue Type: Bug, Status: Has Testcase
