### ISSUE TITLE
Do celery have backfill and catch up feature built in if not than how can we implement these features with celery?

### ISSUE THREAD

**Issue by Akash810** [celery/celery#8652] opened 2023-11-20 07:08 UTC
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the if the same enhancement was already implemented in the
  main branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

# Design

## Architectural Considerations

None

## Diagrams

N/A

## Alternatives

None

**Comment by auvipy** [comment] 2023-11-20 07:22
duplicate of https://github.com/celery/celery/discussions/8653

**Closed** 2023-11-20 07:23 UTC
Labels: Issue Type: Enhancement
