### ISSUE TITLE
Simplest sample not returning result using RabbitMQ on Win7

### ISSUE THREAD

**Issue by deniskak** [celery/celery#897] opened 2012-08-01 14:27 UTC
I've been running the sample and it runs fine (default queue and different queues on local and remote machines) unless I try getting the results of the job. "Get" method always gets stalled and I poll "ready" it always keeps returning False.
I combined the example with calls to pika library (i.e. sending messages with results through pika + listening to queues using the same lib) and everything is working fine, so it's not an issue with RabbitMQ I guess. I can use it this way but still trying to figure out what the cause of this issue is would be great.

My config:
Python 2.7.1 (32 bit)
Celery 3.0.4 (with all the correct dependencies through easy_install)
RabbitMQ-2.8.4
Win7 x64

I've looked on numerous blogs and forums and non of the solutions I found helped in my case. Could you please tell me what could go wrong in this case?

Thanks a bunch!

**Comment by waynenilsen** [comment] 2015-01-06 14:35
Solution of @jennaliu works for me as well. Thank you, I spent a while fighting this one.

**Comment by dirttech** [comment] 2015-03-14 12:09
@jennaliu That solution worked perfectly for me

**Comment by iliapolo** [comment] 2015-05-22 22:33
Solution from @jennaliu works with my environment:

Amazon Windows Server 2012 Base 64bit
x64 Python 2.7.9
x64 Erlang (win) OTP 17
Celery 3.1.17

thanks so much

**Comment by thedrow** [comment] 2015-06-19 08:38
@ask Was the fix reverted?
Do we have another fix in mind?

**Comment by masterrex** [comment] 2015-09-07 17:53
This is still an issue with the latest release. The solution from @jennaliu did not work for me, though when printing app.current_task.backend from within a task an AMQP object was returned (not DisabledBackend). I have confirmed that starting a worker with --pool=solo is a functional workaround. 

Celery 3.1.18
Python 2.7.9 (x64)
Erlang OTP 18 (x64)
Windows-7-6.1.7601-SP1

![celery_win_fail](https://cloud.githubusercontent.com/assets/455210/9721407/71a2a622-555f-11e5-99d6-bacc5b15095a.PNG)

**Comment by dkdndes** [comment] 2015-12-17 09:31
I have the same issue with a mac, it's not windows specific. If I specify CELERY_RESULT_BACKEND='amqp' inside proj.settings it doesn't work but if I add "app.conf.update" as explained by #jennaliu inside proj/celery.py it works.

      1 from __future__ import absolute_import
      2 
      3 import os
      4 
      5 from celery import Celery
      6 
      7 # set the default Django settings module for the 'celery' program.
      8 os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'proj.settings')
      9 
     10 from django.conf import settings  # noqa
     11 
     12 app = Celery('main')
     13 
     14 # Using a string here means the worker will not have to
     15 # pickle the object when using Windows.
     16 app.config_from_object('django.conf:settings')
     17 app.conf.update(
     18     CELERY_RESULT_BACKEND='amqp'
     19     )
     20 
     21 app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
     22 
     23 
     24 @app.task(bind=True)
     25 def debug_task(self):
     26     print('Request: {0!r}'.format(self.request))

**Comment by GraphGrail** [comment] 2016-01-05 12:18
Are there any updates? Reinstalling celery to 3.1.12 ver. doesnot solve issue

**Comment by vklap** [comment] 2016-03-10 12:41
I've uninstalled the latest version, which I just installed about an hour ago (pip uninstall celery), and then installed ver 3.1.18 (pip install celery==3.1.18) and it started working

**Comment by zjost** [comment] 2016-04-22 00:42
@jennaliu solution works for me using Windows 7 64bit, celery 3.1.23, Python 2.7, RabbitMQ 3.6.1 on Erlang 18.3.

**Comment by bigease** [comment] 2016-06-14 21:26
I am seeing this issue on a 14.04 Ubuntu machine.

Interestingly I do not see it on my development machine which is running 16.04.  The only other difference I have is that on my development machine I have python 3.5 and on the 14.04 machine I have 3.4.

I have tried all different backends (rabbitmq, redis, django-celery) and they all do this, so it definitely appears to be an environmental issue.

The workaround from @jennaliu  is not working for me right now.  

I'll keep on digging!

**Comment by bigease** [comment] 2016-06-16 11:03
I have now built a new machine, which now matches the versions of my development machine as far as I can tell.  However, it still exhibits this problem.

I'm really pulling my hair out with this one now!!

**Comment by ask** [comment] 2016-06-23 23:26
Closing this, as with current resources it's not possible to support Windows

**Closed by ask** 2016-06-23 23:26 UTC
Labels: Component: RabbitMQ Broker, Issue Type: Bug, Operating System: Windows, Status: Feedback Needed
